### ISSUE TITLE
list installed only shows Steam Games (nonsteamgame missing)

### ISSUE THREAD

**Issue by trentondyck** [sonic2kk/steamtinkerlaunch#1004]
## System Information
- SteamTinkerLaunch version: v14.0.20231212-1
- Distribution: SteamOS
- Installation Method: Git

## Issue Description

The command:
```
sonic2kk-steamtinkerlaunch-9de3341/steamtinkerlaunch list installed
```
Only shows steam games, nonsteamgames are missing, is this by design?

## Logs

Preparing to install SteamTinkerLaunch on Steam Deck
Updating SteamTinkerLaunch to latest git

Dependency 'innoextract' already installed, nothing to do.
Dependency 'cabextract' already installed, nothing to do.
Dependency 'yad' already installed, nothing to do.

Finished updating SteamTinkerLaunch ('v14.0.20231212-1')!
Steam Linux Runtime 1.0 (scout) (1070560) -> /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime
Steam Linux Runtime 2.0 (soldier) (1391110) -> /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier
Proton Experimental (1493710) -> /home/deck/.local/share/Steam/steamapps/common/Proton - Experimental
Steam Linux Runtime 3.0 (sniper) (1628350) -> /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper
Munchkin Digital (1722860) -> /home/deck/.local/share/Steam/steamapps/common/Munchkin Digital
Proton 7.0 (1887720) -> /home/deck/.local/share/Steam/steamapps/common/Proton 7.0
Steamworks Common Redistributables (228980) -> /home/deck/.local/share/Steam/steamapps/common/Steamworks Shared
Proton 8.0 (2348590) -> /home/deck/.local/share/Steam/steamapps/common/Proton 8.0
Counter-Strike: Source (240) -> /home/deck/.local/share/Steam/steamapps/common/Counter-Strike Source
Tabletop Simulator (286160) -> /home/deck/.local/share/Steam/steamapps/common/Tabletop Simulator
FINAL FANTASY VII (39140) -> /home/deck/.local/share/Steam/steamapps/common/FINAL FANTASY VII
Hellblade: Senua's Sacrifice (414340) -> /home/deck/.local/share/Steam/steamapps/common/Hellblade
Oxygen Not Included (457140) -> /home/deck/.local/share/Steam/steamapps/common/OxygenNotIncluded
Anno 2070 (48240) -> /home/deck/.local/share/Steam/steamapps/common/Anno 2070
Hellblade: Senua's Sacrifice VR Edition (747350) -> /home/deck/.local/share/Steam/steamapps/common/Hellblade Senua's Sacrifice - VR
PixelJunk™ Monsters 2 (749800) -> /home/deck/.local/share/Steam/steamapps/common/PixelJunk™ Monsters 2
Magic: The Gathering Arena (2141910) -> /run/media/mmcblk0p1/SteamLibrary/steamapps/common/MTGA

Total games installed: 17

**Comment by trentondyck** [comment]
Basically I was looking for another way to find the appID, I'm using python in my script now but thought I'd try STL version of it, but the game isn't found (because it's not in the $GEMETA)

**Comment by sonic2kk** [comment]
This isn't a bug, this is a feature request with now list games works. It is intended to list Steam games. There will be a separate argument to the command to list Non-Steam Games.

This is already noted in #960, so I will close this issue as the feature request is already being tracked. I want this feature so I'm not shutting you down, it's just already being tracked in another issue.

Also in future, please attach logs as files 🙂 

<hr>

On a technical note for the implementation, Non-Steam Games are read from `shortcuts.vdf`, but the list command doesn't have any awareness of this. We do have functions that would facilitate this, but I recall a little bit of complexity with implementing it due to the way the `list` command generates the games list, so it would likely have to be a separate path entirely.

It's feasible, we already have the functions in place that can give us all this information internally, care just needs to be taken with integrating it into the list command.

**Comment by sonic2kk** [comment]
Actually,

> Basically I was looking for another way to find the appID

`steamtinkerlaunch gi <AppName>` should support Non-Steam Games? I have used this as of a couple weeks ago and it worked fine for my Non-Steam Games (#963).

**Comment by trentondyck** [comment]
Maybe it's the space or something doesn't seem to work for me. I can wait for #960 to list/test again.

**Comment by sonic2kk** [comment]
#963 was merged some time ago. If you're using a space, make sure you use quotes, just like for Steam games.

**Comment by sonic2kk** [comment]
Fwiw I just tested again and all of my Non-Steam Games and one newly added one is working with `steamtinkerlaunch gi`. Some were added by STL, the newly added one was added from the Steam Client. Sample screenshot:

![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/7917345/065cf4df-f91e-4ff8-a23e-8768647297a3)
