### ISSUE TITLE
Harvestella won't run on stl(cannot find usable proton version)

### ISSUE THREAD

**Issue by Himoteph** [sonic2kk/steamtinkerlaunch#1012]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Steamdeck SteamOS 3.5.7
- Installation Method: ProtonUp-Qt

## Issue Description
Whenever I try to run Harvestella with steam tinker launch as a compatibility tool, and set it up to fork with another program(have tried with a trainer and cheat engine), I get an installing ModOrganizer page, then it crashes. Subsequent attempts to run the game with stl lead it to bypass the option to open the menu, and jump straight to the ModOrganizer install screen. Has not occurred with any other games in my library.

## Logs

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13926307/steamtinkerlaunch.log)

**Comment by Himoteph** [comment]
Also occurs if I completely uninstall 12.12, and install 12.0 instead.

**Comment by sonic2kk** [comment]
SteamTinkerLaunch V12.12 is very old. ModOrganizer 2 doesn't work with v12.12 either which is noted on the wiki and closed issues already. It tries to use the latest MO2 which is v2.5 and it's not compatible with Valve Wine yet. Use SteamTinkerLaunch from git, it's available from ProtonUp-Qt. You'll have to uninstall MO2 from the game prefix and from the global compatdata at `~/.config/steamtinkerlaunch/mo2`.

If STL can't find a usable Proton version, try removing `/dev/shm/steamtinkerlaunch`.

> Distribution: no idea

What do you mean? How do you not know what Linux distribution you installed on your computer?

If you are not an experienced Linux user, I don't recommend using an enthusiast tool like SteamTinkerLaunch.

<hr>

I will also need you to be a lot more specific here. You say the game won't run, then you mention MO2 suddenly. Does it work standalone or only show this issue with MO2? Is your issue about MO2 or the game not running vanilla?

**Comment by sonic2kk** [comment]
Inspecting the log, it looks like no Proton version was found for MO2 or the game as you state, but a lot of things about this log seem really, really wrong. It could simply be because v12.12 is so outdated though.

After clearing `/dev/shm/steamtinkerlaunch`, re-run STL and if the issue persists, inspect `/dev/shm/steamtinkerlaunch/ProtonCSV.txt` to see what STL was actually able to find.

Also, Harvestella is not on the list of supported ModOrganizer 2 games, for [SteamTinkerLaunch](https://github.com/sonic2kk/steamtinkerlaunch/blob/master/misc/mo2games.txt) or [ModOrganizer 2](https://github.com/ModOrganizer2/modorganizer/wiki/Game-Support). I'm not sure what you're trying to achieve here with MO2; Harvestella is not supported either way.

**Comment by sonic2kk** [comment]
The log does not look like it's from an attempted launch of the game with MO2. It looks like MO2 tried to start and didn't. However after that STL is unable to start any process because it can't find a Proton version. I'm not sure what went wrong here and there isn't enough information to know more.

**Comment by sonic2kk** [comment]
Inspecting again, it looks like you're running SteamOS. You should *absolutely not* be using v12.12 on SteamOS. MO2 probably doesn't even work to begin with on SteamOS, because modding on SteamOS is a very bad idea. I've never tried it and don't know how many people are actually able to do it. I don't use SteamTinkerLaunch on my Steam Deck anymore. There are too many issues specific to SteamOS.

The [SteamTinkerLaunch ModOrganizer 2 wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#mod-organizer-2) also already informs you to use the latest git SteamTinkerLaunch with MO2 on SteamOS for the best chance of compatibility.

Steam Deck may also not be officially supported long-term, due to lack of interest from my side, lack of community maintenance, and too many non-enthusiasts using STL on SteamOS (it's difficult to help users who are not passionate Linux users troubleshoot issues with an enthusiast tool). This was noted in https://github.com/sonic2kk/steamtinkerlaunch/issues/859#issuecomment-1818052146.

**Comment by Himoteph** [comment]
I initially get the two second “would you like to open the STL menu to change your settings?”. I open it up, go to game menu, check “use custom command” and “fork custom command”. Set custom command to Cheat Engine.exe. Hit save and play. After a couple seconds, I get this screen. A couple seconds more, I’m back to the steam page.
![IMG_0465](https://github.com/sonic2kk/steamtinkerlaunch/assets/20261321/784f304e-008e-4e60-959c-00f876a3cd79)

**Comment by sonic2kk** [comment]
It would also be a good idea to check what version of Proton is selected on the Game Menu and Global Menu, the log suggests it is `none` but you should be able to select a different version, if `ProtonCSV` generates correctly.

> Set custom command to Cheat Engine.exe. Hit save and play.

You cannot, as far as I'm aware, reliably use custom commands and MO2 together. Also, once again, Harvestella is not a supported MO2 game by SteamTinkerLaunch or upstream ModOrganizer 2, so you **cannot** use MO2 with it.

>  After a couple seconds, I get this screen. A couple seconds more, I’m back to the steam page.

Because ModOrganizer 2 **does not work** with v12.12. It is only supported on the Linux Desktop and with SteamTinkerLaunch from git, not the massively outdated v12.12. The MO2 wiki and Steam Deck wiki also tell you explicitly to ONLY use the latest version of STL from git. There are also several closed issues if you look at the ModOrganizer 2 label noting that v2.5 doesn't work with Wine, and [the changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog) also notes that this fix is only in STL-git. The issue template also asks you to search through issues, and to check the changelog, *and* to test STL-git. In fact, the latter part was a change made earlier today (19677d5c6dd0a6e85207330bce23388224d74313).

Anyway, no MO2 proton version is found to install it with, so installation is failing. As requested you will need to do some troubleshooting to try and figure out why the Proton version is missing, I gave you some places to start (please use STL-git, remove `/dev/shm/steamtinkerlaunch`, then re-run and inspect `/dev/shm/steamtinkerlaunch/ProtonCSV.txt`, also check the Game Menu for the Game Proton version and the Global Menu for the ModOrganizer 2 Proton version, the log says they're `none`).

<hr>

You are going to have to tell me exactly what you're trying to do. Are you actually trying to use MO2 on SteamOS, or is this a side effect you're not expecting? You aren't making it clear if this issue is solely when trying to run the game, or if it only happens with a custom command, or if it only happens with the game, custom command, and MO2?

Also, it's worth mentioning that forked/injected custom commands often do not work on SteamOS because of some SteamOS specific process management that Valve are doing for an unknown reason (#1010 most recently).

**Comment by Himoteph** [comment]
I am not trying to use MO2. MO2 is forcing its way into my life. When I’m in desktop mode, I also get a message that it’s trying to find and run Proton 8 a couple times before giving up. During previous attempts to get this working through repeated uninstall/reinstall of STL, I’ve made sure that in the game menu is either the default of 8.0-4c, or the current experimental version.

Checking settings after a complete uninstall and reinstall of STL. MO2 mode is disabled. Default Proton version is 8.0-4c. Game runs fine without forking…and deleting the steamtinkerlaunch folder in shm got it to start working properly with custom forking in desktop mode…and gaming mode.

I’m going just assume there was a hiccup that was forcing it to try and run MO2 regardless of what I wanted and blinded it to the proton versions I have installed. Especially since it started acting up on other games that were running fine until after I started looking for help.

That being said, you suggested that I install the latest version of Steam Tinker Launch instead of 12.12. Thing is, on both Git and ProtonUp-Qt, the latest released version visible is 12.12.

**Comment by sonic2kk** [comment]
> Thing is, on both Git and ProtonUp-Qt, the latest released version visible is 12.12.

The latest stable release is v12.12, but if you install "SteamTinkerLaunch-git" from ProtonUp-Qt you should get `v14.0.20240112-4` or newer. You may need to enable ProtonUp-Qt's "Advanced Mode" if you didn't already turn it on for other tools.

By "Git" I assume you're referring to GitHub Releases, but that is not what I mean. I am referring to the latest commit on the master branch, often shortened to simply "git" since that's the version control used. It is very common to refer to the latest version as the "git" version, for example many AUR packages do this.

<hr>

If I understood correctly, then it appears everything is working good here. Not sure what happened but it's working so that's fine, just be sure to update to the latest git version of STL, and update it regularly too for the latest fixes :-) And also be aware that unless something drastic changes, there is a significant possibility of SteamOS no longer being officially supported. STL will still run most likely as no code will be removed, but I don't use or test against SteamOS anymore, and if no one comes forward who can then I will have to stop advertising SteamOS support.

**Comment by Himoteph** [comment]
Yeah, everything is working now…and after a bit more playing around I have been able to definitively diagnose that trying to use the January 11th release of proton experimental with STL is what causes everything to catch on fire.

**Comment by sonic2kk** [comment]
Updating Proton Experimental without clearing the STL Proton CSV is going to cause issues since the Proton Experimental version isn't updated, so STL is looking for a Proton version it can't use.

This has come up in numerous other issues, and there were improvements around this since v12.12 was released if I recall. But in general when changing Proton versions, clear the cache in `/dev/shm/steamtinkerlaunch` :-) It's the same required step as if a new GE-Proton version is manually installed.

**Comment by Himoteph** [comment]
Scratch that, I was wrong. The problem is caused by making changes to things in STL while the deck is in gaming mode. As long as any changes to setup are made in desktop mode, everything is fine-but the moment something is changed in the STL menu while in gaming mode, it immediately becomes unable to read the Proton files and tries to install MO2.

**Comment by sonic2kk** [comment]
Can't say I ever had that problem but like I said, SteamTinkerLaunch won't support SteamOS for much longer and I don't encourage you to use it on SteamOS. It's a tool for the Linux Desktop.

I don't have SteamTinkerLaunch on a Steam Deck to test but given that no one else has reported this on SteamOS yet, I don't know that this problem is widespread.

For example, #1010 was on SteamOS (issue says they installed from package manager, but looking at the log, I think they're mistaken).
