### ISSUE TITLE
Vortex mod files being automatically deleted

### ISSUE THREAD

**Issue by brownkidnumber2** [sonic2kk/steamtinkerlaunch#1013]
## System Information
- SteamTinkerLaunch version: Git
- Distribution: Debian 12 
- Installation Method: ProtonUp-Qt first but it didn't allow me to use the command in console so I used PacStall

## Issue Description
I'm new to Linux so please bare with me :') I am trying to use Vortex to mod BG3 but the mod files are being deleted.
![Screenshot_20240112_232203](https://github.com/sonic2kk/steamtinkerlaunch/assets/114453276/9f0b4132-0af8-4bea-817d-debd29f9fbb6)
I tried to revert the changes and just launch the game but then the game is crashing.
I have installed BG3 on another drive, but the Vortex folder is also written there, so I'm not sure if that's a problem.
edit: I forgot to add that disabled mods are not having their files deleted for some reason.

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13926770/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
This sounds like Vortex behaviour, i.e. something happening when running Vortex, and not something STL can do. I can't really help much with Vortex usage, you might be better off asking on a gaming support forum to figure out why Vortex might be doing this. This isn't an STL bug as far as I'm aware, this is something Vortex itself is choosing to do for an unknown reason. It could be specific to modding this game on Linux, it could be a general issue with modding the game, I don't know unfortunately.

SteamTinkerLaunch aims to get Vortex to start where possible, but I cannot provide support for modding games. I hope that makes sense since it would be an unreasonable burden. I also do not use or like Vortex (I did not add the Vortex support and I do not use Vortex).

>  I have installed BG3 on another drive, but the Vortex folder is also written there, so I'm not sure if that's a problem.

This is fine and intended, and awesome that it worked, because it did not work in v12.12 and barely anyone bothers to actually use an up-to-date git version.

<hr>

I did a quick search around and this seems to be a common issue not specific to STL or Linux, I cannot see anything specifically for Baldur's Gate 3 but I am seeing it happening a *lot* for New Vegas, Fallout 3, and Skyrim (unsure if Oldrim or SKSE or both are affected).

It ***seems*** like you'll want to choose the "Save all changes" option, but I am not sure and cannot say that will full confidence. Some people say this is "[normal behaviour](https://forums.nexusmods.com/topic/7365471-files-changed-outside-of-vortex/)" People have also noted that attempting to revert the changes causes a crash basically all of the time with any game thread I have seen, the general advice seems to be to "Save all changes", but I don't understand what that will do, so I'm not the source of truth here. You might want to search around a bit and see if you can find more information on this.

It might also be interesting to check when the mod files were updated, in case something is updating them for some reason. I don't think it's STL, I'm not sure what it could be doing to edit the files.

**Comment by sonic2kk** [comment]
I have been searching around and I can't really find much information that I can make sense of, but it does seem like this happens with Vortex with some systems for unknown reasons. So I guess you aren't alone and this likely isn't exclusive to Linux, so I hope there is a solution that can work!

If you do find that STL is modifying the files in some way do let me know and we can investigate further. I haven't modded a game with Vortex in a very long time, so long ago that it wasn't even on Linux, and it refused to work, so I have never tried Vortex since.

**Comment by brownkidnumber2** [comment]
Ah alright, thanks for the quick replies.

For anyone stumbling upon this, I just added the mods manually and that worked. ".pak" mods require some tinkering, you need to adjust the modsettings file. I followed this vid and it worked out great: youtube.com/watch?v=K1R0kJrVF2g

Nexus is working on a mod manager that will work on Linux so that will be useful when that eventually drops, but its only alpha rn :')

**Comment by sonic2kk** [comment]
Yes, once that drops, I will be removing Vortex from SteamTinkerLaunch. I utterly hate Vortex and hope no one uses said mod manager either, but once that day comes it won't be an issue.

Modding manually is a good idea, after more research it seems like this is generally the safest way to mod Baldur's Gate 3 in general.
