### ISSUE TITLE
Steamtinkerlaunch crashing with “installing modorganizer” page

### ISSUE THREAD

**Issue by Mbhuff03** [sonic2kk/steamtinkerlaunch#1016]
As far as I can tell, steamtinkerlaunch was working fine two days ago. Today I launched a game on steam deck, and I typically go into STL menu periodically to see if I’m using the latest proton. 

I like to use aurora from Cheathappens for some games (don’t hate, it saves time and I don’t use it on multiplayer) which requires STL. 

Today I updated it to the latest proton experimental and it crashed the load into the game. Tried a few other games also and they crashed as well. 

The only symptom is the screen right before the crash with “installing modorganizer” and a load bar at the top. This displays for a second or two (load bar doesn’t seem to load anything) and it goes back to the game launch screen. When I try to relaunch the game, it won’t even show the STL menu before going back to the install modorganizer screen. 

I’ve tried to uninstall and reinstall STL a few times using protonup-qt. Checked that yad was installed by using the “steamtinkerlaunch yad ai” command. 

I can’t figure out what’s wrong. 

I WAS able to reload the STL menu on a fresh install and get the game to open. But when I try to load aurora again, it seems to cause the crash again.   I realize this could be an issue with aurora, but since the games would launch with aurora fine a few days ago and with old proton builds, I don’t think it should cause such an issue.

**Comment by sonic2kk** [comment]
**Do not ignore the issue template, this issue will be closed as you did not follow it. You NEED to provide logs when reporting reproducible bugs.**

Someone else reported something similar and said a clean install fixed it. Very strange, as I haven't seen this on the Linux Desktop. This seems to be limited to Steam Deck though.

I no use SteamTinkerLaunch on my Steam Deck so I cannot test. I have no idea what Aurora is and do not support tinkering on Steam Deck, so I cannot give much help.

Are you definitely using the latest SteamTinkerLaunch from git and not v12.12?

**Comment by sonic2kk** [comment]
Upon re-reading, it seems this Aurora tool uses SteamTinkerLaunch. You should report this downstream then and see if they can figure it out, maybe they're trying to install ModOrganizer 2?

> Checked that yad was installed by using the “steamtinkerlaunch yad ai” command.

Why? SteamTinkerLaunch installs Yad itself on SteamOS, which the Steam Deck wiki page tells you. It is installed to `~/stl/deps/usr/bin` if memory serves.

<hr>

If a fresh install of SteamTinkerLaunch from git works without this ModOrganizer 2 menu shenanigans, and only happens when you try to use this third-party Steam Deck tool(?), then I don't think this is a SteamTinkerLaunch bug. Whatever tool is trying to use SteamTinkerLaunch downstream, you should report the issue to them.

A log would explain this, but out of interest, are you trying to use ModOrganizer 2? Someone reported that MO2 was being forced onto them in #1012, also on Steam Deck, but a reinstall seemed to resolve it.

As the issue template requested already but to be explicit, the log MUST be from the observed crash.

**Comment by sonic2kk** [comment]
If your log notes that `MO2MODE` is `none`, or if you have any STL game configs that have `MO2MODE="none"` in them, #1017 may resolve your issue.

I have only observed such a scenario in one issue where the user noted it only happened with one game (#1012). It was also only reported on SteamOS. I have been unable to re-create it myself.

Upon revisiting that issue, they claimed editing files in Steam Deck Game Mode caused the issue.

It would be useful if you could provide a log file, and also the config for the game causing the issue. Provide the log and config file when you can reproduce the crash.
- Log file for last execution is available at `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`.
- Game config file on Steam Deck is available at `~/.config/steamtinkerlaunch/gamecfgs/id/<appid>.conf` - For example, Half-Life would have a config file of `70.conf`.

This happens a lot so I will emphasise: Do not paste your log into GitHub, upload the file.
