### ISSUE TITLE
flawlesswidescreen keeps downloading vcrun2010 everytime you restart the game

### ISSUE THREAD

**Issue by zqpvr** [sonic2kk/steamtinkerlaunch#1037]
## System Information
- SteamTinkerLaunch version: latest 
- Distribution: SteamOS 
- Installation Method: Protonup-qt 

## Logs

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/14101927/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
I'll look into it, but man, it's kinda rude to just open a GitHub issue with no description or explanation on what research you've done beforehand... You could've at least listed the version you're using instead of just "latest" which is ambiguous :/

You haven't explained what game it does this with, and if and why this is a problem. It would be nice to know these things. It's not good form for any project to open bare bones issues like this, doing a bit to help out the volunteers that maintain the software you use is always a nice gesture.

I'll see what I can find and push a fix if needed.

**Comment by zqpvr** [comment]
v12.12 and the game is spec ops the line, it takes over 2 minutes to launch the game in gamemode

**Comment by sonic2kk** [comment]
v12.12 is not the latest then. This is why you should provide information. You should not be using v12.12, especially on SteamOS, [where the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Deck) tells you to use the latest git.

Have you confirmed if flawlesswidescreen works without vcrun2010? Have you done any technical research before opening this issue? Remember that STL in a Linux Desktop utility for experienced (and ideally developer-orientated) Linux gaming enthusiasts, not some SteamOS tool.

**Comment by sonic2kk** [comment]
If FlawlessWidescreen does not require vcrun2010, we can remove the installation section for it:

https://github.com/sonic2kk/steamtinkerlaunch/blob/ec97d00af6f7a3a59dbac04b1c4d5c452c599f45/steamtinkerlaunch#L13764-L13769

If you can confirm it doesn't require vcrun2010, this would be a straightforward fix. I can make a branch for you to test if you can confirm it doesn't require vcrun2010, just make sure to test with a clean prefix. Also, test on your Linux PC if you are able to as well.

**Comment by zqpvr** [comment]
It works in proton-ge by default, also probably works in default proton.

**Comment by sonic2kk** [comment]
Removing the bug label, as this is implemented intentionally in the code, but may not be required anymore pending further information.

If you are able to confirm that vcrun2010 is no longer required, I made a branch at [`flawlesswidescreen-remove-vcrun2010`](https://github.com/sonic2kk/steamtinkerlaunch/tree/flawlesswidescreen-remove-vcrun2010) that you can test. Make sure to remove the prefix for the game you're testing with, and if possible, test with a fresh game. Ideally as well you would test both on a Linux PC rather than on SteamOS, to make sure things work fine on a supported platform.

**Comment by zqpvr** [comment]
I tested by removing that line.

**Comment by sonic2kk** [comment]
Ok, if you tested with a clean prefix, and tested with a fresh game, feel free to try out that branch also. Then confirm that the problem is also fixed on your Linux PC, and if it fixes the problem with 2 games (or more, if you want to test more, that's fine) on SteamOS and the Linux Desktop, I can merge the change into master.

**Comment by zqpvr** [comment]
Technically this isn't SteamOS, it's https://github.com/ublue-os/bazzite/; it's functionally the same as SteamOS though

**Comment by sonic2kk** [comment]
You should've noted it as Bazzite in your issue then, not as SteamOS :frowning_face: 

If you're not running on a Steam Deck then I guess it's fine to only test Bazzite.

**Comment by zqpvr** [comment]
I am on Steam Deck, bazzite is based off the recovery image from valve, bazzite changed it from arch to fedora.

**Comment by sonic2kk** [comment]
Changing from Arch to Fedora is a pretty significant change, but this is not the point.

If the branch works on Bazzite and on a Linux PC, testing two games at least on each (to try and give confidence in the fix), then it can probably safely be merged. I can test myself, but confirmation from the reporter is better.

Please work with me here and provide more detailed information if possible, a lot of the confusion and mess in this issue could've been avoided with some technical research beforehand :/

**Comment by zqpvr** [comment]
I don't have a linux pc sadly

**Comment by zqpvr** [comment]
I don't have another game that has this 16:9 issue

**Comment by sonic2kk** [comment]
For me, FlawlessWidescreen does not work with Stars Wars: Knights of the Old Republic, without vcrun2010. It also only takes a few moments to install.

There is no real action to be taken here as far as I can see. FlawlessWidescreen needs vcrun2010. Are you sure you tested with a clean prefix if it worked for you?

**Comment by zqpvr** [comment]
are you testing on wine?

**Comment by sonic2kk** [comment]
Yes, Stars Wars: Knights of the Old Republic does not run natively. You may be thinking of KOTOR2.

SteamTinkerLaunch is being used as a compatibility tool as well, so it is definitely running under Wine.

**Comment by sonic2kk** [comment]
Using GE-Proto8-29, FlawlessWidescreen will start. Sometimes strangely the game does not, I guess the start time will need to be increased or something.

The change can probably be merged then.

**Comment by zqpvr** [comment]
it selected proton-ge 8.28 for me automatically

**Comment by sonic2kk** [comment]
Will push a change to remove the vcrun2010 installation. It should fix your problem.

In future, please provide actual information in the issue description, and please do some investigation see if you can report what needs fixing instead of the issue you're facing (that's not always possible but in this case it could've been investigated). Also, GitHub has an "Edit" button which you can use to edit messages, providing one-line responses as though this were a direct message thread can come off as curt. Issue trackers are for providing technical information to diagnose and help fix problems, not simply a support line.

I should also point out that, if you didn't see it on the wiki or in #859, that SteamOS (and SteamOS-like distributions) are not really widely supported. Typically users on these platforms are not developers or Linux enthusiasts, which makes providing support hard, on top of the fact that they can have quirks the Linux Desktop platform does not. I don't use SteamTinkerLaunch on these devices and no one has come forward to provide support, so the project does not get much attention on these platforms. Your best bet is to use a Linux Desktop when using SteamTinkerLaunch.

The above will only change if and when someone can come forward to help develop the project on these platforms.

**Comment by zqpvr** [comment]
alright, thank you.
