### ISSUE TITLE
Vortex fails to install error 

### ISSUE THREAD

**Issue by seanfire99** [sonic2kk/steamtinkerlaunch#1039]
steamtinkerlauncher Version : 12.12
Distro : EndevourOS arch linux base
installation Method : Aur
vortex fails to install all i get is an error saying vortex 1.8.0 and higher does not support win7 please update to win10 or higher i click ignore it finishes installing afterwords i try launching and nothing happens i would give you error logs if i new how but i don't i might have switched to linux but I'm still learning it i have tried installing vortex on lutris it installs launched but mods won't deploy and i also can't launch games via vortex on lutris either tried installing via steam/wine same as lutris but steamtinkerlauncher simply will not work and i have no idea why please help.

**Comment by seanfire99** [comment]
i would also like to add that i used proton-ge-8.30

**Comment by sonic2kk** [comment]
Issues that ignore the issue template and blatantly ignored all information to NOT use v12.12 are now ignored as spam. Use the correct version as the issue template tells you to try the latest git as well as to read the changelog. or better yet, don't use Vortex.

Never use the STL releases, always try the latest master. It seems common sense to me for software that hasn't had a release in over a year, and that directs you to do this before opening an issue. But you already ignored the issue template so not surprised its instructions were also ignored.

The "Bug Report" issue template notes the following (emphasis by me):

> Fill out as much of the required information as you can. Please **do not ignore the issue template**, otherwise your issue may be closed without resolution.
>
> Feel free to **search through currently open issues** to see if someone else has already reported your issue, **or to see if your issue has already been resolved**. If at all possible, **try testing the latest version of SteamTinkerLaunch from the master branch** to see if the issue has already been fixed. You can also **check the changelog on the wiki** to see if its been fixed since the latest release: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog

And the link to the current Bug Report issue template is here: https://github.com/sonic2kk/steamtinkerlaunch/blob/b106b3304dd3c4fd6ad8d4364cb79003f2ca5cc3/.github/ISSUE_TEMPLATE/bug-report.md

The template was selected because this issue was tagged with the "Bug" label automatically, which only happens when selecting the bug report issue template. This is what leads me to believe that it, and the instructions in it, were deliberately ignored.

**Comment by sonic2kk** [comment]
I re-read and in your defense, I can see that you're new to Linux. I should've been a little more patient in such a case, but a few things things:
1. SteamTinkerLaunch is not a modding tool. If you are only using it to mod games, you're probably looking in the wrong place. 
2. SteamTinkerLaunch is a tool for Linux enthusiasts to be an aid in tinkering, such as configuring launch options and so on. If you're new to Linux this likely isn't the tool for you.
3. Modding games on Linux is not for beginners, it requires at least some knowledge on how Wine maps to the Linux filesystem (i.e. how to navigate the `Z` drive in Wine) and a bit of knowledge about Wine prefixes.
4. Vortex under Wine can break often. Mod deployments through, for example, SteamTinkerLaunch or Lutris, can stop working with a Vortex update. To mitigate this, SteamTinkerLaunch does allow you to choose your Vortex version to install so you can go back to a known working version, or a community recommended version. However it will **not** reinstall Vortex, you'll need to remove the Vortex prefix. You may not understand how Wine prefixes work if you are new to Linux, but as mentioned above, this kind of knowledge is a prerequisite to tinkering.

Modding games on Linux with a mod manager is not a walk in the park. It's not something you can do too easily if you're new to Linux, but a bit of reading up on high level Wine usage would be a good place to start. I don't have any resources on hand, I kinda just learned through years of tinkering.

My recommendation though, is to avoid Vortex altogether, and just mod your games manually.
