### ISSUE TITLE
MO2 won't install

### ISSUE THREAD

**Issue by dontpokethebear3893** [sonic2kk/steamtinkerlaunch#1042]
## System Information
- SteamTinkerLaunch version: <V14.0.20240218-1>
- Distribution: <SteamOS 3.5>
- Installation Method: <Github 12.12 release zip file Manual Install>

## Issue Description
When attempting to install MO2 using steamtinker launch, I get the following output:
"(deck@steamdeck steamtinkerlaunch-12.12)$ ./steamtinkerlaunch mo2 start
Preparing to install SteamTinkerLaunch on Steam Deck
Updating SteamTinkerLaunch to latest git

Dependency 'innoextract' already installed, nothing to do.
Dependency 'cabextract' already installed, nothing to do.
Dependency 'yad' already installed, nothing to do.

Finished updating SteamTinkerLaunch ('v14.0.20240218-1')!
Sat Feb 17 01:31:58 PM EST 2024 INFO - setMO2Vars - USEMO2PROTON is 'none', so using latest Proton-GE 'GE-Proton8-25' automatically
innoextract: error while loading shared libraries: libboost_iostreams.so.1.80.0: cannot open shared object file: No such file or directory"

I also noted that the pop-up window attempted to install MO2 2.5. RC1 instead of 2.4.4 as the Wiki says it is hardcode to try and do.

**Comment by dontpokethebear3893** [comment]
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/14319870/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
As the log notes, you're using `SteamTinkerLaunch v12.12`. You should install from the GitHub repository's code button, or with a tool like ProtonUp-Qt, instead of the releases page to make sure you get the actual latest version. Make sure you remove the existing MO2 installation including any installed for a given game. Steps to do this are on the wiki: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#modorganizer-2-v250

Issues using MO2 v2.5.0 are not SteamTinkerLaunch's problem. Use the correct version of SteamTinkerLaunch from git with a fresh install and you should be fine. Closing. This is also a duplicate. If you saw it was using v2.5.0 that should've clued you in that something went wrong on your end. I am very much done dealing with people reporting this problem over and over and over, I believe this is around the 10th duplicate if you search through recent duplicate MO2 issue reports.

![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/7917345/7a9c4198-7f2d-41b3-a8d4-b68456f8d335)

Also, for your own sanity, don't attempt to mod games on SteamOS.
