### ISSUE TITLE
Mod Organizer 2 Does Not Start

### ISSUE THREAD

**Issue by xlbingo10** [sonic2kk/steamtinkerlaunch#1047]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Arch Linux
- Installation Method: Package Manager

## Issue Description
I am unable to launch Mod Organizer 2. I have tried launching it from both the game menu for Skyrim Special Edition and using the `steamtinkerlaunch mo2 start` terminal command. Mod Organizer 2 gets installed and then nothing happens. No errors are given. I followed the troubleshooting steps and the problem persisted. I am using the GOG version of Skyrim Special Edition downloaded through Heroic Games Launcher and added to Steam, however that should not affect the terminal command. I have attached the steamtinkerlaunch.log file as well as both log files with MO2 in the name.

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/14488085/steamtinkerlaunch.log)
[startMO2_.log](https://github.com/sonic2kk/steamtinkerlaunch/files/14488086/startMO2_.log)
[installMO2_protonrun.log](https://github.com/sonic2kk/steamtinkerlaunch/files/14488088/installMO2_protonrun.log)

**Comment by sonic2kk** [comment]
This has come up so many times before. Only Steam versions of games are supported, and also, you're using SteamTinkerLaunch v12.12, which has already been noted not to work. Install a recent version of STL and do not **ever** use a stable release unless you have some niche use-case.

Uninstall MO2 including any game-specific installs that may have occurred ([see MO2 wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#modorganizer-2-v250)), and re-install when you have installed an up-to-date SteamTinkerLaunch version from the master branch.

The issue template tells you to try STL-git, and search closed issues. Please read it in future. A simple search through [any recent ModOrganizer 2-labelled issue](https://github.com/sonic2kk/steamtinkerlaunch/issues?q=is%3Aissue+is%3Aclosed+label%3A%22ModOrganizer+2%22) or even a search for ModOrganizer 2/MO2 would've given you the answer. I have no patience for duplicate issue anymore of this exact problem, I've been dealing with it for months and I am so tired of repeating myself. In fact, not only does the issue template tell you to search through issues and try STL-git, it also tells you to check the changelog:

> Feel free to search through currently open issues to see if someone else has already reported your issue, or to see if your issue has already been resolved. If at all possible, try testing the latest version of SteamTinkerLaunch from the master branch to see if the issue has already been fixed. You can also check the changelog on the wiki to see if its been fixed since the latest release: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog

And the changelog notes that ModOrganizer is now pinned at v2.4.4 because we're still waiting on a widely available Proton version with the MO2 Qt patch. So it appears the issue template guidance was ignored.

<hr>

If you don't use a Steam release of a game with MO2 please don't open any issues here. It is most likely not going to work, but if you really want to try you can, but it's not expected to work and you will not be given any support for such a use-case. Only the Steam release of games will be given any kind of support because of how STL checks for installation paths etc.
