### ISSUE TITLE
STL only crashes with Elden Ring

### ISSUE THREAD

**Issue by darealcaffeine** [sonic2kk/steamtinkerlaunch#1067]
## System Information
- SteamTinkerLaunch version: v12.12 
- Distribution: KDE
- Installation Method: ProtonUp-QT

## Issue Description
STL immediately crashes back to Elden Ring game page in gaming mode under Steam Deck.

It does however work with every other game though. 

Is there a way to reset STL for ER?

I’ve tried deleting the .config folder already like 3x. 

Thanks!

**Comment by sonic2kk** [comment]
Didn't know where else to put this but: Make sure you're using **the Steam release** of Elden Ring.

I have a suspicion this is the EAC malware breaking the game and that there is no fix other than to not play games with EAC, but I've noted a few other troubleshooting steps below. Mainly, use an up-to-date version of SteamTinkerLaunch from master, and test if this happens in Desktop Mode and on your Linux PC (STL is really only useful for users that primarily use a Linux PC, since it's a technical tool for enthusiasts, and SteamOS is no longer tested against).

<hr>

You should try using the most up-to-date SteamTinkerLaunch master, which you can install from ProtonUp-Qt (and manually update each commit) with `SteamTinkerLaunch-git`, making sure you have Advanced Mode enabled (you probably already did, most users do [and it's already documented on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#protonup-qt), just pointing it out) - unless there a specific reason you're using such an old version? There is usually never a reason to use anything except the latest git, and the issue template already mentions to try from master.

You should make sure you're running at least `v14.0.20240317-1` or higher (this version is bumped with every commit).

All of the troubleshooting steps given should be with the latest SteamTinkerLaunch master, either installed manually or from ProtonUp-Qt. Releases are development checkpoints, not for daily usage. v12.12 is over a year old.

> Distribution: KDE

KDE is not a Linux distribution, it is a Desktop Environment. Do you mean SteamOS, or are you using a custom distribution?

> gaming mode under Steam Deck.

- Does it work in Steam Deck Game Mode?
- Does it work on your Linux Desktop? (Issues should always be tested on your Linux PC first, if you don't have one, STL probably isn't great to use as it is for enthusiasts).
- Does it work with the same Proton version without SteamTinkerLaunch? (i.e. Proton 8.0)

> I’ve tried deleting the .config folder already like 3x.

Just remove the per-game config file at `~/.config/steamtinkerlaunch/gamecfgs/id/<elden ring appid>.conf` (as documented on the [Paths wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Paths#per-game-configs)). Please don't remove your entire `~/.config` to attempt to fix any software, lots of important things are there.

If you want to fully reset SteamTinkerLaunch, removing `~/.config/steamtinkerlaunch` is the way to do it. That's the only place where SteamTinkerLaunch stores config information (some temp logging info is stored in shm at `/dev/shm/steamtinkerlaunch`), as we do not follow the XDG spec yet (see #486). 

> Logs

Please provide a log of an attempted run from Desktop Mode, or even better, from Game Mode if you have SSH or something similar set up. This might have some useful hints, although I don't think there'll be much. A log from running the game on your Linux PC would also help, if you have one, to compare.

If you missed it from the Readme and wiki, logs are available at `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`. You might also want to provide your Elden Ring config file, just in case there's something odd in it.

If there are any file names/etc you want hidden or changed feel free to copy the files to another location and edit them manually before uploading, just be careful when doing so :-) 

<hr>

Other things to check:
1. Make sure you configure your game in Desktop Mode and don't do any configuration in Game Mode, as apparently, Valve have broken this kind of configuration in Steam Deck Game Mode, but reports of this have been mixed.
2. Ensure the Proton version that SteamTinkerLaunch is trying to use actually exists (if it doesn't, launching in Desktop Mode should show a notification of a Proton version mismatch).
3. Ensure running the game vanilla, with a clean SteamTinkerLaunch config, works.

<hr>

It is also worth mentioning that EAC is probably the culprit, if this fails in Desktop Mode as well (with the latest SteamTinkerLaunch master, and *not v12.12*). If this is the case, I cannot help.

[Elden Ring contains EAC](https://steamdb.info/app/1245620/info/), which is essentially malware, and it is known to cause many problems just launching if the start command is wrapped in a way it does not like, or if it detects programs/a family of programs (such as scripts, like SteamTinkerLaunch) in userspace that it or the developer do not like. Some users in the past have had no success running EAC games with SteamTinkerLaunch, some have success on one machine and not another. Due to the malicious nature of the software it is impossible to know why it sometimes blocks some programs and not other times.

I do not and will never own Elden Ring, or any game that thought it acceptable to use EAC (or other similar invasive client-side anti-cheat) at any point in its life, so I cannot troubleshoot the game on my end. I think if every other games works and only Elden Ring doesn't work, EAC is a likely candidate. Some users have been able to run SteamTinkerLaunch and Elden Ring and some have not, and I put this inconsistency down to EAC since it can update at any time to break compatibility.

For a smooth experience, if you must play games with EAC, it is probably best to avoid using any kind of tool with them. That's not really a fix and I'm sorry about that, but if it is EAC then it's out of my control.

<hr>

I don't hold much hope, as SteamOS is not the ideal platform to use SteamTinkerLaunch on, and EAC has been known to cause of issues in the past. I also hope this wasn't *too* much of a rant against EAC and was more informative than not. But good luck!

**Comment by darealcaffeine** [comment]
Thanks soooooo much for the detailed and robust response! Will follow your shared advice and report back!

**Comment by sonic2kk** [comment]
Friendly ping, did you have a chance to re-test and see if this still occurs when at least the following conditions are met?
1. Using SteamTinkerLaunch from master.
2. Game is defiinitely using a valid Proton version (GameScope has no way to show the notifier so things could be silently failing if a Proton version cannot be found/a mismatch cannot be resolved).
3. Game is launched from Steam Deck Desktop Mode.
4. You're definitely using the Steam release.

**Comment by sonic2kk** [comment]
Closing due to lack of response. Feel free to re-open if you have time to test, but I think this is simply EAC being problematic. Hoping for the best though :-) Good luck!
