### ISSUE TITLE
Game won't load with STL Steamdeck

### ISSUE THREAD

**Issue by aaronarrowb** [sonic2kk/steamtinkerlaunch#1080]
I have 5 games with trainers attached running fine with STL. However Baldurs Gate 3 has stopped working. It ran fine before Jan 2024. I have resinstalled the game  and when launching through STL in the Main Menu I accidentially changed proton settings. It all auto closed down and won't load since.

I have deleted protons, compatdata for stl and BG3, reinstalled the game multiple times, updated protonup-qr also changed stl versions, but it does not boot. I can't get it back to when you can select main menu of STL. 
It instead asks to choose proton version,of which none work and when I select one it seems to quickly install mod oragniser which I don't need. Any proton selected the game just auto closes. I have attached a pics to show what happens.

Can  I change stl settings per game anywhere or how might I fix this? 
![20240411_162646](https://github.com/sonic2kk/steamtinkerlaunch/assets/166732948/80d805cb-c826-4235-aca4-a314f083168b)
![20240411_162805](https://github.com/sonic2kk/steamtinkerlaunch/assets/166732948/dd5f7702-cb6e-4164-8df4-95074d1210b9)
![20240411_162749](https://github.com/sonic2kk/steamtinkerlaunch/assets/166732948/7061a497-3781-47e7-95ef-3dd8e3ba88b7)
![20240411_162745](https://github.com/sonic2kk/steamtinkerlaunch/assets/166732948/3800757d-91fd-4992-8297-2bfbcff7b5ac)
![20240411_162823](https://github.com/sonic2kk/steamtinkerlaunch/assets/166732948/e17524a3-5fc7-4710-959d-535df083d2ba)

**Comment by sonic2kk** [comment]
> [...] it seems to quickly install mod oragniser which I don't need

This sounds like you're not using the latest STL, but are instead for some reason using the latest release. Please install STL-git, and try removing your per-game config file. The path may be at `~/.config/steamtinkerlaunch/gamecfgs/id/1086940.conf` but as always, verify this path is correct and corresponds to Baldur's Gate 3.

The issue with ModOrganizer 2 is due to SteamOS-specific issues, and was fixed with #1017. Please, never ever use an STL that is not from latest git master. SteamTinkerLaunch-git is available from ProtonUp-Qt for a reason. If you didn't already, make absolutely sure you've read all the documentation on installing SteamTinkerLaunch with ProtonUp-Qt: https://github.com/sonic2kk/steamtinkerlaunch/wiki/ProtonUp-Qt#installation

The Steam Deck wiki page also tells you to use the latest SteamTinkerLaunch from master: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Deck

<hr>

Also, in future, do not ignore the issue template. It's there for a reason. It asks you for a log and also to try SteamTinkerLaunch from master. Ignoring the issue template is unacceptable for any project without good reason.

You also did not provide a log, so it is difficult to know what the issue actually is. You can get a log easily by trying to run the game in Desktop Mode. You can also take screenshots on SteamOS either from Game Mode with Steam+Right Bumper, or from Desktop Mode with Spectacle like on any distro with KDE.

You must always provide logs when filing issues unless there is a very good reason for not doing so, as it provides other information. You cannot expect developers to help you from screenshots alone.

Closing as this issue is, at the very least, likely a result of not using STL from master, and also no log was provided so I cannot help. Using STL from master and creating a fresh STL per-game config for this game may help the issue.

**Comment by aaronarrowb** [comment]
Thanks for this I will try the above. I believe it was installed via discover on steamdeck though it was a year ago roughly, using some guide to get trainers running.

Apoligies for not following the correct process but will in future!

**Comment by sonic2kk** [comment]
You can't install SteamTinkerLaunch via Discover on SteamOS. That is Flatpak SteamTinkerLaunch and is only for use with Flatpak Steam which the Steam Deck does not use, and as the Discover page already states, this is **not** for SteamOS and it points you to the correct installation documentation. This is also stated on the Flatpak SteamTinkerLaunch repo: https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch?tab=readme-ov-file#comvalvesoftwaresteamutilitysteamtinkerlaunch

Your SteamTinkerLaunch installation is most likely from ProtonUp-Qt. Installing from Discover will do nothing as it is only for Flatpak Steam and there is no facility to even use it on SteamOS this way.

**Comment by aaronarrowb** [comment]
You are right it is via Protonup-QT! However deleting that config file and restarting the process worked! STL is now launching fine with BG3 and all working so thank you so much. Been trying to make it work for a week now.

**Comment by sonic2kk** [comment]
Glad to hear it! Happy gaming!

Make sure to update regularly from ProtonUp-Qt. Just redownload from ProtonUp-Qt and your existing installation will be updated, no need to uninstall or anything.
