### ISSUE TITLE
Steam Tinker Launch issues

### ISSUE THREAD

**Issue by ChongaPapi** [sonic2kk/steamtinkerlaunch#1081]
## System Information
- SteamTinkerLaunch version:  12.12
- Distribution:  
- Installation Method:  

## Issue Description

I downloaded steam tinker launch installed it. Forced compatibility through steam properties for fallout 4. Restarted my steam deck. I go to run the game and it's saying failed to download dependencies.

**Comment by sonic2kk** [comment]
No log, issue template mostly ignored, and you're using an outdated version of SteamTinkerLaunch.

The issue template already told you to try from master, the Steam Deck wiki page instructed you to, and yet you ignored this. It also instructed you to attach a log, giving the file path, and the Readme also gives you this. This is an unacceptable way to file an issue.

You also haven't given any information on how you've checked for missing dependencies or what you did before opening an issue. Did anything install to `~/stl/deps`? Files may exist to check their file size and see what exactly failed to download.

I haven't heard of SteamTinkerLaunch failing to download dependencies with this sort of warning before, so it sounds like a network issue. The log may give more hints but you didn't attach it so no one can help you.

SteamTinkerLaunch is not a Steam Deck tool. I'm sick of users assuming SteamOS is the default, which is how this comes across. 

Install from master, attach a log, and do a bit of investigation on your end. This can be re-opened if more information is provided, proper steps are taken, and the issue persists and is not simply a network issue.

**Comment by ChongaPapi** [comment]
Sat Apr 13 18:43:56 EDT 2024 INFO - main - Current SteamTinkerLaunch working directory is '/home/deck/.local/share/Steam/steamapps/common/Fallout 4'
Sat Apr 13 18:43:56 EDT 2024 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Sat Apr 13 18:43:56 EDT 2024 INFO - loadLangFile - Language from command line is 'english'
Sat Apr 13 18:43:56 EDT 2024 INFO - loadLangFile - SYSTEMSTLCFGDIR is '/usr/share/steamtinkerlaunch'
Sat Apr 13 18:43:57 EDT 2024 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Sat Apr 13 18:43:57 EDT 2024 INFO - loadLangFile - Loading language file from script directory '/home/deck/stl/prefix/lang/english.txt'
Sat Apr 13 18:43:57 EDT 2024 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Sat Apr 13 18:43:57 EDT 2024 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Sat Apr 13 18:43:57 EDT 2024 INFO - steamdedeckt - Seems like we have a Steam Deck here - making some specific settings
Sat Apr 13 18:43:57 EDT 2024 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
Sat Apr 13 18:43:57 EDT 2024 INFO - steamdedeckt - Did not detect a running 'gamescope' process - assuming we're running in Desktop Mode
Sat Apr 13 18:43:57 EDT 2024 INFO - steamdedeckt - Set 'FIXGAMESCOPE' to '0'
Sat Apr 13 18:43:57 EDT 2024 INFO - steamdedeckt - Set 'SMALLDESK' to '1'
Sat Apr 13 18:43:58 EDT 2024 INFO - gitUpdate - Pulling 'https://github.com/sonic2kk/steamtinkerlaunch' update in '/home/deck/stl/prefix'
Sat Apr 13 18:43:58 EDT 2024 INFO - installFilesSteamDeck - Fetching from git seems to have succeeded ok.
Sat Apr 13 18:43:58 EDT 2024 INFO - installDependencyVersionFromURL - Downloading innoextract version automatically from URL 'https://archive.archlinux.org/packages/i/innoextract/innoextract-1.9-8-x86_64.pkg.tar.zst'
Sat Apr 13 18:43:58 EDT 2024 INFO - installDependencyVersionFromURL - curl -Lq "https://archive.archlinux.org/packages/i/innoextract/innoextract-1.9-8-x86_64.pkg.tar.zst" -o "/home/deck/stl/deps/innoextract-1.9-8-x86_64.pkg.tar.zst"
Sat Apr 13 18:43:58 EDT 2024 INFO - fetchAndExtractDependency - Installing 'innoextract-1.9-8-x86_64.pkg.tar.zst' from 'https://archive.archlinux.org/packages/i/innoextract/innoextract-1.9-8-x86_64.pkg.tar.zst' to installation directory '/home/deck/stl/deps'
Sat Apr 13 18:43:58 EDT 2024 WARN - fetchAndExtractDependency - Failed to download dependency 'innoextract-1.9-8-x86_64.pkg.tar.zst', will attempt to continue with installation in case dependency archives already exist at '/home/deck/stl/deps'
Sat Apr 13 18:43:59 EDT 2024 INFO - fetchAndExtractDependency - Found archive in '/home/deck/stl/deps' that is potential match for 'innoextract-1.9-8-x86_64.pkg.tar.zst'
Sat Apr 13 18:43:59 EDT 2024 INFO - fetchAndExtractDependency - Could not find any matching dependency archives in '/home/deck/stl/deps' for 'innoextract-1.9-8-x86_64.pkg.tar.zst' - Assuming this dependency is missing and installation cannot continue

**Comment by ChongaPapi** [comment]
(deck@steamdeck ~)$ steam tinker launch - git
steam.sh[75776]: Running Steam on steamos rolling 64-bit
steam.sh[75776]: STEAM_RUNTIME is enabled automatically
setup.sh[75854]: Steam runtime environment up-to-date!
steam.sh[75776]: Steam client's requirements are satisfied
tid(75904) burning pthread_key_t == 0 so we never use it

**Comment by sonic2kk** [comment]
Attach a full log as a file, don't paste text.

For your second reply, I have no idea what you're trying to do... Command names can't have spaces, and what is `steam tinker launch - git` meant to do?

If you're trying to install from git this way, it's not going to work. You can install from ProtonUp-Qt, or remove your existing installation, download a ZIP from current master (NOT the releases page) or clone the repo, and double-click the `steamtinkerlaunch` script to install it to `~/stl`. You can then remove the downloaded STL.

You also cannot run SteamTinkerLaunch from the commandline unless you add it to PATH yourself. ProtonUp-Qt can do this for you so long as you restart any running terminal instances to update the path, but installing manually won't give you this. Since I don't know how you installed SteamTinkerLaunch I can't tell you if it's on your PATH or not.

If you are unfamiliar with Linux usage, or do not use Linux on your desktop PC, SteamTinkerLaunch is likely not software you want to use as it's for Linux enthusiasts.

Based on the log snippet you did attach though, this sounds like a network issue, not something STL can fix. You may want to check if you can download from the links given via a browser and also via the commandline. The log file gives you the commands SteamTinkerLaunch tries to run. For example, `curl -Lq "https://archive.archlinux.org/packages/i/innoextract/innoextract-1.9-8-x86_64.pkg.tar.zst" -o "/home/deck/stl/deps/innoextract-1.9-8-x86_64.pkg.tar.zst"`. If this fails to run manually, then this is certainly a problem with your network and not something SteamTinkerLaunch can fix.

There have been issues in the past with downloading files over filtered or monitored networks, not specific to SteamTinkerLaunch but found as a result of using SteamTinkerLaunch. Only one user that I can recall ever responded to testing steps and fixed their issue by using a different network (in their case, they couldn't download on their home connection until they restarted their router, but another network worked fine without any changes).
