### ISSUE TITLE
ProtonUp-Qt Flatpak can detect missing dependencies

### ISSUE THREAD

**Issue by madscientist16** [sonic2kk/steamtinkerlaunch#1083]
In https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#dependencies it mentions that ProtonUp-Qt Flatpak cannot detect if there are missing dependencies, but when I tried installing steamtinkerlaunch with ProtonUp-Qt it was able to detect that I had missing dependencies.

**Comment by sonic2kk** [comment]
This is something to raise on the ProtonUp-Qt repo, although I'm not sure how it was able to do that, since Flatpak ProtonUp-Qt shouldn't be able to detect missing dependencies for *any* project by default.

Because the Flatpak is sandboxed, Flatpaks shouldn't be able to be aware of other binaries outside of it's sandbox by default. I'm not even sure opening up the permissions can fix this for ProtonUp-Qt, since it runs in a much more isolated shell. Please double-check if you have any modified Flatpak permissions. You can do this with Flatseal, if you use a recent version of KDE there is a robust Flatpak permissions manager built into the System Settings, and you can also do this from the command line (can't remember the commands off the top of my head, sorry 😅).

Definitely something to raise on the ProtonUp-Qt repo as this wouldn't just affect (or benefit depending on how you look at it) SteamTinkerLaunch. It would also help if you provided screenshots too.

My concern here would be that the Flatpak detection to skip checking dependencies isn't actually working, and ProtonUp-Qt is still checking for them on Flatpak when it shouldn't be, meaning dependencies would always be flagged as missing. Please test if you always get warmed about missing dependencies, and if the warnings reduce/go away once you meet them, and include this in your upstream issues.

Nonetheless thank you for the report! We can revisit the documentation as needed based on upstream discussion.

**Comment by sonic2kk** [comment]
As per further discussion on DavidoTek/ProtonUp-Qt#375, the ProtonUp-Qt Flatpak can detect missing dependencies provided it has access to do so (it should by default).

The wiki has been updated to reflect this: https://github.com/sonic2kk/steamtinkerlaunch/wiki/ProtonUp-Qt/_compare/76c5f70ffbe9c7946fe2ebbf2f460ba50dea279f

Thanks for catching this!
