### ISSUE TITLE
Steam Deck Issue handling NXM Links for MO2

### ISSUE THREAD

**Issue by adinunzio10** [sonic2kk/steamtinkerlaunch#1091]
## System Information
- SteamTinkerLaunch version: master branch
- Distribution: Steam Deck 
- Installation Method: Manual clone from repo and install

## Issue Description
I am having issues with getting the nxm link handler to work. When clicking links in nexus website, it does not trigger a download in MO2.  I am sure it is user-error but cannot find out why.  Figured since I want to help support steam deck support this is a good troubleshooting opportunity.

STL Settings: 

- I am launching MO2 Via game mode. (Launching the game in steam deck desktop mode and it launches STL which launches MO2) 
- In STL Global Settings I confirmed that MO2 compatdata is pointing to the correct STL Location for MO2. 

MO2 Settings:

- I do have link handling enabled in settings
- I am linked to my account successfully

Firefox Settings:

- Firefox handler settings has 'Use System Handler'  Which I found someone else having in #551 but I could not find a solution as it was more about vortex. It did point me to verifying my .desktop application file
- When I try to change the handler, the only option is ask, other, use system handler. if I choose other and then select my desktop file it doesn't seem to accept it and resets back to use system handler. 

Desktop Application File:

- I checked my /home/deck/.local/share/applications and I saw ModOrganizer-steamtinkerlaunch-dl.desktop
- I noticed the file has path set to /home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/Modding/MO2 which I do not think is right
- I changed it to /home/deck/.config/steamtinkerlaunch/compatdata/Fallout New Vegas/pfx/drive_c/Modding/MO2 and restarted STL but it renames the file to -old and regenerates one pointing at .local
- Also tried to change it again and delete /dev/shm/steamtinkerlaunch but it still made the -old and recreated.
- The exec path is properly pointing to /home/deck/stl/prefix/steamtinkerlaunch mo2 u %u

I also tried starting from scratch by removing stl in /dev/shm/steamtinkerlaunch /home/deck/stl and /home/deck/.config/steamtinkerlaunch, uninstalled fallout new Vegas and removed it from both /home/deck/.local/share/Steam/steamapps/compatdata/22380 and /home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/ deleted the MO2 .desktop file.

I then installed again by git clone of this repo master branch and then running /home/deck/stl/steamtinkerlaunch once to set it up and then again with compat add then restarted my steam deck. Installed fallout and set it to stl and ran it, set it to mo2 gui and then configured MO2.  That did not change any of the prior behavior. 

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/15050471/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
I genuinely don't know, and I tell people all the time regardless of platform to simply not use these links.

I have come to the conclusion that these links are just broken (since they rarely work for me in general and not just for MO2). This is not something I am interested in fixing either, sorry, as I hate these mimetype links.

Someone recently submitted a PR to try and fix it with #1082. It didn't cause any regressions and it fixed the issue for them.

Also, it's worth pointing out that modding on SteamOS **is not supported**. I do not endorse modding games on SteamOS, with STL or otherwise.

Closing as unfortunately there have been many attempts to fix this and nothing has worked.

**Comment by adinunzio10** [comment]
Yeah I thought I would at least check to see if I was missing something. I had it working via stl on my desktop when I setup TTW a half year or so ago. I had started over today with a fresh clone of the master branch so since that PR was merged I should have too.   I won't worry about it though as on steam deck it will be easier for me to do most the work via ssh which means I won't use the links anyway.

I understand but am not worried about lack of support/endorsement and would not post modding issues to you.  Wasn't sure if the nxm link handling was something worth looking more into later as other users might ask about in the future. If I decide that in the future I do want to look into it I can do that on my own. 

Anyway thanks for the quick response!

**Comment by sonic2kk** [comment]
In my experience, the link handling works better on desktop (OP of #1082 was probably testing on desktop). It's worked on my PC since forever, and it worked on my laptop (which I haven't switched on in quite a while, it's gathering dust somewhere...). I've never tried on SteamOS but I remember NXM links didn't work on there at all once Firefox Flatpak came into play (HMM mime links don't work, for example).

I understand you haven't tested recently but I don't think anything should've broken on your Linux Desktop, so this issue is likely specific to SteamOS, which is unfortunate but I can't really investigate. Like everything related to SteamOS usage it would have to be a community effort to fix. I wouldn't even know where to begin with investigating it to be completely honest, even if I had a Steam Deck with SteamTinkerLaunch to test on :sweat_smile:

**Comment by adinunzio10** [comment]
Yeah that totally makes sense. I haven't used the desktop recently but I bet it does work fine there. I figured it was more unique to SteamOS which you do not have anyone dedicated to help investigate and test there issues.  

Besides the nxm link , I have STL and MO2 with mods working just fine on my Steam Deck.  In a perfect world I would want to be the 'Steam Deck guy' for STL so we at least have someone testing properly. Like my other comment, not making any promises lol, but if time permits I want to look into things like this (and dependencies discussed yesterday)

**Comment by sonic2kk** [comment]
Any time you can contribute is great and appreciated! Ideally there wouldn't need to be just one, but a bunch of people who can contribute here and there to fix issues they encounter. This is how I got started contributing to STL and is why I ultimately took it over, I was just a user and I would contribute fixes to things I found and help out with issues where I could. My guess though is that the amount of people that are both technical enough and have the time and motivation are low as it is on the Linux Desktop, and even lower on SteamOS, hence the lack of contributions.

There will be zero expectation to contribute regularly, you can work on whatever you want and whenever you want :-) I will be here to review anything you submit anytime.

**Comment by sonic2kk** [comment]
Discussion that may interest you over at #1093 :-)

**Comment by zerodogg** [comment]
@adinunzio10 I'm a bit uncertain about what the issue is here. When you click an nxm:// link, and you tell it to "use system handler", what exactly happens? Nothing? Does /dev/shm/steamtinkerlaunch.log get updated? (and if it does get updated, can you upload it here?)

**Comment by ghost** [comment]
I actually have the same issue about not recognising the NXM Links (also using fallout new vegas on steam deck - latest git as of now, only installed it via ProtonUp-QT / latest git version a few hours ago). Tried running MO2 from both STL from the game itself in steam (w/ compatibility option, game mode), and standalone. This is from game mode, but standalone is the same.

Clicking on one gives this:
<img width="857" alt="image" src="https://github.com/sonic2kk/steamtinkerlaunch/assets/19907098/909cb3ac-bd58-47b7-a026-22efc5aa56ea">

Then selecting the one option that appeared makes a ton of these notifications pop up which happens every time:

<img width="857" alt="image" src="https://github.com/sonic2kk/steamtinkerlaunch/assets/19907098/d36ce297-ca3f-4de5-a6c2-676467fcb8e0">

But nothing happens afterwards. 
steamtinkerlaunch.log does get updated and it looks like it's getting confused at some point near the end, log file here

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/15171248/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
> Clicking on one gives this:

This is the exact issue I remember people having, and I have no idea why this happens on SteamOS but not the Linux Desktop. I can't even blame Firefox Flatpak, because I have a Firefox Flatpak install for testing and it doesn't do this.

> Then selecting the one option that appeared makes a ton of these notifications pop up which happens every time:

This is just SteamTinkerLaunch launching, if you have used SteamTinkerLaunch on SteamOS before for something other than MO2 (which is not the intended use-case, especially on SteamOS where you shouldn't be modding games where it can be helped) you'll have seen this a lot. Everytime SteamTinkerLaunch starts on SteamOS, these notifications appear.

> But nothing happens afterwards.

Did you try using #1096? I suspect this strange and annoying behaviour on SteamOS means that PR will still not work.

Note this comment from @zerodogg in [this comment](https://github.com/sonic2kk/steamtinkerlaunch/issues/1093#issuecomment-2081188436) (note that you shouldn't use the patch from that comment, use #1096 instead which is complete):

> Either way you will need to start MO2 again normally once for steamtinkerlaunch to rewrite the global config file. Then try the links again.Either way you will need to start MO2 again normally once for steamtinkerlaunch to rewrite the global config file. Then try the links again.

This issue and #1093 are not necessarily the same, because SteamOS has a lot of idiosyncrasies on the desktop that make it a godawful experience for a Linux enthusiast tool like SteamTinkerLaunch, so these two issues are still in my mind distinct. You will still likely have to select MO2 from that dialog.

Line of note from your log that may make it a similar issue to #1093 but it may still be a separate issue specific to SteamOS:

```
Tue 30 Apr 22:24:54 IST 2024 ERROR - dlMod2globnexurl - Attempted to download Url 'nxm://newvegas/mods/86405/files/1000129235?key=0CnJ19xUA8U0L8m0ECVvFQ&expires=1714684839&user_id=208764072' for game 'newvegas', but seems like global '/home/deck/.config/steamtinkerlaunch/mo2/dldata/global.conf' has incomplete data - giving up
```

**Comment by zerodogg** [comment]
Reading that steamtinkerlaunch.log file, it does look very much like the same problem from #1093 that #1096 fixes. Give that a try.

I do have a Steam Deck I can try to reproduce the other strangeness on, but it'll probably be a week or so until I have time to do that.
