### ISSUE TITLE
Menu never show up

### ISSUE THREAD

**Issue by EpiChrist** [sonic2kk/steamtinkerlaunch#1105]
## System Information
- SteamTinkerLaunch version: v12.12 
- Distribution: Ubuntu 22.04.4 LTS
- Installation Method: ProtonUp-Qt

## Issue Description
Well, the menu for «Steam Tinker Launch» never show up. For example, I launch «Skyrim Special Edition», and nothing special appear. Only the game launching menu. Of course, the game is playable. Here's the log for it :
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/15293122/steamtinkerlaunch.log)

For an another game, a native one for instance, it crash directly. I try with «Terraria» and here's the log :
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/15293242/steamtinkerlaunch.log)

For some complementary information :
YAD is up to date, I have the version 13.0.
I use the regular steam launcher, not the flatpak one.

**Comment by sonic2kk** [comment]
This sounds like some kind of system issue or user configuration issue.

Have you confirmed that Yad works on your system?

Also, please confirm that for Skyrim, you are using SteamTinkerLaunch as a Compatibility Tool. The log looks a bit odd where the AppID is using the placeholder one. It also looks as though the incoming command for it is `settings`, as though `steamtinkerlaunch settings` was ran instead of the game being ran from Steam.

<hr>

With that out of the way: You should also be using master, v12.12 is not supported. Releases will **never, ever** be supported, which is a big reason why there hasn't been one in over a year. The issue template also already told you to use master. You can install it from ProtonUp-Qt with SteamTinkerLaunch-git, as per the STL [ProtonUp-Qt wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/ProtonUp-Qt#installation).

Once you've installed master, try running SteamTinkerLaunch from the commandline, if you added it to PATH when installing then running `steamtinkerlaunch settings` should be enough. If you get any notable error output.

If you see any errors related to locale (such as "`Locale Not Supported By C Library`"), your system likely has a locale issue. See "[SteamTinkerLaunch starts my game but does not show the Wait Requester](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Troubleshooting#steamtinkerlaunch-starts-my-game-but-does-not-show-the-wait-requester)" on the Troubleshooting wiki page for some loose guidance, but it is NOT prescriptive. Do NOT blindly follow this section, make sure you understand how to find and fix locale issues.

**Comment by EpiChrist** [comment]
> Also, please confirm that for Skyrim, you are using SteamTinkerLaunch as a Compatibility Tool. The log looks a bit odd where the AppID is using the placeholder one. It also looks as though the incoming command for it is settings, as though steamtinkerlaunch settings was ran instead of the game being ran from Steam.

You're gonna laugh. I mixed my log. All my fault for this.

Anyhow, I finally get the «master» version and it **work**. For an unknown reason, I always thinking that the master was the release version.

Thanks for your help!
(Even if you've helped me to figure that I need glasses and sleeping...)

**Comment by sonic2kk** [comment]
No problem, happy gaming!
