### ISSUE TITLE
Hedge Mod Manager stuck on configuring Sonic Colors: Ultimate when installed via SteamTinkerLaunch (Steam Deck)

### ISSUE THREAD

**Issue by Omnicastus** [sonic2kk/steamtinkerlaunch#1142]
**System Information**
- SteamTinkerLaunch Version: v12.12
- Distribution: SteamOS Latest Stable
- Installation Method: Terminal

**Issue Description**
When attempting to install Hedge Mod Manager via the command "steamtinkerlaunch hmm start," it consistently hangs when trying to configure Sonic Colors: Ultimate. The game is a legally purchased Steam copy and has had no modifications made to it.

**Logs**
[steamtinkerlaunch.log](https://github.com/user-attachments/files/16355962/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
No one has stepped forward to help with the Hedge Mod Manager integration in a very long time. The issue comes from issues installing .NET 4.8 if I recall, the only way to get it to work is to keep uninstalling and retrying.

On SteamOS, HedgeModManager is not supported because is almost always is unsuccessful, but it works on the Linux Desktops (I recently re-installed on a fresh Arch installation to mod Sonic Frontiers without issue).

Sorry, there's nothing I can do here. Maybe manually install .NET 4.8 into the Sonic Colors Ultimate prefix with something like Protontricks would work, but even that has mixed success. Modding anything on SteamOS is just a bad idea all around.
