### ISSUE TITLE
Can't prelaunch windows Executeable

### ISSUE THREAD

**Issue by mkuehn94** [sonic2kk/steamtinkerlaunch#1145]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Arch
- Installation Method: AUR

## Issue Description
Hello, thanks for the awesome project. It's just a little comfusing on how to start a windows executable (mod menu) before the main game. I tried running Executables from my linux directory as well as the emulated proton one: "/compatdata/221100/pfx/drive_c/windows/".
However the game won't start, I searched a lot in the issues but couldnt really find anything really.

**Comment by mkuehn94** [comment]
this can be apparently archieved by protontricks

**Comment by sonic2kk** [comment]
There wasn't really enough information here to help, the description wasn't too clear on the steps followed and a log was missing, and majorly you were using v12.12 instead of the latest master branch, which probably caused problems as well.

But if you only wanted to do one thing with SteamTinkerLaunch, glad you found an alternative :+1: Though for the record, these projects are entirely separate and solve independent problems.

**Comment by mkuehn94** [comment]
Found a way to "launch" my program beforehand.
Problem is, the game wont start, only after i stop the exe. 

log is here: https://pastebin.com/raw/sqHERk7S

what i do: 
[
![image](https://github.com/user-attachments/assets/ce15ede2-04ae-47ae-9582-407556223489)
](url)
run command and then go back, start the game. bot working :(

**Comment by sonic2kk** [comment]
One-Time Run is not for this use-case, it is for running installers and such once in a game's prefix. It does not launch the game.

If you want to launch an executable with your game, you're looking for the Custom Command options on the Game Menu. You need to use the "Fork Custom Command" option. Did you check the [Custom Command](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Custom-Command) wiki page? There are also tooltips on the Game Menu for each of these options.

You may need to specify a Wait Time as well depending on when and how you need it to launch.

If you need the executable to launch _after_ your game, you will want to use the "Inject Custom Command" option, which starts the game first and then the custom command. You can also specify a wait time for this as well if you need the custom command to start a specified amount of time _after_ the game launch.

Also, in future, please attach logs as files to GitHub.

**Comment by sonic2kk** [comment]
Also, you are still using the very outdated SteamTinkerLaunch v12.12. Please update to SteamTinkerLaunch from master, you should not use releases unless there is a major system issue preventing you from doing so. I do NOT support anything except the latest commit to master. There have been [hundreds of changes since v12.12](https://github.com/sonic2kk/steamtinkerlaunch/compare/v12.12...f899d3ca8b411fa9fcd7d320c195897b3d53f811) which was released in March 2023.

I also updated the Custom Command wiki page to note about the Steam Linux Runtime option, which you _may_ need to disable if you run into issues with your tool not detecting the game executable.

**Comment by mkuehn94** [comment]
Thank you so so much for your time! I'll get the updated version from git.
however, using these options:
![Bildschirmfoto_20240727_050031](https://github.com/user-attachments/assets/713e6dcc-8d96-4891-b724-791da0f215cb)
fiddled around with a few other "custom command" options, but it never runs my custom command, just the game

and here the logs, not on pastebin :)

[loggg.txt](https://github.com/user-attachments/files/16397951/loggg.txt)

Would mean a lot for me to get this workin really! thank you!

**Comment by sonic2kk** [comment]
>  fiddled around with a few other "custom command" options, but it never runs my custom command, just the game

You didn't enable the "Use Custom Command" option it looks like from the screenshot.

From inspecting the log, you are also still using SteamTinkerLaunch v12.12, do not expect your custom command to work with v12.12. Or anything, for that matter. It is from March 2023, the Steam Client has broken some things since then.

**Comment by mkuehn94** [comment]
> You didn't enable the "Use Custom Command" option it looks like from the screenshot.
> 
> From inspecting the log, you are also still using SteamTinkerLaunch v12.12, do not expect your custom command to work with v12.12.

Thanks again! I did enable "Use Custom Command" first, but will update now

**Comment by sonic2kk** [comment]
The log that you attached doesn't seem to be from an attempted launch of the game. Can you attach a log updated from v12.12 to master, with "Use Custom Command" and "Fork Custom Command" enabled (the screenshot only shows one enabled instead of both for some reason), and attempt to launch your game, and then attach the log?

**Comment by sonic2kk** [comment]
Also I should note that the game "non-binary" that you are running has native Linux support, but you are not using the native Linux version (and Windows custom commands cannot be used with Native titles because there is no prefix to run inside of). If there is a native Linux version of your tool, you can use that instead and use SteamTinkerLaunch as a launch command instead of a compatibility tool.

**Comment by mkuehn94** [comment]
Thanks and thanks again for ur help, any way to buy ur a "coffee" or something? 

> Also I should note that the game "non-binary" that you are running has native Linux support, but you are not using the native Linux version (and Windows custom commands cannot be used with Native titles because there is no prefix to run inside of). If there is a native Linux version of your tool, you can use that instead and use SteamTinkerLaunch as a launch command instead of a compatibility tool.

thanks makes sense, but i set it to use proton deleibratelly

> The log that you attached doesn't seem to be from an attempted launch of the game. Can you attach a log updated from v12.12 to master, with "Use Custom Command" and "Fork Custom Command" enabled (the screenshot only shows one enabled instead of both for some reason), and attempt to launch your game, and then attach the log?

Thanks again, before I post the wrong log again, where is it located?

/home/max/.config/steamtinkerlaunch/logs/
/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log
all off them?

to find the root of the issue, so other people might not have to, i installed a windows only game. build this tool from the repo but it still persists:
![image](https://github.com/user-attachments/assets/72a154f3-b926-4343-85e5-322386da9290)
still the same problem. I try to upload all necessary logs:
[steamtinkerlaunch.log](https://github.com/user-attachments/files/16398015/steamtinkerlaunch.log)
[Legends of Idleon.log](https://github.com/user-attachments/files/16398016/Legends.of.Idleon.log)
[Legends of Idleon.log](https://github.com/user-attachments/files/16398020/Legends.of.Idleon.log)

if there are any more , that are relevant, please let me know.


Edit: might this have to do with .NET executables? I'll try a simple PE binary

**Comment by mkuehn94** [comment]
found a good lternative (ypthon script with just 4 lines)
maybe you should still look into it tho, seems like  bug to me, or im completely incompetent

**Comment by sonic2kk** [comment]
From your log, the custom command is executed.

> Sa 27. Jul 05:38:14 CEST 2024 INFO - prepareLaunch - CheckCustomLaunch:
> Sa 27. Jul 05:38:14 CEST 2024 INFO - checkCustomLaunch - USECUSTOMCMD is set to '1' - trying to start custom program '/home/max/reclass/ReClass.NET/ReClass.NET_Launcher.exe'
> Sa 27. Jul 05:38:14 CEST 2024 INFO - checkCustomLaunch - FORK_CUSTOMCMD is set to 1 - forking the custom program in background and continue
> Sa 27. Jul 05:38:14 CEST 2024 INFO - launchCustomProg - '/home/max/reclass/ReClass.NET/ReClass.NET_Launcher.exe' not found - searching in gamedir
> Sa 27. Jul 05:38:14 CEST 2024 INFO - launchCustomProg - '/home/max/reclass/ReClass.NET/ReClass.NET_Launcher.exe' also not in '/home/max/.local/share/Steam/steamapps/common/Legends of Idleon//home/max/reclass/ReClass.NET/ReClass.NET_Launcher.exe' - checking if absolute path was provided
> Sa 27. Jul 05:38:14 CEST 2024 INFO - launchCustomProg - '/home/max/reclass/ReClass.NET/ReClass.NET_Launcher.exe' is absolute path
Sa 27. Jul 05:38:14 CEST 2024 INFO - launchCustomProg - Changed pwd into the custom directory '/home/max/reclass/ReClass.NET'
Sa 27. Jul 05:38:14 CEST 2024 INFO - launchCustomProg - '/home/max/reclass/ReClass.NET/ReClass.NET_Launcher.exe' seems to be a MS Windows program - starting through proton
Sa 27. Jul 05:38:14 CEST 2024 INFO - launchCustomProg - '/home/max/reclass/ReClass.NET/ReClass.NET_Launcher.exe' seems to be a MS gui program - starting regularly
Sa 27. Jul 05:38:14 CEST 2024 INFO - launchCustomProg - FORK_CUSTOMCMD is set to 1 - forking the custom program in background and continue

> maybe you should still look into it tho

No thanks, you insist on being vague and looking for alternatives instead of collaborating. Custom commands are working fine for me and many users, I am not going to and further I am *unable to* look into *your issue* when you yourself are not willing to help.

I have no idea what you tried, you still won't provide the exact steps you tried or what is going wrong specifically, in detail. But you insist on just looking for any excuse not to use this tool, and that's fine if you don't want to, but please only open issues if you are willing to troubleshoot.

I gave plenty of advice on what you could try (setting a custom command fork delay, or using inject instead and settijng a delay, or disabling the Steam Linux Runtime). If it still doesn't work, it's an issue specific to *your system* that I cannot troubleshoot further.

When opening issues for any project, it depends of course but I find it is good to assume user-error before developer fault. Especially for SteamTinkerLaunch, a LOT of people use this as a troubleshooting forum and simply abandon issues that are purely user-error.

**Comment by mkuehn94** [comment]
how am I being vague? posted all the logs and send you screenshots of the diffferent confirguartions. even went so far to download a DIFFERENT game (after got to it working with another tool) **just** to fix your bug but you didnt seem any intrested. and very disrespectful in the end. 

I am not instredted in your tool, the UI is the worst cuttered shit iv'e evens seen, the settings are buggy, and you wont 
even apperciate if a guy tryied to without any personal gain. I'm sure a lot pf guys will help you this way.

This project will die anyway :)

**Comment by sonic2kk** [comment]
Screenshots of different configurations, and simply dumping logs on a developer, are only part of the equation. You need to actively help in troubleshooting. If you look through previous issues, you'll see those are the ones that get resolutions.

This is also *not* my bug, as I can't re-create it, and custom commands work perfectly fine for me. That's the whole point and why *you* have to investigate just as much as me. I can't help users who don't first help themselves. You had no obligation to try again if you didn't want to and weren't interested in improving this project.

If you dislike the SteamTinkerLaunch UI, please contribute to the Yad project or direct others to do so, to remove the limitations of this project's UI. If you don't believe Yad to be the issue, but the usage of it here, feel free to open a PR. 

> This project will die anyway :)

If I ever stop using it, or lose interest, it sure seems that way :+1:

**Comment by mkuehn94** [comment]
>This is also not my bug
explains a lot.
