### ISSUE TITLE
MO2 will not open or install from menu

### ISSUE THREAD

**Issue by cosmic2325** [sonic2kk/steamtinkerlaunch#1155]
## System Information
- SteamTinkerLaunch version: Git
- Distribution: Linux Mint
- Installation Method: used package manager pacstall

## Issue Description
when i open steamtinkerlaunch and try to click mo2 to run in standalone mode it doesn't do a single thing no idea whats going on?  I understand that mo2 doesn't work  on V12.12 but I'm on version 14 something -3. I'm very new to Linux so please forgive me if I've made some simple mistake or if this is a duplicate post

## Logs
here's what startMO2.log said
creating minidump for the current process
trying file '.\ModOrganizer-2.5.2-20240829T050531.dmp'
writing mini minidump
minidump written correctly
\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00minidump written correctly
I'm unsure what other logs i should post?

Thanks, cosmic

**Comment by sonic2kk** [comment]
The error you pasted is a Wine error that happens when an executable is incompatible with Wine. "Minidumps" are what Wine generates.

It sounds like you may have tried to install ModOrganizer 2 with SteamTinkerLaunch v12.12, or at least a version before `v14.0.20231129-1` (3dc3f301816b287ba36266df9c1c106f0c87147f), and you didn't uninstall ModOrganizer 2 first. Your pasted error output shows you're trying to launch ModOrganizer v2.5.2, which may not be compatible with Wine or at least the Wine version you're trying to use. SteamTinkerLaunch versions after `v14.0.20231129-1` pins the downloaded ModOrganizer 2 version to v2.4.4, but if ModOrganizer 2 was already downloaded or already had a prefix created for it, then this won't work because ModOrganizer 2 is already installed. Remember, all SteamTinkerLaunch does is install and run ModOrganizer 2 in each prefix.

Instructions on [how to remove ModOrganizer 2 are on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#modorganizer-2-v250) specifically for situations where v2.5.0 or above have had attempted installations. Make sure you remove the global prefix and the ModOrganizer 2 installation for any game you may have tried to use ModOrganizer 2 with (if you did anything beyond `steamtinkerlaunch mo2 start`, you probably have ModOrganizer 2 install files in at least one game prefix).

I understand you're new to Linux so that might sound like a lot, but modding games on Linux should ideally be done with a bit of knowledge on Wine prefixes and the Wine filesystem. SteamTinkerLaunch is also created with experienced Linux users in mind, and is not a modding tool and doesn't give support beyond installing tools, and expects some knowledge of how to use Wine.

If you absolutely have to use ModOrganizer 2 v2.5.2, you can verify its compatibility with the Proton version you are using by running it manually without SteamTinkerLaunch, and if you know it works, you can choose that specific installer executable as a custom installer for ModOrganizer 2 in the Global Menu or from the commandline.

I don't believe this is a SteamTinkerLaunch but because this is an issue related to running ModOrganizer 2 v2.5.2 which may have compatibility issues under Wine, and SteamTinkerLaunch pins to v2.4.4.

Good luck!
