### ISSUE TITLE
MO2 - Stream error while parsing setup headers

### ISSUE THREAD

**Issue by MintyGitOut** [sonic2kk/steamtinkerlaunch#1164]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: openSUSE Tumbleweed
- Installation Method: Community Package

## Issue Description

When attempting to install mo2 using the `steamtinkerlaunch mo2 start` command, it simply errors out and fails no matter what I try, even after looking at the troubleshooting section for it.

## Logs

[steamtinkerlaunch.log](https://github.com/user-attachments/files/16923762/steamtinkerlaunch.log)
Along with the command I used to run it and the results:
aidan@BFG9000:~> steamtinkerlaunch mo2 start
Sun Sep  8 04:43:24 PM CDT 2024 INFO - setMO2Vars - USEMO2PROTON is 'none', so using latest Proton-GE 'GE-Proton9-10' automatically
Warning: Unexpected setup data version: 6.3.0
Warning: Unexpected Style value: 77
Warning: Unexpected Uninstall Log Mode value: 18
Warning: Unexpected Auto Boolean value: 3
Stream error while parsing setup headers!
 ├─ detected setup version: 6.3.0
 └─ error reason: basic_ios::clear: iostream error
If you are sure the setup file is not corrupted, consider 
filing a bug report at https://innoextract.constexpr.org/issues
Done with 1 error and 4 warnings.

**Comment by sonic2kk** [comment]
This is likely because you are using SteamTinkerLaunch v12.12, and these are likely errors resulting from Wine. You should uninstall ModOrganizer 2 and then use SteamTinkerLaunch from master to install ModOrganizer 2. Instructions on how to remove ModOrganizer 2.5.X invalid installations can be found on the [SteamTinkerLaunch ModOrganizer 2 wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#modorganizer-2-v250).

You should always use the latest version of SteamTinkerLaunch from `master`. Issues similar to this have been covered in the past, as well as guidance to use the latest version of SteamTinkerLaunch from `master`. Please search the issue tracker before opening issues.

**Comment by MintyGitOut** [comment]
> This is likely because you are using SteamTinkerLaunch v12.12, and these are likely errors resulting from Wine. You should uninstall ModOrganizer 2 and then use SteamTinkerLaunch from master to install ModOrganizer 2. Instructions on how to remove ModOrganizer 2.5.X invalid installations can be found on the [SteamTinkerLaunch ModOrganizer 2 wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#modorganizer-2-v250).
> 
> You should always use the latest version of SteamTinkerLaunch from `master`. Issues similar to this have been covered in the past, as well as guidance to use the latest version of SteamTinkerLaunch from `master`. Please search the issue tracker before opening issues.

Uninstalled the community package and switched to using git with ProtonUp-Qt. Worked great. Thank you and I'm sorry for not trying this earlier
