### ISSUE TITLE
[BUG] Steam Deck "compat add" code ALWAYS runs no matter what STL command is used!

### ISSUE THREAD

**Issue by Arcitec** [sonic2kk/steamtinkerlaunch#1166]
The SteamTinkerLaunch code for Steam Deck integration is currently buggy.

- It always runs `compat add` no matter what command the user gives.
- `~/stl/prefix/steamtinkerlaunch` = "Added compatibility tool."
- `~/stl/prefix/steamtinkerlaunch compat add` = "Added compatibility tool. Added compatibility tool."
- `~/stl/prefix/steamtinkerlaunch compat del` = "Added compatibility tool. Deleted compatibility tool."

The fix is to ONLY run "compat add" when the user specifies "compat add" on the command line.

And in particular, the bare `~/stl/prefix/steamtinkerlaunch` command should ONLY be responsible for downloading Steam Deck dependencies, _not_ adding compat tool (that's always been a separate command for a good reason). :)

All tools that manage STL installations currently run both `~/stl/prefix/steamtinkerlaunch` and `~/stl/prefix/steamtinkerlaunch compat add` in that order, exactly as the wiki says. So this needs to be resolved in a way that keeps that earlier promise, and keeps the purpose of the original, separate STL "compat add/del" commands.

Reference: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#install

**Comment by sonic2kk** [comment]
SteamTinkerLaunch's Steam Deck integration is going to be considered unofficial before release of v14.0. Very few community members came forward to help, and I will never, _ever_ use SteamTinkerLaunch on Steam Deck ever again.

However, I don't see why this is a problem or a bug.

> that's always been a separate command for a good reason. :) [referring to `steamtinkerlaunch compat add`]

On Desktop, yes, but not on Steam Deck. It has always been the case that this runs automatically on Steam Deck since support was added.

> All tools that manage STL installations currently run both

Indeed, but a user may not use these tools. If a user double-clicks the script, it will run `compat add` on Steam Deck.

<hr>

I don't understand how this is a bug, or how this makes it "buggy". Can you elaborate on _why_ this is a bug? I am not disputing that the Steam Deck integration is less than ideal, I fully acknowledge that and have been asking for community contributions since July 2023 (#859). But for this _specific_ report, I would like to understand better why this is a bug. Redundant, perhaps, but not really a bug to my understanding at the moment.

The wiki documentation you linked to looks incorrect and should probably be adjusted, the step to run `steamtinkerlaunch compat add` is invalid. However, I would not refer to this as a "promise."

**Comment by Vysp3r** [comment]
It's not a "bug" since it's not breaking the install process, but it's redundant like you said.
If you say you need to run `steamtinkerlaunch compat add` after running `steamtinkerlaunch` while it already runs it is not ideal.
I guess we could call this a QoL improvement.
It's not what I would expect it to do, but it does not break anything at least.

**Comment by sonic2kk** [comment]
If it's not really breaking anything, I think it's better to keep it. It is redundant on the "happy path", but since Steam Deck is not a reliably supported platform for this project, I would rather keep it for insurance. I do not trust any of the Steam Deck integration to work properly at the moment.

If and when the integration is in a better state, like if people from the community can step up to maintain it if they are passionate enough about the platform, then it could be removed as a minor quality of life enhancement as you said, but only once Steam Deck support can be trusted to work properly. Installing SteamTinkerLaunch for development purposes on my old Steam Deck was enough to put me off using it, I don't have it on my OLED and have no plans to use it there. Steam Deck support won't get ripped out but since I don't use SteamTinkerLaunch on the platform I have plans to put Steam Deck support as some kind of "somewhat works, but is not actively maintained" status.

But for now I don't think this is really an issue. It would be a welcome change if/when Steam Deck support is vastly improved. But for right now, I would sleep better at night with it in there (Steam Deck users lose me enough sleep at night as it is...).
