### ISSUE TITLE
STL can launch from command line but never from Steam

### ISSUE THREAD

**Issue by winteriscariot** [sonic2kk/steamtinkerlaunch#1170]
## System Information
- SteamTinkerLaunch version: steamtinkerlaunch-v12.12
- Installation Method: AUR
- Environment: Arch Linux, Labwc (wlroots wayland)

## Issue Description
I can launch STL using either the desktop file or `steamtinkerlaunch settings` and the menu shows up just fine. Setting the compat tool in Steam to Steam Tinker Launcher and then clicking Play, nothing happens. The game says it's running but no window appears.

I've deleted and readded STL to steam compat tools, restarted steam, can't get it to work.

## Logs

[steamtinkerlaunch.log](https://github.com/user-attachments/files/17090452/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
You are using SteamTinkerLaunch v12.12, which is very out of date. You should try using SteamTinkerLaunch from `master`.  Only the latest commit to `master` is ever supported, releases are not supported. The version you are using is [hundreds of commits behind](https://github.com/sonic2kk/steamtinkerlaunch/compare/v12.12...master) and is from March 2023.

From your log, it looks like this may be a Proton version mismatch loop. Did your Proton version change and you forgot to reboot / remove `/dev/shm/steamtinkerlaunch`? Advice to fix is also on [Troubleshooting wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Troubleshooting#my-game-doesnt-start-with-steamtinkerlaunch)?

**Comment by winteriscariot** [comment]
Thanks for your response, I'll go ahead and install the latest git version and see how it works. FWIW I'm using the latest version in the release section of this repo. I think I did manage to get it to go by just wiping out all custom settings and starting from scratch. Seems like there are a lot of moving parts that can potentially conflict with others (or if I have an out-of-band setting, ie, in steam launch settings).

**Comment by sonic2kk** [comment]
You should not be using the releases section, I was trying to point out that those are not supported. Only the latest commit to master is ever supported. 

> I think I did manage to get it to go by just wiping out all custom settings and starting from scratch. Seems like there are a lot of moving parts that can potentially conflict with others

I don't think so. This was probably because of a Proton version mismatch. You can check the log to see where I'm coming from on that. SteamTinkerLaunch on master has better checks to resolve the mismatch too (refer to [the Changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog) for information on all changes on master currently).

I'm not sure what you mean by "moving parts" either. You never need to clear out all custom settings. Please don't do this when troubleshooting problems.
