### ISSUE TITLE
"ERROR Steam not found"

### ISSUE THREAD

**Issue by o2a2** [sonic2kk/steamtinkerlaunch#1172]
**## System Information**
- SteamTinkerLaunch version: v12.12 
- Distribution: Zorin OS
- Installation Method: Pacstall package manager

**## Issue Description**
_steamtinkerlaunch compat add_ command fails. Steam is not found according to log.

**## Logs**
WARN - setSteamPaths - Steam 'userdata' directory not found, other variables depend on it - Expect problems
grep: : No such file or directory
grep: : No such file or directory
ERROR Steam not found
ERROR - checkIntDeps - Above programs need to be installed to use 'steamtinkerlaunch'
ERROR - checkIntDeps The dependency check can be disabled by enabling 'SKIPINTDEPCHECK' - exiting now

I've had it with this nonsense. Installation went smooth - files are where they should be according to the manual here. Steam is in its default place. Just can't do this merger with compat. mode. Searched a lot and it seems that i'm the only one. "setSteamPaths" gives me impression that i could force data somewhere - probably to the steamtinkerlaunch script in usr/bin area. But that's just an impression.

Best regards.

**Comment by sonic2kk** [comment]
Where is Steam installed on your system? There is no default Steam installation path, it can be in at least five different paths that I know of and that's just Steam native. Here are the ones I know of, normally a handful of these exists and are symlinks but I have seen cases for other projects where each of these _are_ the Steam root
- `~/.local/share/Steam`
- `~/.steam/root`
- `~/.steam/steam`
- `~/.steam/deblain-installation`
- `~/.steam`

Can you give any further information? I can't help you if you don't even tell me where Steam is installed. Most of your report is not that constructive, i.e. "I've had it with this nonsense". You're also using an outdated version of SteamTinkerLaunch, v12.12 is from March 2023, although I don't expect that that is causing the problems.

If you are truly tired of this nonsense, nothing is forcing you to use SteamTinkerLaunch. Sorry, I just feel like this attitude is disrespectful.

> "setSteamPaths" gives me impression that i could force data somewhere - probably to the steamtinkerlaunch script in usr/bin area. But that's just an impression.

No, that is the function name that sets the variables for Steam paths. You shouldn't force data anywhere.

<hr>

Just a hunch, but are you using Steam Snap or Steam Flatpak by any chance? It seems like Zorin is based on Ubuntu, which uses Snaps and I have heard it tends to prefer Snaps (I have not used anything Debian-based in 8 years, including Ubuntu, so I'm not familiar myself).

**Comment by sonic2kk** [comment]
Actually, checking the code, the part of the code that prints "ERROR Steam not found" does this based on whether it can run the `steam` command: https://github.com/sonic2kk/steamtinkerlaunch/blob/c174a06f1b98d2aa523fe93e2afaed2713f46563/steamtinkerlaunch#L18664

If you would like to check, you can try running `steam` from the commandline and seeing if it can execute successfully. If it says "command not found" then you are likely not using a typical Steam Native installation and may be using an alternative repackaging. You can emulate the check that SteamTinkerLaunch does by pasting the following if/else into the commandline:  `if [ ! -x "$(command -v "steam")" ]; then echo "Could not find Steam, there is no Steam command available on the system."; else echo "Found Steam, it is at '$(which steam)'."; fi`.
- `command -v "steam"` returns the path to the Steam Client (it checks how the command is seen by the shell you're in, i.e. it will expand it out here)
- `-x` checks if the file is executable (and exists)
- `which steam` in this case is equivalent to `command -v steam`, it just gets the path
- The overarching example is an if/else check to say "If there is no executable Steam file found from `steam`, then print that Steam is not found. Otherwise, print that Steam _was_ found and display its path." 

On my system, this returns that the `steam` executable is at `/usr/bin/steam`.

So I expect this is not specifically that the Steam path doesn't exist, although that may be part of it. This merits checking what kind of Steam installation you have. If running `steam` from the terminal does not work then you may have some other kind of Steam installation.
- Steam Snap is probably not supported, there is no code to support it on this side, maybe someone has an unofficial Snap (Note: Steam Snap is discouraged by Valve as well).
    - Steam Snap can be in two different locations to my knowledge.
        - The traditional location seems to be `~/snap/steam/common` (or `~/.snap/steam/common`? Not sure, I don't use Snaps...)
        - To my understanding a new configuration can be used which can place Steam Snap at `~/.snap/data/steam` if a newer type of containment is used.
- Flatpak is supported on a best-effort basis on this side and by an extremely dedicated maintainer, but is installed separately from this repository, it is over at [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch](https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch). You can find more information on the Flatpak version on the [Steam Flatpak wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Flatpak).
    - Steam Flatpak's install location is always under `~/.var/app/com.valvesoftware.Steam/data/Steam`. Maybe there are other paths too, but this is the primary one I know of and that other applications check for.

**Comment by o2a2** [comment]
Wasn't meant to be disrespectful and if it was then **i'm sorry**. Hah... And i guess jokes on me. I've burned so many hours trying to fix this one small issue, only to overlook the most obvious way.

My steam path: /home/machine_id/.var/app/com.valvesoftware.Steam/.local/share/
Used version 12.12 because its marked as latest - maybe i'm reading github incorrectly; im not a very active user here, this template is designed for devs i assume.
Steam software is from flathub. Zorin has this neat library ready OOB. And thats where i found what i was looking for all along. I could - from the very start - install Steam Tinker Launch there. With a push of a button, no more, no less. And of course everything works now. Jesus Christ :P... 

Thank You very much for giving me so much of your time and all the details. I've found the answer only after reading them. And sorry, once again :].

**Comment by sonic2kk** [comment]
That path you have given is the Steam Flatpak path. v12.12 is marked as the latest _release_, but you should always use the latest commit to master. GitHub also tells you that v12.12 is from March 2023, but that there have been 200+ commits since then.

As you've figured out, you cannot use SteamTinkerLaunch from here with Steam Flatpak, you must use Flatpak SteamTinkerLaunch. This is also noted on the [Installation wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#steam-flatpak).

> im not a very active user here, this template is designed for devs i assume.

SteamTinkerLaunch is a tool made for Linux enthusiasts and has possibly gravitated more towards being a dev-ish tool(?), but the template is not really "for devs". It is just expected that users follow it and use the latest commit to master. I wanted to get rid of releases altogether, but that was not well received. I don't care for stable releases when using the latest commit is easy.
