### ISSUE TITLE
shader repositories not available in "game shaders" menu. what am i doing wrong?

### ISSUE THREAD

**Issue by dumbledurf** [sonic2kk/steamtinkerlaunch#1180]
## System Information
- SteamTinkerLaunch version:  v12.12  
- Distribution: steamOS, steamdeck
- Installation Method: protonup-qt

## Issue Description
i added links to shader repositories in repocustomlist.txt following the proper formatting and they show up in "shader repos" menu but not in "game shaders" menu. only AstrayFX is on there but that came with STL when i installed it. i know this isnt a proper bug report because im probably doing it wrong but i would appreciate a hint. thank you the tool.

[repocustomlist.txt](https://github.com/user-attachments/files/17197458/repocustomlist.txt)

**Comment by zany130** [comment]
1. version 12.12 is old. the latest version is 14.0 though to get it on protonup you need to enable advanced mode in the about menu. There have been tweaks to how reshade works since 12.12 such as making it more streamlined and easy to use ( i think we had sepperate options for installing and enabling the reshade .dll :sweat_smile: )

2. You do not need to add repos into the repocustomlist.txt that is only for shader repos that are not available on the official repo list at https://www.pcgamingwiki.com/wiki/ReShade#List_of_known_shader_repositories all the repos you are trying to use are listed there so steamtinkerlaunch will automaticly find them and download them by default assuming you enabled them, which brings me to the third point 

3. even if you had repos into the custom list you still need to enable them in shader repo option
 and then install them into the game directory using the game shaders option
 
 all of this should be documented here https://github.com/frostworx/steamtinkerlaunch/wiki/ReShade
 
 If anything is unclear or missing in the wiki page please let me know

**Comment by dumbledurf** [comment]
Thank you for pointing all this out! That helps alot!

**Comment by zany130** [comment]
NP

reading the wiki over maybe it can be clarified

that the Shader repos option is for downloading  the repos into your `STLSHADDIR	` (by default  `~/.config/steamtinkerlaunch/downloads/shaders/`) 

then the Game Shaders option is for linking the shaders you want into the right directory in the game

BTW you can and should have more repos enabled in the Shader repos option vs the Game Shader repo option

think of Shader repos as all the repos you MAY possible want to use in any game (so a global list) and Game Shaders are the ones you want to specifically use for that game (so a per game list)

**Comment by sonic2kk** [comment]
Thanks a ton @zany130!

If there is anything that can be improved here documentation-wise, I think you have permission to edit the wiki, so please go ahead and improve anything you think is unclear or otherwise could be better :-)
