### ISSUE TITLE
[Feature Request] Support for umu-launcher for non-Steam games

### ISSUE THREAD

**Issue by Jonathing** [sonic2kk/steamtinkerlaunch#1183]
## System Information
- SteamTinkerLaunch version:  `v14.0.20241003-2`
- Distribution:  Nobara Linux 40 (KDE Plasma)

## Feature Description

[umu-launcher](https://github.com/Open-Wine-Components/umu-launcher) recently had its [first release](https://github.com/Open-Wine-Components/umu-launcher/releases/tag/1.1.1), so I was wondering if support for umu-launcher for non-Steam games would be on the table. The main use of this would be to benefit from [umu-protonfixes](https://github.com/Open-Wine-Components/umu-protonfixes), that have historically been included with GE-Proton, for non-Steam games.

The Open Wine Components team went into detail into how it works on their README and it looks to be a custom wrapper over both Steam Linux Runtime and Proton. The only noticeable difference I see is that their instructions do not make any mention of the reaper command. I'm not sure how that would be dealt with by STL. I searched for "reaper" in umu-launcher's repo and didn't find anything pointing to them using it.

I have a passing interest in implementing this myself but I've tried reading and taking in the monolithic bash script and it's honestly incredibly overwhelming. Props to you for what you do :+1:. But, if you need me to keep trying to take a crack at it I can.

**Comment by sonic2kk** [comment]
The main benefit of `umu-launcher` is really to use the Steam Linux Runtime outside of Steam, which is not relevant for SteamTinkerLaunch which already uses the Steam Linux Runtime. Plus, SteamTinkerLaunch already lets you toggle between using and not using the Steam Linux Runtime. I could see this being difficult or impossible to do if we were to use Umu.

I don't think we need to integrate with umu since we can just use GE-Proton for Non-Steam Games, which will give us the benefit of getting those Proton fixes. If there is a way we could integrate umu-protonfixes with non-GE-Proton versions, however, I would be interested in supporting this. Although I couldn't find any information on how to do this on the Readme, and it is possibly not intended to be used this way; It may be intended to be used as part of a Proton version, and therefore would be up to other Proton versions to integrate with (i.e. Proton-tkg).

If you mean for Non-Steam Games in the sense of games not launched via Steam, this is not supported by SteamTinkerLaunch. Umu's main benefit is for users who do not wish to use Steam to launch their games, which does not apply to this project.

Let me know if I have misunderstood, but I don't think Umu is relevant to this project.

**Comment by Jonathing** [comment]
Likely not. Though, I have historically had weird issues with running GE-Proton on non-Steam games even within Steam. I'll keep poking around at umu-protonfixes specifically since that's the main incentive for looking at something like this in the first place. Thanks!

**Comment by ninetailedtori** [comment]
It might help with my issues with vortex, actually. It seems to keep failing due to missing kernel32.dll, but I've reinstalled proton GE through STL and even outside, several times, I don't understand the issue very much. Attempting to launch with Proton non-GE will fail, and I'm uncertain if it's possible to test vortex starting with umu-run, because I can't really work out the STL vortex settings hahah.

**Comment by sonic2kk** [comment]
`kernel32.dll` errors, when they cause problems (as they are usually harmless) usually come from an outdated Wineprefix or an incompatibility from the tool with Wine. Launching Vortex or ModOrganizer 2 with a new version of Proton in that same prefix is a problem because it uses raw Wine and not the Proton script which manages the prefix.

This has nothing to do with umu, and umu is not meant for use with Steam.

**Comment by ninetailedtori** [comment]
Oh I see. So I just have to update the Wineprefix version then. Nvm then hahah. Why not for non-Steam games though? There's been a history of weird issues where Proton doesn't work for some non-Steam games but Wine does, so it would be cool to use umu for those.
