### ISSUE TITLE
Steamtinkerlaunch runs during "updating executable stage" with BO1 and BO2

### ISSUE THREAD

**Issue by sjp761** [sonic2kk/steamtinkerlaunch#1186]
## System Information
- SteamTinkerLaunch version: Latest git commit as of 10/17/24
- Distribution: Fedora
- Installation Method: Personal git build spec file 

## Issue Description
When running a steam game that has an updating executable stage. Steamtinkerlaunch seems to run during that unintentionally. This is most prominent with Black ops 1 and 2 and steam.

## Logs

[steamtinkerlaunch.log](https://github.com/user-attachments/files/17426755/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
I don't understand what phrase you're referring to. What is the "Update Executable" stage? Is this some kind of setup phase specific to Black Ops 1/2, or is this a setup phase from Steam? SteamTinkerLaunch will run when the Steam Client tells it to run, and sometimes it will run tools at unusual steps, probably the strangest part to me is that it runs SteamTinkerLaunch _most of the time_ when the Steam Client itself is opened.

If this comes from the game, there is nothing I can do. If this comes from Steam, it would be tricky to try and workaround I would imagine as we'd have to guess if an execution is one we want to skip. I can see, for example, in your log there is the following command: `run /home/user/.local/share/Steam/legacycompat/steamservice.exe /extractguids /mnt/games/SteamLibrary/steamapps/common/Call of Duty Black Ops II/t6zm.exe` -- We would have to guess if there are some times we should skip SteamTinkerLaunch, but it becomes a bit tricky to do so. That is, if this is a log from that specific stage and not from the game launch (which I am unable to tell from the log if this is a game launch or an executable running when you wouldn't want it to).

Overall, I need information on what the problem is here, what makes this a bug? Is SteamTinkerLaunch loading the menu, or just running in the background? I don't think I have ever seen any kind of "updating executable stage" so I'm not sure if I can test this, and any game I have played with SteamTinkerLaunch in the past has never had this problem.

If this is just a case of SteamTinkerLaunch running in the background, then I don't think this is worth trying to fix, and may not be possible to fix if this just comes directly from the Steam Client.

NOTE: If the menu _is_ showing, Luxtorpeda faced a similar issue recently where it would launch the Main Menu every time the Steam Client opened (https://github.com/luxtorpeda-dev/luxtorpeda/commit/672f5eb69154d9fcd9e13205c79c66240af26759). But SteamTinkerLaunch was never affected by this, and their fix is probably not applicable to us (as we allow launching from Steam without `SteamAppId` defined I believe).

**Comment by sonic2kk** [comment]
Closing due to lack of response, please comment if you have anything more to add to this issue.
