### ISSUE TITLE
I strugging to install yad on Ubuntu

### ISSUE THREAD

**Issue by linix86x** [sonic2kk/steamtinkerlaunch#1200]
I found this ppa in its seams to have a updated version of yad and I sure is this good to install

https://launchpad.net/~fbostanci/+archive/ubuntu/distroguide

**Comment by fishslap135** [comment]
ran into this issue myself, im new to this kinda stuff so my temporary solution is very sketchy, open the steamtinkerlaunch text file (located in usr/bin/) and change the two "minyad" to your current version number (eg. mine was from 7.2 to 0.40.0)

**Comment by HanPrower** [comment]
Wait, is Ubuntu/Debian still building yad from the old Sourceforge repo, instead of the Github repo?

Sourceforge, not updated since 2017: https://sourceforge.net/projects/yad-dialog/

vs GitHub updated in July: https://github.com/v1cont/yad

Both by v1cont.

You might want to bring this up with your chosen distribution, not here, as to why you're having issues.

Also STL already has specific installation instructions for Ubuntu based distros:
https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#ubuntu-and-ubuntu-based-distributions-pop_os-linux-mint-etc

**Comment by linix86x** [comment]
I came across this reddit post and the second comment solution worked https://www.reddit.com/r/linux_gaming/comments/1036rqh/how_do_you_actually_install_steamtinkerlaunch_it/

**Comment by sonic2kk** [comment]
This issue tracker is not the place to discuss issues installing third-party packages on your distribution. As @HanPrower correctly pointed out, there are instructions for Debian-based distributions that do not package an up-to-date Yad, and further this issue should be brought up to your distribution.

Yad is a dependency of SteamTinkerLaunch, but it isn't created, developed, or maintained here.
