### ISSUE TITLE
Can't access wiki page

### ISSUE THREAD

**Issue by Caitlynmcc234** [sonic2kk/steamtinkerlaunch#1202]
I cant access this wiki page: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Custom-Program
![image](https://github.com/user-attachments/assets/2b7c15f0-24fc-4a19-befa-755cf6c17656)

**Comment by CaitlynMcClelland** [comment]
nvm

**Comment by sonic2kk** [comment]
Sounds like a link is wrong somewhere. Where did you find this link and where should we update it?

**Comment by CaitlynMcClelland** [comment]
![image](https://github.com/user-attachments/assets/6ffd36f5-fa87-45c8-a676-88a25a44e5a6)
this doesnt work, but this link on google does:
https://github.com/sonic2kk/steamtinkerlaunch/wiki/Custom-Command

**Comment by CaitlynMcClelland** [comment]
this is where it was going to before
https://github.com/frostworx/steamtinkerlaunch/wiki/Custom-Program

**Comment by sonic2kk** [comment]
Ah, seems the sidebar link needs to be changed from pointing to "Custom Program" to pointing to "Custom Command" as the page was renamed.

I have fixed this on the wiki now, and updated links on the sidebar to use `sonic2kk/steamtinkerlaunch` as opposed to `frostworx/steamtinkerlaunch` (the creator and previous maintainer). GitHub redirects, but I figured I'd update the links since I was here :-)

Thanks! This issue can be closed now.
