### ISSUE TITLE
Floating Window for configuration incorrect size

### ISSUE THREAD

**Issue by nepnep1111** [sonic2kk/steamtinkerlaunch#169]
At least of the last update the STL gui has been much smaller than before making configuration a pain as most of the options aren't visible. This has been an issue than the Alea Milestone release. I am providing a log and photo of the issue. The issue might be an issue with my configuration but I can't confirm that.
![window](https://user-images.githubusercontent.com/28652514/101687492-32335c00-3a30-11eb-8ac1-fcf65fdaf238.png)
[379720.log](https://github.com/frostworx/steamtinkerlaunch/files/5668664/379720.log)

**Comment by frostworx** [comment]
You know that all windows can be scaled and that the size is autosaved _(until the user didn't disable the option)_, do you?
By default the window decoration is disabled (can be enabled as well), so scaling works with alt+ RMB.
That's why I didn't spend much time in adjusting the [default scaling factors ](https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L945)

**Comment by nepnep1111** [comment]
Window decorations allowed for manual resizing of the window.
