### ISSUE TITLE
Exit button in favorites menu

### ISSUE THREAD

**Issue by gu1ll0me** [sonic2kk/steamtinkerlaunch#182]
In the selection menu, the exit button closes SteamTinkerLaunch and does not start the game - this is the action I expected. But in the favorites menu, the same button starts the game. So if we just want to see the options in the favorites menu without starting the game, we have to return to the selection and use the exit button.

Shouldn't this button have the same behaviour that the selection menu?

Thanks.

**Comment by frostworx** [comment]
I first didn't understand what you mean, because the favorites menu doesn't have an "Exit" button in default mode.
You apparently meant the favorites set as default menu. There this issue is reproducible and this is clearly a bug.
Should be simple to fix and will probably be pushed with one of the next commits.
Good find!

**Comment by gu1ll0me** [comment]
Yes, indeed, I set the favorites menu as default.

Thank you.

**Comment by frostworx** [comment]
Thanks for confirmation!
The bug should be fixed with
https://github.com/frostworx/steamtinkerlaunch/commit/25097936b410c7ba16719e08d190c90d3104b4ad

**Comment by frostworx** [comment]
Please report back and close the issue when you can confirm the fix.
Thanks.

**Comment by gu1ll0me** [comment]
Works for me. Thanks.
