### ISSUE TITLE
Giana (again)

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#187]
Giana still causes multiple problems:
- the MP10Setup.exe download src (web.archive.org) should be replaced with something more stable. wget also returns 403 here, looks like they changed something. If you know a good download url feel free to share it here!
# md5sum MP10Setup.exe
e57645c5ab34485d56d019aaa17c3150  MP10Setup.exe

- The required proton version is set to "proton-5.0-10b", but is not forced. Might be a better solution to add OVERRIDEPROTON="1" to the tweaks to force this version

**Comment by frostworx** [comment]
"Item not available
The item is not available due to issues with the item's content."

I think I'll drop Giana completely then.

**Comment by michaelneverwins** [comment]
The wayback machine says the MP10Setup.exe URL was crawled "510 times between March 3, 2005 and January 26, 2021" (although it looks like all captures since mid-2020 were 404s). Could the problem be with just the one snapshot you're using? Or is this a matter of `archive.org` having not-so-great servers?

**Comment by frostworx** [comment]
Buried with https://github.com/frostworx/steamtinkerlaunch/commit/2015b77100a2909043f090dea8e4516f00bc3c7a
