### ISSUE TITLE
Vortex: NXM links not working

### ISSUE THREAD

**Issue by emersonrp** [sonic2kk/steamtinkerlaunch#260]
When I click on a "Mod Manager Download" link at Nexus, I was delighted and surprised when Firefox offered to open it with "Vortex (SteamTinkerLaunch - stl)" but if I go ahead, nothing happens in my (already-running) Vortex.  I'm not at all sure what all of the moving parts are to getting something inside Wine to be a protocol handler, so I'm not sure where to go next to try to debug this.  Any thoughts, anyone?  (Manjaro; stl v6.10 from AUR; Proton 6.3; trying to mod Oblivion, if it matters.)

**Comment by frostworx** [comment]
Firefox offers "Vortex (SteamTinkerLaunch - stl)", because the desktop file `~/.local/share/applications/vortex-stl-dl.desktop`
is created, if vortex is installed via stl.
Maybe one of the paths used during installation changed meanwhile and therefore the desktop file doesn't work.
Please check if this is the problem.
When you rename the desktop file, stl will create a new one, so you can also check if your vortex settings are correct (most are in the global.conf) and simple let it recreate.
One of the changes of the lat release was
`Every occurrence of 'compdata' was replaced with 'compatdata' - make sure to update your VORTEXCOMPDATA accordingly if you already installed Vortex` (see [here](https://github.com/frostworx/steamtinkerlaunch/releases/tag/v6.10)), which could be related as well.

**Comment by frostworx** [comment]
missing feedback, invalid
