### ISSUE TITLE
Can't set STL as default Compatibility Tool

### ISSUE THREAD

**Issue by UltraBlackLinux** [sonic2kk/steamtinkerlaunch#278]
Hey there,
I am having some problems with setting STL as the default compatbility tool, like this: 
![Screenshot_35](https://user-images.githubusercontent.com/62404294/127213548-94575a6d-0851-48ed-b277-a8cb29fc4ee5.png)
Steam just unchecks the checkbox after restarting it, and defaults it back to proton.
Is there something I can do about this? I don't want to force proton for all games, including the ones that support linux.
Thanks!

**Comment by frostworx** [comment]
There's nothing I can do about it, as it is a steam and not a steamtinkerlaunch issue.
But steam should set "Steam Tinker Launch" as default compatibility tool anyway.
Just choose any game and press the "I"nfo button, to check if it is mentions "Steam Tinker Launch was selected from you for this title" (or similar, it is in german here)

**Comment by frostworx** [comment]
Just wanted to add a comment in this [wiki entry](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Compatibility-Tool),
just to find out that I already do so :)

**Comment by UltraBlackLinux** [comment]
Well I don't want to set it up manually for every game (it's not the default option), and the global option does not change the game's compatibility options individally.
As steam always deselects it, I thought this might be an issue with STL, as it acceps proton - There must be a reason...

**Comment by frostworx** [comment]
So, did you actually check my previous post *("I"nfo button)*?

**Comment by frostworx** [comment]
Well Steam unchecks **every** external compatibility tool here (reproducible with boxtron, luxtorpeda, proton-ge, roberta, steamtinkerlaunch)_.
"The Enable Steam Play for all other titles" checkbox is unchecked with every single one and the "Run other titles with:" dropdown always falls back to Boxtron here _(probably just because it is the first in the alphabet)_
Like already said, the selected compatibility tool **is set anyway** for all other games.
This is clearly a steam bug.

**Comment by UltraBlackLinux** [comment]
> So, did you actually check my previous post *("I"nfo button)*?
I don't get what you mean by that - the game's properties don't show a comp tool

**Comment by frostworx** [comment]
![compat-info](https://user-images.githubusercontent.com/8840590/127312746-1acf61a8-dd14-4320-a6e9-b9925c3270ff.png)

despite

![despite](https://user-images.githubusercontent.com/8840590/127312914-40f46194-1376-4bfa-a296-594279d767ff.png)

**Comment by UltraBlackLinux** [comment]
> ![compat-info]https://user-images.githubusercontent.com/8840590/127312746-1acf61a8-dd14-4320-a6e9-b9925c3270ff.png
>
> despite
> 
> ![despite]https://user-images.githubusercontent.com/8840590/127312914-40f46194-1376-4bfa-a296-594279d767ff.png

Oh I see - Sorry, I have never used that button. Okay, so it actually uses STL despite of it unchecking the checkbox and showing proton GE - Weird.
Thanks for your help anyways.

**Comment by frostworx** [comment]
No problem, thanks for confirming!

**Comment by MithicSpirit** [comment]
I was also having this issue, but it wasn't using STL regardless (I couldn't even run games since steam didn't have one set). For anyone also having this issue, this is what worked for me (likely not officially supported, ymmv, and will probably break eventually with an update): 
1. Set default compat tool to anything that works fine (e.g. Proton experimental)
2. completely close out of Steam
3. open the file `~/.local/share/Steam/config/config.vdf` in a text editor
4. Search for the text `"CompatToolMapping"`, which should be a dictionary/map
5. Find the entry `"0"` in that dictionary
6. Change the value of `"name"` in `"0"` to `"Proton-stl"`, here's what that section should be looking like, excluding override entries for other games (indention removed for readability):
```
"CompatToolMapping"
{
	"0"
	{
		"name"		"Proton-stl"
		"config"		""
		"Priority"		"75"
	}
}
```
7. You may open steam again and it should work fine, but note that it still won't show up as being enabled in the settings

**Comment by frostworx** [comment]
Good to know, thx @MithicSpirit.
It already looks exactly like this in my config, so maybe they closed something down here.

**Comment by frostworx** [comment]
Added a note in the [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Compatibility-Tool)
