### ISSUE TITLE
Steam Launch Option not working in v6.13

### ISSUE THREAD

**Issue by rodrigo21** [sonic2kk/steamtinkerlaunch#279]
After updating to v6.13 the Steam Launch Option using **stl %command%** doesn't work anymaore. Downgrading to v6.10 make stl work again.
Steam Compatibility Tool is working fine but gamescope is broken when using PROTON_USE_WINED3D. This is also broken in v6.10.

STL log for v6.13 and using Steam Launch Option: [stl.log](https://github.com/frostworx/steamtinkerlaunch/files/6889707/stl.log)

**Comment by frostworx** [comment]
Thanks for reporting. I guess `stl %command%` broke because of the changed launch process from steam described [here](https://github.com/frostworx/steamtinkerlaunch/issues/269). Will try to find a solution.


I'd guess gamescope doesn't simply work with `PROTON_USE_WINED3D` then _(independent from stl)_.
There is not much I could do there _(automatic disabling of one of them isn't nice imho)_

**Comment by frostworx** [comment]
Sorry, I replied before having checked your log.
In fact it is stopping with the recently introduced steam reaper command line _(so it is above issue)_.
I hope the reaper didn't break this forever.

**Comment by rodrigo21** [comment]
gamescope works with PROTON_USE_WINED3D, I'm using **PROTON_USE_WINED3D=1 ENABLE_VKBASALT=1 mangohud gamemoderun gamescope -W 1920 -H 1080 -b -- %command%** and it runs fine.

If it's a problem with Steam then you can close the issue and thanks for stl, it's a great tool.

**Comment by frostworx** [comment]
ok, thanks for clarification _(and for the nice feedback :))_.
I'll migrate the PROTON_USE_WINED3D/gamescope part then into a new issue.

**Comment by frostworx** [comment]
Opened a new issue [here](https://github.com/frostworx/steamtinkerlaunch/issues/280), would be nice if you'd keep an eye on it :)

Back to the Steam launch option:
How important is the stl %command% functionality for you?
I personally barely use it _(only for a handful of native linux games)_, and have no idea if people tend to use it generally.
Can't promise that I can fix the "reaper problem", so I might drop the launch option completely _(although I would not like it to be forced to do so)_

**Comment by rodrigo21** [comment]
I was using stl %command% for all my proton games and start using the compatibility tool today when v6.13 stopped working.
Why don't you revert to what v6.10 was doing as it still works? When I downgraded to test it was working.
But the compatibility tool it's great too.

**Comment by frostworx** [comment]
I possibly can't revert, because steam changed their internal game start command _(using the `reaper` described [here](https://github.com/frostworx/steamtinkerlaunch/issues/269))_.
I just analyzed the steam env var and command line differences between launching as launch option and compatibility tool, and check if the steam internal change can be reverted from my side, but a) can't promise anything b) I'm not sure if this is the right way to go

**Comment by frostworx** [comment]
*thinking loud for spreading some possibly interesting findings*:

The switch to the reaper launch command _(indirectly)_ has to do with the [Steam-Linux-Runtime](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Linux-Runtime), because the way how it is transferred has changed with that new command.

Now, when starting a game via` stl %command%`
`SteamLinuxRuntime` still shows up in the launch command *(which changed very much though anyway and therefore probably needs further investigation)*
and the env variable
`STEAM_COMPAT_TOOL_PATHS` is set
*(f.e. `STEAM_COMPAT_TOOL_PATHS=/PATH/TO/steamapps/common/Proton 6.3:/PATH/TO/steamapps/common/SteamLinuxRuntime_soldier`)*

When starting the game using stl as compatibility tool *(so with every compatibility tool generally)*
the env variable `STEAM_COMPAT_TOOL_PATHS` is empty
and the launch command is still the same, so the Steam-Linux-Runtime is basically always disabled
like it "always" was, like described [here](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Linux-Runtime)

**Comment by Termuellinator** [comment]
> How important is the stl %command% functionality for you?

For me it's very important (i haven't touched the compatibility-tool way at all until now ^^)  - and as i tend to only buy native games (at least outside bundles and so on), it would be a shame if that stopped working/i had to stay at 6.10 ^^

What i'm a little confused about is that you are saying it's due to the `reaper`-changes, but after downgrading to 6.10 again, it still works flawless. So it must (at least in part) something that changed between 6.10 and 6.13 - or does 6.10 use a workflow that is depreciated by steam and will stop working in the future?

**Comment by frostworx** [comment]
Thanks for the feedback,  @Termuellinator!
You're right, I  haven't expressed very good.
In fact it is due to the reaper changes, but my [initial "fix"](https://github.com/frostworx/steamtinkerlaunch/issues/269)
introduced with 6.13 hasn't actually fixed anything, but tried to pass through the original reaper command without any further stl interaction, which apparently didn't work correctly with every constellation.
I'm just debugging it and I'm pretty confident that I can provide a fix shortly, by expanding the setGameVars function, but generally speaking this is a moving target and could always break/change *(In fact it seems to have already changed since I discovered the reaper line in above issue, but not 100% sure yet)*

**Comment by frostworx** [comment]
This is more complicated than expected. _(looks like it needs a bigger rewrite for the whole command line filtering/separating to be sane completely)_

I'm offline for about a week starting this Friday, so there's not much time left before.

I just pushed an initial WIP fix though.
Would be nice, if you would test it a bit as well _(ideally both for command line and as compatibility tool, and also both, maybe even
with windows and linux games)_.
Every run will generate a line in the the debug file `/tmp/stl-reaper-slr-strategy-DEBUG-XXXXXXXXXXX`

Would be very appreciated if you'd help by checking if all assumptions in the file are correct and if the game started as expected.

**Comment by Termuellinator** [comment]
Oh first glance (only tried one native game for now), that seems to work again, yes :+1: 
i launched the game with only stl %command% launch option, no compat tool set and get:
`Life is Strange - Before the Storm (554620) - HAVESCTP='0', but also HAVEREAP='1' - assuming stl is set to both command and compat tool - steam doesn't provide STEAM_COMPAT_TOOL_PATHS, so having to cutting out the reaper line to continue; HAVESLR='0'`
I guess that's what you mean with assumptions? If so, it's not correct in that case ^^

**Comment by frostworx** [comment]
Thanks for testing!
Hah **BINGO**, looks like you found a new constellation indeed, which maybe needs to be covered as well:
`no compat too set at all` 👍
Properly closing the whole issue probably needs some time, as I try to rewrite it as future-proof as possible.
But good to hear you can at least play until then :)

**Comment by Termuellinator** [comment]
i'll see if i can do some more tests with non-native games in different combinations and let you know if those assumptions match :)

**Comment by frostworx** [comment]
Thanks a lot! :)

**Comment by rodrigo21** [comment]
stl %command% is working again with the latest git master with Proton:
`qua 28 jul 2021 12:44:31 -03 - Kingsway (588950) - HAVESCTP='1', and HAVEREAP='1' - assuming stl is as used as command line tool - cutting out the base game command to continue; HAVESLR='1'
`

**Comment by frostworx** [comment]
nice, thx for testing as well!
So looks like it is usable enough, that I can go onto the planned short trip at least :)

**Comment by frostworx** [comment]
I think this should work fine now with [this commit](https://github.com/frostworx/steamtinkerlaunch/commit/0b4a12bc912bbbb0a1173e6f6f9db06d3be0877a).
Please report if something doesn't work as expected.
