### ISSUE TITLE
PROTON_USE_WINED3D=1 conflicts with gamescope

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#280]
As reported [here](https://github.com/frostworx/steamtinkerlaunch/issues/279)
"gamescope is broken when using PROTON_USE_WINED3D."
but [works correctly](https://github.com/frostworx/steamtinkerlaunch/issues/279#issuecomment-887997242) when used standalone like this:
`PROTON_USE_WINED3D=1 ENABLE_VKBASALT=1 mangohud gamemoderun gamescope -W 1920 -H 1080 -b -- %command%`

**Comment by frostworx** [comment]
Mmh, I can't reproduce this here *(test game was Braid)*
It starts both with _PROTON_USE_WINED3D_ en- and disabled with both 'gamemoderun' and 'gamescope' enabled using Proton 5.13. _(also used  `-W 1920 -H 1080 -b --` gamescope parameters)_

Which proton version and game did you test, and could you please provide a log, @rodrigo21?

**Comment by rodrigo21** [comment]
It's seems the problem is with my build of Proton-tkg 6.13, I'm getting this:

`0100:err:user:load_desktop_driver failed to load L"winex11.drv"`
`0104:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.`
`0104:err:winediag:nodrv_CreateWindow The explorer process failed to start.`

With Proton 5.0, 5.13 and 6.3 it's working.

So don't worry about it, it's on my side.

**Comment by frostworx** [comment]
Thanks for testing! Glad to hear, because I really wondered how I should be even able to generate that conflict
(of course it could have been possible though, my program is a monster, but for sure far from perfect) :)
*closing here*
