### ISSUE TITLE
⚠ Looking for contributors!

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#309]
Starting from 1st of Nov. I will have much less time for working on stl,
so contributors are welcome to keep the project alive!

**Comment by Faalagorn** [comment]
You're always pushing many contributions in a short amount of time, that's why you are burning down, but it's okay to just keep up a slower pace, so don't worry about it and feel free to slow things down.

Don't worry about missing contributors either, lot of us Linux users, **especially** those that can contribute, are heavy terminal users while your program is a GUI one so it is tailored more at the opposite spectrum, there are various users that eventually will be exposed to it (we all used to keep about lack of GUI tools, chicken an egg problem), especially if more Linux beginners at some point. And if not, it's useful as it is! :)

Much love :green_heart:!

**Comment by frostworx** [comment]
Thanks my friend! 😀
I understand and partially agree with what you say, but IMHO it doesn't make much sense to ignore `stl` completely anyway
_(I'm fine with those _"community people"_ who boycott me/`stl` though 🙄, they do not count)_.

I'm a terminal user myself, but I do not want to "hack" everything into games configurations on steam
every time from scratch. I'm pretty sure nobody does.
`stl` is written in bash, has **LOTS** of valuable functions _(which can be great for both learning and improving)_,
so IMHO people who can contribute code do not really have an excuse if they are interested in gaming and open source development  _(of course not everybody has the time to do so, but for sure some do)_
Also, there are many other options to contribute and none is taken, f.e.
often `stl` would be a valid/easy solution for multiple "noob" questions/problems, but it is rarely mentioned anywhere.
Every contribution is equally important: translations, create/maintain distro packages, help with the wiki and so on...

Of course, it is great to have some people who do/did contribute and write articles and release videos👍,
but IMHO a little bit more `community` would not be too much requested IMHO.

**Comment by frostworx** [comment]
steamtinkerlaunch was added to the Solus repo _(thanks to the author here as well👍!)_, maybe this motivates users of other distributions to create a package as well!? _([little annoucement from me with some related urls](https://www.reddit.com/r/SteamTinkerLaunch/comments/pxr74p/steamtinkerlaunch_package_landed_in_solus/))_

**Comment by frostworx** [comment]
I'm planning to release the new version this Wednesday, so this is a good moment to help ironing out some bugs and glitches.

**Comment by frostworx** [comment]
I think this can be unpinned and closed. Thanks @Faalagorn 👍
