### ISSUE TITLE
mf-install support!

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#32]
Which games still require mf-install to work correctly?
Does it make sense to implement it?
Might be interesting:
https://github.com/ValveSoftware/Proton/issues/1464

**Comment by arrowgent** [comment]
thousands of games.
i dont think even protondb has a full dialog of the titles affected
and winedb seems so out of date for many games

might be more prudent to wait for wine/proton/GE to come up with solutions that are "legal"

ive also used direct mf installer before hand to solve the problem (the less than legal way using windows files)

i dont think winetricks/protontricks has a solution for that 100%
it does have a MF option but ive read it only installs minor files

ive started using GE-5.9 and i dont think ive seen a black screen video since

**Comment by frostworx** [comment]
Thanks for your thoughts!
It might last very long until a wine-builtin solution covers most games and without a clean list with working/not working games it is hard to know if automatically using a 3rd party script makes much sense. I also haven't spotted many affected titles in the wild personally with that problem and many most recent reports are pretty old.
Didn't know that GE has MF fixes but unfortunately both GE and TKG have a bug with VR games, so I mostly stick with vanilla proton when possible, even if I'd love to use a wine-staging (or generally 'more active') proton.

edit: Oh, closing this was accidently, but now after I notice it I'm not sure if I reopening makes much sense :)

**Comment by frostworx** [comment]
Just decided that I'll add a automatic mf function

**Comment by frostworx** [comment]
I have a mf-install using function ready.
When a game has `USEMF=1` set _(f.e. with Steam Category MF)_ stl will go through following process when the game is started:

- check if the game WINEPREFIX _(GPFX)_ already has mf installed. If yes, return and start game.
- check if mf-install is found in "~/.config/stl/downloads/mf-install". If yes automatically install into  _(GPFX)_  and start the game. 
- requester opens, giving the user the option to download mf-install into above directory automatically, if yes, download for all future games, install into  _(GPFX)_  and start the game. 
- if user selects to not install it the game will start without mf

I'm currently undecided if I should leave in the automatic download option or change the requester to  
"download manually into  '~/.config/stl/downloads/mf-install' to use mf automatically" with Exit or Continue options.

**Comment by arrowgent** [comment]
the z0z0z/mf-install is considered not legal
because it uses windows files directly, basically aquiring them from microsoft without a license to use them
hence the problem.

its a stupid legal gray area that even if you own a legit copy of windows, youre using the files in ways that are not allowed

the alternate issue is, steam installs .net, visualstudio, and directx without any question at all on Wine (windows)
why not setup installers to provide the MF files "freely" ?

where as you, the streamtinkerlaunch, are not providing the files directly
steam/proton have decidedly completely taken the stance to remove any comment/mention of it to protect their asses

**Comment by frostworx** [comment]
Thanks for your comment. I'm still undecided which way would be better.
Fortunately I have still much to do until I can push the next working release, so I can think about it a bit longer... :)

**Comment by frostworx** [comment]
removed it. Not worth it...
