### ISSUE TITLE
Reshade no longer working

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#329]
Reshade is no longer getting loaded in my game (even though I set the reshade option in stl) this might not necessarily be an STL issue and sorry for that.

[.config/stl/logs/stl/title/Trails\ of\ Cold\ Steel.log](https://hastebin.com/xaxodocoqa)

[cat .config/stl/logs/proton/title/steam-Trails\ of\ Cold\ Steel.log](https://hastebin.com/amicohapor)

EDIT looks like its failing when it tries to find the architecture type through `echo`
`installReshade - ERROR in ReShade installation - no file information detected for '/usr/bin/echo' or any 'neighbor file' - setting USERESHADE=0 for this session`

**Comment by frostworx** [comment]
Thanks for reporting, I can reproduce the issue... Will look into it...

**Comment by frostworx** [comment]
Should be properly fixed with https://github.com/frostworx/steamtinkerlaunch/commit/40d50e30fa100439a06f454dd3a617b759582937
I recently removed "which" as dependency. The result was that the placeholder variable for unconfigured programs was no longer "/usr/bin/echo" but just "echo" _(a complete new stl config would haver worked as expected)_.
I replaced every existance of _(the new)_ `"$(command -v "echo")"` with "$DUMMYBIN" to make it changeable anytime and every check against "echo" with
`[[ "$CHECKVARIABLE" =~ ${DUMMYBIN}$ ]]`
_(so only if  `$CHECKVARIABLE` ends with "echo", which is valid for both the new `"echo"` and for the old `"/usr/bin/echo"`)_
should be safe enough, as binaries ending with "echo", but not being "echo" are pretty rare :)

**Comment by frostworx** [comment]
np
