### ISSUE TITLE
Failed to add as a compat tool

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#331]
I need to reset steam so I ran `steam-runtime --reset` and now I can't re add stl as a compat tool with `stl compat add` it gives this 
```
/usr/bin/stl: line 14419: /SteamTinkerLaunch/compatibilitytool.vdf: No such file or directory
/usr/bin/stl: line 14419: /SteamTinkerLaunch/toolmanifest.vdf: No such file or directory
Sun Oct 24 10:58:27 PM EDT 2021 INFO - CompatTool - Creating symlink '/SteamTinkerLaunch/stl' pointing to '/usr/bin/stl'
ln: failed to create symbolic link '/SteamTinkerLaunch/stl': No such file or directory
```
I made sure to unset any stl as the global compat tool before doing the reset and also unsettling it from any games as I heard  issues can happen when it can't find a compat tool that was previously set

downgrading form the git version in the aur to the release version fixes this so I guess it was a regression since the last release version?

**Comment by frostworx** [comment]
The directory `compatibilitytools.d` is expected to exist, but wasn't created properly.
_(the log warns with: WARN - setSteamPath - 'compatibilitytools.d' not found for variable 'STEAMCOMPATOOLS' in 'pathA' or 'pathB'! )_.

Fixed in https://github.com/frostworx/steamtinkerlaunch/commit/f4deb33014cbaaa26747c0e46b7ee49f669fe898
thx
