### ISSUE TITLE
[TEST] DotNet installation - Proton-6.17-STL-1 no longer required!?

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#393]
Just successfully installed Vortex via
`steamtinkerlaunch vortex start`
but set the Proton version used for vortex to
`USEVORTEXPROTON="Proton-7.0rc3-GE-1"`
before.
The installation succeeded and Vortex was usable, so it looks like the special STL Proton is no longer required.
Please test and report back if it works for you as well (ideally both with Vortex and MO2).
If it does, I will replace the default Proton version used for both with the latest Proton GE version.

**Comment by frostworx** [comment]
Vortex seems to work, but MO2 fails with the good old 'python plugin could not be loaded error' _(here)_

**Comment by kronikpillow** [comment]
proton-GE also works for MO2 :) successfully used it

**Comment by frostworx** [comment]
yes, it does work for MO2, but possibly not for installing dotnet.
Are you sure you used proton-ge for the mo2 compatdata (please check logs) and not simply mo2 in the game compatdata?
(the latter simply uses the proton version used for the game and is supposed to work - but without having dotnet installed)

**Comment by frostworx** [comment]
just re-run my test
- clean configs  _(so no `~/.config/steamtinkerlaunch` at all)_
- `steamtinkerlaunch dcp l` _(to download the latest Proton GE automatically)_
- `steamtinkerlaunch settings`, choose the latest Proton GE _(currently Proton-7.0rc3-GE-1)_ for `USEMO2PROTON`
- `steamtinkerlaunch mo2 start` _(installs and should start MO2 ~5 minutes)_

Installation kind of works, but MO2 is not started. When trying to start it again _(so again `steamtinkerlaunch mo2 start`)_
it complains about python module broken, as mentioned above.

So `Proton-6.17-STL-1` at least is still required for the MO2 compatdata, but _(apparently)_ not for Vortex.

**Comment by frostworx** [comment]
no need to keep this open for a monologue

**Comment by frostworx** [comment]
Reopened, for Vortex re-investigation _(via #413)_

**Comment by frostworx** [comment]
retested, basically with the commands [above](https://github.com/frostworx/steamtinkerlaunch/issues/393#issuecomment-1002596056), just using `vortex` instead of `mo2`
Installation seemed to work fine using `Proton-7.2-GE-2`, the dotnet installation _(mscorsvw.exe)_ caused a coredump though.
Anyway the installed dotnet/vortex combo seems to work, all Vortex compatible installed games were added as expected as well. haven't started any game or mod.
Default `USEVORTEXPROTON` will remain `Proton-6.17-STL-1` anyway for now

**Comment by simon-labomedia** [comment]
Commenting before it's closed, as I didn't understand this was the actual answer to my problem at first :
This might be the fix you need if you can't install Vortex, especially if using Ubuntu 20.04 LTS or older.

When setting up STL and trying to install Vortex with `steamtinkerlaunch vortex start` and the default settings, you might run into an issue related to GLIBC . You can check your GLIBC version with `ldd --version` . See #390 .

This is because the default Proton for installing Vortex, called 'Proton-6.17-STL-1', really needs this dependance.

If the version is lower than required, this is a problem, because GLIBC is tied to your distro's version, and you can't really update it without breaking most of the other packages you have.

So if you can't use this particular Proton to install Vortex, you might try other versions, like I did. This didn't work for me, as it seems, like it was mentioned, that all the other Proton versions that are available by default in STL have a problem with a program called "DotNet', which prevents the installation of Vortex.

So the only way to get Vortex installed without GLIBC_2.32 is to use a custom GE Proton, for example the one which is mentioned in the first post. At least it worked for me.

Note : DotNet requires at least Wine6.6 to work. Default package on Ubuntu 20.04 is Wine5.0, but using WineHQ and it's PPA can get you, at least, Wine7.0 .
