### ISSUE TITLE
`steamtinkerlaunch vortex getset` fails with `sed: -e expression #1, char 0: no previous regular expression`

### ISSUE THREAD

**Issue by macinsight** [sonic2kk/steamtinkerlaunch#417]
`steamtinkerlaunch vortex getset` fails after a clean installation in the stl-default prefix for vortex with `sed: -e expression #1, char 0: no previous regular expression`

See the attached [steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8082755/steamtinkerlaunch.log) for (possibly) more detailed information.

**Comment by frostworx** [comment]
thx for reporting, will try to reproduce this when I find the time.

**Comment by frostworx** [comment]
Can't reproduce this with the following steps:

- `empty /dev/shm/steamtinkerlaunch/`
- `empty ~/config/steamtinkerlaunch/`
- `$ stl vortex install` _(takes some minutes)_
- `$ stl vortex getset` -> **no output, because nothing is configured yet, but also no crash**
- `$ stl vortex start` -> **installed compatible games are auto-detected and -configured; Vortex starts up, might take some minutes**
- `close Vortex`
- `$ stl vortex getset` -> **correct output of the freshly created Vortex config**

I assume you did something differently.

What is interesting though is, that the newvegas installPath is returned correctly here, means it was added by steamtinkerlaunch correctly before as well
_(here `settings.mods.installPath.newvegas = "Z:\\media\\B4-1\\SteamLibrary\\Vortex\\{GAME}\\mods"`)_

So my guess is that Vortex fails with some check when "activating" _("Manage")_ the game in Vortex and THEN falls back to its defaults _(overwriting the previous correct entry)_

I guess when Vortex is happy with its check #414 should be fixed

**Comment by frostworx** [comment]
ping?
