### ISSUE TITLE
Installation on Ubuntu distro's?

### ISSUE THREAD

**Issue by ghost** [sonic2kk/steamtinkerlaunch#419]
https://github.com/frostworx/steamtinkerlaunch/wiki/Installation

I see the how to for all major flavors of Linux but Debian/Ubuntu.

I've ran sudo apt-get install -y git make gawk xdotool and installed all the Dependencies. Ive rebooted and restarted Steam but don't have a option for steamtinkerlaunch nor does "stl %command%" work.

How do you install steamtinkerlaunch on Ubuntu?

**Comment by frostworx** [comment]
This has been discussed already [too often](https://github.com/frostworx/steamtinkerlaunch/issues?q=is%3Aissue+ubuntu+is%3Aclosed).
You might want to read the [this](https://github.com/frostworx/steamtinkerlaunch/wiki/Yad) for installing yad.

_(unsure why you think that installing gawk and xdotool also gives you `steamtinkerlaunch` though)_

**Comment by ghost** [comment]
Thanks for the response. 

Iook forward to trying this tool. 

If this has been asked too often then why aren't there better instructions on the installation page?

**Comment by frostworx** [comment]
The basic installation instructions in the README are imho enough _(and other projects do not have longer ones, because a `make install` and installing dependencies is default)_ and all the extra effords [for yad](https://github.com/frostworx/steamtinkerlaunch/wiki/Yad) are much more than other projects offer, but feel free to contribute better instructions/wikis anytime.

**Comment by frostworx** [comment]
please close, when you're done here
