### ISSUE TITLE
New GE-Proton builds not found

### ISSUE THREAD

**Issue by leon22heart** [sonic2kk/steamtinkerlaunch#423]
Recently Proton-GE by Glorious Eggroll changed its naming scheme . From Proton-x.x-GE-x  it changed to GE-Protonx-x . The Proton-x.x-GE-x  builds found in compatibilitytools.d are recognized by steamtinker launch , the others aren't .
It cant be found in the drop down menu per game or if set in the global config .

Using Arch and steamtinkerlaunch v.9.2.1 AUR.

**Comment by frostworx** [comment]
Personally I only use GE by downloading it directly using steamtinkerlaunch, which still works fine.
I guess this should be simple to fix though, so I guess this will be fixed shortly when I find the time.

**Comment by frostworx** [comment]
above change should already fix it. GE autobump function is only checking for the new names.

**Comment by frostworx** [comment]
so?

**Comment by leon22heart** [comment]
Still waiting for an update on Aur. By building the app from githtub and using it , i see it finds the new renamed proton builds. 
I cant verify if the following behavior is a bug . Steam  and steamtinkerlaunch are closed. Downloading new ProtonGe build in compatibility.d using protonup-qt. The first run of steamtinkerlaunch cant find it , the second can. 
Probably a misbehavior , but cant verify if it the new proton builds naming scheme or a steamtinkerlaunch internal issue.
But this specific thread can be considered fixed since it finds the new proton builds.

**Comment by frostworx** [comment]
I won't bump the version fur such a little fix. but there's also a [git package](https://aur.archlinux.org/packages/steamtinkerlaunch-git), which you could use. 
regarding your other issue: steamtinkerlaunch "caches" the found proton versions in a temp. file in /dev/shm/steamtinkerlaunch/.
so when both steamtinkerlaunch and steam are closed and an additional proton version is installed, this cache file needs to be renewed in theory. Practically there's no way to know when the cache needs to be renewed, so this can't be fixed directly.
Indirectly I could simply change the default download path for (auto-)downloaded/updated proton ge versions and steamtinkerlaunch would simply download all custom proton versions into `~/.local/share/Steam/compatibilitytools.d/`
Initially I decided against this because
- Steam itself requires a restart to recognize newly installed custom proton versions (no idea if this is still the case)
- I wasn't sure if "messing" around in an official steam directory is the way to go, so I used an own dir.

Nobody ever requested a path change or even askedf, so I assume this is fine for all who use the function.

_(another possibility would be to always check for new proton versions and remove the cache completely. this would delay multiple functions though and therefore is no real sane solution)_

**Comment by frostworx** [comment]
hrhr, I just checked for the custom proton download path, because I wondered if I did not already add an option.
I did: You can configure both the download and extract path for custom proton versions globally or even simply enable the global option `CUPROTOCOMPAT` _("Extract custom Proton in compatibilitytools.d")_, so (automatically) downloaded proton versions are directly extracted into `compatibilitytools.d`.
Too many options for most users, and apparently even too many that I can remember them all on my own.

**Comment by leon22heart** [comment]
I agree with your remarks. 
Steam yet does no recognize custom proton builds unless restarted. As a developper i can see why it is a problem to mess too much with steam official internal folders. 
The variable option is a nice addition will try to test it a little but in my opinion the fundamental issue of not recognizing the new proton builds is fixed.
If it needs and 2 restarts of steam in order to update the versions in steamtinkerlaunch so be it especially if they are downloaded externally via an alternate tool than steamtinkerlaunch.

**Comment by frostworx** [comment]
Thanks for the reply and for the heads-up regarding the Steam restart still required.
If you like, you can ping back after testing, when you think that `CUPROTOCOMPAT` should be better on by default. I, personally, don't really have a preference.

**Comment by leon22heart** [comment]
Sorry to be late , had find time to test. Combined with the erratic behavior of elden ring i could not pinpoint if steamtinkerlaunch proton or vulkan caused me issues for this game.
Personally i believe that it should be off by default for 2 reasons
1. The occasional cashing of the newer versions make the new versions visible after max 2 restarts. Does this coincide with the update of proton-exp or something other , that i dont know.
2. This is a very specific option something like an advanced option in an advanced tool. The vast majority use the internal downloader of steamtinkerlaunch so no problem at all.

Btw thank for this tool , hope to see the promising latency reduction project integrated if it is viable in the future.

**Comment by frostworx** [comment]
Thanks for taking the time to test and for the suggestion!

You mean [LatencyFleX](https://github.com/ishitatsuyuki/LatencyFleX), right?
I found it interesting, when it was initially announced, but tbh I did not even have the time to try it out yet.

**Comment by leon22heart** [comment]
Exactly. Since i fear any ban from eac on elden ring and epic stores games i still havent tried it out. I dont have any other recent game to test it. It still has a lot of work to be done but i feel it is very promising.

**Comment by frostworx** [comment]
Agreed it is promising. I might try it with God of War when I find the time, but implementation into steamtinkerlaunch likely won't happen any time soon.
*closing here*
