### ISSUE TITLE
steamtinkerlaunch mangohud option prevents Trails of Cold Steel III from running

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#426]
`SteamTinkerLaunch v9.3.20220306`
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8208767/steamtinkerlaunch.log)
[The Legend of Heroes Trails of Cold Steel III.log](https://github.com/frostworx/steamtinkerlaunch/files/8208774/The.Legend.of.Heroes.Trails.of.Cold.Steel.III.log)
Was working a few days ago. Going to try different versions of steamtinker to see if that helps

Forgot to mention that the game runs with no issues using the same proton version (7.0-1) directly as a compat tool vs using steamtinkerlaunch

also noticed how it was setting the window name to nyrna don't think that really matters but I tried disabling nyrna to see if it helps and the game still does not launch
So haven't gotten to work on any version of steamtinkerlaunch which is strange as it was working last night. (I updated steamtinker today before the issue happened so that's why I thought it was that)

Was able to get it to work  on `SteamTinkerLaunch v9.3.20220306` by 
deleting `/dev/shm/steamtinkerlaunch/`(tried this before and didn't help)
deleting `.config/steamtinkerlaunch/` (guess something got messed up here)
deleting the game prefix (tried this before and it didn't help)

some config that I'm doing is breaking it, it seems as it's not launching again, Ill test what causing the issue but a few options that come to mind that I'm using are mangohud, game mode,  and the pev tools.
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8209480/steamtinkerlaunch.log)
[The Legend of Heroes Trails of Cold Steel III.log](https://github.com/frostworx/steamtinkerlaunch/files/8209482/The.Legend.of.Heroes.Trails.of.Cold.Steel.III.log)
game config
[991270.txt](https://github.com/frostworx/steamtinkerlaunch/files/8209490/991270.txt)

Figured it out apparently the mangohud option in steamtinkerlaunch is what's causing the issue.
running the game with proton 7.0-1 without steamtinkerlaunch and mangohud added as a launch command works as expected so something is going on with steamtinkerlaunch it seems which is strange, as I'm using the same mangohud config files (manged by overlay) and I tried leaving all other options in steamtinkerlaunch to there defaults and it still only does not work when done through steamtinkerlaunch. Even launching the game with steamtinkerlauncher as the compact tool with mangohud as a steam launch option and disabled in steamtinker works fine. It's when its ticked in steamtinker that the game does not launch

**Comment by frostworx** [comment]
Sorry, this report is really confusing for me.
could you sum it up into a few sentences with one correct logfile?
I also haven't changed anything regarding mangohud, so I don't see a reason why steamtinkerlaunch should have stopped working with it recently. Have you tried other steamtinkerlaunch versions and can pin it to one specific version?
Else I'd assume it is not steamtinkerlaunch related at all.
Especially as it seems to work correctly with a clean steamtinkerlaunch configuration, I don't see what the problem is.

_(also it is "steamtinkerlaunch", not "steamtinker" or "steamtinkerlauncher", maybe you want to simply use the short form "stl")_

**Comment by zany130** [comment]
Basically the issue is if you enable the mangohud option in STL the game doesn't launch. This happens regardless of STL version (which confuses me if this is even a STL issue)

 disabling Mango hud in STL and adding it as a steam launch command allows the game to work.

Just tried other games and it works there so it's something specific to this game but i don't see how that could be

**Comment by frostworx** [comment]
thanks for the summary :)
There is basically nothing in steamtinkerlaunch, which directly changes mangohud. When enabled, It just sets the MANGOHUD variable and optionally uses a separate mangohud config - that's all.
I remember though, that there were some constellations where mangohud conflicted with some other tools _(f.e. gamescope)_,
so I'd guess something else is causing the problem here.
Have you checked if anything else which could conflict here is enabled as well?
You might already know it, but you can easily check which settings are different for one game from your default game config by opening the "GameCfgDiffers menu in the `CATEGORY` submenu.

**Comment by zany130** [comment]
Yeah, I tested with a fresh (i.e removing) `.config/steamtinkerlaunch/` and `/dev/shm/steamtinkerlaunch/` and only changed mangohud in the options. and still got the issue here is a 
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8225797/steamtinkerlaunch.log)
 and the config for the game
[991270.txt](https://github.com/frostworx/steamtinkerlaunch/files/8225825/991270.txt)
 
 
 EDIT: something else I noticed is that while disabling mangohud in STL and adding it as a steam launch command does actually allow the game to launch it doesn't actually load the mangohud overlay if you do this. ( didn't notice before but cause I never tried going past the launcher)
 
 If I don't use STL   (by setting proton as the compat tool) mangoud does load and work when I pass it as a steam launch command.
 
 So it's as if something in STL is preventing mangohud from working correctly in this specific game. Which makes no sense

**Comment by frostworx** [comment]
Can't see anything suspicious - everything looks fine so far from steamtinkerlaunch side.
As you wrote that mangohud works standalone, it might be some steam(-linuxruntime) related change.
This reminds me at your [old bug here](https://github.com/frostworx/steamtinkerlaunch/issues/347) which sounds related overall imho. So it might really be some new SLR  "feature". I'm afraid I can't help you here.

`startGame - No SLR was provided via command line, so configuration USESLR '1' is ignored '' 0`

**Comment by zany130** [comment]
so found a fix for this I had to pass mangohud as a launch command AND enable it in STL which actually makes sense as if I pass it as a steam launch command but don't have it enabled in STL it will resolve to disabled right?  what is strange is why it doesn't work with the STL  mangohud option on its own

**Comment by frostworx** [comment]
how do you enable mangohud as launch command?
I guess you do not use the MANGOHUD variable, right? (steamtinkerlaunch only uses that variable and never calls mangohud directly - as already said, steamtinkerlaunch simply uses that variable, which is used by mangohud directly - so it is no steamtinkerlaunch variable). Maybe mangohud behaves differently here (no idea, I never use it).

**Comment by zany130** [comment]
I just add `mangohud %command%` to the steam's set launch commands option which from my understanding adds `mangohud` to the beginning of the game command. I'm guessing when I do that it with it disabled in STL it resolves to false so the game loads without it. 

What I don't get is why setting it in both STL and steam it suddenly allows the game to load.

from my understanding they both do the same thing no?  add mangohud to the final launch command

**Comment by frostworx** [comment]
that's what I thought.
`mangohud %command%` apparently starts the game though the "manguhud" binary directly, so the `MANGOHUD` variable isn't used at all. A "fix" would be to use that binary as well in steamtinkerlaunch instead of the variable, but as both is offered by mangohud directly, this is more a mangohud  and no steamtinkerlaunch "issue". It might also be possible that the `MANGOHUD` variable is deprecated _(no idea)_ which would theoretically lead to the situation that this indeed would "require" a steamtinkerlaunch change.
But yes, I assume starting mangohud using its binary and afterwards "disabling" its functionality by setting its internally parsed variable MANGOHUD to 0 disables the mangohud functionality generally.

**Comment by zany130** [comment]
ah ok makes sense so should I go ahead and close this or do you want to leave it open for further investigation (can help with that to)

**Comment by frostworx** [comment]
Thanks for the offer to help! :)
If you like you could try to find out if the `MANGOHUD` variable is deprecated _(or has known issues)_.
Be aware though, that even if this is the case, I can't tell when I find the time to rewrite the corresponding parts in steamtinkerlaunch (although I'd guess that it should not be that complicated).
If it works fine for you as-is, it is of course ok as well, when you just close the issue here
_(I guess if the variable has problems, the issue will show up again as new issue anyway soon or later :))_

**Comment by frostworx** [comment]
Just checked the projectpage and the MANGOHUD variable is still directly on the project page.
I've seen you also opened an issue over there, so I'm closing here.

**Comment by zany130** [comment]
So after more testing and talking on the mangohud project it seems I'm running into a known but difficult to reproduce issue with mango hud and game mode 


(there conflicting it seems as disabiling gamemode let's me use mangohud as normal in STL and also solves the inconsistent startup when i don't use STL


 (that's why i didn't mention that issue as i didn't know if it was related as i could consistently get the game to not run with STL but couldn't without). So it does indeed seem to not be an issue in STL

**Comment by frostworx** [comment]
hm, would have been an interesting detail, that gamemode was running as well. there were already issues with both running in the past.
