### ISSUE TITLE
[TEST] concatenate multiple game launch options (f.e. gamemode, mangohud, gamescope, proton version, steam linux runtime)

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#465]
I [currently](https://github.com/frostworx/steamtinkerlaunch/issues/324#issuecomment-1126887645) rewrite and merge all functions which create the final game launch command based on the functions and tools enabled by the user.
I hope it will be working just fine on commit _(soon)_, but several tool combinations might not work as expected _(f.e. could require a different sort order or a "--" seperator between the separate commands)_, so it would be nice if some people tested the new function early and report back.

What helps with testing:

The steamtinkerlaunch log file _(the log for the last game start as usual can be found under `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`)_
will explicitly log the initial incoming game launch command (`launchSteamGame - Original incoming start command`)
and the final concatenated command _(`launchSteamGame - Final outgoing start command`)_

It would be nice if you check the final command for missing or wrong parameters, I might have missed something.
What also would help is logging a working **functional** steam launch option which uses multiple external tools without using steamtinkerlaunch, f.e. by
using a steam launch option like
`/usr/bin/gamemoderun /usr/bin/mangohud %command% > /tmp/game-testrun.log`
_(of course your tools might vary)_

~~I'll drop a note here when the initial rewrite landed in git~~

The initial rewrite [just landed](https://github.com/frostworx/steamtinkerlaunch/commit/5aa9130c4bb61e6c256f13528caa1c008e9286d6)

Happy testing/reporting _(I might take a bit longer with replies than usual)_

Thanks for your interest.

**Comment by zany130** [comment]
finally got around to testing this. Sorry for the delay. 

**steamtinkerlaunch as a compat tool**
_________________________________
With just `useslr` it still doesn't find/use SLR, but with `forceslr`
games launch even with mangohud, gamemode, and now gamescope (Since I'm using AMD now 😄)


**steamtinkerlaunch as a lunch command**
____________________________________


setting `useslr` is enough as previously mentioned  and finds and uses slr from the incoming proton commands

Even better it works with mangohud,gamemode, and gamescope enabled now 🥳 (again I previously reported games would not launch with those options enabled and SLR for those who didn't see the other SLR issue)

Next I will try to see if other situations where using gamemode or mangohud (and possibly gamescope) was not working with other tools (such as cheat engine) and report back on that.

**Comment by frostworx** [comment]
thx for testing. I'd say so far so good. have fun with your new gpu :)

**Comment by frostworx** [comment]
Assuming you're testing alone here, @zany130. Are you still planning to test here anything? Else I'd close here.
Take your time, I just don't like "idling" issues :)

**Comment by zany130** [comment]
sorry been busy with other stuff so I put this on the back burner (actually started getting back to it yesterday and found a few unrelated bugs which I'll open issues for (even one that was super simple so I'm taking advantage and learning how to do a PR)

from my testing cheat engine now works when using game mode (before it wasn't) so this seems to fix it 🥳 There an issue when enabling both gamescope and cheatengine and that's that cheat engine will be launched in the same gamescope window as the game (which is not good) but I'll open a separate issue for that
