### ISSUE TITLE
Link to yad readme in the wiki + create seperate Ubuntu install instructions

### ISSUE THREAD

**Issue by Apacelus** [sonic2kk/steamtinkerlaunch#482]
The instructions listed [here](https://github.com/frostworx/steamtinkerlaunch/wiki/Yad#compile-yad) may not work anymore(or at least they didnt for me). Please instead link to the [yad readme](https://github.com/v1cont/yad#readme) where the instructions are up2date.

Also, please let me create a small readme specifically for Ubuntu, as it was very frustrating to come to this project and find out that there is no native ubuntu version(which is understandable, I am not implying you **have** to make one) but also the instructions to install are scattered around the issues, the wiki, and some other places.
I am suggesting to make a separate Wiki page for Ubuntu and link to it in the readme, instead of having people figure it out themselves(after all they came here to quickly get a tool for a steam game, not to study the readme).

**Comment by Apacelus** [comment]
I reposted in the discussion thread

**Comment by OdinVex** [comment]
I simply set `MINYAD=0` and installed yad from distro, running fine at the moment. I think they may just be using a different version scheme.

**Comment by frostworx** [comment]
what's your point? are you planning to contribute something?

**Comment by OdinVex** [comment]
My only point was I had issues with the way the script was using Yad versions, Ubuntu appears to be using a different version scheme, so the script wasn't executing because it determined the minimum requirements weren't met. Merely posting about it. As for the rest of the post, that was mentioned here by accident, I was alt-tabbing to a private discussion with someone and then stepped away from my PC and got called away far longer than intended. Removing it, my bad. Edit: Seems I got carried away too, edited.

**Comment by frostworx** [comment]
mhm
