### ISSUE TITLE
Uninstaller?

### ISSUE THREAD

**Issue by Apacelus** [sonic2kk/steamtinkerlaunch#483]
Is there an uninstaller script somewhere?

**Comment by frostworx** [comment]
Distributions which maintain a package, of course, can simply use their package management, but no, there is no uninstall option in the Makefile currently.

**Comment by sonic2kk** [comment]
Not all Makefiles (very few in my experience) have an `uninstall` block. However, would a manual uninstall process work? I imagine something like this is what would go in a Makefile `uninstall` block but I have no experience with those :sweat_smile: 

```sh
sudo rm -rf /usr/bin/steamtinkerlaunch  # Remove STL program
sudo rm -rf /usr/share/steamtinkerlaunch/*  # Remove STL files (translations etc)
sudo rm -rf /usr/share/doc/steamtinkerlaunch/*  # Remove STL readme
sudo rm -rf /usr/share/applications/steamtinkerlaunch.desktop  # Remove STL .desktop file (shortcut in application launchers e.g. GNOME Dashboard or KDE Kickoff)
sudo rm -rf /usr/share/icons/hicolor/scalable/apps/steamtinkerlaunch.svg  # Removes STL icon
sudo rm -rf /dev/shm/steamtinkerlaunch/*  # Remove remaining STL files, almost certainly unnecessary but can make for a clean uninstall/reinstall scenario :)
```

I got these paths from following the installation steps in the [Makefile](https://github.com/frostworx/steamtinkerlaunch/blob/master/Makefile#L9-L18) and verifying them on my own system, but I recommend checking the exact paths and writing the commands out yourself to make sure you don't mess anything up - Escalated remove commands can be scary! I also didn't test this myself but this should be the gist of uninstalling (I hope).

**Comment by frostworx** [comment]
basically you're right, but I'd prefer to not "hardcode" `sudo`, as the users should know what they are doing and what the makefile does as well. uninstall blocks, **if** they even exist as you already pointed out, often do not work correctly as nobody, including the authors do not really maintain them. The reason is probably that they are usually not required, because un-installing packages system-conform is mainly the job of package management packages.
Installing any program manually IMHO always should be the last resort. It can be dangerous, files might be left behind in the system, updating the program can be complicated and so on. So contributing and maintaining packages to the own distribution
always is the better choice and helps the community as well apparently.

**Comment by frostworx** [comment]
Closing here, but you're invited to reopen any time if you think this needs further discussion.
