### ISSUE TITLE
No Options Work/Apply

### ISSUE THREAD

**Issue by AHandheldFan** [sonic2kk/steamtinkerlaunch#494]
I have it set as a compatibility tool. It launched, I set the options I want, but they don't do anything or work, none of them.
So I have to manually enter the steam launch options.
Any fix?

**Comment by AHandheldFan** [comment]
HELLO...anyone able to help?

**Comment by sonic2kk** [comment]
Hi, I'd like to try and help. Could you provide some more information?

- What version of STL are you using?
- What distribution are you using?
- What options more specifically are you trying to use?
- Could you attempt to launch your game through STL again with your desired options selected, and attach the log found at `/dev/shm/steamtinkerlaunch`?

Also, it may take a while for issues to have responses and longer again for resolutions. Encountering issues is annoying but please try and be patient 🙂

**Comment by AHandheldFan** [comment]
> Hi, I'd like to try and help. Could you provide some more information?
> 
> * What version of STL are you using?
> * What distribution are you using?
> * What options more specifically are you trying to use?
> * Could you attempt to launch your game through STL again with your desired options selected, and attach the log found at `/dev/shm/steamtinkerlaunch`?
> 
> Also, it may take a while for issues to have responses and longer again for resolutions. Encountering issues is annoying but please try and be patient slightly_smiling_face

Latest STL - Built from source (master branch)
Pop_OS! 22.04
I am trying to use dxvk_async. mangohud and FSR (when I enter them manually they work)
Log file below...but it's not going to tell you much when settings don't apply.
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/8862783/steamtinkerlaunch.log)

**Comment by frostworx** [comment]
Thanks again for your help and kudos for your patience,  @sonic2kk

**Comment by sonic2kk** [comment]
@tooelitepete Hmm, I had a look at the code and I can see a checkbox for DXVK Async but I can't see where it's actually exported. Can't test at the moment unfortunately :sweat_smile: 

MangoHUD I've used recently so it should definitely work, does STL point to the correct MangoHUD executable?

The log file helps give insight to see exactly what STL is doing, and it's good practice to attach it anyway :slightly_smiling_face: 

You could try appending the environment variables to the game config file (the Game Files button on the Main Menu and selecting the Game config file) and seeing if they work that way. They *should* since they work through the Steam launch options, but just an additional troubleshooting step.

**Comment by AHandheldFan** [comment]
@sonic2kk No they do not work that way either.
MangoHud is pointing to the correct executable.
I'm starting to get really frustrated. I expect a piece of software to work, at the very least, somewhat work.
Also the ray tracing enable option was another one that didn't work, but none of them work for me unless I manually input the launch options in Steam.

**Comment by sonic2kk** [comment]
I'm not sure why they're not working then, are you by any chance using Flatpak Steam or something? That's really the only thing I can think of, otherwise I'm out of ideas, sorry. I didn't see anything relevant to that in your logs though so I'd imagine not.

> I'm starting to get really frustrated. I expect a piece of software to work, at the very least, somewhat work.

Indeed, though as you can understand it works for the majority of users, myself included. If this was a widespread reproducible problem we would be able to offer more support 🙂 To that end, STL "somewhat works" at the very least, just not in your particular instance. Which is frustrating for sure.

If you can think of any further details to add please do. For now though I'll have to leave it up to someone else or yourself to debug further to see if you can find the deeper cause of the issue. Help us help you 🙂

**Comment by AHandheldFan** [comment]
That'd be right, no one else chimes in or even offers to help.
I'm flagging this project to Git for being misleading (and I have evidence)

**Comment by frostworx** [comment]
That came expected. Thanks for your patient help anyway @sonic2kk
