### ISSUE TITLE
Large Address Awareness Issue

### ISSUE THREAD

**Issue by tim-elmer** [sonic2kk/steamtinkerlaunch#528]
I'll prefix this with stating that I'm not sure if this is STL's fault or not, apologies if not.

I'm attempting to launch my favorite modding nightmare; Dragon Age: Origins via STL and MO2. All the plumbing seems to work (game launches, is playable, albeit fragile). Unfortunately, the game crashes once it tries to load over 1.5 GiB. I've tried with and without the `PROTON_FORCE_LARGE_ADDRESS_AWARE` flag, and with and without using a LAA patched version of the game.

Any advice?

[Dragon Age Ultimate Edition.log](https://github.com/frostworx/steamtinkerlaunch/files/9224689/Dragon.Age.Ultimate.Edition.log)

**Comment by frostworx** [comment]
Sorry, I can't see any reason for steamtinkerlaunch causing this issue, so I'm afraid I can't help you very much.
Enabling some wine or proton logging might help to find the issue.
You could also try using Vortex instead of MO2 alternatively if that is an option.
good luck!

_(maybe just a coincidence, but seems like "Frosty mod manager" has a 1.5gb problem [as well](https://www.reddit.com/r/BattlefrontModding/comments/lcvbpr/comment/gotkdow/?context=3). if mo2 would have generally the same problem, there would be more google hits though :))_

**Comment by tim-elmer** [comment]
Fair enough. I know from my experience that MO2 can handle way more than that, but I'll bang my head against it some more. Thanks!

**Comment by jake770321** [comment]
Maybe this will help? https://github.com/doitsujin/dxvk/issues/1318#issuecomment-1199215660

**Comment by tim-elmer** [comment]
> Maybe this will help? [doitsujin/dxvk#1318 (comment)](https://github.com/doitsujin/dxvk/issues/1318#issuecomment-1199215660)

**Comment by tim-elmer** [comment]
That was _not_ what I meant to do. Way too easy to change state in GH sometimes.

I meant to state that I've switched platforms for various reasons, so I can't confirm if this addresses the issue, but it sounds like it might once it hits distribution.
