### ISSUE TITLE
Wiki Request: Installation Page

### ISSUE THREAD

**Issue by VGJUNKY** [sonic2kk/steamtinkerlaunch#548]
Would love to see local install instructions on the wiki, I've been running stl in a local user folder for months without many issues. Might help novices just try it out without writing files to their root directory which is harder to remove. I'm sure there's limited functionality like for example no Linux native game support as you can't use steam launch options, so maybe just have a note about that.

All I've done is:

- Grab a version from the releases, unzip it in a local home user directory.
- Open a terminal in that folder, drag and drop the 'steamtinkerlaunch' file or type it in.
- Copy over the language file as per the terminal output's instructions.
- Then run 'steamtinkerlaunch compat add'

Could even add simple uninstall/removal instructions.

- Running 'steamtinkerlaunch compat del' from the local folder
- Deleting files from ~/.config/steamtinkerlaunch

This request may seem small and simple, but I think this program is meant for new users. So giving more simple non-root instructions to follow is a good thing.

**Comment by sonic2kk** [comment]
In my opinion, I think the spirit of this suggestion is sound and I agree. There are installation instructions but as far as I know (aside from Steam Deck) there isn't really any mention of non-root installation. As you noted there is no `steamtinkerlaunch` launch option available, and there could be other caveats that make non-root installation undesirable.

The generally preferred way to install SteamTinkerLaunch is through your package manager. If unavailable, downloading the repo and running `sudo make install`. The command is noted on the [Readme](https://github.com/frostworx/steamtinkerlaunch#installation):

> If steamtinkerlaunch is not in your package management yet, just `sudo make install`

Installation instructions for different distros and setups can vary. There are separate instructions for [Steam Deck](https://github.com/frostworx/steamtinkerlaunch/wiki/Steam-Deck), [Flatpak](https://github.com/frostworx/steamtinkerlaunch/wiki/Flatpak) (**only for Flatpak Steam!**), and [Ubuntu](https://github.com/frostworx/steamtinkerlaunch/wiki/Ubuntu). There is also a wiki page for [manual installation](https://github.com/frostworx/steamtinkerlaunch/wiki/Installation).

There is a dedicated issue for wiki discussion (#457), it used to be pinned but is now a little buried and easy to miss. I have some ideas on how we could go about improving installation instructions and after that, perhaps with a warning above it, we could add instructions for non-root installation.

Good suggestion, one way or another I'll see about trying to get this on the wiki if it's generally considered reasonable advice to document, and get the information on potential caveats with this method so that they are also included on a potential future wiki entry :+1:

**Comment by sonic2kk** [comment]
@VGJUNKY Local installation instructions have been added to the [Installation wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Installation#local-non-root), including what should be a fix for the issue you mentioned about no launch option for native games.

If you have any feedback I'd love to hear it :+1:

**Comment by frostworx** [comment]
@VGJUNKY the major overhaul by @sonic2kk was merged. you're invited anytime to also contribute to the wiki of course if you want.
please reply and/or close here if *solved*

**Comment by VGJUNKY** [comment]
This looks great, ty for taking my suggestion into account. Also great uninstall instructions 👍

**Comment by sonic2kk** [comment]
Hey @VGJUNKY, opening this issue and detailing the manual installation steps basically paved the way for our ProtonUp-Qt support. Thanks a bunch for letting us know this way of installing STL was reliable :heart:
