### ISSUE TITLE
"WARNING - disabling 'USEMANGOAPP' because program 'mangoapp' was not found"

### ISSUE THREAD

**Issue by Slippingstones** [sonic2kk/steamtinkerlaunch#584]
Log:
[1295510.log](https://github.com/frostworx/steamtinkerlaunch/files/9579081/1295510.log)

STL v11.0

Not really sure what's up here, wanted to try the new MangoApp since it combines HUD with gamescope, and adds FSR info. 
Seems it isn't able to find mangoapp? Haven't seen anything else about this yet.

**Comment by sonic2kk** [comment]
Do you have MangoApp installed and if so, where? You can probably find this with `which mangoapp`. Looking at STL's code, it looks like STL just appends the `mangoapp` command somewhere in the launch options. So it shouldn't be looking for it anywhere except where the path says it is (usually somewhere like `/usr/bin` or `/usr/local/bin`). Seems like the `MANGOAPP` variable is just set to `mangoapp`. I *think* this is also done for GameScope too if I'm not mistaken.

In case it wasn't clear, SteamTinkerLaunch doesn't package MangoApp itself, or any similar programs like GameScope. It just offers a frontend to enable it for games.

**Comment by Slippingstones** [comment]
Followed your instructions, and nothing was found. Unsure how I would go about installing MangoApp. I have MangoHUD 0.6.8 on Fedora which works fine, and seems to imply it comes with MangoApp via their github. Gamescope, and MangoHUD also both work independently(and together in some cases). 

Edit: I will actually say I have Nobara which comes preinstalled with STL, and most things setup already, but uses fedora as a base. Just attempted reinstalling MangoHUD to no avail :(

**Comment by sonic2kk** [comment]
Ah, I had no idea it came preinstalled on Nobara! (though I did request it be added to the repos :smiley:)

This is most likely not an issue specific to STL just a heads up, but MangoApp does not seem to come installed with MangoHud. At least on Arch it doesn't, it's a [separate package on the AUR](https://aur.archlinux.org/packages/mangoapp). I believe Nobara switched to using their own repos instead of Fedora Copr recently, but I can't find where the repos are so I'm not sure if it's a separate package available for Nobara. I couldn't find it on the old `gloriouseggrolls/game-utils` copr repository anyway.

You might be best asking GE on Discord about how to install MangoApp, or wherever else he's available to contact.

EDIT: This may or may not affect STL v11.0, but just to make you aware, there is an open issue (and a merged PR) relating to MangoApp: PR #581 and Issue #582. Maybe an STL Git option should be available for Nobara users somehow, if Nobara only packages the latest stable.

**Comment by frostworx** [comment]
Title _(from the log)_ says it all.
 `"WARNING - disabling 'USEMANGOAPP' because program 'mangoapp' was not found"` means
`steamtinkerlaunch` could not find a `mangoapp` installation and therefore can't use it.

Maybe we should create a new minor release 11.11 shortly anyway 😀

**Comment by sonic2kk** [comment]
I don't believe this to be a SteamTinkerLaunch specific issue but you might be able to get support on the MangoHud Discord server as well if you haven't been able to get support from GE on this.

You might also be able to install MangoHud from source, it seems like the Arch and Nobara packages don't include MangoApp. Installing from source is not ideal though, I'd still recommend asking around to see if you can get this working. Since MangoApp is not installed this doesn't seem to be a STL problem but it would be nice to have a resolution for others on Nobara that come across this and potentially to add a note on the MangoHud wiki that MangoApp needs to be installed separately and that can be done with XYZ steps :smiley:

**Comment by sonic2kk** [comment]
I have looked around and can't really find anything solid on how to use MangoApp, outside of mentions of it in the MangoHud changelog and the AUR repository. I know it's primarily intended for use with Steam Deck, though.

@Slippingstones were you ever able to get this resolved? If so it would be great if we could document it for other users. Maybe it's something you have to build separately or a flag you can set to build MangoApp with MangoHud. Honestly not sure.

**Comment by Slippingstones** [comment]
@sonic2kk  apologies I've been going through a bout of depression. I'll attempt to use the latest release of STL, and build mangohud manually to see if anything changes.

**Comment by sonic2kk** [comment]
No rush, health comes first of course :) Thanks for replying, we can keep this open until you're able to test.

**Comment by Slippingstones** [comment]
> No rush, health comes first of course :) Thanks for replying, we can keep this open until you're able to test.

Appreciate that. So I ended up reinstalling Nobara unrelated to this post. I updated STL to v 11.11, and swapped to X11 to build MangHUD thinking maybe Wayland was the issue. No luck on my part still. I am currently on a desktop. Gamescope, and MangoHUD both seem to be working together so I don't think it's a huge issue anyways. Appreciate all the assistance, and positive responses however. 

I actually am unable to install the AUR Mangoapp packages because the URL no longer gives a response. Same error on Arch via Garuda ultimately as before where MangoAPP isn't found. Perhaps since it's main use is with the steamdeck that's why I'm having this error.

**Comment by sonic2kk** [comment]
Hmm, so I am able to attempt an installation of MangoApp from the AUR (it fails because some mangohud files already exist in my filesystem).

I had a look at the PKGBUILD for MangoApp and as I suspected, MangoApp is indeed a build-time flag. See [this part](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mangohud#n43) of the PKGBUILD file on the AUR (if you can access it, if not you may need to restart your computer/router).

```
build() {
local meson_options=(
  -Duse_system_spdlog=enabled
  -Duse_system_vulkan=enabled
  -Dappend_libdir_mangohud=false
  -Dmangoapp=true
  -Dmangohudctl=true
  -Dmangoapp_layer=true
)

  arch-meson MangoHud build "${meson_options[@]}"
  meson compile -C build
}
```

Note `Dmangoapp=true` and `Dmangoapp_layer=true`. These are flags passed when MangoHud is built - The MangoApp package on the AUR just clones the MangoApp repository and build it on your machine. It doesn't distribute a precompiled binary. Also note that MangoApp also has a 32bit variation Lib32-MangoApp. Repositories are here:

- https://aur.archlinux.org/packages/mangoapp
- https://aur.archlinux.org/packages/lib32-mangoapp

If you were to install MangoApp from the AUR, it would replace MangoHud as well as it builds both of them together. From reading this, to my understanding MangoApp is basically like an "extra" of MangoHud.

However MangoHud is packaged on Nobara means that MangoApp is not built with it. I don't think it's possible to distribute MangoHud and MangoApp separately, or at least it doesn't seem to be *conventional*. I have little experience with PKGBUILD files but it seems like MangoHud is a dependency of MangoApp, maybe MangoApp just changes how MangoHud is injected, that could be the case based on the description from FlightlessMango in flightlessmango/MangoHud#625.

> The purpose of [MangoApp] is to "easily" make mangohud compatible with any application, or at least any application that gamescope can run. This solves issues with some OpenGL games and certain ports that have stdc++ issues as it's no longer directly injected into the game

Also, as an aside, though MangoApp may work standalone, it is really designed to run with applications using GameScope. Your mileage may vary without using GameScope, but I know you mentioned you specifically wanted to use this *with* GameScope :smiley: 

So really as it stands I don't think you can use the MangoHud binary on Nobara if you want to use MangoApp. You would have to build from source, and as I am not super well versed in the options for building with these kinds of options I'm not sure how you would do it. You might have to look around for other examples of how to pass build flags to whatever build system MangoHud uses (seems like Meson?)

It would've saved a lot of headaches if this was included in the MangoHud Readme's building and installing section (afaict it's not). It might also be worth politely asking GloriousEggroll to add either a separate MangoHud binary with MangoApp enabled, or include it in the main binary. I believe he is fairly active on his Nobara/Proton-GE Discord server but you might be able to contact him in other ways.

Either way, I'll add a note about MangoApp being an extension of MangoHud that has to be specifically enabled when building MangoHud with a flag. Sorry we didn't really get this "resolved", as  it turns out the core of the issue really was that MangoApp was not installed. Hopefully there's a happier resolution upstream for you :smile:

**Comment by sonic2kk** [comment]
Updated the MangoHud wiki with a MangoApp section: https://github.com/frostworx/steamtinkerlaunch/wiki/MangoHud#mangoapp

**Comment by Slippingstones** [comment]
I would say this is solved with the update to MangoHUD wiki, and knowledge that mangohud must be built with the flag enabled :)
