### ISSUE TITLE
TSMP does not show Play Button | WAS: ETS2 crashes without any errors

### ISSUE THREAD

**Issue by taynotfound** [sonic2kk/steamtinkerlaunch#588]
**Version** 11
**Ditro** Ubuntu

I tried DirectX, OpenGL and normal. It just crashes with Steamtinkerlaunch.

![image](https://user-images.githubusercontent.com/50525948/190878961-557deec5-9c89-410a-a287-8332512262d2.png)
Maybe this screenshot help. 

No logs provided cuz no logging made in that time

**Comment by sonic2kk** [comment]
Looks like STL didn't find your Proton version. Make sure you set it correctly in the Game Menu.

Also, there should be logging either at `/dev/shm/steamtinkerlaunch` or `~/.config/steamtinkerlaunch/logs/steamtinkerlaunch/title/Euro Truck Simulator 2.log`.

I actually own this game and have played it with STL, so it should work. One of the notifications in that screenshot looks a little strange to me as well, perhaps it is related to the Proton version: `Starting game 'YYY (ZZZ)' using  X...` (I assume it just got cut off at the end :smiley:).

Are you using SteamTinkerLaunch as a compatibility tool or a launch option? Compatibility tool is for Proton games, launch option is for native games. Forcing STL as a compatibility tool will always download the Windows version of a game, this seems to be something Steam does and not something STL can do much about. So just keep this in mind when you're playing native games (like ETS2).

**Comment by taynotfound** [comment]
I didn't know I needed to set the Proton in the Game Menu tbh😅 yea I am a bit dumb lel. gonna try that tomorrow

The notication you are mentioning was because I tried with normal just "Play ETS2" and there it told me things abt my Graphics not Existing basically.

I'm going to try it as a launch argument tomorrow as it's like 2AM for me

And yea I didn't know ETS logs stuff.

**Comment by sonic2kk** [comment]
Normally you don't have to set the Proton version but for some reason this time STL didn't catch it 😅 No worries.

Btw, they aren't ETS specific logs. STL generated logs virtually every time you run it at `/dev/shm/steamtinkerlaunch` and on a per-game basis in the logs folder I mentioned 😃

**Comment by taynotfound** [comment]
Okay now it does not crash but it does not show the Button to press to play

![image](https://user-images.githubusercontent.com/50525948/190895126-3eae4c36-d684-45e3-b8ef-dc4c598f9afa.png)
I can only Press "X"


Here is the Log
https://hastebin.com/uyapisiqor.apache


And without proton its completely borked. It Stretches the Window out of my Screen and the Mouse is completely not working. Thats why i try Proton

**Comment by tayron1** [comment]
I cant only press the X

**Comment by sonic2kk** [comment]
Is this issue specific to SteamTinkerLaunch? Does the game show the play button if you launch it without SteamTinkerLaunch? Looking at the logs it looks like you're using STL to launch a custom executable for this game, so it might be worth looking around online to see if this executable is supported with Wine.

Likely this is not an issue specific to SteamTinkerLaunch.

> And without proton its completely borked. It Stretches the Window out of my Screen and the Mouse is completely not working. 

If there is an official Linux release of this TruckersMP, you can try to lock the game to your display by using GameScope. Just remember, if you're playing a native Linux game, you should use SteamTinkerLaunch as a launch option :smile:

**Comment by sonic2kk** [comment]
Ah, looking into it, that window that you showed looks like it's some sort of GUI program. I had thought it was part of the game UI.

You might want to try installing the `dotnet48` winetrick **via SteamTinkerLaunch** (STL does some magic to get dotnet48 to install correctly). You can do this from SteamTinkerLaunch by clicking the Winetricks button and doing the following:

1. Ensure "Winetricks category" is set to `dlls`
2. Ensure "WInetricks Proton" matches the version of Proton you're running the game with (almost always does)
3. Press the "Select" button and wait a bit, a window will appear with a list of things you can install
4. This list should be alphabetical, so scroll down a little bit until you see `dotnet48`. Click the checkbox beside it and then click "Select"
5. The window will close and you'll be back to the previous screen. It should show `dotnet48` under "**Currently selected pacakges:**
6. Press the "Install" button and wait for it to install. This can take a while as dotnet48 is quite a lengthy install, I'd recommend grabbing a coffee :wink: 
7. Once it's installed you can click the "Done" button, then try to launch your game. All being well, you'll see your play button now.

You *shouldn't* encounter any issues, but if you do, you can remove the game's wine prefix by launching it with SteamTinkerLaunch, pressing the "Game Files" button, selecting the "WINEPREFIX" option, and then deleting the folder that opens. Then you can rerun your game and it'll be like `dotnet48` was never installed.

Good luck!

**Comment by taynotfound** [comment]
I pressed "Install" it gave me the Notifation that its installing.
Not even a minute after it showed me that its already done tho. But no window popped up yet. I dont hear much coming from my HDD too.

![image](https://user-images.githubusercontent.com/50525948/190927962-0d64053a-d975-4f9c-b5cd-15a81736df6d.png)

**Comment by taynotfound** [comment]
Seems like its installed idk? It gave me the Notifs after i pressed play too. Still no Play button. Idk whats wrong with it

**Comment by taynotfound** [comment]
Just selected a bit more stuff to install like Python, IE and some stuff. Now it takes a lot longer. Lets see

**Comment by taynotfound** [comment]
Welp. No help with that too
still same issue

**Comment by sonic2kk** [comment]
> Seems like its installed idk? It gave me the Notifs after i pressed play too. Still no Play button. Idk whats wrong with it

It could be that this program does not work on Linux. Did you verify that it works without SteamTinkerLaunch? How did you launch it previously?

> Just selected a bit more stuff to install like Python, IE and some stuff. Now it takes a lot longer. Lets see

This probably won't do anything, `dotnet48` is the winetrick I thought that was needed.

> Welp. No help with that too

I was not around to see your replies until now. Please be patient, sometimes it can take a while for issues to be resolved :slightly_smiling_face:

**Comment by sonic2kk** [comment]
There is a third party tool (https://github.com/truckersmp-cli/truckersmp-cli#known-issues) which in its known issues mentions that `d3dcompiler_47.dll` may be required. You should be able to install this DLL with Winetricks, too. Though I'm not sure why this would prevent logging in from working, I know this is a common workaround for several games and used to be an extremely common workaround for non-Steam games.

Sadly, there is a limited amount of support I can give for this issue. You could try deleting your Wine prefix and running the game with a version of GE-Proton if you aren't already (keep in mind deleting the Wine prefix will remove the winetricks tweaks, so you'll have to reinstall them, though if `dotnet48` and `d3dcompiler_47` do nothing, it's probably not worth reinstalling them if you try another Proton version), if the above DLL winetrick does not solve your issue. Unless this issue only occurs when launching the game via SteamTinkerLaunch, this is probably just a problem with the custom program you're trying to use.

If you tried running this program before with your system Wine or with Lutris Wine, it could simply be that the version of Proton you are using doesn't have the patches the version of Wine you can the game with before has. To that end, it might be worth trying a build of Proton-tkg (https://github.com/Frogging-Family/wine-tkg-git/actions/workflows/proton-arch-nopackage.yml). If you do not know how to install custom Proton versions, see the Proton-tkg readme for guidance: https://github.com/Frogging-Family/wine-tkg-git#proton-nightly-builds

I truly hope you can get this resolved because it would suck if this just didn't work. Though it is not uncommon for GUI programs to have issues, things are constantly improving on this front, which is why I recommend Proton-tkg if you *know* the game works with other versions of Wine/Proton.

**Comment by taynotfound** [comment]
> I was not around to see your replies until now. Please be patient, sometimes it can take a while for issues to be resolved slightly_smiling_face

I meant with that that it didnt help to install more stuff lel.

**Comment by taynotfound** [comment]
> There is a third party tool (https://github.com/truckersmp-cli/truckersmp-cli#known-issues) which in its known issues mentions that `d3dcompiler_47.dll` may be required. You should be able to install this DLL with Winetricks, too. Though I'm not sure why this would prevent logging in from working, I know this is a common workaround for several games and used to be an extremely common workaround for non-Steam games.
> 
> Sadly, there is a limited amount of support I can give for this issue. You could try deleting your Wine prefix and running the game with a version of GE-Proton if you aren't already (keep in mind deleting the Wine prefix will remove the winetricks tweaks, so you'll have to reinstall them, though if `dotnet48` and `d3dcompiler_47` do nothing, it's probably not worth reinstalling them if you try another Proton version), if the above DLL winetrick does not solve your issue. Unless this issue only occurs when launching the game via SteamTinkerLaunch, this is probably just a problem with the custom program you're trying to use.
> 
> If you tried running this program before with your system Wine or with Lutris Wine, it could simply be that the version of Proton you are using doesn't have the patches the version of Wine you can the game with before has. To that end, it might be worth trying a build of Proton-tkg (https://github.com/Frogging-Family/wine-tkg-git/actions/workflows/proton-arch-nopackage.yml). If you do not know how to install custom Proton versions, see the Proton-tkg readme for guidance: https://github.com/Frogging-Family/wine-tkg-git#proton-nightly-builds
> 
> I truly hope you can get this resolved because it would suck if this just didn't work. Though it is not uncommon for GUI programs to have issues, things are constantly improving on this front, which is why I recommend Proton-tkg if you _know_ the game works with other versions of Wine/Proton.

Trying this later ^^

**Comment by sonic2kk** [comment]
Just out of curiosity, have you tried to run this program on Linux without STL? What I'm getting at is, does this issue with this program only happen when you're using SteamTinkerLaunch? If this issue happens without SteamTinkerLaunch and if none of the above suggestions help, you might have to look around online and find out how to get this program to work.

SteamTinkerLaunch supports launching third party programs and aims to give you the tools to help get your programs to work, but it does not set out to guarantee support with third party applications that don't already work with Wine. Of course, there can and have been issues in the past where *specific* applications don't work *only* when trying to launch them with STL, but we can't exactly fix programs that don't work on Linux in general.

Compatibility with tools is always improving, and if your application doesn't work you could always report it as a bug to Wine (https://bugs.winehq.org/), though you'd have to try running it with system Wine before reporting the problem to them.

Wine compatibility is constantly improving, but some applications may still not work, and STL can't do very much about that sadly. But don't be disheartened, in my experience applications not working are more and more becoming the exception rather than the rule. So feel free to try other custom commands with other games using STL!

**Comment by frostworx** [comment]
I'm very confident that this issue is not steamtinkerlaunch related, but didn't want to prevent you from helping

**Comment by sonic2kk** [comment]
I also don't think it's specific to SteamTinkerLaunch, however I just found this neat little tidbit on the Custom Program section: [A Steam guide for getting TruckersMP working on Linux with SteamTinkerLaunch](https://steamcommunity.com/sharedfiles/filedetails/?id=2800355160). Not sure if there have been updates or anything since then but might be worth taking a look at!

**Comment by frostworx** [comment]
You might want to check the last comment 😀

**Comment by frostworx** [comment]
same as in #599

```
I doubt this leads anywhere, so closing
If you're willing to provide any useful information, feel free to reopen "lol"
```
