### ISSUE TITLE
cabextract missing for flatpak support

### ISSUE THREAD

**Issue by jarrard** [sonic2kk/steamtinkerlaunch#593]
Been trying to use winetricks to install some stuff like corefonts. 

Can't be done as cabextract is not available for flatpak. I've tried to fix it myself but nothing works. :(

**Comment by jarrard** [comment]
Managed to fix it by installed cabextract into USER .local/bin folder and putting that in the flatseal steam file path options.

Really it shouldn't be a problem to begin with but anyway.

**Comment by sonic2kk** [comment]
Flatpak support is missing quite a lot as far as I know. Please ask in the Flatpak support thread about including cabextract with the Flatpak 😃

Flatpak STL is maintained by a different user as far as I know.

Perhaps STL Flatpak could add this directory (or a similiar one) to it's path, just like you did via Flatseal, and either the Flatpak or STL could download the cabextract dependencies. Though the problem is how to do this in a cross-platform way, I wonder how Protontricks Flatpak does it.

**Comment by frostworx** [comment]
> Really it shouldn't be a problem to begin with but anyway.

send a PR to help others then

**Comment by sonic2kk** [comment]
@jarrard SteamTinkerLaunch Flatpak has merged in cabextract to it's repository, this issue should now be resolved. Not sure how releases and such work over there but it should be available at some point if it isn't already.
