### ISSUE TITLE
Steamtinkerlaunch spams my notifications

### ISSUE THREAD

**Issue by taynotfound** [sonic2kk/steamtinkerlaunch#599]
https://user-images.githubusercontent.com/50525948/192057193-81b015ac-be5d-4214-8ad3-b5d0164e98c8.mp4

**Comment by taynotfound** [comment]
The Recording didnt even catch the spaming

**Comment by taynotfound** [comment]
![image](https://user-images.githubusercontent.com/50525948/192057400-f46158d2-1af7-4510-8294-363755b31052.png)

**Comment by sonic2kk** [comment]
While this is a problem, the issue seems to be that you have not selected a Proton version. This doesn't seem to be the first time this has happened either if I recall from your other issues.

Please remember to read the [sticky issue](https://github.com/frostworx/steamtinkerlaunch/issues/93) before opening an issue. When you create an issue, it also asks you to read this issue before continuing. Please provide information about your system (STL version, distro, and most importantly a log file).

Please try to run your program again and attach a log. You can likely fix the notification spam by selecting a Proton version, but I'd like to see a log to see if we can work out *why* STL isn't catching your Proton version. You can find a log most conveniently at `/dev/shm/steamtinkerlaunch`.

Out of curiosity, where is Proton installed on your machine? If you don't know, Proton installs to the Steam library folder of the first game that requires it. You can search for Proton in your Steam library like you would search for a game, then right click > manage > browse local files.

I'm wondering if maybe SteamTinkerLaunch is failing to read the paths to your home folder, or perhaps your drives use some characters SteamTinkerLaunch for some reason cannot read. Just a wild guess though.

**Comment by taynotfound** [comment]
I dropped steamtinkerlaunch and did on the Steam Play thingy that it installs Proton 7 and then it did that. Uninstalled it and now trying truckersmp-cli. as that was the only use for it lol

**Comment by taynotfound** [comment]
btw if ur curious. truckersmp-cli doesnt work too

**Comment by sonic2kk** [comment]
> I dropped steamtinkerlaunch and did on the Steam Play thingy that it installs Proton 7 and then it did that. Uninstalled it and now trying truckersmp-cli. as that was the only use for it lol

I'm sorry, I'm not sure what this means. Did you uninstall SteamTinkerLaunch?

Also, you did not provide any logging. Please make sure you answer the questions laid out above and in the sticky issue, namely:

- SteamTinkerLaunch version
- Distribution
- Installation method
- Log file

> btw if ur curious. truckersmp-cli doesnt work too

If this is related to your other opened issue #588, it's probably best to have the discussion on that issue.

I'm sorry but I'm having trouble understanding the current status of this issue and the problems you are having. Please make sure you provide all requested information when opening an issue.

**Comment by frostworx** [comment]
I doubt this leads anywhere, so *closing*
If you're willing to provide any useful information, feel free to reopen "lol"

**Comment by hazelnot** [comment]
I've had this issue as well today, except with it complaining over and over again that it can't find proton-9.0-4c

[steamtinkerlaunch.log](https://github.com/user-attachments/files/18252148/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Sounds like you didn't delete `/dev/shm/steamtinkerlaunch` after updating a Proton version, which is required because you are using v12.12 instead of the latest master where this issue is fixed.

Information on the issue you're facing [is also on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Troubleshooting#newupdated-proton-versions-arent-showing-up).

**Comment by hazelnot** [comment]
Ah fair, I'll just update STL then, thanks!
