### ISSUE TITLE
Can it launch games from outside of steam?

### ISSUE THREAD

**Issue by premier69** [sonic2kk/steamtinkerlaunch#612]
Not so much an isse as a question.

i downloaded an iso, a windows game and installed it by mounting the image and just double cliking, essentially just unpacking the game to a wine folder. is it possible to launch these kinds of installed games with STL?

**Comment by AliceDTRH** [comment]
Yes. https://github.com/frostworx/steamtinkerlaunch/wiki/Add-Non-Steam-Game may help with that.

**Comment by sonic2kk** [comment]
You can set a custom command from the Game Menu to launch with your game (before or after it with a customisable delay), or instead of your game. Make sure you enable the "custom command" option and set the path.

You can run Windows and Linux custom command applications (including scripts) regardless of whether you're using SteamTinkerLaunch with a Windows game or a native game.

As long as you know the path to the executable, `.lnk` etc file you can browse to it from SteamTinkerLaunch (if you want to enter an exact path, use Ctrl+L with the file dialog open - That's how you enter file paths with GTK3 dialogs, pretty handy 😃). Please remember though that if your game doesn't work outside of SteamTinkerLaunch it probably won't work with SteamTinkerLaunch. Basically if your program is incompatible with Wine/Proton from the start SteamTinkerLaunch won't do anything fancy by default to get it to work, aside from letting you download and use custom Proton versions/use system Wine which may have improved compatibility unrelated to using SteamTinkerLaunch.

You can also use SteamTinkerLaunch with Steam shortcuts, so if you added this game as a shortcut to Steam you can also use STL that way.

Hope that answers your question 😃

**Comment by premier69** [comment]
i don't know why bu i can't get the gui to launch in my linux mint installation, i think i followed the ubuntu guide correctly... I'll look into the other stuff you guys wrote, Thank You!  I'll be back in a few minutes if i have more questions...

in this case for example i want to get cyberpunk 2077 working in linux which i haven't been able to earlier by double clicking the .exe to play it or using lutris.

**Comment by sonic2kk** [comment]
> i don't know why bu i can't get the gui to launch in my linux mint installation

Someone reported a few issues with Yad on Linux Mint, but just make sure you're using Linux Mint 21 or newer as it is based on Ubuntu 21.04 which SteamTinkerLaunch needs. It's GUI, which uses Yad, only works on Ubuntu 21.04 or newer and distros based on it.

> in this case for example i want to get cyberpunk 2077 working in linux which i haven't been able to earlier by double clicking the .exe to play it or using lutris.

If you bought Cyberpunk 2077 on Steam it should just work by launching it via Steam. If you bought it on GOG/EGS you should be able to get it to work with Lutris and perhaps a custom version of Proton like GE-Proton. I can't give you any support if you are not using a legal copy of the game.

**Comment by frostworx** [comment]
original answer was already answered _(btw please check the wiki first and then ask)_
feel free to open a separate and complete issue for the gui problem, after you made sure everything was read and done before.
you're on your own with downloaded isos...
