### ISSUE TITLE
Lost Internet connection

### ISSUE THREAD

**Issue by Dersubayes** [sonic2kk/steamtinkerlaunch#627]
System:
- SteamTinkerLaunch version: v11.11
- Distribution: 
- Installation Method: 

Description:

When I start a game with Steam Tinker Launch the game is offline. I have tried changing the version of proton and I have checked that "block internet" is unchecked.. If I start the same game with normal proton, everything works without problem

Logs are with de Ubisoft Connect added how a Non Steam App

[2293692860.log](https://github.com/frostworx/steamtinkerlaunch/files/9745698/2293692860.log)

[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/9745701/steamtinkerlaunch.log)

[UbisoftConnect.log](https://github.com/frostworx/steamtinkerlaunch/files/9745702/UbisoftConnect.log)

**Comment by frostworx** [comment]
This is not really a steamtinkerlaunch issue.
A non-steam game should start the defined exe and not a custom program _(might be "fixable", but for me, this is out of scope of the project. Proper PRs welcome, of course. With some luck, the future enhanced custom program implementation, discussed in #625 can improve the situation)_

Both functionality for every non-steam program and every custom-program is not supported generally.
The users have to take care themselves if they work.
Seems like there is also a weird mixture between multiple non-steam compatdata directories _(2293692860, 3287651050)_

Generally a combination between external `UbisoftConnect` and a  `Assassins Creed Origins v1.02-v1.51 Plus 16 Trainer.exe`
looks like dynamite, as both individually are already almost doomed to fail _(shitty drm, unknown dependencies, possibly badly written code, which might be incompatible with proton, all together started forked without any redist help from steam)_.

Sorry, totally out of scope and I recommend not to waste any time into this.
Leaving this open for a while in case someone else has some _(very likely steamtinkerlaunch unrelated)_ hints for you.

**Comment by sonic2kk** [comment]
If this only happens with STL perhaps there is something wrong here, though I've never experienced anything like this. I'll have to check the logs in a bit when I'm on PC.

In the meantime, @Dersubayes please fill out the missing entries in your System Information. Both of those missing fields may be of particular interest here.

Please also tell us how you launch the game without STL. Do you use it as a shortcut with Steam?

Also, how are you using STL with this game? Are you using it as a launch option or as a compatibility tool? Or are you using Ubisoft Connect as a custom command with STL for another game?

Logs might have answers to some of these but to avoid guesswork, please provide more detail 🙂

**Comment by sonic2kk** [comment]
Starting to dig through the logs and noticed you're using GE-Proton7-37. Make sure this is the same version of Proton you're using when you launch the game without STL, make sure this isn't a Proton compatibility issue.

So far in the logs I'm not seeing anything that points to this being directly related to STL. It could be just that the Ubisoft DRM doesn't work when launching via STL or something.

You'll need to provide more information.
- In the case of the Ubisoft game, is Ubisoft Connect a Non-Steam Game that you're starting with STL and using a custom command with?
- Does this happen with any other game you have tested? You only mention this specific instance.

Also noticed from your logs that you are on Steam Deck, but it would've been useful to have this in the opening issue :smile: 

EDIT: just noticed `2293692860.log` and `UbisoftConnect.log` are the same log. I guess Ubisoft Connect is being started as a Non-Steam Game with STL. Also not seeing any reference to the Steam Linux Runtime or similar hints in the log, so I am assuming this is a Non-Steam Game being started with STL as a compatibility tool. The exe is also pointing to the custom program's prefix it looks like? `/home/deck/.local/share/Steam/steamapps/compatdata/3287651050/pfx/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/UbisoftConnect.exe` Maybe the installer was ran with Steam or something? Not sure.

I haven't encountered this issue with any games on my Deck as far as I know, but I'm really intrigued why this works without STL. It could be a Wine compatibility thing - My hunch is the Proton version rather than STL.

**Comment by frostworx** [comment]
> If this only happens with STL perhaps there is something wrong here

you might have missed my previous reply

**Comment by sonic2kk** [comment]
Hmm, I read through the OP and your message again and I think I get the gist. Maybe it's the Trainer that's causing the connection failure for Ubisoft Connect. In that case, I'd also agree it's unrelated to STL.

The logs provide no indication that STL is doing anything so it's something on the user's end that needs configured better it seems - I would also agree that even in general Non-Steam Shortcuts should be for well defined standalone executables rather than installed programs. In that case, on Steam Deck in particular, you're much better off with [Bottles](https://usebottles.com/) or [Lutris Flatpak](https://github.com/flathub/net.lutris.Lutris) (linking the Flathub repo because I think it still needs the GNOME dependencies to be installed separately).

There could be a whole host of other things wrong here unrelated to STL so there'll need to be a lot more info and testing.

**Comment by frostworx** [comment]
Thanks for confirming and sorry, didn't want to prevent you from helping.
But I'm very certain that this is not steamtinkerlaunch related, and therefore wanted to save you some time.
_(sure, custom programs could be made to work with non-steam games in case this does not work currently, but that is likely not the point, and likely not worth the effort)_

**Comment by Dersubayes** [comment]
Hello and thanks you two for the effort.

I will try to clarify some things to resolve the doubts :

1- yes, it's on steam deck (sorry I could swear I put it in the 1st message but somehow i lost it)

2- I have installed Ubisoft Connect by adding the installer to steam and then once installed adding the exe of the program.

3- If I start the program without using the STL, it works perfectly. I have already verified that it is the same version of proton in both cases. Program only fails if I choose STL.

4- Doesn't seem a trainer problem. If I remove the execution of the trainer from the STL and simply execute it through STL without giving more added options, it still gives me the same problem. 

This puzzles me.... if i don't put extra options, shouldn't STL works the same way that if I start with the proton directly?

5- I tried reinstalling SteamTinkerLaunch and deleting config file and nothing has changed.

P.D: I must say that I have found more failures but they are always with applications added from outside of Steam. (Battle, chiaki, moonlight ..etc) Maybe as @frostworx says non steam apps are out of scope and not worth the effort.

**Comment by frostworx** [comment]
Looking at the log it seems you're trying to run ubi from a different compatdata it was originally installed (two different steamappids). So I'd suggest to actually start the installer itself in that prefix, which likely will also install some required dependencies on its own.
When that worked, it would be interesting if the freshly installed ubi connect worked as non-steam game, but without the custom program enabled. If not you're welcome to append a new log.
If it does and the custom program still does not work without it, I guess that a custom program simply was never tested in combination with a non-steam game before and the function is simply not implemented.
It might be easy to fix, but it could cause multiple follow up problems as well and I doubt I find the time anytime soon to look into this (for pretty low gain)

**Comment by sonic2kk** [comment]
> P.D: I must say that I have found more failures but they are always with applications added from outside of Steam. (Battle, chiaki, moonlight ..etc)

Just to be sure, by "failures" you mean these apps also do not have access to the Internet?

As Frostworx mentioned, running an application in a different prefix than it was installed to could be causing issues. But if Ubisoft Connect is only causing issues when SteamTinkerLaunch is selected as a compatibility tool (and works if it is *not* selected, in the same application listing in your Steam library), that would be quite strange indeed.

**Comment by sonic2kk** [comment]
boop @Dersubayes Have you had any update on this? Some more information about the other apps you're experiencing issues with and what kinds of failures you're experiencing would be much appreciated :smile:

**Comment by sonic2kk** [comment]
No update after 3 days, closing this issue. Feel free to reopen if you have anything more to add OP :smile:

**Comment by veritas0x0** [comment]
Hey @sonic2kk I have this same issue(Ubisoft Connect launched with STL has no internet access but works without STL) Did you want me to open a new issue?
