### ISSUE TITLE
Unable to locate STL collection config in default path

### ISSUE THREAD

**Issue by Shadark** [sonic2kk/steamtinkerlaunch#644]
## System Information
- SteamTinkerLaunch version: v11.12.20221029-1
- Distribution: SteamOS
- Installation Method: Manual Installation, but also happened with ProtonUp-Qt install

## Issue Description
Honestly I'm not sure if this is an issue on my side at all or just some misinformation, or something wrong with the wiki, in any case:

As the [project wiki indicates](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Collections), "Collection Configuration Files are searched in the [User Configurations](https://github.com/frostworx/steamtinkerlaunch/wiki/Configuration-Files#User-Configuration) **STLCOLLECTIONDIR** (_STLCFGDIR/collections_) or in the [system-wide](https://github.com/frostworx/steamtinkerlaunch/wiki/Configuration-Files#Systemwide-Configuration) dir **GLOBALCOLLECTIONDIR** (_SYSTEMSTLCFGDIR/collections_)".

And, also [as the documentation says](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Configuration-Files), _STLCFGDIR_ should be, by default, _$HOME/.config/steamtinkerlaunch_ (or _XDG_CONFIG_HOME/steamtinkerlaunch_ if XDG_CONFIG_HOME is set).

However, when launching STL installation, both manually or from ProtonUp-Qt, STL gets installed to $HOME/stl. And, inside _$HOME/stl/prefix/collections_ there are multiple .conf files for all the Collections. But, in _$HOME/.config/steamtinkerlaunch/collections_, the folder is empty.

I'm able to launch Skyrim from the collection. When launching with no compat mode, only the Skyrim launcher opens. When using STL compat mode, STL GUI opens before launching the game, but I can't see no mention of Vortex being launched even with vanilla Skyrim is in the "Vortex" collection.

I guess this could be a non-issue but I am having some other problems (that I'm not sure if they're entirely STL-related, so that's why I'm not posting an issue for that) with installing Skyrim Together Reborn (STR) + mods on the Steam Deck and I got to the point where I'm able to launch Skyrim + mods from Vortex or MO2 without any issue, but I can't launch STR executable with mods (on Vortex, MO2 crashes with [this error](https://github.com/rockerbacon/modorganizer2-linux-installer/issues/362#issuecomment-1186399082)). As I said, I'm not sure if these issues are STL-related, but at least I would like to make sure if my collections are working (since I've added STR as a non-Steam game in my Vortex collection, but it's not loading Vortex config apparently).

In any case, any help is more than welcome, and feel free to close this issue if this is outside the scope of the project. Thanks in advance!

## Logs
[steamtinkerlaunch.log "vanilla", without opening Skyrim](https://github.com/sonic2kk/steamtinkerlaunch/files/9893846/steamtinkerlaunch.log)
[steamtinkerlaunch.log after opening Skyrim](https://github.com/sonic2kk/steamtinkerlaunch/files/9893859/steamtinkerlaunch.log)

**Comment by Shadark** [comment]
Skimming through the logs on the 2nd file, lines 166-168 indicate that the collection can't be found in both paths, so I guess STL is searching in both? But my collection is called Vortex, so I'm not sure why it's not "finding" it.

**Comment by Shadark** [comment]
sharedconfig.vdf: 
[sharedconfig.vdf.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/9893873/sharedconfig.vdf.txt)

**Comment by sonic2kk** [comment]
Hey there! I'm sorry, I'm not really sure what the issue is.

Configuration data won't be stored in the SteamTinkerLaunch installation directory, it gets stored in `$HOME/.config/steamtinkerlaunch`.

I'm not sure what data is meant to get stored in the `collections` folder there, but if you add your game to the collection and launch it, it should launch with Vortex enabled by default. That's all adding your game to a collection should do - Enable the corresponding option. So if your game launches with Vortex enabled, that should be all the collection function has to do I think?

The only other thing I can think of is that the category is not named with the correct case maybe, but I'm not sure if that actually matters too much from skimming the code. Make sure it's named `Vortex`, with a capital `V`, as that's what the wiki denotes (Steam categories are displayed all uppercase, but internally they are stored case sensitive).

<hr>

As for the issue you're having with your mod, that is likely a problem with the mod running on Linux. As far as I know, STL should not affect mod compatibility on Linux. Sorry but I can't give you much support on it. If you get any feedback on your open issue on the other repo, and it is something Linux specific that you think we have to fix, please leave a comment here and we can get it sorted.

<hr>

For your Collections issue, please give me a little more background as I'm just not sure what the problem is exactly :sweat_smile: Thank you!

**Comment by sonic2kk** [comment]
> Skimming through the logs on the 2nd file, lines 166-168 indicate that the collection can't be found in both paths, so I guess STL is searching in both? But my collection is called Vortex, so I'm not sure why it's not "finding" it.

Ah! This was a very useful hint. I'm not sure exactly what's going wrong but it can't find the category config for Vortex for some reason (I guess it's looking for `<blank>.conf`, where it shouldn't be `<blank>`). Steam Collections are not as far as I know a very broadly used feature, but this is indeed a bug and something I'll look into fixing!

*(Unrelated specifically to this issue, but I could see this causing problems with non-root installs in general (such as on desktop via ProtonUp-Qt), where STL might always point to the root folder on desktop even if there's nothing there. A failsafe to check elsewhere might be a good idea here. Small note to self on that one!)*

Hmm, I'll have to look into this, but I have a feeling that these lines you pointed out:

```
Sat Oct 29 16:17:41 CEST 2022 INFO - autoCollectionSettings - Searching collections for game '489830' in 'sharedconfig.vdf'
Sat Oct 29 16:17:41 CEST 2022 SKIP - autoCollectionSettings - Config '/home/deck/stl/prefix/collections/.conf' not found - skipping
Sat Oct 29 16:17:41 CEST 2022 SKIP - autoCollectionSettings - Config '/home/deck/.config/steamtinkerlaunch/collections/.conf' not found - skipping
```

Are the problem.

**Comment by sonic2kk** [comment]
Also, with your first log, it looks like you're running SteamTinkerLaunch from the command line. The log looks fine there, I'm not sure what you are expecting to happen in that log.

**Comment by sonic2kk** [comment]
I don't use the Steam Collections feature (I have ~100 of my own collections, no need for extra clutter) but I think the Category isn't being fetched correctly from the `sharedconfig.vdf` file. I'll have to do some tests to see if the script isn't reading it correctly anymore.

Relevant code is here, the end is where the I believe parsed collection names are passed to the `while` loop: https://github.com/sonic2kk/steamtinkerlaunch/blob/master/steamtinkerlaunch#L9062-L9089 (might take a while to load, but you can also open the file locally if you wish and go to those lines :slightly_smiling_face: )

I'll do some testing and see if the parsing of the `sharedconfig.vdf` is the culprit here.

**Comment by sonic2kk** [comment]
Hmm, I just did a quick test locally with this code, creating/copying the relevant files:

```sh
SC="sharedconfig.vdf"
STLCOLLECTIONDIR="collections"
AID="489830"

if [ ! -f "$SC" ]; then
    echo "sharedconfig not found"
else
    echo "found sharedconfig"

    while read -r SCAT; do
        echo "scat is $SCAT"
        SCATCONF="$STLCOLLECTIONDIR/$SCAT.conf"
        if [ -f "$SCATCONF" ]; then
            echo "found scatconf"
        else
            echo "no scatconf found"
        fi
        
    done <<< "$(sed -n "/\"$AID\"/,/}/p;" "$SC" | sed -n "/\"tags\"/,/}/p" | sed -n "/{/,/}/p" | grep -v '{\|}' | awk '{print $2}' | sed "s:\"::g")"
fi
```

And this seems to correctly return Vortex found for the AppID.

I'm not totally sure what the problem could be. Even in the log line before it searches for the files, STL correctly has the `AID` for your game (and it matches what's in your `sharedconfig.vdf`). Your casing also looks correct.

I'll keep digging.

**Comment by sonic2kk** [comment]
Might be a silly question but, does `Vortex.conf` definitely exist in your `/home/deck/stl/prefix/collections` folder?

**Comment by sonic2kk** [comment]
@Shadark I took a look at the issue you mentioned and though it should work with Vortex, you can probably emulate the steps the first reply outlined with SteamTinkerLaunch by doing the following:

1. Set SkyrimTogether.exe as your custom command (you may need to choose "Only custom command" if it's meant to launch instead of your game)
2. For the custom script you can add a custom start script to a game with SteamTinkerLaunch

These steps might work, I haven't used that mod and you might need to do other tinkering steps, but that might work.

Although I would say it would be more straightforward to use Vortex.

Also, as for loading that mod as a Non-Steam Game, modding Non-Steam Games is **not** supported by SteamTinkerLaunch.

**Comment by sonic2kk** [comment]
@Shadark  Another idea I just had, maybe you need to restart Steam before the `sharedconfig.vdf` will update? Not sure if this is the case though but something worth trying.

**Comment by Shadark** [comment]
> Might be a silly question but, does `Vortex.conf` definitely exist in your `/home/deck/stl/prefix/collections` folder?

Yeah, it does.

I'll add that in some of my previous tries trying to get STR to work, I followed the advice of a person that I found online that did manage to get STR working on the SD using STL. They told me that because of (apparent) capitalization, they made a symbolic link from Vortex.conf to VORTEX.conf, but I'm guessing with the current code that it wouldn't be needed.

> @Shadark Another idea I just had, maybe you need to restart Steam before the `sharedconfig.vdf` will update? Not sure if this is the case though but something worth trying.

I've also restarted the SD multiple times and it didn't seem to work.

---

As we established from the logs, it seems that vanilla Skyrim isn't being loaded through the Vortex collection. I'll add that, yesterday, I ran "_steamtinkerlaunch vortex games_" and neither Skyrim nor STR (I think it didn't appear there, in fact) had the "Vortex Steam Collection" column set to "Yes" (not sure if relevant, but Skyrim with id 489830 also didn't had a Game Title in there).

Is there anything else that I could try to check to see if, at least, collections could be working properly so I can try to narrow down the issue a bit?

In any case, again, thanks for your help and feel free to comment on whatever else you could need!

**Comment by sonic2kk** [comment]
> I'll add that, yesterday, I ran "steamtinkerlaunch vortex games" and neither Skyrim nor STR (I think it didn't appear there, in fact) had the "Vortex Steam Collection" column set to "Yes" (not sure if relevant, but Skyrim with id 489830 also didn't had a Game Title in there).

STR is not going to show up because it is not a Steam game. STL cannot and does not offer support for Non-Steam Games, you're very much on your own with getting mods to work. But the broad issue of the collection not working is a problem.

Just so you know too, you do not need to use Steam Collections to use Vortex with your game. But this is a problem and I'd like to look into fixing it, so thanks for bringing it to my attention either way :-) 

No leads yet on what's causing it. So in short you should be able to use Vortex with STL just not using the collections feature if you need your mod to work right now.

Since the capitalisation symlink thing worked for another user, you could try creating that symlink and seeing if it works for you. That would be strange but I guess in that case. It really seems like STL just isn't reading the folder with the categories correctly and I'll need to look into why. Maybe it's a thing specific to Steam Deck that I'll need to test on Deck to try and debug (I don't use mods on my Deck as a rule so I can't test Vortex specifically but I'll try some of the other collections options).

<hr>

Interestingly, the `steamtinkerlaunch vortex games` command does not show a correct games list for me (several entries for New Vegas, several entries for Factorio, and several invalid game listings). So I cannot test that feature and I'm planning to look into what's causing that soon too.

So no leads yet, but hopefully I'll figure it out soon :-)

**Comment by sonic2kk** [comment]
So I added a couple of games to a new Steam Collection, and that collection isn't showing up in my `sharedconfig.vdf`. Where did you get your `sharedconfig.vdf` file? The location should be `/home/deck/.local/share/Steam/userdata/65217330/7/remote/sharedconfig.vdf` - Is this where you found yours? I added some extra logging (locally - for now) to help debug this.

My `sharedconfig.vdf` shows up as modified, but new collections don't appear to be showing up there under my game's AppID. This is very strange.

**Comment by sonic2kk** [comment]
Okay that was really strange. I removed my game from the Steam Collection, added it again, and now it shows up in the `sharedconfig.vdf` file.

Can you try removing your game and adding it to the Collection again? This seems like a weird Steam bug, but I successfully got this after removing and re-adding my game to the Vortex collection:

```
Sat 29 Oct 18:58:29 BST 2022 INFO - autoCollectionSettings - Searching collections for game '584400' in '/home/emma/.local/share/Steam/userdata/65217330/7/remote/sharedconfig.vdf'
Sat 29 Oct 18:58:29 BST 2022 SKIP - autoCollectionSettings - Global Config '/usr/share/steamtinkerlaunch/collections/favorite.conf' not found - skipping
Sat 29 Oct 18:58:29 BST 2022 SKIP - autoCollectionSettings - Collections Directory Config '/home/emma/.config/steamtinkerlaunch/collections/favorite.conf' not found - skipping
Sat 29 Oct 18:58:29 BST 2022 SKIP - autoCollectionSettings - Global Config '/usr/share/steamtinkerlaunch/collections/SEGA.conf' not found - skipping
Sat 29 Oct 18:58:29 BST 2022 SKIP - autoCollectionSettings - Collections Directory Config '/home/emma/.config/steamtinkerlaunch/collections/SEGA.conf' not found - skipping
Sat 29 Oct 18:58:29 BST 2022 SKIP - autoCollectionSettings - Global Config '/usr/share/steamtinkerlaunch/collections/Sonic.conf' not found - skipping
Sat 29 Oct 18:58:29 BST 2022 SKIP - autoCollectionSettings - Collections Directory Config '/home/emma/.config/steamtinkerlaunch/collections/Sonic.conf' not found - skipping
Sat 29 Oct 18:58:29 BST 2022 SKIP - autoCollectionSettings - Global Config '/usr/share/steamtinkerlaunch/collections/Steam.conf' not found - skipping
Sat 29 Oct 18:58:29 BST 2022 SKIP - autoCollectionSettings - Collections Directory Config '/home/emma/.config/steamtinkerlaunch/collections/Steam.conf' not found - skipping
Sat 29 Oct 18:58:29 BST 2022 INFO - autoCollectionSettings - Global Config '/usr/share/steamtinkerlaunch/collections/Vortex.conf' found - loading its settings
```

There is some extra detail in the logs that I'll push up in a bit. Initially this didn't show up, it was as if my game was not in any collections. Your `vdf` file does show your game being in the Vortex collection, but please try removing and re-adding juuuust in case that fixes it. I don't think it's relevant, but I added my game to the Vortex collection using the Manage button -> Add to -> Vortex. I think you can drag games in and that should work too, and if it doesn't it's probably a Steam bug, but still worth trying just in case :-)

**Comment by Shadark** [comment]
Hello again! I'll try to respond in order to some of the questions/follow ups you mentioned:

> STR is not going to show up because it is not a Steam game. STL cannot and does not offer support for Non-Steam Games, you're very much on your own with getting mods to work.

I know, honestly I'm finding more help that I imagined considering the scope of my own issues, so I'm grateful for that. For this part, I was referring more to the fact that vanilla Skyrim didn't have the "Collection" column set to yes, in case it was relevant.

> Since the capitalisation symlink thing worked for another user, you could try creating that symlink and seeing if it works for you. That would be strange but I guess in that case.

If I recall correctly, they mentioned that they did the symlink just to get the collection working (I'm guessing initially?) but that afterwards the symlink wasn't there anymore but everything seemed to be working fine, so I can't know if originally the symlink did, indeed, work.

> The location should be /home/deck/.local/share/Steam/userdata/65217330/7/remote/sharedconfig.vdf

Correct, changing the user ID of course, but that's where I found the sharedconfig.vdf file.

> Can you try removing your game and adding it to the Collection again?

I've removed and readded Skyrim Special Edition to the Vortex collection twice, once adding it via drag&drop and another adding it via menu. Both times it appears on the sharedconfig.vdf file as being in the Vortex collection, but steamtinkerlaunch.log still doesn't find any collection when I try to launch the game:

```
Sun Oct 30 19:21:45 CET 2022 INFO - autoCollectionSettings - Searching collections for game '489830' in '/home/deck/.local/share/Steam/userdata/40895998/7/remote/sharedconfig.vdf'
Sun Oct 30 19:21:45 CET 2022 SKIP - autoCollectionSettings - Global Config '/home/deck/stl/prefix/collections/.conf' not found - skipping
Sun Oct 30 19:21:45 CET 2022 SKIP - autoCollectionSettings - Collections Directory Config '/home/deck/.config/steamtinkerlaunch/collections/.conf' not found - skipping
```

**Comment by Shadark** [comment]
A bit unrelated but I guess I could maybe solve my original STR issue with this, or at least dive a bit deeper:

Currently I only have vanilla Skyrim + some mods installed with Vortex. I'm able to launch Skyrim Script Extender (SKSE) from the executable already configured in Vortex. So what I'm doing is:
- Launching Vortex by:
  - Launching Skyrim via STL and selecting Vortex OR
  - Directly from command line
- Selecting SKSE64 in the Tools section
- SKSE -> Skyrim opens with the mods I've installed/activated.

However, I'm not sure about the procedure to launch SKSE from "outside" Vortex but preserving the modlist. I've tried by activating Skyrim STL Vortex options, but as far as I see that only opens a GUI asking me if I want to load Vortex. If I don't do anything, SKSE -> Skyrim load, but without mods loaded. Also, vanilla Skryim being or not in the "Vortex" collection doesn't seem to do anything, either.

Edit: Just to confirm (in case this is a _bigger issue_ than the collection not working: are we supposed to get a Vortex modlist working from _outside_ Vortex? As in, opening Skyrim (without opening Vortex UI) and loading the preconfigured Vortex modpack. I thought yes, but I can't seem to get it working no matter what I configure in the Skyrim STL config.

Any insights about this? Thanks again!

**Comment by sonic2kk** [comment]
@Shadark sorry, I'm not sure why your comment was marked as off-topic and I personally don't see it as off-topic per-se.

> However, I'm not sure about the procedure to launch SKSE from "outside" Vortex but preserving the modlist.

I don't have a *definite* answer to this regarding Vortex, but with MO2 you aren't intended to be able to launch a game modded outside of MO2. It uses a virtual filesystem to store and load mods when you run your game from MO2. However

> Just to confirm (in case this is a bigger issue than the collection not working: are we supposed to get a Vortex modlist working from outside Vortex? As in, opening Skyrim (without opening Vortex UI) and loading the preconfigured Vortex modpack. I thought yes, but I can't seem to get it working no matter what I configure in the Skyrim STL config

From my understanding, this is not intended, on Windows or Linux. I believe mods should only be enabled when you launch a game from the Vortex UI just like on Windows. I am fairly certain you cannot load a modded game outside of your mod manager, but this may not be the case with Vortex.

If this is the case on Windows, but doesn't work with STL, I would say this means it doesn't work on Linux and isn't an STL-specific issue.

<hr>

Either way, I think it's a good idea to raise it in #555. I don't use Vortex but to my understanding you aren't expected to be able to load mods if you don't run your game from Vortex mod manager.

**Comment by sonic2kk** [comment]
> I've removed and readded Skyrim Special Edition to the Vortex collection twice, once adding it via drag&drop and another adding it via menu. Both times it appears on the sharedconfig.vdf file as being in the Vortex collection, but steamtinkerlaunch.log still doesn't find any collection when I try to launch the game:

This is really strange, this behaviour suggests to me that STL isn't seeing your categories for your game. Though it is finding the sharedconfig, it's like it doesn't see any categories under that AppID. Could you please attach a full log again? The blank `/.conf` should have the name of each collection for the currently running Steam game's AppID. The blank is where the name of the found category is supposed to be.

It's really strange because I can't reproduce this on my PC or my Steam Deck (I added a random game to a brand new Vortex collection and it was able to see all my collections that the game was in, including the Vortex one which it was able to load the settings for).

You could try renaming your `sharedconfig.vdf` so Steam generates a new one - I say rename because then you can always restore it afterwards. It is unlikely but there could be some strange problem with your file. If that fails, delete your Vortex collection and re-create it.

Sorry this is taking so long for what might seem like a very straightforward issue to fix - I'm trying my best to try and reproduce it but failing - Though in testing I did notice an issue with tags that have spaces, it seems to not detect those properly so I'll try fix that at some point too :-) Something has come out of this issue so far at least heh

**Comment by sonic2kk** [comment]
Hey @Shadark I really don't expect this to make any difference, but I did just push an update to slightly change how STL matches collection names. Just pinging because there's a chance it could help.

Thanks again for the patience on troubleshooting this :+1: Even if we didn't get much of a resolution for your modding problem just yet, hopefully we can figure out what's causing this and maybe save other users that are having the same problem.

<hr>

Another question that actually just occured to me as well, is that your *full* `sharedconfig.vdf`? Is Skyrim the only game in a collection in your library? It's totally fine if it's not and/or if you don't want to share your full one, this is just asking for more information to help troubleshoot and reproduce the problem as best as I can. My `sharedconfig.vdf` is *huge*, like really huge, because I have well over 1k games and tons of them are in collections, so the file is like 116k for me at almost 10k lines long, whereas yours is a lot smaller in comparison.

I'm doing some other tests to try and reproduce the problem on Desktop and Steam Deck, so I'm just trying to get a better sense of how best to try and replicate the problem.

<hr>

Something else you could try is deleting `/dev/shm/steamtinkerlaunch`. It should be a folder, just delete that whole `steamtinkerlaunch` folder. I am not convinced since I haven't experienced it in my tests, but it could be causing issues. The fodler really only contains some temp files, so it's fine to remove :-)

So to summarize all of my previous suggestions:
- Upload a fresh full log please :-) 
- Try deleting your Vortex collection in Steam and creating it again, then running STL and seeing if the `autoCollections` function (you can Ctrl+F for it) still returns `/.conf`
- Try renaming your `sharedconfig.vdf` file and running STL again, and checking that same part of the log to see if it still returns `/.conf`
- Try deleting `/dev/shm/steamtinkerlaunch` and then running STL again, and once again looking in that same function log for `/.conf`

If we still don't have any luck we'll take it from there.

<hr>

I also just tried launching a brand new game that wasn't in any collection, and STL as expected returned `/.conf` for the category search. When I added it to the `Vortex` collection (to simulate a **fresh** game that is **only** in **one** collection), STL was able to pick up the `Vortex.conf` without issues. I didn't even have to restart Steam.

I triple checked the formatting of your attached `sharedconfg.vdf` and the formatting looks to be correct too.

There's no rush for a reply, take your time debugging (or playing if you got it working in the end :smile:) but in the meantime I will keep thinking and testing where I can to try and get to the bottom of this.

**Comment by Shadark** [comment]
> @Shadark sorry, I'm not sure why your comment was marked as off-topic and I personally don't see it as off-topic per-se.

I did that myself because I thought it could derail this precise issue since it was more a side-product of my own issues with STR+Vortex and not a Collections issue 😅

> Another question that actually just occured to me as well, is that your full sharedconfig.vdf? Is Skyrim the only game in a collection in your library? It's totally fine if it's not and/or if you don't want to share your full one, this is just asking for more information to help troubleshoot and reproduce the problem as best as I can. My sharedconfig.vdf is huge, like really huge, because I have well over 1k games and tons of them are in collections, so the file is like 116k for me at almost 10k lines long, whereas yours is a lot smaller in comparison.

My GF and I are "sharing" the Deck, so all the other games are being installed in my profile, and my own sharedconfig.vdf is the one with 99% of the games installed in the Deck. Since I'm testing Skyrim issues on her account, that's the only game that I really installed from her profile. Not sure if relevant, but at least seems to be a possible source of differences between your setup and mine.

> So to summarize all of my previous suggestions:

Did that in order (deleted all logs, created fresh log, renamed .vdf config, launched Skyrim inside newly created Vortex collection), same issue: 
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/9911145/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
> I did that myself because I thought it could derail this precise issue since it was more a side-product of my own issues with STR+Vortex and not a Collections issue 😅

Ah okay phew! I thought maybe there had been some kind of mistake. No worries then and sorry for unhiding it heh

> Not sure if relevant, but at least seems to be a possible source of differences between your setup and mine.

Ahhhhh, as far as I know SteamTinkerLaunch hasn't been tested at all with multiple accounts on one device (I believe there's a comment about this in the code, too). It's possible that this is causing confusion, SteamTinkerLaunch might not be selecting the right User ID and so possibly reading the wrong sharedconfig.

As a test, you could add Skyrim to a "Vortex" collection (or any other collection tbh) and then see if STL is finding any collections in the logs.

This isn't to say you're doing anything wrong, but as far as I've seen in the last almost 1 year, no users have tested SteamTinkerLaunch with shared accounts, so there could be issues with how SteamTinkerLaunch gets the user ID for the userdata folder. That's just a guess though, and users with a usecase like yours are what will help us find (and, with some luck, fix) bugs like this.

<hr>

Haven't checked your log yet but I'll read through it soon (just got off work), thanks for testing again! Much appreciated 👍

**Comment by sonic2kk** [comment]
Just looked through your logs, nothing out of the ordinary there.

Could you go to `/home/deck/.local/share/Steam/userdata/` and see which folders are there? For me there are three folders: `0`, `ac`, and a folder with my user id. However for your case I would expect 4 folders: `0`, `ac`, and two folders with names resembling an AppID (one for your account and another for your GF's account).

If this is the case, SteamTinkerLaunch is checking in `40895998/7/remote/sharedconfig.vdf` for the list of categories.

This is just speculation based on my limited understanding of how multiple Steam accounts on one install behave, sorry if this is wrong or if you already did check the correct folder :sweat_smile: Though it would still be interesting to see if you added Skyrim (or any game used with STL) to a "Vortex" collection on the other profile, would STL see the collections.

<hr>

There's something else I'd like you to try but it might be easier with a keyboard attached. Basically, I would like you, from Dolphin (the default Steam Deck file explorer), to go to `/home/deck/.local/share/Steam/userdata/40895998/7/remote/` (you can right click on the path at the top and select "edit", then paste that path in). Then, you can press F4 (or go to View > Show Panels > Terminal), and paste in the following command:

```
echo "$(sed -n "/\489830\"/,/}/p;" "sharedconfig.vdf" | sed -n "/\"tags\"/,/}/p" | sed -n "/{/,/}/p" | grep -v '{\|}' | cut -d '"' -f4)"
```

This command is what STL uses to parse each category name under the relevant AppID section in the `sharedconfig.vdf` file, but here I hardcoded some specific hardcoded values that STL would otherwise fetch itself. The `489830` is the AppID, `sharedconfig.vdf` is the file to parse. STL would normally just pass the current game's AppID and the path to the sharedconfig, which it is able to grab before the game launch. But for testing here, I just hardcoded the values. Feel free to play around with the AppID and fetch any categories for other games if you want!

Since it's bad form to just give commands and ask users to run them, I'll try to explain from my own (admittedly limited) understanding what this command actually does.

At a high level, `sed` is a nifty command that manages editing parts of a string (**s**tream **ed**itor). The `-n` means the command runs silently without returning the output of each chained `sed` call (since we want to only echo the final part, we use the `-n` flag). The `grep` command fetches specific sections of lines that match the passed pattern (not sure what that specific pattern does, but it works!), and the final `cut` trims specific instances of a character (the `-d`elimiter), and the `-f` specifies how many of those instances to cut, in this case 4 (since we want to remove all the quotes from the `"0"        "Vortex"` line).

This should basically return all matches categories for the AppID. On my Steam Deck, PC and laptop, it returns my Skyrim SE collections each on a new line, like:

```
Bethesda
The Elder Scrolls
```

Since STL's output seems to not be seeing *any* categories for Skyrim, the output here should probably be blank for you. But if it does actually return "Vortex" (or any other categories that the game is in), that would be interesting.

Basically the idea here is to emulate STL's fetching of the categories. There's no pressure to do this, I totally get not wanting to just run commands willy-nilly, but it would be interesting to see!

If you do indeed have two of those User ID folders, it would be very interesting for you to run that command on both. You can run the exact same command on any sharedconfig as long as the folder you're running the command from has the sharedconfig, and you can replace Skyrim's AppID with any AppID in the sharedconfig to see if it fetches the correct collections for other games.

<hr>

A side note: If you and your GF are both using STL to play games, STL doesn't store game configs on a per-user basis. So if you've configured a game with SteamTinkerLaunch, and your GF tries to play that same game with SteamTinkerLaunch, it will load your configuration. Or at least that would be the expected behaviour. This scenario is pretty much entirely untested to my knowledge so there's not any known caveats really.

Thanks! Hopefully we can yield something from this issue yet :crossed_fingers:

**Comment by sonic2kk** [comment]
@Shadark Has there been any more updates with this issue? :slightly_smiling_face:

**Comment by Shadark** [comment]
> @Shadark Has there been any more updates with this issue? 🙂

Sorry, been out of town for a while! I'll try to check this week and post the results. Thanks for checking!

**Comment by sonic2kk** [comment]
No worries, thanks for the ping back :-) Take your time!

**Comment by sonic2kk** [comment]
Hey @Shadark, just a courtesy warning that I'll probably be taking a short break soon. There is still no rush but feel free to submit any logs or other things you come across in testing.

Thanks :-)

**Comment by sonic2kk** [comment]
Closing due to lack of response -- Please feel free to re-open if you have issues with this again :-)
