### ISSUE TITLE
Spurious download: File 'X' already downloaded.

### ISSUE THREAD

**Issue by jinks** [sonic2kk/steamtinkerlaunch#648]
## System Information
- SteamTinkerLaunch version: 11.11
- Distribution: Arch Linux 
- Installation Method: AUR package

## Issue Description

Whenever I launch a game (any game) I get the popup "File 'X' already downloaded." before launching the game.

The file in question *does* exist in the proton DL directory and is redownloaded if I delete it. I just don't know where it's coming from and what is prompting the download.

```sh
(15:33)[jinks@hydra] ..amtinkerlaunch/downloads/proton/custom % ls -l                        
total 746328
-rw-r--r-- 1 jinks jinks 415957578 Sep 12 00:09 GE-Proton7-33.tar.gz
-rw-r--r-- 1 jinks jinks 348274923 Dec  7  2021 Proton-6.17-STL-1.tar.gz
-rw-r--r-- 1 jinks jinks         0 Nov  6 04:13 X
```

## Logs
https://gist.github.com/jinks/bd9a237dce37a093c289215efad772a8

**Comment by sonic2kk** [comment]
Hi there! Thanks for opening an issue.

When creating an issue, you would've been presented with an option to file a bug report or feature request. This sounds like a bug report, can you please fill out the bug report template, giving further information about your setup and attaching the SteamTinkerLaunch log file?

Thanks :-)

**Comment by jinks** [comment]
> When creating an issue, you would've been presented with an option to file a bug report or feature request.

I should have, but I wasn't. Wondered about that myself. :)

I modified the original post, but I can't label it. I hope that's OK.

**Comment by sonic2kk** [comment]
Thanks, much appreciated! Not sure what went on with the issue tracker but I appreciate the update, it was pretty helpful to get that information (especially the log!)

So first I want to give you a little background on your questions:

> The file in question does exist in the proton DL directory and is redownloaded if I delete it. I just don't know where it's coming from and what is prompting the download.

The file is meant to be downloading the latest GE-Proton. Here's a snippet of the log:

```
> Sun  6 Nov 15:08:16 CET 2022 INFO - StatusWindow - for 'Download custom Proton'
> Sun  6 Nov 15:08:16 CET 2022 INFO - dlCustomProton - File '/home/jinks/.config/steamtinkerlaunch/downloads/proton/custom/X' already exists - nothing to download
> Sun  6 Nov 15:08:16 CET 2022 INFO - updateWinRes - Waiting for Window 'SteamTinkerLaunch-DownloadCustomProtonStatus'
> Sun  6 Nov 15:08:16 CET 2022 SKIP - dlCustomProton - Don't know how to extract 
```

I am not sure what is prompting the download either. Did you download a custom Proton version with SteamTinkerLaunch before? Not that that is a problem or anything, I am just wondering if that might've spurred it.

Note the last section in the log: It says it doesn't know how to extract. And from the path in the other line, is it just downloading a file called `X`? If so, I think this is an issue relating to a recent change on GitHub's side, where they changed the layout of the releases page and various parts of SteamTinkerLaunch that download files from GitHub broke. This was fixed in most places with commit 28e61c0aa79e231b3605582290a11a3ec7dd73cd, but that hasn't made its way into a full release yet.

My current theory is that maybe SteamTinkerLaunch tried to download a GE-Proton release and failed to do so with v11.11 because of those changes I mentioned on GtiHub's side. And then it keeps trying to download and extract each time you launch a game, but it is failing to properly download the version of GE-Proton that it wants to.

<hr>

Can you check if this problem still occurs in git? You can either install STL manually or, since you're on Arch, you should be able to use the `steamtinkerlaunch-git` package.

If the problem **does** still occur for you in master, could you give any more background on what you were doing before this started happening? That way I can try and reproduce the issue (And if it does still occur in master, feel free to switch back to stable if you want :slightly_smiling_face:)

I have a strong feeling though that this is related to the GitHub problems we had before with MO2 and Vortex, and it could be something that was fixed in master.

Thanks!

**Comment by jinks** [comment]
> I am not sure what is prompting the download either. Did you download a custom Proton version with SteamTinkerLaunch before? 

I have set the default in STL to always launch with the latest proton-GE, so that's probably the cause for the download attempt.

> My current theory is that maybe SteamTinkerLaunch tried to download a GE-Proton release and failed to do so with v11.11 because of those changes I mentioned on GtiHub's side.

It would appear you are correct. STL master pulled in proton-GE_7.41 upon first launch and hasn't complained about any download problems over several launches.

I'd guess one of [these lines](https://github.com/sonic2kk/steamtinkerlaunch/commit/28e61c0aa79e231b3605582290a11a3ec7dd73cd#diff-77c6d4bb1bf7c1988ff5a068c856b6c24e113663f2e61cb3a2c98723c0fafc04L12929-L13141) introduced the uppercase 'X' due to an empty variable then.

I'll stick to -git for a while before switching back. :)

**Comment by sonic2kk** [comment]
Ah, glad to know that worked! Sorry you ran into this problem but very glad to know that master fixed it :smile: 

I'm *loosely* hoping to have a new release of STL rolled out sometime in December, but there are a couple of things I'm holding out for making it into the next release (mo2-overhaul which needs further testing, and HedgeModManager support which I am currently working on).

Once v12 is out I'm sure you'll see the version bump and if you'd like you can switch back, or keep using STL-git - living on the edge can be fun :wink:

Thanks!

**Comment by har-nick** [comment]
Sorry for the necro, but I had the same issue across bin and git branches. Checking the logs showed I was missing the `jq` package. Installed it, relaunched STL and it grabbed a new Proton version. No issues since.

**Comment by sonic2kk** [comment]
Huh, that's interesting. I didn't think the Proton downloading needed `jq`. I might look into that and try fixing it, because that doesn't sound right to me initially. `jq` is a pretty good dependency to have though, it adds some neat functionality like ProtonDB rating fetching and Steam Deck compatibility fetching.

Thanks for reporting this though! Maybe it needs `jq` to ping the API if it uses that but there are other ways to fetch it I think, I may look into changing the logic there. Or if I can't / it's too much effort, I'll just more explicitly note that this functionality needs `jq`.

**Comment by sonic2kk** [comment]
Just checked and yes, SteamTinkerLaunch does require `jq` to be installed for online Proton versions to be fetched.

With b731f7e4990dcfd6d96aabb4e4ea6ebe8f43a582 I've added a logging guard for this. I think I'll look into replacing the JQ calls, not sure if this will make it in before v12 but I would like to remove the dependence on JQ here (although I freaking love JQ, I prefer having it only impact minor cosmetic things like no ProtonDB/Steam Deck compatibility info)
