### ISSUE TITLE
how to handle / instead of \ in vortex and hidden folders [.foldername]

### ISSUE THREAD

**Issue by fmoerl-real** [sonic2kk/steamtinkerlaunch#652]
## System Information
- SteamTinkerLaunch version: 
- Distribution: 

## Issue Description
SteamTinkerLaunch does not find hidden folders, this is, for example my steam installation is in \\$HOME\\.steam
So, any browsing of folders or files within such folders is impossible 
Further, Vortex enables only for the Windows folder discrimination, that is [\\] but on linux is [/]

**Comment by sonic2kk** [comment]
Hi there!

When browsing folders you should be able to just go to `\home\user\myfolder\anotherfolder`. Wine should be able to handle that. If not, put a `Z:` in front since Wine maps your global filesystem to the Z drive.

As for hidden folders, I'm not sure. If it doesn't see them with the path normally maybe that's a Wine problem, I don't recall having trouble with this before.

Anyway, I'm sorry to say that this is not a SteamTinkerLaunch issue but an issue with using a program with Wine generally, so I'm going to close this. You might have better luck elsewhere online asking generally on how enter paths on Wine :-) 

Good luck!

**Comment by fmoerl-real** [comment]
Hi Sonic2kk,

browsing is possible, but also a copy of a path was not accepted by vortex. And yes, steamtinkerlaunch enables browsing also with [/]. I think, a checkbox or a button to enable hidden folder visibility would be nice. 

For vortex, is there any configuration file to handle the base folders?

Greats

F

**Comment by sonic2kk** [comment]
> I think, a checkbox or a button to enable hidden folder visibility would be nice.

I am not sure how SteamTinkerLaunch would implement this, if it is something specific to Wine. Can you right click in the file browser and show hidden files or anything?

SteamTinkerLaunch only gives support for running Vortex with Wine and some other auto configuration. Any Wine-specific quirks are really up to users to figure out on their own, but if you could give more details on how we could potentially add this I'd be open to hearing it :smile:
