### ISSUE TITLE
HedgeModManager won't launch after installing with STL

### ISSUE THREAD

**Issue by EVDESTROYER** [sonic2kk/steamtinkerlaunch#658]
## System Information
- SteamTinkerLaunch version: v11.12.20221114-10
- Distribution: SteamOS
- Installation Method: Manual

## Issue Description
HedgeModManager won't launch after installing with STL, you said it seems it can't download/find the Winetricks executable.

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10006615/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Thanks for opening a new issue! I appreciate it.

Just copying over my comment from the other issue for completeness, I'll have a follow up comment after it:

<hr>

 In your instance, STL has not found your Winetricks installation:

```
Mon Nov 14 11:56:30 AM CST 2022 SKIP - chooseWinetricks - DLWINETRICKS is set to '0', but '/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks' was not found!
Mon Nov 14 11:56:30 AM CST 2022 INFO - installDotNet - WINEDEBUG="-all" WINEPREFIX="/home/deck/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx" WINE="/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-41/files/bin/wine" "" --unattended "dotnet48"
```

It seems as though it is failing to download Winetricks for some reason. I haven't seen this happen before, so I'm not sure what's causing it yet.

It seems like it does find WInetricks later on though:

```
Mon Nov 14 12:05:07 PM CST 2022 INFO - prepareHMMGames - Install dotnet48 for install 64bit HedgeModManager game 'Sonic Origins'
Mon Nov 14 12:05:07 PM CST 2022 SKIP - chooseWinetricks - 'WINETRICKS variable' already exists and points to '/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks'
```

It finds it with the last HMM game it sets up, but can't find it for HMM itself, Forces or Frontiers.

Interestingly, DotNet48 looks like it installed successfully for Sonic Origins.

```
Mon Nov 14 12:05:07 PM CST 2022 INFO - prepareHMMGames - Found compatdata dir for 'Sonic Origins' at '/home/deck/.local/share/Steam/steamapps/compatdata/1794960/pfx/drive_c/users/steamuser' - Assuming it is installed
Mon Nov 14 12:05:07 PM CST 2022 INFO - prepareHMMGames - Install dotnet48 for install 64bit HedgeModManager game 'Sonic Origins'
Mon Nov 14 12:05:07 PM CST 2022 SKIP - chooseWinetricks - 'WINETRICKS variable' already exists and points to '/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks'
Mon Nov 14 12:05:07 PM CST 2022 INFO - installDotNet - Starting dotnet48 install - check /dev/shm/steamtinkerlaunch/installDotNet.log
Mon Nov 14 12:05:07 PM CST 2022 INFO - installDotNet - WINEDEBUG="-all" WINEPREFIX="/home/deck/.local/share/Steam/steamapps/compatdata/1794960/pfx" WINE="/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-41/files/bin/wine" "/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks" --unattended "dotnet48"
Mon Nov 14 12:05:18 PM CST 2022 INFO - installDotNet - Stopped dotnet48 install - check /dev/shm/steamtinkerlaunch/installDotNet.log
Mon Nov 14 12:05:18 PM CST 2022 INFO - prepareHMMGames - Finished installing dotnet48 for 'Sonic Origins'
```

The time between the log files indicates that dotnet48 successfully installed for Sonic Origins. So this issue is likely only related to STL being unable to find the Winetricks executable.

**Comment by sonic2kk** [comment]
Can you go to `/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src` and see if there is a `winetricks` file? Or if that path even exists?

If it does, delete the compatdata folder at `/home/deck/.config/steamtinkerlaunch/hedgemodmanager` and then re-run `steamtinkerlaunch hmm start "nightly"` (or leave out `nightly` if you want stable, but I think you wanted nightly? :smiley:)

<hr>

If you're interested, and also partly to remind myself while troubleshooting this, the problem is this:
- SteamTinkerLaunch uses a program called Winetricks to install some needed components to get HMM to run on Linux
- On Steam Deck, STL is supposed to automatically fetch the latest Winetricks (in your log there is a `gitUpdate` log message too) and it's meant to put it at `/home/deck/.config/steamtinkerlaunch/downloads/winetricks` - Since it can't be installed system-wide on Steam Deck
- For some reason, it is not installing correctly it seems like. SteamTinkerLaunch is unable to find Winetricks at the path, so when it tries to install the Winetricks components it needs, it doesn't have a program to do it with: `WINEPREFIX="/home/deck/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx" WINE="/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-41/files/bin/wine" "" --unattended "dotnet48"` - Note the `"" --unattended "dotnet48"` - The path to Winetricks is meant to go in those quotes !

However, when it gets to the end and tries to install Sonic Origins' winetricks, it is able to find the executable. Which is why I am curious if it exists for you.

**Comment by sonic2kk** [comment]
Just pushed a commit that attempts to download and set Winetricks earlier. You can try the following steps now:
1. Run `./steamtinkerlaunch` from its installation folder (`/home/deck/stl/prefix`)
2. Delete the HMM compatdata folder again at `/home/deck/.config/steamtinkerlaunch/hedgemodmanager`
3. Re-run your STL HMM install command

SteamTinkerLaunch now attemps to download and set Winetricks before any calls to install HMM itself and any HMM supported games.

**Comment by EVDESTROYER** [comment]
There was a winetricks file inside of `/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src`

I have tried deleting the compatdata folder at `/home/deck/.config/steamtinkerlaunch/hedgemodmanager` and re-ran `./steamtinkerlaunch hmm start` (I'm trying to install the stable build; I'm not looking for Frontiers mod support yet). It did not change anything.

I think it's worth mentioning that I'm having to do the ./ version of the command inside the prefix folder because the normal one isn't working for me, Idk if that's normal or not.

**Comment by sonic2kk** [comment]
Thanks!

> I think it's worth mentioning that I'm having to do the ./ version of the command inside the prefix folder because the normal one isn't working for me, Idk if that's normal or not.

This is fine, `./` just means you're running an executable file in the current directory. On Steam Deck this is expected, though once the ProtonUp-Qt v2.7.5 Flatpak rolls out you can use that to install STL (v2.7.4 Flatpak is a unreliable) and it'll be on your PATH, meaning you can run SteamTinkerLaunch from anywhere on the command line :-) 

> There was a winetricks file inside of `/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src`

Interesting, I wasn't sure if there would be or not. It's very strange that STL can't find it then... I wonder if the latest commit will fix it.

> It did not change anything

Once you're on the latest commit version (`20221115-1`) can you try again and then attach another log? :-)

**Comment by EVDESTROYER** [comment]
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10007133/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Thanks, STL is now correctly finding your Winetricks install but it is still unable to install `dotnet48` for some reason.

```
Mon Nov 14 03:06:48 PM CST 2022 INFO - installHMM - HedgeModManager executable found at '/home/deck/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe' - Checking if we need to set up its Wine prefix
Mon Nov 14 03:06:48 PM CST 2022 INFO - installHMM - No existing HedgeModManager prefix found - Creating one
Mon Nov 14 03:06:49 PM CST 2022 INFO - installHMM - Installing dotnet48 for HedgeModManager
Mon Nov 14 03:06:49 PM CST 2022 SKIP - chooseWinetricks - 'WINETRICKS variable' already exists and points to '/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks'
Mon Nov 14 03:06:49 PM CST 2022 INFO - installDotNet - Starting dotnet48 install - check /dev/shm/steamtinkerlaunch/installDotNet.log
Mon Nov 14 03:06:49 PM CST 2022 INFO - installDotNet - WINEDEBUG="-all" WINEPREFIX="/home/deck/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx" WINE="/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-41/files/bin/wine" "/home/deck/.config/steamtinkerlaunch/downloads/winetricks/src/winetricks" --unattended "dotnet48"
Mon Nov 14 03:07:46 PM CST 2022 INFO - installDotNet - Stopped dotnet48 install - check /dev/shm/steamtinkerlaunch/installDotNet.log
```

The time between installs here is not right - It should take more than ~1 minute to install `dotnet48`.

I have pushed a commit that will now generate a unique file in `/dev/shm/steamtinkerlaunch`. It should be named something like `installDotNet.logHMMPREFIX`. Please `./steamtinkerlaunch` first to update, then delete your compatdata, and finally run `./steamtinkerlaunch hmm start` again - Then once installation "finished" (or rather, *fails*) attach that log ending in `HMMPREFIX`. This log will let me see what is going wrong with the dotnet installation :-)

**Comment by sonic2kk** [comment]
Small note: Once you're on the latest commit, there is an experimental `./steamtinkerlaunch hmm uninstall` option to remove HMM files including the compatdata. It might be more straightforward to do that than to delete it each time :-) But it has not been heavily tested (my time today was taken up adding GameBanana 1-click install support)

**Comment by sonic2kk** [comment]
@EVDESTROYER ping :-) If you can send over that file I can try and troubleshoot the issue

**Comment by sonic2kk** [comment]
Linux Gaming Central recently wrote a blog post that even suggested using Pacstall to install SteamTinkerLaunch, and HMM seemed to work for them. I wonder if this is just a case of bad luck -- Maybe you could try uninstalling and reinstalling SteamTinkerLaunch? Or maybe Pacstall needs to be installed differently? I am not sure to be honest :sweat_smile:

**Comment by sonic2kk** [comment]
@EVDESTROYER The next time you test, could you attach 3 files please:
- `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`
- Any files with a name like `installDotNet.log` - Even if one doesn't end with `HMM` it would still be useful to see
- `~/.config/steamtinkerlaunch/globa.conf`

**Comment by sonic2kk** [comment]
#662 seems to be solved, @EVDESTROYER can you retest ?

v11.12.20221118-2 has the latest fixes in place which should hopefully resolve the issue on SteamOS of a Proton version not being found. Though it seems separate from your issue, I'll need some logs to debug further

**Comment by sonic2kk** [comment]
SteamTinkerLaunch v11.12.20221118-3 features more improvements still, one user reported success with STL's installation of HMM.

**Comment by sonic2kk** [comment]
Closing due to lack of response from OP for additional logs and testing. Please re-open or file a new issue if you still have trouble :-)
