### ISSUE TITLE
download custom wine not working

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#659]
## System Information
- SteamTinkerLaunch version: v11.12.20221114-10
- Distribution: Garuda Linux
- Installation Method: AUR

## Issue Description
download custom wine is no longer showing wine versions to download from

(while we are at it I think it would also be nice to add lutris and GE wine builds)

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10006872/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
> download custom wine is no longer showing wine versions to download from

This is because of a change with the GitHub URL fetching - It's fixed in the mo2-overhaul branch (https://github.com/sonic2kk/steamtinkerlaunch/commit/96e7c601a0b19e9c3156e4a9dbd9834199243603) so it'll be implemented when that branch is merged (or if it introduces bugs, I'll try take that commit and apply it to master before v12 comes out).

> (while we are at it I think it would also be nice to add lutris and GE wine builds)

I agree! I wanted this in v12 but I am too lazy to add it right now :sweat: Swamped with HMM, getting `mo2-overhaul` merged and a small fix for some experimental one-time run features.

<hr>

I am not *too* sure on Lutris builds (I wouldn't be against it but not sure how much extra effort it might be) but Wine-GE builds I think would be a great addition. Could you open a feature request for downloading more Wine variants? I would like to close this issue since it *should* be fixed once the mo2-overhaul branch is merged (I am holding back on merging because of merge conflicts and also I want to make sure my existing mod setups don't get borked).

Thanks :-)

**Comment by zany130** [comment]
yeah, sorry should have opened a feature request for that my bad :sweat_smile: btw I am still planning to update the reshade wiki just taking a little break and enjoying some games :smile:

**Comment by sonic2kk** [comment]
> btw I am still planning to update the reshade wiki just taking a little break and enjoying some games

There's no rush at all with that :-) Take all the time you need. Enjoying games is something I've been really slacking on recently - But sometime before v12 comes out I'll take a week or two off to relax once the HMM issues settle
