### ISSUE TITLE
Lutris and GE wine builds

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#660]
## System Information
- SteamTinkerLaunch version: v11.12.20221114-10
- Distribution: Garuda Linux

## Feature Description
[lutris](https://github.com/lutris/wine) and [GE](https://github.com/GloriousEggroll/wine-ge-custom) wine builds could be useful

**Comment by sonic2kk** [comment]
Thanks :-) I said it on the other issue too but for completeness, I am fully in favour of adding these features. Sadly I just don't have time to work on it right now, but in future I am hoping to! It may not make it into v12 though

**Comment by sonic2kk** [comment]
Something to note here is that some parts of SteamTinkerLaunch including Steam expect a specific directory structure including a Proton script, which afaik the GE-Wine and Lutris Wine builds do not have (since they are Wine builds). I also suspect they have slightly different directory structures, including GE-Wine which may have a different structure to GE-Proton.

I think the "solution" here is to do two things:
1. Document that using Wine builds with Steam is unsupported
2. Update the code to check for a Wine build and try to run with that. Some tools e.g. MO2, Vortex, HMM will expect the Proton script and they are set up to use it, so these tools should probably log a warning when a user tries to select a Wine version to run it with
3. Log a warning if a user tries to run a Steam game with a Wine build
4. Investigate writing these out to a separate CSV i.e. `WIneCSV.txt`, or maybe we can just include them in the regular CSV. The issue here is that some tools e.g. MO2 or HMM, and the Proton mismatch checker, may need updated if we write them all out to the same CSV. There is code which looks for `GE` in the `ProtonCSV.txt` file in order to resolve version mismatches. This may need to be changed, maybe setting it to `GE-Proton` is enough (though I wonder how this would impact older GE-Proton versions...)

The merit in having support for the Wine builds is mainly for custom commands, or at least that's how i see it. I think it would be handy to be able to run a custom command with a GE-Wine build for example. And also, in general, the ability to download these tools would be handy too.

A potential implementation would be to allow downloading these versions, writing them out to a separate CSV file and then showing them in a separate dropdown under "Wine Options". This would override the system Wine and of course the regular Proton version. I also like this approach because it means Wine options won't be listed under "Proton version".

This will unfortunately almost certainly miss v12, but it is something I would like to see added at some point!

**Comment by sonic2kk** [comment]
I think having a separate CSV for these tools is the best solution, and having it as a separate menu option gated behind a checkbox perhaps. I'm not sure where it would go, somewhere separate from the Proton options.

Maybe if possible this should only be shown if the user has downloaded any custom Wine builds, like how we only show MO2 options for users who have MO2 installed.

May look into this soon-ish

**Comment by sonic2kk** [comment]
Actually, it should be possible to just integrate this with the existing Wine download options...

~~Wine is currently downloaded to `~/.config/steamtinkerlaunch`, when really it should probably be in `downloads`. I will probably do some refactoring that has some code which moves the `~/.config/steamtinkerlaunch/wine` folder into the STL downloads folder.~~ Wine is *extracted* to `~/.config/steamtinkerlaunch/wine`, but the downloaded archives go to `~/.config/steamtinkerlaunch/downloads/wine`.

**Comment by sonic2kk** [comment]
Ok, I implemented it for Wine-GE and Lutris Wine. PR will be up shortly. Game compatibility may vary, and  the SLR is in use by default - not sure if this is a good idea, but it can be disabled by unchecking the SLR option.

A better UI is probably overdue for this Wine downloading. ProtonUp-Qt should let you download the Wine versions and you could move/set a custom install directory, so I am not too worried for now :-)

**Comment by sonic2kk** [comment]
@zany130 PR is up at #783 to implement this at long last :-) Took way too long, I am very sorry about that! But it's ready now.

**Comment by sonic2kk** [comment]
I actually decided to just merge this as it shouldn't break any existing code for Wine, and appears to work.

Wine versions download and extract correctly, though compatibility compared to regular Proton may vary. It's probably best to only use this with Non-Steam Games/custom commands.

Let me know if you run into any issues, and feel free to close if this is resolved now :-)

**Comment by zany130** [comment]
sorry it took me a while but finally got around to testing and works for me 👍

**Comment by sonic2kk** [comment]
No worries, it took me much longer to investigate implementing it (turns out 95% of the groundwork was already there :sweat_smile:)
