### ISSUE TITLE
ReShade installs into custom command

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#669]
## System Information
- SteamTinkerLaunch version: v11.12.20221118-4
- Distribution: Garuda Linux
- Installation Method: AUR

## Issue Description
ReShade installs into custom command if both are enabled.

## Logs
[1198090.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10050883/1198090.log)

Specifically, these lines which show it is using the custom command (Cheat Engine) instead of the game exe.

```
installd3d47dll - Destfile '/home/zany130/Applications/cheatengine/Cheat Engine 7.4/d3dcompiler_47.dll' already exists - skipping this file
installRSdll - Destfile '/home/zany130/Applications/cheatengine/Cheat Engine 7.4/dxgi.dll' already exists, but has a different version - updating
installRSdll - Destfile '/home/zany130/Applications/cheatengine/Cheat Engine 7.4/d3d9.dll' already exists, but has a different version - updating
prepareLaunch - installDepth3DReshade:
prepareLaunch - checkReshade:
setFullGameExePath - Using the directory '/home/zany130/Applications/cheatengine/Cheat Engine 7.4' of the used custom command as absolute game exe path
checkReshade - Found a '/home/zany130/Applications/cheatengine/Cheat Engine 7.4/ReShade.ini' without default paths pointing to 'reshade-shaders' - not touching it
```

**Comment by sonic2kk** [comment]
Good find! I didn't even consider this before. Interestingly, most things have the *opposite* problem, see #639.

When installing ReShade, the `installReshade` function makes a call out to `setShadDestDir` which sets the destination installation directory using `setFullGameExePath`. However, as shown in your log, this function actually has a check *specifically* to use ReShade with the Custom Command.

I'm not sure how we would want to go about solving it. In this case, it makes no sense to use ReShade with Cheat Engine. But equally, installing to both the custom command and the game makes little sense. And installing to *only* the game instead of the custom command may be undesirable.

This is my 11pm initial-draft idea of what we could do. The default behaviour should be to install ReShade to the game, and we should have a checkbox (probably per-game in the Game Menu with the other ReShade settings) named *something* like "Enable ReShade with Custom Command".

As well as this, if ReShade is enabled *and* ***only*** a custom command is selected, we should install ReShade to the custom command directory regardless of this setting.

To me, this makes the most sense for a solution. But if you have any other suggestions or things I missed please suggest :-)

*(P.S. I know you worked on the previous ReShade improvements, so if this is something that you would like to work on and have a good grasp on what most users would consider "good" behaviour, by all means feel free! Otherwise, I will try to take a look at this sometime in the next few days)*

**Comment by zany130** [comment]
Yup took a look at the code and that's exactly what is happening. I never even considered installing reshade into a custom command might be something a user would want, but a use case is what if they use a custom executable for the game or something....

Yeah, I think the best solution would be to  add a checkbox for installing reshade into the custom command and by default, install into the game exe path

not sure if ill have too much time to implement this ( or some other reshade improvements I been thinking about), this coming week (a lot of stuff thanksgiving and bday) but if you haven't found the time by the following week I wouldn't mind giving it a stab

**Comment by sonic2kk** [comment]
> Yeah, I think the best solution would be to add a checkbox for installing reshade into the custom command and by default, install into the game exe path

Agreed. Though I'm not sure how to best implement it. There is a scenario where a user may want ReShade for both their custom command and their game (though probably unlikely). I think for now, we could just add a check to `setFullGameExePath` something like:

```bash
if [ "$USECUSTOMCMD" -eq 1 ] && [ -f "$CUSTOMCMD" ] && [ "$USECUSTOMCMDRESHADE" -eq 1 ]; then
```

Where `USECUSTOMCMDRESHADE` would correspond to the value of the checkbox under the per-game ReShade settings :-)

There is syntax for compound checks, because _really_  this check should be `if (custom command enabled AND if we have a custom command AND if the custom command wants reshade) OR if only custom command is selected`. But I forget the Bash syntax for that at the moment :-)

<hr>

I think further flexibility on this should wait until #625, where we can have a separate checkbox to enable ReShade support for these custom commands, allowing ReShade to be enabled for both the custom command as well. Of course we'd probably need to revisit *this* implementation, but since the custom command control stuff will probably not happen for a few more months, we can focus on solving the primary use-case for now -- Which is having a user manually set when they want ReShade for a custom command, and having the default be that it goes to the game.

I don't see having ReShade for *both* being absolutely necessary, whereas the issue you described would certainly be annoying.

<hr>

If I don't get a chance to look at this by Wednesday, I'll let you know. I'm tentatively planning to take a couple week break starting around Wednesday (+/- depending on a ProtonUp-Qt PR I have up). Have a nice birthday too :birthday: No worries if you don't get a chance to look at it regardless :-) Thanks for the report!

**Comment by sonic2kk** [comment]
Attempted to implement this with https://github.com/sonic2kk/steamtinkerlaunch/commit/037af09080ea9076e00eabcd8bbec103c077a894  but I am not too familiar with the ins and outs of using and testing ReShade. Feel free to test whenever you're free :-)

**Comment by zany130** [comment]
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10059884/steamtinkerlaunch.log)
hmm now its not finding the  install dir

```
Mon Nov 21 02:16:42 PM EST 2022 INFO - installReshade - No conflict found in old logfiles
Mon Nov 21 02:16:42 PM EST 2022 SKIP - installReshade - INSTDESTDIR '' not found
Mon Nov 21 02:16:42 PM EST 2022 INFO - prepareLaunch - installDepth3DReshade:
Mon Nov 21 02:16:42 PM EST 2022 INFO - prepareLaunch - checkReshade:
Mon Nov 21 02:16:42 PM EST 2022 INFO - checkReshade - Creating initial '/ReShade.ini' with default paths pointing to 'reshade-shaders'
Mon Nov 21 02:16:42 PM EST 2022 INFO - checkReshade - USERESHADE is '1' - looks like ReShade is not yet installed in '' - installing because USERESHADE is enabled
```
i'll try again with a fresh config folder ( this was already with a fresh `/dev/shm/steamtinkerlaunch
`

EDIT: also i'll try the same game as before (cold steel IV) to rule that out though I think i tested reshade on nier before...

EDIT2: same issue with clean steamtinkerlaunch folders and cold steel IV

**Comment by sonic2kk** [comment]
Ah shit I guess I broke something, oops... I'll take a look now and try figure out what I broke. If I can't figure it out, I'll try and temporarily revert it...

**Comment by sonic2kk** [comment]
May have a fix, need to test to ensure it doesn't break custom commands as it is a bit long winded :-) 

I think I put the check in the wrong place. I'm testing now to make sure general custom commands work.

**Comment by sonic2kk** [comment]
Pushed a commit that attempts to fix this. Retest if you get a chance :-) If this doesn't fix it, I'll revert the change because I am not really well versed enough to attempt a fix for this right now :sweat_smile:

**Comment by zany130** [comment]
well it goes back to the old behavior of installing reshade into the custom command
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10061012/steamtinkerlaunch.log)

```
installReshade - Installing 64bit ReShade as '/home/zany130/.local/share/Steam/steamapps/common/NieRAutomata/NieRAutomata.exe' is 64bit
installd3d47dll - Destfile '/home/zany130/Applications/cheatengine/Cheat Engine 7.4/d3dcompiler_47.dll' already exists - skipping this file
installRSdll - Destfile '/home/zany130/Applications/cheatengine/Cheat Engine 7.4/dxgi.dll' already exists in the same version '5.4.2' - skipping this file
installRSdll - Destfile '/home/zany130/Applications/cheatengine/Cheat Engine 7.4/d3d9.dll' already exists in the same version '5.4.2' - skipping this file
```
ill try to take a  look at this in the near future but 
not sure why this is not working...

**Comment by sonic2kk** [comment]
Sorry that I ended up not being able to fix it. I can imagine it's not a nice thing to run into.

I'm taking a bit of a break starting today, please by all means feel free to investigate in the meantime and get a PR up if you fix it. Or if nothing else you can always use this issue to document the things that you run into :-)

Apologies that I didn't get to take more of a look into this, but thanks for reporting nonetheless :)

**Comment by sonic2kk** [comment]
Wow, it's been a while! But I wanted to work on something other than Hedge Mod Manager issues for a while and decided to revisit this :-)

I took a look at the code again and made another attempt to try and fix this on a separate branch [`reshade-customcmd-fix`](https://github.com/sonic2kk/steamtinkerlaunch/tree/reshade-custcmd-fix). If you have time, feel free to try it out and see if it fixes the problem.

I think the problem back when I did this originally was the ReShade install folder was not being set *at all* if the user did not enable ReShade for the custom command, which was a mistake on my part. I had the check in `setShadDestDir` and `setFulLGameExePath` was not called unless the user wanted to use ReShade for the custom command, which was a very silly error on my part.

I moved this logic into `setFullGameExeDir` which has an if/else block. The conditional is the same as it was in the initial commit but it was moved to what should hopefully be the correct spot.

Checkout the branch mentioned and see if that resolves the problem. If not please attach a log anyway as you have been doing. I realise its the holidays so there is no rush at all to test this out (to be honest I shouldn't even be spending so much time on STL this close to the holidays, but what can you do :sweat_smile:)

Fingers crossed for a positive result here!

**Comment by zany130** [comment]
Yup works as expected in the new branch. Nice!! :partying_face: 

EDIT: forgot to test if enabling the new use with reshade works just tested if my scenario works lol be back shortly

EDIT2: yup enabling the new option brings back the old behavior of installing reshade on the custom command 

So this is complete

**Comment by sonic2kk** [comment]
Great news to wake up to :-) I'll get it merged in soon then!

**Comment by sonic2kk** [comment]
Merged into master, should be fixed now! Thanks for testing!

(Also, I got sick again, and now I fully blame ReShade for it :laughing:)
