### ISSUE TITLE
HedgeModManager won't launch after installing with STL (cont.)

### ISSUE THREAD

**Issue by EVDESTROYER** [sonic2kk/steamtinkerlaunch#673]
## System Information
- SteamTinkerLaunch version: v11.12.20221121-5
- Distribution: SteamOS
- Installation Method: Manual

## Issue Description
HedgeModManager won't launch after installing with STL (Sorry I didn't get back to this sooner, have been very busy as of late)

## Logs
[global.conf.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/10086075/global.conf.txt)
[installDotNet.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10086076/installDotNet.log)
[installDotNet.logHMMPREFIX.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/10086077/installDotNet.logHMMPREFIX.txt)
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10086078/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Looks like dotnet48 did not install correctly into the HMM prefix. The HMMPREFIX log has some hints that suggest installation failed. I'm not sure why it would fail, but just ensure that your Steam Deck does not go to sleep during installation. From a cursory search on the Winetricks repo, it seems this can happen in some cases:
- `~/.cache/winetricks` is invalid / corrupted, you could try removing this folder (**only** the `winetricks` folder, **not** your entire `.cache` folder) and then re-trying
- `~/.cache/winetricks` is not writeable -- This is unlikely on most systems + Steam Deck
- The boot drive is very full - If your Steam Deck's SSD has a low amount of storage space available, it may cause Winetricks to fail for some reason (I am not sure of an exact amount but I would class low storage in this instance to be < 20gb)

Try running `./steamtinkerlaunch hmm uninstall` and then re-running `steamtinkerlaunch hmm start nightly` (or leave out `nightly` if you need the latest stable). You can check that uninstallation worked by checking `~/.config/steamtinkerlaunch/hedgemodmanager` and making sure that folder is empty (or that the `hedgemodmanager` folder doesn't exist at all).

Interestingly, it looks like dotnet48 installation succeeded for the game it was installing for (the `installDotNet.log`). Maybe it was just a one-off that installation failed.

Good luck!

<hr>

Courtesy note as well: If you are planning on playing 64bit games, once HMM is up and running you may need to manually add a DLL for 64bit games to work: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Hedge-Mod-Manager#dependencies

**Comment by EVDESTROYER** [comment]
Uninstalled HMM and deleted the winetricks folder like you asked

[installHMM_protonrun.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10086765/installHMM_protonrun.log)
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10086766/steamtinkerlaunch.log)
[installDotNet.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10086767/installDotNet.log)
[installDotNet.logHMMPREFIX.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10086768/installDotNet.logHMMPREFIX.log)

**Comment by sonic2kk** [comment]
Still failing to install Winetricks with the same error. Unfortunately I don't know why this is happening, and this may be an issue in Winetricks at the moment. Though it appears like it has succeeded for other games (i.e. Sonic Origins I believe from the log).

The line that makes me suspect Winetricks is failing to correctly install dotnet:

```
warning: dotnet40 install completed, but installed file /home/deck/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx/dosdevices/c:/windows/Microsoft.NET/Framework/v4.0.30319/ngen.exe not found
```

I am on break at the moment so I won't be able to spend too much time looking into this yet, but interesting. I guess looking around for similar issues and how they were resolved will be the starting point here :-)

**Comment by sonic2kk** [comment]
Can you check the permissions on the Winetricks cache folder? This seems like a very strange error and I can't find much about it on the Winetricks repo.

If you go to `~/.cache` and right click on the winetricks folder -> Properties, and then go to the "Permissions" tab, you can see the permissions like so:

![image](https://user-images.githubusercontent.com/7917345/203850123-f6a7f601-dbf6-4174-89af-ecf38f9b6402.png)

On the Steam Deck I would guess the user and group would both be something like `Deck`, and access permissions would be identical.

**Comment by sonic2kk** [comment]
Just tested and on my PC it still works fine and doesn't give those errors.

I guess another possible fix here is to try deleting Winetricks -- SteamTinkerLaunch installs Winetricks locally to `/home/deck/.config/steamtinkerlaunch/downloads/winetricks`. You could try deleting this `winetricks` folder, uninstalling HMM and reinstalling. Perhaps there was an issue with the version of Winetricks that was downloaded but I am not totally sure.

Have not yet tried to reproduce this on my Steam Deck, but it worked fine as of a few days ago.

**Comment by sonic2kk** [comment]
Just pushed a commit that adds a `--force` flag to the dotnet48 Winetricks installation. I don't expect this to make much difference, but in my test just how it didn't break anything and it's only being passed experimentally for now.

If you bump to SteamTinkerLaunch 20221124-1 (`./steamtinkerlaunch` will auto update) and then re-run the installation, that *might* fix it. But I have my doubts here, `--force` very, very rarely fixes anything with Winetricks and dotnet in my experience.

**Comment by EVDESTROYER** [comment]
I checked the permissions on the `winetricks` folder and they were as you said they'd be. I also re-ran the HMM install after updating STL with the `./steamtinkerlaunch` command, it still does not work unfortunately.

**Comment by sonic2kk** [comment]
I don't really know why Winetricks is failing, this _could_ just be an issue with Winetricks that's out of our hands (unlikely and I hope not).

I don't know if this will work as I can't reproduce the issue, but what happens if you get the DLL mentioned in the following link and put it in the folder with the HMM exe (`~/.config/steamtinkerlaunch/downloads/hedgemodmanager`): https://github.com/sonic2kk/steamtinkerlaunch/wiki/Hedge-Mod-Manager#dependencies

I don't think this will fix it, for full disclosure, but since the cause of the issue is still unknown I'm not sure what else could fix it at this moment. I will hopefully figure it out soon though :-)

**Comment by EVDESTROYER** [comment]
After doing `./steamtinkerlaunch hmm start` with `mscorees.dll` it gave me an error message (albeit not a very helpful one):

"HedgeModManager.exe - Error

A fatal error has occured. However, mscorees.dll could not be loaded to properly display the appropriate error message.

Please reinstall the .NET framework"

**Comment by sonic2kk** [comment]
Also, did you try removing Winetricks? It should be in somewhere like `~/.config/steamtinkerlaunch/downloads/winetricks`. If you remove the `winetricks` folder that should force a redownload. I also don't see this being very likely to fix it, but I'm sort of at a loss here at the moment unfortunately.

If I can actually reproduce this, I would report it upstream. Perhaps it's the `--unattended` flag causing issues as I've seen that mentioned in a couple of Winetricks issues previously, but I'm not sure why I can't reproduce the problem...

**Comment by EVDESTROYER** [comment]
Pretty sure I've removed the winetricks folder before, but I just did it again for good measure, same error message as before.

**Comment by sonic2kk** [comment]
Ah, that's an interesting error message. I guess that confirms that dotnet48 is failing to install.

**Comment by sonic2kk** [comment]
> Pretty sure I've removed the winetricks folder before, but I just did it again for good measure, same error message as before.

Thanks, sucks that this didn't work.

Out of ideas for this very moment, I'm really sorry. I'll keep thinking and investigating though!

**Comment by sonic2kk** [comment]
Just saw it mentioned again so I wanted to ask: What's the storage situation like on your Deck? Some users reported issues with dotnet40 failing to install with "low" disk space. No specifics on what "low" is from them though.

Also, this probably won't make a huge difference but are you on SteamOS Stable, Beta or Preview? If you didn't change it / don't know then you're probably on Stable :-)

**Comment by EVDESTROYER** [comment]
According to Steam, I have 81.45gb of storage space available on my SSD. Also, yeah, I should just be on Stable, I haven't changed it.

**Comment by sonic2kk** [comment]
It may be worth reporting this error upstream to Winetricks

**Comment by sonic2kk** [comment]
This is more than likely an upstream issue with Winetricks. dotnet48 (or more specifically dotnet40) seems to failing to install. I'm not sure why this is and this may not be something STL can fix.

You could try manually installing dotnet48 into a clean 64bit prefix with GE-Proton, but this could be awkward to do on a Steam Deck. From what I have seen this issue seems to affect a handful of users and I could not find any solid advice on fixing the issue. Sorry that we aren't getting anywhere with this, but given that this seems to work sometimes and not other times, this is probably a case of Wine being fiddly. All the steps I can think of have already been tried (clean prefix, reinstall Winetricks, PC reboot, clear Winetricks cache) but I can't figure out why it would be failing.

Maybe GE-Proton7-42 would have more success since it's based on a newer Wine version, but I highly doubt it.

**Comment by sonic2kk** [comment]
It's unlikely but there was an update recently to STL that ignores when it can't ping GitHub and still downloads HMM. I'm fairly sure in your case HMM was able to successfully download but it might be worth a retest.

The manual installation steps would also apply, if the issue persists then this is a Winetricks issue that I don't think can be fixed from the STL side :(

**Comment by AYTT56** [comment]
Yea im having the same issue, i put the mscorees.dll and got the same error message when launching the game but i can launch hmm just fine

**Comment by sonic2kk** [comment]
That is strange but also unrelated to this issue.  You could try manually installing dotnet48 for that game though. And also ensure the DLL is in the same directory as the game's exe, some sega games have strange directory structures.

There isn't enough information here to try and debug the issue, this is also unrelated to OP's issue and I'd prefer not hijack :-)

If you're on Steam Deck remember that games have to be installed on the main SSD and also launched at least once because of a Steam client bug that has been reported twice on the Steam for Linux issue tracker. Once installed in the correct location, run the game at least once and also run HMM at least once.

Outside of that if you still have issues, open a new issue. This is not a general HMM support issue.

**Comment by AYTT56** [comment]
I am on steam deck and i did have frontiers installed on my sd card but when i moved it to the ssd hmm doesnt launch anymore. I tried uninstalling and reinstalling and it didnt work so i moved frontiers back to the sd card and hmm was launching again. So it seems hmm doesnt wanna launch when frontiers is on the ssd for some reason i even uninstalled stl and everything but nothing seems to work

**Comment by sonic2kk** [comment]
Once again, please open a new issue instead of using this one. And **please** fill out the issue template in as much detail as you can.

You'll need to attach a SteamTinkerLaunch log of attempting to launch Hedge Mod Manager with Sonic Frontiers on your boot SSD. You can find this at `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`, as noted on the Readme. You will also have to attach an `installDotNet.log` file. I suspect for some reason installing `dotnet48` for Frontiers is erroring and causing SteamTinkerLaunch to crash, and thus Hedge Mod Manager won't open. But this should be debugged separately, as once again, **this is not a general HMM support issue**, and to be honest I am tired of HMM users treating any open HMM issue this way.

**Comment by sonic2kk** [comment]
There has been no response from OP for a while and as far as I can see this is not something on the STL side that can be solved at least not right now. Closing this issue, feel free to re-open if there is more to discuss related to the opening issue.
