### ISSUE TITLE
Cant install MO2 through main menu or konsole (Steam Deck)

### ISSUE THREAD

**Issue by McGriggles** [sonic2kk/steamtinkerlaunch#679]
Tried installing from the Main Menu. The pop up window appears and says that its downloading/installing MO2 0% then prematurely closes. Trying to install it with the "./steamtinkerlaunch mo2 start" command gives me an error in the konsole stating:

"innoextract: error while loading shared libraries: libboost_iostreams.so.1.78.0: cannot open shared object file: No such file or directory". 

Trying to launch mo2 gui fails to launch and stl asks to retry settings. Attempted with Fallout 4, will be attempting with Skyrim SE now. Had previously installed mo2 with the rockerbacon script/installer, but had made sure to delete all files/directories as well as deleted and redownloaded and verified fallout/f4se .exe files prior to setting up Steam Tinker Launcher.

**Comment by sonic2kk** [comment]
Thanks for opening an issue!

When creating a bug report, you would've been provided with an issue template. Please edit your opening post to follow the issue template, it is not helpful to remove the template and enter free text. The template is there for a reason :-) This **includes attaching a log file**.

The error you're getting in terminal is interesting. Unfortunately without the log that the issue template asked you to provide, it's difficult to know more about what went wrong. Though truthfully I'm not sure how much a log would give for this sort of issue, for completeness I would prefer you to attach one. Did SteamTinkerLaunch download innoextract and if so what version did it download? It should be in the file name under `~/stl/deps/usr/bin`

Out of curiosity, have you disabled the read-only filesystem and attempted to install packages like innoextract or anything like this? Cases like this could be causing issues too where non-standard packages were installed. It would also be useful to know the version of SteamOS you're running, so please fill that in when you amend your initial opening issue.

**Comment by McGriggles** [comment]
Apologies, for some reason I dont remember seeing the issue template but I see it now. Editing

**Comment by sonic2kk** [comment]
In the meantime I looked up that error and I couldn't find anything useful yet. I found various posts talking about it but none in relation to innoextract and they were about compilation issues across distros, which shouldn't apply here.

Did you by any chance install any packages by disabling the read-only filesystem? If so, it's possible some of these dependencies may have pulled in innoextract or otherwise may be causing some issues/conflicts.

I just checked and there may be a newer version of innoextract available that SteamTinkerLaunch can use. The latest on the Arch archives [seems to be 1.9-7](https://archive.archlinux.org/packages/i/innoextract/), ~~I forget what SteamTinkerLaunch uses~~ if I kept the wiki up-to-date correctly, [SteamTinkerLaunch uses innoextract 1.9-5](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Deck#dependencies). It also worked previously, maybe a SteamOS update changed something? Not sure right now :-)

You could try manually replacing the innoextract binary in `~/stl/deps/usr/bin` with the latest one from the Arch archives (the one ending in `.zst`, the one ending in `.sig` is for Pacman which we aren't using here). Extract it into the path mentioned and if necessary, rename it to `innoextract`. Then try installing MO2.

A version bump for innoextract may be needed I guess. Bumps from `-5` to `-7` are usually very minor rebuild fixes but maybe if some SteamOS packages changed this is necessary :-)

**Comment by McGriggles** [comment]
Ahhh! Accidentally submitted a new issue when I opened a new one to edit the template. So sorry. I've never actually submitted any issues on github before. Let me remove that

**Comment by sonic2kk** [comment]
Going to copy my above response into your new issue and close this one. Thanks :-)

**Comment by sonic2kk** [comment]
> Ahhh! Accidentally submitted a new issue when I opened a new one to edit the template. So sorry. I've never actually submitted any issues on github before. Let me remove that

Using either issue is fine :-) It's no big deal. And no worries either way, finding your way around a new platform takes time. What matters is finding a resolution to the issue and that's what we'll work on (though I'll be going to sleep soon so it'll probably have to wait until tomorrow heh)
