### ISSUE TITLE
Cannot mount yad appimage

### ISSUE THREAD

**Issue by knightofbatons** [sonic2kk/steamtinkerlaunch#704]
## System Information
- SteamTinkerLaunch version: v11.11 & v12.0 & latest Git release
- Distribution: SteamOS 3.43 & 3.44
- Installation Method: ProtonUp-Qt 2.7.7

## Issue Description
when i use SteamTinkerLaunch (as compatibility tools & as a launch option) it cannot mount the yad appimage (Home/stl/deps/user/bin/Yad-8418e37-x86_64.AppImage), 
![1](https://user-images.githubusercontent.com/20508065/210169113-8700e5b3-4f90-4a6e-a633-423f88d05ceb.jpg)
![2](https://user-images.githubusercontent.com/20508065/210169128-b2b8d0df-d5aa-4794-a0cf-a4b80347ca15.jpg)

i try to run it with --appimage-extrace option but still not work, 
![3](https://user-images.githubusercontent.com/20508065/210169142-29f23d27-3e6c-4bbb-a613-e6eb470a3e1a.jpg)

I started to guess that there was a problem with the yad appimage file, so i download a new one from https://github.com/frostworx/steamtinkerlaunch-tweaks/releases/tag/Yad-8418e37-x86_64.AppImage
The newly downloaded file can be mounted
![4](https://user-images.githubusercontent.com/20508065/210169157-ca6b0191-dd16-4dbe-aa7f-0e04805e1295.jpg)

and i change the yad ( Home/stl/deps/user/bin/yad) Points to the newly downloaded file 
The problem is solved

![5](https://user-images.githubusercontent.com/20508065/210169166-a4bdf949-cf71-4c7e-aca0-69ccbe0aea67.jpg)

I am not a developer in this field ,not even familiar with Linux ,I can't tell if the problem comes from “installed via ProtonUp-Qt” or “SteamTinkerLaunch”，I saw many people have the same problem in the message area of a video about how to use SteamTinkerLaunch, so I want to see if I can help by reporting this bug

**Comment by sonic2kk** [comment]
Thanks for the investigation!

It sounds like it may be that SteamTinkerLaunch could not download the Yad AppImage. However, no other users have reported it and it works for many users. I don't think this is a SteamTinkerLaunch issue but a network issue. Since when you manually download the file, it works.

Some other users have reported EXE downloading issues that turned out to be ISP issues and certificate issues, where they could not download Hedge Mod Manager or MO2. These are not SteamTinkerLaunch issues and there's nothing I can do about it. It seems to happen when the result of the following Bash code fails to return a valid result:

```bash
if ! ping -q -c1 archlinux.org &>/dev/null; then
    echo "Offline"
else
    echo "Online"
fi
```

If that Bash code returns `Offline` even if you're online, then it's an ISP issue.

If any users have this issue the first thing they should try would be to remove the AppImage and manually download it, like you did.

I will take a look at updating the Yad download so that it will still attempt to download Yad even if the online check fails, but this should only affect a small handful of users. The "many" users you mentioned could not be bothered to report an issue like you did.

> not even familiar with Linux

SteamTinkerLaunch is primarily for users who are familiar with Linux. I don't expect every user to be a developer but I expect users to try and troubleshoot issues like you did, and to have some experience using a Linux Desktop. Those tend to have the most productive outcomes.

<hr>

Thanks for reporting and for the investigation, and indeed manually downloading the AppImage is probably required here for the most "fool-proof" solution. I will look at updating the code to attempt to download Yad anyway but this issue is **not** specific to SteamTinkerLaunch and **is most likely** an ISP issue causing the `ping` check to fail. Other programs that rely on this will fail too. The Yad downloading may still fail, as for one users Hedge Mod Manager still failed to download and all command line downloading seemed to fail for that user, which is nothing SteamTinkerLaunch can fix.

I'll push an attempt to fix this shortly :-)

P.S. - You can use Spectacle to take screenshots on your Steam Deck the same way you would on a regular KDE Plasma install. That may be a useful tip for the future as a 1280x800 screenshot may be smaller and faster to upload :-)

**Comment by sonic2kk** [comment]
Latest STL git attempts to download Yad anyway even if the offline check is true. This may cause some problems for users who are actually offline, and the core issue is not a SteamTinkerLaunch issue.

Thanks for reporting even though other users could apparently not be bothered. If that does not fix it then it sounds like a very strange ISP issue that will need to unfortunately be resolved separately.

Thanks! Closing :-)

**Comment by knightofbatons** [comment]
Thank you very much. If it is an ISP problem, it can explain why all the people in the video message area I mentioned earlier have the same installation method. However, some people have encountered this problem and others have not.

I completely deleted the previous installation, and then tested the latest Git release in the same network environment. My problem has been solved.

Many steam deck users are just game players. It is likely that using steam deck is their first time to contact the Linux system. When they want to use the cool features of the steamtinkerlaunch, they may learn how to use it in the video I mentioned earlier on how to use the steamtinkerlaunch. Some people may not even read the documents in github, let alone come here to give feedback when encountering problems



In addition, thank you very much for your suggestion on Spectacle, which is much better than taking photos

**Comment by sonic2kk** [comment]
> Many steam deck users are just game players. It is likely that using steam deck is their first time to contact the Linux system.

Indeed, and this has been a source of many invalid and low-effort issues. SteamTinkerLaunch is still primarily for experienced Linux users - Users who have not used Linux before are going to have a hard time modding, and may not understand many of the options available in SteamTinkerLaunch. I still try to make it straightforward to use but I still expect users to have knowledge on how to debug more than "it doesn't work" like some of the recent issues coming in have been. Many of these users also blame Steam client bugs on SteamTinkerLaunch, or are exceptionally rude and refuse to provide basic information to help troubleshoot. Other users don't understand the information asked for, meaning very little can be done to help them.

It is frustrating when trying to give users troubleshooting steps and they either give up and don't reply anymore, or you have to start from first principles and explain what a Wineprefix is. I do understand that users have to start somewhere with tinkering but many don't care and, as you put it, are "just game players" - SteamTinkerLaunch is really better suited imo to users who have more experience with gaming on Linux and with Wine.

That's just my two cents given what I've seen over the last 11 months. The ones that just "play games" and have never even used Linux on their desktop and use Windows are likely not going to have a great tinkering experience unless they're willing to get their hands dirty, and many are not or don't care to learn. ¯\\_(ツ)_/¯

**Comment by frostworx** [comment]
one of the main reasons why I gave up spending my time into the project.
I hope you still have fun working on it at least

**Comment by sonic2kk** [comment]
It can definitely be a source of frustration :-) but the way I look at it is that *I* use SteamTinkerLaunch with the games I play, so in part I look at it as a personal tool that I also get to maintain and extend. I also know there are users who do get a lot of use out of STL as well (I saw one person online describe it as "essential software"), focusing on making improvements for myself and other users without getting too bogged-down on rude users or Linux newbies helps my motivation.

Help those that are also willing to help themselves is how I look at it :-)

**Comment by frostworx** [comment]
yeah, that worked fine for me for a long time since I created it.
may many helpful people raise to keep the momentum going.
edit: and may you find more time for actual coding than for replying tons of duplicate $issues _(not this one)_ comprehensively
