### ISSUE TITLE
STL cannot download Yad

### ISSUE THREAD

**Issue by BioIron** [sonic2kk/steamtinkerlaunch#707]
## System Information
- Device: Steam Deck
- SteamTinkerLaunch version:  v12.0
- Distribution: SteamOS 3.4.4
- Installation Method: ProtonUp-QT v2.7.7 (from Discovery app)

## Issue Description
Everytime I launch a game (any game) on gaming mode, it gets stuck on the steam loading screen. I can get back to the main menu, but can't close the game (still loading) unless I restart the Deck.
If try to launch the same game through desktop mode (let's go with Neon Abyss, for example), some pop-ups appear on the right down part of the screen in this order:
- Preparing to install SteamTinkerLaunch
- Downloading latest SteamTinkerLaunch
- Adding SteamTinkerLaunch as compatibility layer.
- Finishing installed SteamTinkerLaunch ('v12.0')
- Closing tray icon '18659'    //// NOTE: This number changes everytime i launch the game. I think it increases.
- 'Neon Abyss (788100)' stopped. Exiting SteamTinkerLaunch.

And... no game or STL launcher appears. 
I can press the "Play" button on the Steam client, and see the whole process again... but also again, no game or STL launcher. While in desktop mode, it seems that i don't need to "force exit" anything or restart, unlike in gaming mode.
Except for the last two pop-ups, the rest of the messages appeared when i installed STL for the first time... and the second one... and the third one, through ProtonUp-Qt. Reinstalling STL doesn't seems to solve whatever the issue is.
I have never installed the STL flatpack/discovery version on this Steam Deck. 
STL v11 worked fine before, but that was long ago, though... 
I use STL through Steam Compatibility layer. I can change back to other Proton versions, and the game starts and works flawlessly.
This particular game, Neon Abyss, is installed in the internal drive.
Erm... don't know what else to add.
Anyways, here is the mandatory logs. One starting the game from desktop mode, and another one from gaming mode. 
Hope it helps:

## Logs
[steamtinkerlaunchGAMING.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10352100/steamtinkerlaunchGAMING.log)
[steamtinkerlaunchDESKTOP.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10352067/steamtinkerlaunchDESKTOP.log)

**Comment by sonic2kk** [comment]
Hi!

Everything is working fine on my end with SteamOS 3.4.4 and the latest Steam Client Beta. I tested STL v12 and STL from git, I don't have any issues. I tested in Game Mode and Desktop Mode. I have had the issue you described with having to restart the Steam Deck to close a game before irrespective of SteamTinkerLaunch, but it's extremely intermittent and I haven't had it in a long time.

I know it was just an example, however as luck would have it I actually own Neon Abyss, and I had never installed it on my Steam Deck before. I installed it and launched it fresh with SteamTinkerLaunch for the first time and it worked without issue.

I would also just like to mention two things:
- As noted on the SteamTinkerLaunch Discover page, SteamTinkerLaunch Flatpak is only for Flatpak Steam. This is also noted on the SteamTinkerLaunch wiki. You were correct in not using it
- SteamTinkerLaunch is not reinstalling itself, it's trying to update, which because of a limitation with GitHub it can't do when installed via ProtonUp-Qt.

The Desktop Mode log is very interesting. It thinks that the "Exit" button was pressed for some reason. Following the flow of the log it seems like SteamTinkerLaunch thinks that the Wait Requester showed up and that SteamTinkerLaunch was exited.

Perhaps this is an issue with Yad, though I doubt it somewhat. Some ISPs cause Various issues with SteamTinkerLaunch. Try uninstalling SteamTinkerLaunch and installing SteamTinkerLaunch-git (either manually or via ProtonUp-Qt with its Advanced Mode enabled in the About menu). Recently a user reported an issue where Yad could not be downloaded, and an experimental fix was added in master. The issue was #704 and lists different errors, so I'm not sure how related they are.

If that also doesn't work and you aren't already on it, you could try the Beta channel. That's what I use and what SteamTinkerLaunch is tested against.

You could also go to the SteamTinkerLaunch installation folder at `~/stl` and verify that the SteamTinkerLaunch dependencies in the `deps` folder look valid e.g. they're more than 0 bytes, etc.

Hopefully some of this resolves your issue :-)

**Comment by BioIron** [comment]
> Perhaps this is an issue with Yad, though I doubt it somewhat. Some ISPs cause Various issues with SteamTinkerLaunch. Try uninstalling SteamTinkerLaunch and installing SteamTinkerLaunch-git (either manually or via ProtonUp-Qt with its Advanced Mode enabled in the About menu). Recently a user reported an issue where Yad could not be downloaded, and an experimental fix was added in master. The issue was #704 and lists different errors, so I'm not sure how related they are.
> 
Have just tried that. Uninstalled "regular" STL and reinstalled STLgit using ProtonUp-QT in advanced mode. It still appeared on the list as Steam Tinker Launch, so it kind of weirded me out.
Unfortunately, did not solve it. But it seems i'm actually on git now, as the version in the pop-up has changed to:
- Finishing installed SteamTinkerLaunch ('v12.12.20230101-2')

Issue persist, both in gaming and desktop mode, but new STL version, so i will upload another log (desktop), just in case:
[steamtinkerlaunchGIT.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10353104/steamtinkerlaunchGIT.log)

> You could also go to the SteamTinkerLaunch installation folder at `~/stl` and verify that the SteamTinkerLaunch dependencies in the `deps` folder look valid e.g. they're more than 0 bytes, etc.
> 
Checked... i guess?
Went to `~/stl` and all three folders have something in it. `deps` is 684,5 KiB, with 7 files, 9 sub-folders. `prefix` is 1,5 MiB, with 179 files, 14 subfolders. `prefix-temp` is 7,5 MiB, with 253 files, 70 sub-folders.
Don't know what i need to look up in there. I lack quite a bit of knowledge on any on this...

> If that also doesn't work and you aren't already on it, you could try the Beta channel. That's what I use and what SteamTinkerLaunch is tested against.
> 
I was in Steam Deck Stable client. Changed to Steam Deck Beta.
Did the change on desktop mode.
After update and restart, issue persist, but with a new twist:
Gaming mode no longer gets stuck, and now Neon Abyss correctly closes by itself.

I will add some new logs. They are free, after all:

[steamtinkerlaunchBGIT.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10353298/steamtinkerlaunchBGIT.log)
[steamtinkerlaunchBGITGaming.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10353339/steamtinkerlaunchBGITGaming.log)

The first log was STLgit + Stable, these are STLgit + Beta. Maybe something changed?

> The Desktop Mode log is very interesting. It thinks that the "Exit" button was pressed for some reason.
> 
Kind of worried about this, and thought that maybe i was touching something on screen by accident.
With extreme caution, resting the Deck in a place with no risk to press the bumpers, i used the touch screen to quickly tap the "Play" button, and then put my hands up to prevent any undiserably input.
Nothing changed, and issue persists. It was fun to try, though.

In any case, thanks for your time and possible fixes.

**Comment by sonic2kk** [comment]
The log is very strange indeed and still shows the same issue where SteamTinkerLaunch thinks its being closed in Desktop Mode. It thinks that it's going to the Main Menu and then being closed, the following log lines are of interest:

> Thu Jan  5 16:16:25 CET 2023 INFO - MainMenu - Looks like we're in Steam Deck desktop mode here on the Main Menu
> Thu Jan  5 16:16:25 CET 2023 INFO - MainMenu - Clicked '0' - 'EXIT'
> Thu Jan  5 16:16:25 CET 2023 INFO - MainMenu - exiting 'Settings Menu' and opening 'Exit'

Even by looking at the timestamps it is clear that something is wrong here, since the Exit button would have to be pressed within a second of the main menu opening (which is borderline unreasonable!)

And I'm fairly sure this is caused by an invalid `yad` installation:

> Went to `~/stl` and all three folders have something in it. `deps` is 684,5 KiB, with 7 files, 9 sub-folders

Thanks for checking, this is way too small for the deps folder. On my Steam Deck it is 60.8mb, with the Yad AppImage taking up 60.1mb of that (at `~/stl/deps/usr/bin`).

I am guessing that SteamTinkerLaunch attempted to download Yad and for network reasons was unable to. Manually installing the Yad AppImage should fix this issue: https://github.com/frostworx/steamtinkerlaunch-tweaks/releases/tag/Yad-8418e37-x86_64.AppImage

Download the AppImage to `~/stl/deps/usr/bin` (overwriting a file with a similar name), and then creating the `yad` symlink manually. You can do this once the file is downloaded by clicking and dragging it onto an empty space in the folder and choosing the "Link Here" option. Then re-name the symlink to simply `yad` (all lowercase as shown). If you've used KDE on the Desktop you may already know how to do this.

Not sure why Yad is failing to download but as it works for other users even as recently as 30 minutes ago, I believe this is a strange network issue. Thanks for reporting and hopefully with some luck, manually downloading the Yad AppImage will fix this.

**Comment by BioIron** [comment]
> I am guessing that SteamTinkerLaunch attempted to download Yad and for network reasons was unable to. Manually installing the Yad AppImage should fix this issue: https://github.com/frostworx/steamtinkerlaunch-tweaks/releases/tag/Yad-8418e37-x86_64.AppImage
> 
> Download the AppImage to `~/stl/deps/usr/bin` (overwriting a file with a similar name), and then creating the `yad` symlink manually. You can do this once the file is downloaded by clicking and dragging it onto an empty space in the folder and choosing the "Link Here" option. Then re-name the symlink to simply `yad` (all lowercase as shown). If you've used KDE on the Desktop you may already know how to do this.
> 

And... it worked!
Did exactly what you instructed. Weirdly enough, at the first try (pressing "Play" on Steam), it gave an error saying something like it didn't find the yad symlink in the specific path, even if it was already there, and even after i recreated it twice. 
After opening/executing the symlink, an small window appeared, and when pressed the "Play" button on Steam again, STL started working as intended, both in desktop, and gaming mode.
So... all fixed! For now, at least.
Thanks for your support :)

**Comment by sonic2kk** [comment]
All good! Not sure why it failed to download but at least it is fixed! I should note how to do this on the wiki.

EDIT: Documented it earlier: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Deck#installation
