### ISSUE TITLE
How can I uninstall a wine/proton prefix?

### ISSUE THREAD

**Issue by LeviathaninWaves** [sonic2kk/steamtinkerlaunch#712]
Sorry, wasn't sure where else to ask this. I need help figuring out how to uninstall a prefix on Steam Deck. Did a D3D11 install with winetricks, also installed Reshade and now I need to roll back some of that so I can narrow down the cause of some missing texture glitches in a custom build of the Dolphin emulator. Thanks in advance.

**Comment by sonic2kk** [comment]
The Dolphin emulator doesn't use Wine, so I'm not sure where that's coming from. It shouldn't use a prefix at all.

You can remove a prefix for a Wine game on Steam Deck from Game Mode by going to "Options" (can be opened with the "Menu" or "Start" button on your controller) and choosing to remove Proton files. I forget which submenu it's under, maybe "Developer"?

In general, prefixes are located at `/path/to/libraryfolder/steamapps/compatdata/<appid>/`>. On Steam Deck there has been a persistent Steam Client bug where prefixes are strangely always created on the main SSD library folder, so in that case the path would be `~/.local/share/Steam/steamapps/compatdata/<appid>`. I'm not sure if this bug was fixed in SteamOS 3.4.X / with a Steam Client Beta.

There will only be a prefix in the library folder path if you're dealing with a game running via Proton and if you're running the game through Steam. Otherwise the prefix could be anywhere depending on various factors (maybe `~/.wine`?).

I would strongly recommend taking a backup of your prefix *just* in case there's anything important in it. I'm not sure what would be stored there in this case but games sometimes store save data and the likes in the prefix. A Wine/Proton prefix is basically what your application sees as the "Windows installation" and so it may store files in the AppData or Documents folders and so on.

SteamTinkerLaunch offers the option to re-create a prefix but I'm not sure how this works for Non-Steam games. It also provides an option to browse to the prefix of the currently opened program under the "Game Files" button on the Main Menu (check the `WINEPREFIX` checkbox and then open). I haven't tested this for Non-Steam Games but I don't see any this wouldn't work. It relies on `xdg-open` but I'm fairly sure the Steam Deck has it, and no one has reported problems with this feature on Steam Deck, so it should work :-)

This isn't really a SteamTinkerLaunch issue but I hope this helped!

**Comment by LeviathaninWaves** [comment]
> The Dolphin emulator doesn't use Wine, so I'm not sure where that's coming from. It shouldn't use a prefix at all.
> 
> You can remove a prefix for a Wine game on Steam Deck from Game Mode by going to "Options" (can be opened with the "Menu" or "Start" button on your controller) and choosing to remove Proton files. I forget which submenu it's under, maybe "Developer"?
> 
> In general, prefixes are located at `/path/to/libraryfolder/steamapps/compatdata/<appid>/`>. On Steam Deck there has been a persistent Steam Client bug where prefixes are strangely always created on the main SSD library folder, so in that case the path would be `~/.local/share/Steam/steamapps/compatdata/<appid>`. I'm not sure if this bug was fixed in SteamOS 3.4.X / with a Steam Client Beta.
> 
> There will only be a prefix in the library folder path if you're dealing with a game running via Proton and if you're running the game through Steam. Otherwise the prefix could be anywhere depending on various factors (maybe `~/.wine`?).
> 
> I would strongly recommend taking a backup of your prefix _just_ in case there's anything important in it. I'm not sure what would be stored there in this case but games sometimes store save data and the likes in the prefix. A Wine/Proton prefix is basically what your application sees as the "Windows installation" and so it may store files in the AppData or Documents folders and so on.
> 
> SteamTinkerLaunch offers the option to re-create a prefix but I'm not sure how this works for Non-Steam games. It also provides an option to browse to the prefix of the currently opened program under the "Game Files" button on the Main Menu (check the `WINEPREFIX` checkbox and then open). I haven't tested this for Non-Steam Games but I don't see any this wouldn't work. It relies on `xdg-open` but I'm fairly sure the Steam Deck has it, and no one has reported problems with this feature on Steam Deck, so it should work :-)
> 
> This isn't really a SteamTinkerLaunch issue but I hope this helped!

Thank you, this is a Windows build of Dolphin.

**Comment by sonic2kk** [comment]
One thing I forgot to mention is that if you need to manually remove the prefix and you have several Non-Steam Games, it might be difficult to know which one is the one you're looking for. Steam has some algorithm that I don't understand for generating the AppID for Non-Steam games that seems to use some sort of CRC sum based on the name and path.

As a small aside, Non-Steam Game AppIDs are typically longer than Steam game AppIDs, which should make it easier to spot.

If it's a Windows build of Dolphin then you may be able to use SteamTinkerLaunch as the compatibility tool and locate the prefix this way under the Game Files section. That is likely the most straightforward way.

Otherwise I'm not sure where in Steam you could find the AppID for Non-Steam Games. A roundabout way could be to set a custom artwork for Dolphin in Desktop Mode (e.g. change or set the banner/hero or logo) and then go to `~/.local/share/Steam/userdata/<Steam User ID>/config/grid` and locate the picture that you set. The name will start with the AppID that Steam generated for the game. For example for banner images it'll be called `<app_id>_hero.png`. If the ID was `132464636456` then your prefix would be at `~/.local/share/Steam/steamapps/compatdata/132464636456`.

Good luck!
