### ISSUE TITLE
Mo2 won't install

### ISSUE THREAD

**Issue by FatedRin** [sonic2kk/steamtinkerlaunch#714]
## System Information
- SteamTinkerLaunch version: 
- Distribution: 
- Installation Method:

**Comment by sonic2kk** [comment]
No useful information was provided here. If I had to guess I'd say you're trying to install with GE-Proton7-43 going by previous issues. Try GE-Proton7-42 and see if that works.

The issue template is there to help debug issues, please fill it out before opening future issues. Since this issue is blank except for the template, I will close this issue. Please open a new issue filling out all requested information + any future technical information you can find out about the problem.
