### ISSUE TITLE
7th Heaven mod manager

### ISSUE THREAD

**Issue by ghost** [sonic2kk/steamtinkerlaunch#720]
### Supported Games
Final Fantasy 7 steam 2013 release / PC 1998
### link to github page
https://github.com/tsunamods-codes/7th-Heaven

**Comment by sonic2kk** [comment]
You're going to have to give some more background. Which FF7? Does it work on Linux/Wine? Does it need any tweaks?

I own FF7 and FF7R but I haven't played them and I'm not sure if/when I'll get around to it, so support probably won't come from me unless it is very very straightforward to add (e.g. just downloading an exe).

You can't make a feature request that says "please add X" with a link and give no other background I'm afraid. You need to outline the process for running it on Linux. Recall the note on the Feature Request issue template:

> Please give as many details about your desired feature as possible, including any technical details or previous approaches you have tried.

**Comment by sonic2kk** [comment]
It looks like it might rely on .NET 7 and vcrun2019 (or maybe vcrun2022). No idea how .NET 7 plays with Wine.

Couldn't see any information on official Linux support, so you'll need to provide information on how to run it on Linux.

**Comment by sonic2kk** [comment]
It also seems like that mod manager requires 32 and 64bit versions of .NET 7 and I would *assume* vcrun2022 (it just says "latest"). vcrun2022 has to be install by Winetricks and I don't know if it installs the 32bit versions.

Basically I'm going to need information on how this program works on Linux, if at all, and any steps required for it. I'd also like to know if it has to run in its own prefix and if that works i.e. will it still see FF7, does it have support built in to check for installed games on Linux like HMM does.

I'm not overly interested in adding support for this as it's for one game, potentially two if it supports FF7 and FF7R, and it's a game I am not interested in very much. However the background here would be useful for other users.

I am hesitant to add support for a single-game mod manager (MO2, Vortex and HMM support several, with some overlap too). Though I wouldn't be against documenting the steps to get it running on the wiki.

**Comment by sonic2kk** [comment]
I skimmed the discussion here and it seems like an involved process that requires some bleeding-edge builds and a good amount of effort that I am not overly interested in doing for a single-game mod manager: https://github.com/tsunamods-codes/7th-Heaven/issues/19

Given that I haven't played FF7 and don't have much knowledge, it would potentially leave a bad impression on the maintainers of the mod manager, if they were to give permission for integration to begin with. Plus testing this on Steam Deck could be a nightmare...

So unfortunately the answer for this proposal is no. The steps mentioned in that issue should be possible to do manually with SteamTinkerLaunch I think to some extent, but it's probably better left to another tool. But single-game mod managers aren't really a goal for this project, it's why we have support for Hedge Mod Manager but not something like SA2ModManager. Also I think some users get the wrong impression of the project because of its mod tool support, but SteamTinkerLaunch is not just an installer for modding tools on Linux.

Thanks for the suggestion and sorry you didn't get the answer you were looking for.

**Comment by sonic2kk** [comment]
Seems like this is going to get support as a Flatpak anyway (which is not ideal for everyone in fairness) so there is no need for this to be supported in SteamTinkerLaunch.
