### ISSUE TITLE
Vortex Mod Manager: Symlink as only Deployment Method available

### ISSUE THREAD

**Issue by martyTF** [sonic2kk/steamtinkerlaunch#721]
Version: steamtinkerlaunch 12.0
OS: NobaraProject (Fedora based)

Despite the wiki saying that Hardlinks are the default as Linux doesn't like Windows Symlinks, it's the exact opposite for me, where I can't select Hardlink Deployment for Vortex, only Symlink Deployment is available:
![image](https://user-images.githubusercontent.com/69526651/211872863-58086db4-66f2-4509-b129-115ece4fee37.png)

Tested on multiple games (Witcher 3, Cyberpunk 2077, Blade & Sorcery).

Launching the games through Vortex doesn't really work, and launching them through Steam launches them completely Vanilla.

**Comment by sonic2kk** [comment]
Vortex is apparently broken at the moment because of what I assume are changes on the Vortex side, see the pinned #709.

Since Vortex is buggy on Linux for the moment we can assume that this is to blame for the link and deployment issues.

I don't use or particularly like Vortex and I am not really sure what the linking stuff is about, I've seen other users talk about it but it was implemented before I had even heard of SteamTinkerLaunch. However if the issue persists if/when the Vortex Linux issues are resolved, we can re-open this issue perhaps - Though I think this is more along the lines of general Vortex usage on Linux, not anything to do with SteamTinkerLaunch specifically.
