### ISSUE TITLE
Possible to add vcredist 2022

### ISSUE THREAD

**Issue by juan-90s** [sonic2kk/steamtinkerlaunch#723]
## System Information
- SteamTinkerLaunch version: v12
- Distribution: SteamOS 3.4

## Feature Description
I know some mod need Visual Studio Redistributable 2022 as a environment. Although I don't have much technical background. I think it's possible to add vcredist 2022 into Steam First Run Setup page.

**Comment by sonic2kk** [comment]
I believe this can be installed via Winetricks, which SteamTinkerLaunch supports.

Am I missing something?

**Comment by sonic2kk** [comment]
My mistake, it cannot be installed via Winetricks yet, it is pending https://github.com/Winetricks/winetricks/pull/1974

Once Winetricks has support, SteamTinkerLaunch will support `vcrun2022`.

Nothing can be done on the SteamTinkerLaunch side for this, I'm not sure what you meant by "Steam First Run Setup" page as that is managed separately from SteamTinkerLaunch. The SteamTinkerLaunch button for configuring the Steam First Time Run is not for this sort of usage either as far as I know.

In the meantime vcrun2022 will have to be manually installed. Perhaps using the verb in the PR would work, but as you mentioned you aren't from a technical background maybe you won't want to do this. Though as an aside, you're expected to have a bit of technical knowledge when using SteamTinkerLaunch, as it is for tinkering.

Hopefully this answers your question!

**Comment by frostworx** [comment]
@juan-90s meant, that Steam also provides a "Steamworks Shared/_CommonRedist/vcredist/2022"
package, which needs to be added to `misc/steamworks-shared.txt`
to make it available as [Steam First Run](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-First-Time-Setup) package.
Using the [Steam First Run](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-First-Time-Setup)
implementation it is possible to install packages provided by [Steamworks Shared](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steamworks-Shared) even if the corresponding game does not have that package as a [Steamworks Shared](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steamworks-Shared) pre-install dependency
winetricks is not required here and in most cases [Steamworks Shared](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steamworks-Shared) should be preferred over winetricks in steam combination when possible, because it takes care that the package is installed "the-steam-way" (one exception is dotnet, where Steamworks Shared ships an incomplete version,  which does not help with 3rd party dotnet stuff.)

The vcrun2022 hasn't changed so adding

```
"vcrun2022-x64";"vcredist/2022/VC_redist.x64.exe";"/q /norestart"
"vcrun2022-x86";"vcredist/2022/VC_redist.x86.exe";"/q /norestart"
```

to `misc/steamworks-shared.txt` should be enough.
*reopening*

**Comment by juan-90s** [comment]
@frostworx 
I added that lines to `misc/steamworks-shared.txt`. But vcredist 2022 didn't come up in Steam First Run page. 

I think I have to create a new script in `eval/packages/` which like [this file](https://github.com/sonic2kk/steamtinkerlaunch/blob/master/eval/packages/vcredist2019) 
Since there's a id for such packages, I don't know how to write the id for adding vcredist 2022

Thanks

**Comment by frostworx** [comment]
oh, you're right of course @juan-90s

Haven't touched that function for a very long time and totally forgot about the modified files... :)

I guess you can simply use the vcredist2019 file you linked as a template, but to be sure it would make sense to also compare the parameters used in the "upstream" bundled version which can usually be found under
`~/.local/share/Steam/steamapps/common/Steamworks Shared/_CommonRedist/vcredist/2022/installscript.vdf`
good luck so far

**Comment by frostworx** [comment]
@sonic2kk oh sorry sonic, I didn't even know that I still have write access to the project.
Just merged an _(untested)_ PR for a possible fix.
@juan-90s please test if possible

**Comment by juan-90s** [comment]
I do manage to make vcredist 2022 into [Steam First Run](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-First-Time-Setup). 

Firstly, download the [depot](https://steamdb.info/depot/228989/manifests/) and copy the files into `~/.local/share/Steam/steamapps/common/Steamworks Shared/_CommonRedist/vcredist/2022/`. By the way, vcredist 2022 does not initially come with Steamworks Shared so that I downloaded it manually. Then, create similiar file as the templete in `eval/packages/`.

Although I performed Steam First Run, I don't know how to validate whether I succeed to install vcredist 2022.

**Comment by sonic2kk** [comment]
Great catch @frostworx! I had no idea about this (I haven't touched this Steam run stuff before, I was totally unfamiliar :sweat_smile:)

Thanks for catching it and no worries about the push, please feel free to push any fixes like this :-) Based on my (quick) skim and referring to how the other packages were added, it looks reasonable to me.

**Comment by sonic2kk** [comment]
@juan-90s I am not sure exactly either but you mentioned some mods require this package, and I *believe* that this package is just installed into the game's prefix. So trying to run a game with a mod that requires vc2022 may be a good step in validating that it installed properly.

Apologies for my earlier misunderstanding :-)

**Comment by frostworx** [comment]
hey, @sonic2kk 
No promises, but I'll try to find a bit more time again for steamtinkerlaunch. I miss it a bit sometimes to be honest ;)

Yeah, whenever a game depends on a Steam Works Shared program, Steam automatically downloads it into `~/.local/share/Steam/steamapps/common/Steamworks Shared/_CommonRedist` and automatically installs it on a first run (that's why the steamtinkerlaunch function is called [Steam First Run](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-First-Time-Setup).) That function tries to override the original behavior by intercepting the whole first run process and storing copies of the temporary install vdfs Steam automatically installs behind the scenes.
The user usually never sees those files, because they are automatically removed after execution.
The copies for every games started via steamtinkerlaunch can be found under
`~/.config/steamtinkerlaunch/meta/eval/id/`

Using the [Steam First Run](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-First-Time-Setup) it should be possible to run the original first run setup again (at least it was when I implemented it, but there was nearly zero feedback - might be a hidden unknown gem ;)) and/or override it with extra packages (so for example vcrun2022).

@juan-90s 
you say you had to download the appid directly, so I'd say there is no gamer installed which depends on it.
In the 230 vdfs I currently have in `~/.config/steamtinkerlaunch/meta/eval/id/`
`grep "vcredist*.*2022" *.vdf`
only found one game which pulls in vcrun2022 as dependency: 658920
https://store.steampowered.com/app/658920/HalfLife_2_VR_Mod/

**Comment by juan-90s** [comment]
@frostworx There is one called Steamworks Common Redistributables which AppID is [228980](https://steamdb.info/app/228980/depots/)

the command I used in Steam Console:
`download_depot 228980 228989 8457487755951768435`

**Comment by frostworx** [comment]
@juan-90s yes I know the package, not sure what you want to tell me though.
That package is automatically updated (i.e. the 228989 depot for vcrun2022 is downloaded) whenever a game depends on it.

**Comment by juan-90s** [comment]
@frostworx oh yeah, it's not a actual game but a Skyrim [mod](https://www.nexusmods.com/skyrimspecialedition/mods/65089)  which maybe the author developed the mod within vs2022. But as I tested, the problem I met in modding is not related to the vc runtime.

**Comment by sonic2kk** [comment]
If I understand correctly, vc2922 was downloaded as part of the Steam First Run, but there is a separate issue with the mod test case? 

If so this issue can possibly be closed, as the functionality was implemented.

**Comment by sonic2kk** [comment]
Closing as it appears the feature was implemented and working, and the existing issue is related to a mod external to SteamTinkerLaunch.

Like before, please re-open if anything else pops up :-)
