### ISSUE TITLE
Steam Tinker Launch causing issues with game saves

### ISSUE THREAD

**Issue by ro161012** [sonic2kk/steamtinkerlaunch#731]
System Information
- SteamTinkerLaunch version: v12
- Distribution: Steam OS
- Installation Method: Proton Up-Qt

I recently used shader cache move to move my comptdata and shader cache files to my sd card. All was working fine. Then I forced STL to add some trainers. I checked the boxes for use custom cmd and fork custom cmd in the game menu, and picked the exe for the trainer. Then I hit save and play. My saves were gone!. I reinstalled and tried it without stl and the saves were there! Please advise.

Logs
[31337.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10553201/31337.log)
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10553202/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
Hi!

Your saves for that game were probably stored in the compatdata, this isn't SteamTinkerLaunch causing issues but rather a misunderstanding of where your game saves were stored. Please take care when moving your game prefixes especially on Steam Deck.

On Steam Deck there is / was Steam Deck specific bug where Steam will always create compatdata folders on the main SSD. If that is the case, perhaps what has happened is that Steam has re-created the compatdata on your boot SSD and thus there would not be any save files, since it created a fresh one. If Steam has done this, you could delete the compatdata on the boot SSD and then move the compatdata you moved to the SD card over to the compatdata on the boot SSD.

This isn't a SteamTinkerLaunch issue, so closing :-)
