### ISSUE TITLE
Installing Steam Tinker Launch with Pacstall in Ubuntu 22.10 Breaks the Software Updater Application

### ISSUE THREAD

**Issue by intelligentgaming** [sonic2kk/steamtinkerlaunch#739]
Good evening all.

After installing Steam Tinker Launch using Pacstall in Ubuntu 22.10 the Software Updater application now crashes with the below. 

![image](https://user-images.githubusercontent.com/67860954/218277166-b996e9f9-706c-4c4e-a8b0-547f23f39f2b.png)

To test this, I reverted back to an earlier Timeshift snapshot, and reinstalled Pacstall, rebooted, and ran Software Updater which worked correctly. 

I then installed Steam Tinker Launch using Pacstall and Software Updater was broken again. 

Luckily I can still update the system using sudo apt update && sudo apt upgrade -y but this is still an annoying bug.

Any ideas?

**Comment by sonic2kk** [comment]
Hi! That certainly sounds frustrating, but I do not maintain the Pacstall package so sadly I can't give you much help here. In fact, I don't maintain *any* of the SteamTinkerLaunch packages available. The only "maintenance" I provide outside of this repo is helping out with ProtonUp-Qt support (STL still requires extra work on Ubuntu with ProtonUp-Qt because of Ubuntu's massively outdated dependencies) and commenting on the AUR package, as I use Arch. Every other package is maintained by very generous community members :-)

You'll have to report this bug [upstream to Pacstall](https://github.com/pacstall/pacstall-programs/issues) and hopefully get some answers there. Please keep in mind the Pacstall is a big project with various different packages available, with SteamTinkerLaunch being only one of those packages, so it may take a while to diagnose and troubleshoot the issue :-)

Since I can't do much over here (as far as I'm aware anyway) I'm going to close this issue, but if you could, please leave a comment here linking to the Pacstall issue so I can take a look whenever it's created. I'd be interested in seeing what's going on.

Good luck! Hopefully this is resolved soon.

**Comment by sonic2kk** [comment]
OP reported the bug upstream to pacstall/pacstall#788

**Comment by Elsie19** [comment]
Checking it out now.
