### ISSUE TITLE
Mod Organizer 2 won't launch the game, complains that Steam isn't running

### ISSUE THREAD

**Issue by SimplyTadpole** [sonic2kk/steamtinkerlaunch#742]
## System Information
- **SteamTinkerLaunch version:** 12.0
- **Distribution:** Fedora Kinoite 37
- **Installation Method:** Flatpak

## Issue Description
I installed SteamTinkerLaunch as a Flatpak extension to the Steam flatpak, and hoped to use it to install Mod Organizer 2 to mod New Vegas. STL installed MO2 itself just fine, but unfortunately MO2 will not launch New Vegas - it complains that Steam isn't running. Obviously I have to be running Steam to even launch STL itself, so MO2 is for some reason refusing to recognize Steam. Attempting to launch the game anyway causes New Vegas to immediately crash, therefore STL is not working properly for me. I attempted to look through the wiki as well as through the issues, but I couldn't find anything related to this issue.

![image](https://user-images.githubusercontent.com/70490001/218335298-be50bd79-478c-4c09-b4db-6c9d9a9215e1.png)

## Logs
[Here's my log file](https://github.com/sonic2kk/steamtinkerlaunch/files/10717207/steamtinkerlaunch.log).

**Comment by sonic2kk** [comment]
Just to make sure, are you launching MO2 from Game Mode? That is, you press the "Play" button with STL, and then when then prompt opens, you choose "MO2 GUI"?  That is the correct way to launch games with MO2. The MO2 button on the main menu (which from the log, you might be using?) is only for modding. You aren't meant to launch games that way.

I don't use Flatpak Steam and thus don't use Flatpak STL, but if I recall I think some users were able to use MO2. If you are launching MO2 in Game Mode, then I'll ping the Flatpak maintainer and see if they have any insight here (though it's not a "Flatpak" issue and more a "SteamTinkerLaunch Flatpak" issue, given my lack of knowledge on Flatpaks they may have more insight here).

Good luck :-)

<hr>

Side note:

> Obviously I have to be running Steam to even launch STL itself

This came up very recently in #740, not 100% sure about Flatpak but STL can be ran from the command line without Steam :-) On regular systems, `steamtinkerlaunch settings` will open the settings menu. On Flatpak I'm not sure, maybe that works, or maybe it has to be something like `com.valvesoftware.Steam.Utility.steamtinkerlaunch settings`.

**Comment by sonic2kk** [comment]
Just tested (non-Flatpak ofc) and when running in MO2 Standalone Mode (with the main menu button), I get the same message you are seeing. But when launching from GUI mode, it works fine. Comparing my Standalone Mode log, it seems to match the log you attached, so perhaps this is just a case of needing to launch MO2 differently and is hopefully not some kind of Flatpak quirk.

The wiki also mentions that [Standalone Mode is not meant for launching games](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#standalone-mode), and tries to link to the Game Mode section but I just noticed a small formatting error that I'll fix now.

**Comment by SimplyTadpole** [comment]
Ah, sorry, I wasn't aware it would launch MO2 automatically this time - when I first ran NV with STL, it launched the main game automatically without letting me install MO2, so I thought it'd always launch the vanilla game. The wiki is rather overwhelming, so I'll admit I didn't really understand the difference between how these work ^^'

I launched it with the MO2 GUI as you mentioned, but the game still crashes. 
[Here's the new log file](https://github.com/sonic2kk/steamtinkerlaunch/files/10717258/steamtinkerlaunch.log), is this the way I'm supposed to launch the game and the issue is simply unrelated, or am I still doing something wrong?

**Comment by sonic2kk** [comment]
It looks like this is launched properly this time, there could still be a couple of things wrong though:
- You may need to run New Vegas once without SteamTinkerLaunch to make sure it generates its configuration files and, crucially, performs the correct setup of its DirectX related stuff
- More likely, there a lingering wineserver process on your system. This line in your log suggests it: `ERROR - startGame - Could not determine pid of '/var/mnt/Storage/Game Installations - Steam/steamapps/common/Proton 7.0/dist/bin/wineserver'` - Sometimes Wine/Proton processes are not properly killed (I experience this a lot outside of Steam with regular Wine, but rarely with Steam, though it has happened before, see #730). You may need to search for and manually kill a rouge `wineserver` process. A reboot should also properly kill it.

And of course as well, try launching without any mods if you have them enabled, to make sure this isn't an issue brought on by mods etc :-)

<hr>

> The wiki is rather overwhelming, so I'll admit I don't really understand the difference between how these work ^^'

Heh yup, such as Linux gaming :-) The long and short is that "Standalone Mode" means you don't need Steam (e.g. you can mod without your hour counter going up, as per #740) and that you can more reliably mod several different MO2 game instances. Standalone Mode runs MO2 in its own dedicated prefix instead of the game's prefix, which is why MO2 can't see that Steam is running (and New Vegas is probably crashing for DRM-related reasons here I would guess). Standalone Mode can also use a custom Proton version, whereas Game Mode will always use the game's Proton version. The Standalone Mode Proton version can be configured from the Global Menu.

Game Mode runs MO2 in the game's prefix and is used for running the game through MO2.

**Comment by SimplyTadpole** [comment]
How can I run New Vegas without STL *without* losing my STL prefix and all the mods and configurations I've already done?

And unfortunately I haven't found any wineserver process, I'll try to see if rebooting will fix it.

**Comment by sonic2kk** [comment]
> How can I run New Vegas without STL without losing my STL prefix and all the mods and configurations I've already done?

Just don't select SteamTinkerLaunch as the compatibility tool. I don't see how mod configuration would be lost here? The SteamTinkerLaunch configuration and mods don't go away if you stop using SteamTinkerLaunch for a game.

If you're worried about saves etc, you only have to open New Vegas to the point where it reaches the launcher. Then you can close the launcher and re-run New Vegas and SteamTinkerLaunch.

**Comment by SimplyTadpole** [comment]
That seems to have done the trick, the issue all along was that I needed to launch it with regular Proton first to have it properly install the Visual C++ and DirectX runtimes properly. Thank you for your patience and advice, and I'm sorry for taking up your time.

**Comment by sonic2kk** [comment]
Woohoo, I'm glad it's working! Enjoy your journey through the wastes :-)

> I needed to launch it with regular Proton first to have it properly install the Visual C++ and DirectX runtimes properly

Sometimes this even fails with GE-Proton. I honestly just blame Bethesda for this :sweat_smile: 

> Thank you for your patience and advice, and I'm sorry for taking up your time

Not at all, it's part of what I'm here for :-) Thanks for sticking with me and troubleshooting, enjoy!
