### ISSUE TITLE
STL not launching games after first successful run

### ISSUE THREAD

**Issue by masterovhell** [sonic2kk/steamtinkerlaunch#745]
I'm honestly not sure if this is the right place to post this, or if there is something really simple I'm missing. But this is the only software that I found that allows me to do what I want, so I really want it to work. Thanks for any help.

System Information:
OS: Devuan GNU/Linux 5.0 (Daedalus/Ceres) Debian Testing but w/o SystemD
STL Version: steamtinkerlaunch-v12.0
Installation Method: ProtonUp-Qt, previously Manual Installation but still the same issue.

I've gone through the ProtonUp-Qt installation, gotten everything up and running to the point of launching one of my games, The Ascent through STL and it works perfectly. I launched it with a game trainer, a .exe file that I set to run the custom command section of the Game Menu. I checked "Use Custom Command" and "Fork Custom Command" and then set the .exe trainer to run in the custom command box.

Here's the main issue now. Upon running the game for the first time, post installation it works. The trainer runs alongside the game and everything runs perfectly. However, after closing the game and trying to open it again, all with the same configuration, the game crashes after about 4-5 seconds. If I click play again with the same settings or retry with different settings, the game starts running, but nothing shows up. YAD appears to be running in my taskbar, but no game or trainer ever runs. I have to kill the game by clicking stop in Steam in order to make changes again.

This then also seems to be the case with other games if I set them to run with STL. I tried to get Besiege to run with it just as a test and it's the same thing, the game doesn't do anything after the first STL launch and them close afterwards.

It seems after the first overall run of STL, the entire thing breaks as a compatibility tool and just refuses to work.

Thanks for any and all help, I appreciate it.

**Comment by masterovhell** [comment]
I found it. I guess it was something simple.

Me doing some extra "tinkering" lol would've helped.

Not sure if it's a feature, but STL removes the proton version to launch with after the first launch, so the game just sat doing nothing. Had to re-check the proton version I run, and reselect the trainer for the custom commands and everything is working again.

I was under the complete impression that every setting was saved once I set them, guess not. But I'm completely okay with this, as long as it all works lol. If this means I have to set my games every time to the way I want, that's fine. It takes like 10 seconds for me.

Even though nobody responded, thanks for making this software. It's the solution to game trainers on Linux.

Much appreciated.

**Comment by sonic2kk** [comment]
Didn't get around to seeing this until now and only noticed because the closed issue count was higher than what I happened to remember :-)

Glad you got the issue sorted in the end, but there was one thing I wanted to comment on.

> Not sure if it's a feature, but STL removes the proton version to launch with after the first launch

It should not and I have never experienced this. STL should save the settings for each game. I haven't encountered a scenario where it doesn't. It sounds like for some reason your SteamTinkerLaunch settings are not being saved, which could be the result of various things but perhaps STL does not have permission to write out to the settings file for your game.

SteamTinkerLaunch saves configs to `~/.config/steamtinkerlaunch/gamecfgs`. Inside this folder are `id` and `title` folders. The `id` folder stores the "real" game configs based on AppID (e.g., `70.conf`). Then the `title` folder is a symlink which uses the game title so that it's easier to locate game config files (e.g., `Half-Life.conf`).

I would check the permissions for these folders in case, for some reason, STL cannot write here. You seem to have a unique setup at least compared to other users who have posted, so it is possible STL may require some tweaks to save correctly on this Debian-spinoff(?) or your specific configuration of it. If we can get to the bottom of this and it turns out to be an STL quirk that needs addressed for this scenario, I can look into it!

It may be worth running SteamTinkerLaunch from the command line and checking for any strange output related to permissions. If you run `steamtinkerlaunch settings <app_id>` it will open the settings menu for that game outside of Steam. Then you can go into the Game Menu, tweak various settings, and save them. Perhaps if there are permissions issues, these will be noted in some Bash errors/warnings in the terminal.

If you don't know the AppID, you can search for it with `steamtinkerlaunch gi "game name"`.

You can also look in `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log` and see if there are any logged warnings about file permissions or incorrect paths to save/load the config file for that game. It might say that it can't find it, or read it, or when saving maybe it can't write out to it. 

If you have the chance I would be really interested to know if something is going on here, because STL absolutely should be saving configs :slightly_smiling_face: 

> Even though nobody responded, thanks for making this software. It's the solution to game trainers on Linux.

I see a lot of people using these "trainer" programs, I still don't fully understand what they are or why people use them, but they seem to be a common use-case for STL so that's a good thing in my mind.

Also, I was asleep when this issue was posted, and it is pretty much only me that responds to issues, which is why there was no response in the brief window that this issue was opened.
