### ISSUE TITLE
Steam Deck installation instructions do not include adding steamtinkerlaunch to PATH

### ISSUE THREAD

**Issue by MustacheEmperor** [sonic2kk/steamtinkerlaunch#750]
[The Steam Deck installation instructions](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#steam-deck) mention that ProtonUp-QT will add steamtinkerlaunch to PATH for you, but the instructions to install without ProtonUp-QT don't mention adding it to PATH. The instructions direct you to do something that will not work, because steamtinkerlaunch isn't in PATH. 

5. From here, you can run ./steamtinkerlaunch. You can simply type ./steamt and press "Tab" to autocomplete (either with a physical keyboard or your on-screen keyboard)
6. Wait for the script to finish, and then run steamtinkerlaunch compat add to ensure SteamTinkerLaunch is added as a compatibility tool in Steam.

Without adding it to PATH after step 5, step 6 will fail as `command not found.`

**Comment by sonic2kk** [comment]
Steps 5 and 6 are intended to be ran from the directory of the SteamTinkerLaunch, as made obvious by the `./steamtinkerlaunch` - `./steamtinkerlaunch` will fail regardless of whether SteamTinkerLaunch is in your PATH or not with a file not found error because there's no script to execute with `./`. Though Step 6 on the wiki forgets the `./`, I will fix that after this post. In general, this will work.

The steps for a manual non-root install explain how to add SteamTinkerLaunch to PATH, so I will update the wiki to direct users to that.

Also, if you missed it, there is a dedicated issue for suggesting improvements to the wiki: #457.

**Comment by sonic2kk** [comment]
Wiki has been updated, let me know if this solves the issue.

**Comment by MustacheEmperor** [comment]
Aha, thank you - I was just about to suggest an edit myself, but this covers it!
