### ISSUE TITLE
If Hedge Mod Manager fails to execute, pipe output to console

### ISSUE THREAD

**Issue by biggestsonicfan** [sonic2kk/steamtinkerlaunch#755]
## System Information
- SteamTinkerLaunch version: 12.0
- Distribution: OpenSUSE Tumbleweed

## Feature Description
Basically if SteamTinkerLaunch is started with the `hmm` flag, and `hmm` fails at any point, all Proton output isn't piped back to the console, giving very little debug information to go off of to try to resolve. Currently I'm having issues where .NET 4.8 install via protontricks isn't properly installing the 'System.Windows.Controls.Ribbon' module, SteamTinkerLaunch silently fails with no info piped to console or logs.

I'm also encountering an issue where instead of Hedge Mod Manager being downloaded to `~/.config/steamtinkerlaunch/downloads/hedgemodmanager`, the game's prefix is copied to it.

**Comment by sonic2kk** [comment]
The prefix issue you mentioned sounds strange, not sure why it would do that.

Various debugging information can be found at `/dev/shm/steamtinkerlaunch` particularly for DotNet48 installation failing. My recommendation is to try and install dotnet48 with Proton 5.0, as noted on the wiki. Sadly dotnet48 issues with Proton/Wine are very common.

Please feel free to open a PR to pipe the output or log any further information if you have a specific way in mind for it that you think would be useful :-) All improvements to STL's HMM support would be very welcome. If you're unable or just don't want to that's of course fine, I can look into it when I have a moment, but just letting you know that if you have any implementation ideas or further improvements to logging then you are absolutely welcome to contribute if you're able and willing !

**Comment by biggestsonicfan** [comment]
I did the Proton 5.0 trick as mentioned via [this guide](https://linuxgamingcentral.com/posts/updated-sonic-frontiers-steam-deck-modding-guide/), but I could always only get HMM running and not Frontiers, or Frontiers running and not HMM. Now I can't seem to get either following the same guide :fearful:

I'll take a look at the code in a bit and see if I can't spot where I can insert anything useful.

**Comment by sonic2kk** [comment]
I wonder why that was the case, it seems like dotnet48 is just very unreliable under Wine :frowning: Even in my own experience over the years, dotnet48 in particular has always been a real annoyance. It worked during my tests across two machines, and all STL does is run the Winetricks commands for the relevant prefixes (and Winetricks just tries to make it more convenient to run the installer with the given Wine version/prefix parameters), so I would say something is going wrong on the Wine side with installation for some reason.

I appreciate that you're taking the time to investigate the problem, this is the kind of attitude I love to see from the community, and the willingness to contribute is also great! I wrote that reply very late last night so I hope I didn't come across wrong, I just wanted to let you know that you're absolutely welcome to contribute here to get an implementation that you think will be helpful for debugging (as I don't have too much experience in the area of what Wine output might be helpful).

Relevant HMM code can be found between the `### HEDGEMODMANAGER (HMM) BEGIN` comment and `### HEDGEMODMANAGER (HMM) END`. It does make use of a couple of already existing STL functions written long ago (like `installDotNet`), but the core of the HMM code is between those comments. Another helpful way to get around the code is to search the langfiles (like `lang/english.txt`) for a given string, and copy the variable name e.g. `NOTY_HMMDL` and doing a Find in the code for it. I recognise STL is rather... large, and it is a focus I have for this year to try and trim it down as best as I can (aiming for < 20k lines, some variable cleanup, etc), so hopefully those tips can help you navigate around. At least that helped me when I started contributing to STL about a year ago, and as maintainer now it still helps :-)

**Comment by biggestsonicfan** [comment]
Well I've been locked out of testing for 24 hours thanks to Denuvo, but it seems I was able to diagnose a few things:

- SteamTinkerLauncher was failing to point to the `compatdata` dir for Frontiers, even though starting hmm with SteamTinkerLauncher _set up_ for "Frontiers" specifically. This is why SteamTinkerLauncher was creating it's own prefix for hmm, because it wasn't recognizing the Frontiers compatdata dir. Managed to fix this by manually assigning it before the first "./steamtinkerlaunch hmm start".
- SteamTinkerLauncher seems to lack any wine piping that I'm aware of. Manually installing `dotnet48 d3dx9 vcrun2019 d3dcompiler_47` with Protontricks reveals a _lot_ of output, including a lot of _useful_ output if it fails. SteamTinkerLauncher again will just fail silently and you can only assume everything was done correctly. So the hmm not giving output when it fails as well is part of a bigger problem. 

My proposal is the addtion of a --debug flag to pipe any and all wine output to the terminal of which SteamTinkerLauncher is being run at. Right now it appears that it just silently runs _any_ child processes in the background?

EDIT: It appears that with a fresh Wine prefix without `dotnet48` gives the same "System.Windows.Controls.Ribbon" error as I was encountering when following the guide and `dotnet48` installed correctly. Something's clearly going wrong in the pipeline there. I will continue to investigate.

**Comment by sonic2kk** [comment]
No rush on any of this, I appreciate the investigation!

> SteamTinkerLauncher again will just fail silently and you can only assume everything was done correctly. So the hmm not giving output when it fails as well is part of a bigger problem.

I'm fairly sure the Winetricks output at least for `dotnet48` is redirected to `/dev/shm/steamtinkerlaunch`, I have been able to see some dotnet failures here such as missing `ngen.exe`. There's the possibility that there's a way to get more output here and I'm open to it for sure. The Winetricks log may be present in `/dev/shm/steamtinkerlaunch` but I'm not sure how persistent it is, it may only show the most recent Winetricks execution that wasn't DotNet.

In any case, I think the `--debug` flag is a really good idea. That way all the output can be displayed in the terminal. Showing this to a "regular" user by default would likely cause more problems than it would solve in my opinion, so having a user go out of their way to enable it makes the most sense to me. Definitely in favour of adding this, at least for HMM specifically. Adding it globally to STL is something that could be considered in future, but it may be overkill for right now. I can think of a few places where displaying/storing Wine output might be useful (custom commands) but in some others I think it should already be present (Vortex, MO2). And for games, there is already a Proton log.

As for piping other Wine output for HMM by all means I'm open to this as well. Probably at the very least we can pipe the HMM exe output. If there are other places you feel could use improvement for HMM please don't be afraid to suggest :-) I basically want to avoid a "partial" solution, I want to ensure as much good debugging information can be properly either displayed or logged or both.

The error you're mentioning is certainly interesting, I don't recall seeing it before so it's possible something has changed somewhere (maybe wine, hmm, some additional Winetricks are not required, not totally sure). I appreciate all the time you've put into this, let me know if you need anything from my side to help troubleshoot further / implement some improvements here :-)

**Comment by sonic2kk** [comment]
Also as for the prefix related issue, SteamTinkerLaunch should be creating its own prefix for HMM, but it should do it at `~/.config/steamtinkerlaunch/hedgemodmanager/compatdata`. It installs `dotnet48` and some other Winetricks there, then `dotnet48` per-64bit-game that is currently installed.

**Comment by biggestsonicfan** [comment]
> Also as for the prefix related issue, SteamTinkerLaunch should be creating its own prefix for HMM, but it should do it at ~/.config/steamtinkerlaunch/hedgemodmanager/compatdata. It installs dotnet48 and some other Winetricks there, then dotnet48 per-64bit-game that is currently installed.

But why? :thinking: Should hmm not piggyback off the game's prefix if those dependencies would be required per-game anyway?

**Comment by sonic2kk** [comment]
Only `dotnet48` is required per game, which is why HMM has its own prefix. Some winetricks required for HMM have also historically broken games, e.g. `d3dcompiler_47` used to break some games. It's best to only install the required Winetricks for the games that require them.

`d3dcompiler_47` is installed for Sonic Generations as this used to be required for the D3D11 mod but this is no longer the case and will be removed for the next STL release. This is the only shared dependency between HMM and its games that I can think of.

32bit games don't require any additional Winetricks, 64bit games unfortunately require `dotnet48` because of some incompatibility with the 64bit games' mod loaders and Wine. HMM instead requires several Winetricks to work: `dotnet48 d3dcompiler_47 d3dx9 vcrun2019`.

There is also the case where HMM does not run in a game's prefix. HMM should not actually *ever* run in a game's prefix, it runs in its own prefix. It's used standalone outside of games to install mods using either `steamtinkerlaunch hmm start` or the Application Menu entry.

**Comment by biggestsonicfan** [comment]
Forgive my misunderstanding here, but how does hmm _pass mods_ across prefixes then?

EDIT: We're also investigating if `dotnet48` isn't actually required at all, and the only dependency that isn't satisfied by mono is `system.windows.controls.ribbon`, as it's only a WPF GUI dependency. Research is preliminary, but it'd be nice not to bloat prefixes with dotnet if it's not required.

**Comment by sonic2kk** [comment]
> Forgive my misunderstanding here, but how does hmm *pass mods* across prefixes then?

I'll try to explain a little better :-)

When you install a mod with HMM, it gets moved into a mods folder in the game's install folder. HMM itself does this, not SteamTinkerLaunch. We don't do anything to manage settings mods here. HMM's modloader for that game (which it installs itself independent of STL once again) manages looking for and loading mods once you run a game. The modloader is actually a DLL named `d3d11.dll`, which is what actually loads the mods.

The mod files themselves are stored in the game folder. For Sonic Frontiers, HMM puts mods at `/path/to/steamapps/common/SonicFrontiers/Mods/<ModName>`. There are also some DLLs in here which the modloader looks for like the `Codes.dll` for cheats.

STL doesn't do anything aside from install the required components to run HMM, which is the Winetricks described, and installs `dotnet48` for each installed 64bit game that requires it.

Hope that makes a little more sense, there's no STL-specific stuff going on here when it comes to actually installing mods. That's all HMM behaviour. Mods aren't passed across prefixes at all.

> EDIT: We're also investigating if `dotnet48` isn't actually required at all, and the only dependency that isn't satisfied by mono is `system.windows.controls.ribbon`, as it's only a WPF GUI dependency. Research is preliminary, but it'd be nice not to bloat prefixes with dotnet if it's not required.

For HMM itself, this could very well be the case and that would definitely be great to reduce bloat for HMM itself - `dotnet48` is like almost a gig I think :sweat_smile: It would be great to reduce this on Steam Deck in particular.

But for the 64bit modloaders, `dotnet48` is probably going to be required until Wine implements whatever is missing. I don't know exactly what it is that's missing though, perhaps it is something "light" as well like the ribbon component, but I am not sure :sweat_smile: I remember some discussion around the main required component being `mscoree.dll`, however from what I recall:
- This didn't solve the issue for every user. Some users only needed `dotnet48`, some only needed `mscoree`, some needed both, and for some neither worked (though a *lot* of users reported blank issues and/or did not follow up at all)
- Most `mscoree.dll` sources I could find (understandably) did not allow redistribution, so STL could not automatically download this DLL.

Maybe that'll be a hint though :-)

**Comment by biggestsonicfan** [comment]
Interesting. So HMM is just a _frontend_? Then perhaps a linux-native frontend should be made to handle the setup to load the mods. Or even a light command-line version that doesn't require WPF.

**Comment by sonic2kk** [comment]
> Interesting. So HMM is just a frontend? Then perhaps a linux-native frontend should be made to handle the setup to load the mods. Or even a light command-line version that doesn't require WPF.

I think the devs have mentioned this before, because yup it's just a frontend. I think there is/was interest creating a native Linux frontend. I don't see why it wouldn't be doable but it isn't something that STL itself should do imo. I think there's a cross-platform UI framework called Avalon that there was some talk about using (I think the Ryujinx emulator also wants to use this as well?).

Not totally sure about a command line version but I don't see why it also wouldn't be possible.

**Comment by biggestsonicfan** [comment]
I definitely agree that it falls out of the STL scope, no doubt. But I also feel that giving a _frontend_ it's own prefix is just bloat, especially if you're trying to have multiple games on something limited like a Steam Deck. I also don't see any reason why a singular mod manager would have to be cross platform. Two mod managers could exist maintained by respective operating system users to better maintain the "look and feel" of their environments. No sense in trying to maintain something cross-platform if the devs can only offer limited support for the other platform, especially given how ever-evolving the linux ecosystem is.

I looked at some of the source of hmm and it looks like some command line options are supported? I don't know the full extent, however.

**Comment by sonic2kk** [comment]
> I definitely agree that it falls out of the STL scope, no doubt. But I also feel that giving a frontend it's own prefix is just bloat, especially if you're trying to have multiple games on something limited like a Steam Deck

I disagree, while it is a "frontend" it's a standalone application and so should run independently of games in its own prefix. Not to mention the fact that it requires several Winetricks not solely limited to `dotnet48`.

Even when an application does not need specific Winetricks it also runs in its own prefix. ModOrganizer 2, Vortex, and Depressurizer each run in their own prefixes. Cheat Engine also ran in its own prefix before it was removed. There's a reason Steam games each have their own prefix, why Lutris gives games their own prefixes, and why Heroic Games gives games their own prefixes. The same logic should apply to standalone applications.

Relying on a game prefix is not a good idea imo to begin with, it removes the flexibility to run HMM independently of a game, which is how it is used.

> Two mod managers could exist maintained by respective operating system users to better maintain the "look and feel" of their environments. No sense in trying to maintain something cross-platform if the devs can only offer limited support for the other platform, especially given how ever-evolving the linux ecosystem is.

Indeed, I would agree with this, though feature-parity and expanding the dev team for a single, unified mod manager is what I would consider the best solution, in my armchair opinion. If a Linux build crops up in one way or another it would remove the need for HMM support in SteamTinkerLaunch and it seems like that will eventually happen, but in the meantime I'll do my best to keep the support here as best I can.

> I looked at some of the source of hmm and it looks like some command line options are supported? I don't know the full extent, however.

Yes, that's how it parses URLs for the One-Click GameBanana integration. Other options may be supported but I can't remember, it's been a few months since I looked at the code.

**Comment by biggestsonicfan** [comment]
> I disagree

Nono, you misunderstand, I didn't mean to say a separate prefix for the frontend was bad, I meant that having a wine prefix for just a frontend _instead_ of a native linux frontend is bloat comparatively. A 500kb executable would be much nicer than an entire Wine prefix for something that's essentially a gui for configuration.

**Comment by sonic2kk** [comment]
Ahh, in that case you certainly have a point. If there was a native executable it would be a *huge* improvement in that regard. Just one more benefit to having native tools :-)

**Comment by biggestsonicfan** [comment]
![Screenshot_20230307_151847](https://user-images.githubusercontent.com/9744201/223576833-c84a0121-5d68-45bb-93cc-b7ac178c6c4c.png)

One of the big issues with stl not having any output is something like this. Not all wine versions support command line Windows version switching, and it tells you which Windows version to switch to in the console.

In order to know what version I have to properly set it to, I need to open `/dev/shm/steamtinkerlaunch/WINETRICKS.log` and I see that the last lines are installing `vcrun2019`, then I head to the Winetricks source to see what it's trying to set it to:

https://github.com/Winetricks/winetricks/blob/50bf014e12fd97cefc29e36441aa7bbe4b6f83fa/src/winetricks#L13013

Alright, so I set it to Windows XP. The install proceeds until `ucrtbase2019`, which the log this time shows `win7`

So I'm _guessing_ perhaps the `--debug` flag would just be a condition within whatever writes the log files to also display to console? Would that be the best bet?

On a side note for testing, I commented out installing `dotnet48` for hmm, but it still seems to have force installed it. I wanted to test the ribbon dll.

EDIT: It appears no logging is done when hmm fails though, which I guess is the point of this issue:
```
Tue Mar  7 03:30:29 PM PST 2023 INFO - startHMM - Starting HedgeModManager in prefix '/home/rob/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx' with Wine '/home/rob/.local/share/Steam/steamapps/common/Proton 5.0/dist/bin/wine' and using executable at '/home/rob/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe'
Tue Mar  7 03:30:32 PM PST 2023 INFO - stlCleanup - Ensuring tray icon is definitely removed
Tue Mar  7 03:30:32 PM PST 2023 INFO - stlCleanup - Closing SteamTinkerLaunch
```
Again it failed, and I assume it's due to the `ribbon.dll` not being there.... and nope... time for more debugging!

EDIT2: using `WINEPREFIX="/home/rob/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx/" wine "/home/rob/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe"`, I was able to launch hmm for the first time, as the Wine setup menu appeared this time. I thought upon a successful configuration, hmm would start the next time on it's own, but again, `./steamtinkerlaunch hmm start` silently fails.

**Comment by sonic2kk** [comment]
> So I'm *guessing* perhaps the `--debug` flag would just be a condition within whatever writes the log files to also display to console? Would that be the best bet?

There isn't really any sort of code like this in STL, log files for Wine executions are written out with something along the lines of `<wine_command_stuff> 2>&1 | tee "$STLSHM/LOG_FILE_NAME.log"`. There is no standard way for writing out logs, aside from the main `steamtinkerlaunch.log` which uses `writelog "TYPE" "${FUNCNAME[0[} - Message"`.

So for a `--debug` option there would need to be some conditional checks most likely. Something like:

```bash
# Somewhere in some HMM argument parsing logic we would check for a `--debug` flag being passed in and set a HMMDEBUG var 
if [ "$HMMDEBUG" -eq 1 ]; then
    # run debug version of command with logging/terminal output/both?/etc
else
    # run regular command
fi
```

> On a side note for testing, I commented out installing `dotnet48` for hmm, but it still seems to have force installed it. I wanted to test the ribbon dll.

Make sure you're using a fresh prefix and definitely running your updated version of the script. The code to install `dotnet48` for HMM itself is located in `installHMM`. You'll want to comment the following lines:

```bash
writelog "INFO" "${FUNCNAME[0]} - Installing dotnet48 for $HMM"
installDotNet "$HMMPFX" "$HMMWINE" "48" "HMMPREFIX" "X"  # 'X' here is to enable the experimental '--force' parameter
writelog "INFO" "${FUNCNAME[0]} - Done"
```

The log lines are not explicitly necessary to comment out but may make the logs a bit nicer to sift through.

Speaking of, looking at the log line you gave, you're probably using STL v12.0 (since it still mentions removing the tray icon). You might have an easier time working from master, but it's not absolutely necessary :-)

> using `WINEPREFIX="/home/rob/.config/steamtinkerlaunch/hedgemodmanager/compatdata/pfx/" wine "/home/rob/.config/steamtinkerlaunch/downloads/hedgemodmanager/HedgeModManager.exe"`

This is not the same command STL uses, this is using your system Wine and not the one you've selected with STL (STL does allow you to select system Wine in some scenarios, but not for HMM at least not out of the box). This could be why STL is "silently failing".

In `startHMM`, you could remove the `&>/dev/null` from the start command `WINEDEBUG="-all" WINEPREFIX="$HMMPFX" "$HMMWINE" "$HMMEXE" "$HMMARGS"`. That may get it to show some output in the terminal. However to get it to log with something like `tee "$STLSHM/startHMM.log`, since that redirects the output it may not actually show it. So solving both of these issues is something we'll need to consider.

**Comment by biggestsonicfan** [comment]
> There isn't really any sort of code like this in STL

Big oof

> Make sure you're using a fresh prefix and definitely running your updated version of the script.

I was and I was. I will try again later.

> This is not the same command STL uses

Yeah I just realized that. I was editing my comment as you replied.  The guide said to first-run hmm on 5.0-10 so the command would be `STEAM_COMPAT_DATA_PATH="/home/rob/.config/steamtinkerlaunch/hedgemodmanager/" WINEPREFIX="/home/rob/.steam/steam/steamapps/compatdata/1237320/" "/home/rob/.local/share/Steam/steamapps/common/Proton 5.0/proton" run "/home/rob/.steam/steam/steamapps/common/SonicFrontiers/HedgeModManager.exe"` however I'm going to have to regenerate the prefix, lemme try the updated script again.

**Comment by sonic2kk** [comment]
> The guide said to first-run hmm on 5.0-10

I haven't read it in-depth and not in a long time but this is not correct exactly. The command you gave is correct for installing dotnet48, but that will not launch HMM, as HMM cannot be launched with Proton 5.0 at least in my experience. You need to use a more up-to-date Proton version.

> Big oof

This is not constructive. Open a PR if it upsets you so much.

**Comment by biggestsonicfan** [comment]
> I haven't read it in-depth and not in a long time but this is not correct exactly. 

Here is a [link to the current guide](https://linuxgamingcentral.com/posts/updated-sonic-frontiers-steam-deck-modding-guide/). (Which was mentioned [earlier in this issue as being 5.0](https://github.com/sonic2kk/steamtinkerlaunch/issues/755#issuecomment-1454696572))

> This is not constructive. Open a PR if it upsets you so much.

This doesn't upset me at all, it just would have made the console output much easier to implement in my opinion. My original pitch was just to implement a `--debug` check within a logging function, but you are saying no such logging function. "Big oof" was equivlant here to "Oh well then I guess we can't implement it that way". I understand it's not constructive, but there's no need to be hostile. I will now hold back from using any unprofessional slang in this issue.

I am trying to work through this as best I can, updating you with what I am encountering along the way in an attempt to be helpful, but if it's not helpful then I might as well just close the PR.

**Comment by sonic2kk** [comment]
The guide seems to call out that a newer version of Proton should be used to run HMM towards the bottom, so all is fine there.

> but you are saying no such logging function

Yes, because we're working with Bash, and outputting to a file is just a case of redirecting output, examples of which are littered around the codebase (Ctrl+F for `2>` or `| tee`, where `tee` is a command that can be used to write output to files, and so there is no need to reinvent the wheel. `writelog` is an explicit function because it writes out the date, log type, etc.

It isn't a case of "professional language".

> but if it's not helpful then I might as well just close the PR

It is interesting to see but the initial suggestion, to show terminal output for a failed HMM launch, could be solved I think by removing the `&>/dev/null` from the HMM start command. The debug option is something that could be implemented but it might just be straightforward to redirect the output to a file in `/dev/shm/steamtinkerlaunch`. It's probably easier to look through a file anyway when debugging. We can also output to a file without the need for any flag checking.

**Comment by biggestsonicfan** [comment]
I see and understand that, but in the case of simply omitting critical information to the user, such as no logging or output completely, this is also "not constructive" for debugging purposes.

> to show terminal output for a failed HMM launch, could be solved I think by removing the &>/dev/null from the HMM start command.

I agree, that would definitely be a solution here, but for things like the installation of `vcrun2019` under 5.0-10, I still feel a pipped output flag would be useful. We don't have to reinvent the wheel for a logging function, but we could add conditional check at each of these pipes checking for a `--debug` flag? It could simply pipe logging to the console and a user could save the console's output if they really wanted to keep that log, and wherever output was piped to null could pipe to the console with this flag. Does that sound reasonable?

**Comment by biggestsonicfan** [comment]
Initially reported issue solved. Closing.

**Comment by sonic2kk** [comment]
> such as no logging or output completely, this is also "not constructive" for debugging purposes.

Indeed, which is what this issue is about solving.

> but for things like the installation of `vcrun2019` under 5.0-10, I still feel a pipped output flag would be useful

I am a bit torn. I think logging it, definitely, is useful, though I am not totally sure about showing it in the terminal. Logging it unconditionally in `/dev/shm/steamtinkerlaunch` would be a lot less work and follow convention of other parts of STL. SteamTinkerLaunch does log winetricks output here to `WINETRICKS.log`, though it may get overwritten. You should check this file and see if it shows output for each installed Winetricks or if it only shows the most recent one. Since it uses `>> "$WTSHMLOG"` I would assume it just appends to this file each time a new Winetricks command is executed.

The relevant code is in `installWinetricksPaks`, which is what gets called to install various Winetricks (not just for HMM either). It doesn't show the dotnet installation as this uses a separate function, `installDotNet`.
