### ISSUE TITLE
My Documents Symlink

### ISSUE THREAD

**Issue by KenJyn76** [sonic2kk/steamtinkerlaunch#770]
- steamtinkerlaunch-v14.0.20230319-2
- Distribution: Arch Linux

## Feature Description
Using Wine-GE on Heroic, I noticed that it symlinks the My Documents folder to my Documents folder in my $HOME, so that games can see each others' saves. Can this be added as a symlink option in steamtinkerlaunch? It's useful for games like Mass Effect or the Witcher, which can import saves from the previous game to preserve your choices across the series.

It would also make other use cases easier, such as running Vortex to manage a game that is installed in a different prefix. Without it, Vortex complains that you haven't run the game to create the correct ini files.

Thanks

**Comment by sonic2kk** [comment]
Sounds like it could be straightforward enough :-) Thanks for the suggestion!

Which "My Documents" folder are you referring to? Is it for each prefix? If you could give an example command of what you would run to do this manually I can take a look at implementing it.

**Comment by KenJyn76** [comment]
In my case, since Heroic uses my account name as the Prefix username, the Documents/My Documents folder is a symlink to $HOME/Documents. So, for example:

`/Games/Heroic/Prefixes/Fallout New Vegas Ultimate Edition/drive_c/users/liam/Documents`

is a symlink to /home/liam/Documents.

`ln -s /home/liam/Documents /Games/Heroic/Prefixes/Fallout New Vegas Ultimate Edition/drive_c/users/liam/Documents`

would create this link. I'm not really sure what determines if a prefix has My Documents or Documents, I've seen both. Both can probably be created without issue, however.

**Comment by sonic2kk** [comment]
Thank you for clarifying that!

> I'm not really sure what determines if a prefix has My Documents or Documents, I've seen both

Interesting point! Inside the prefix, `drive_c/users/steamuser/My Documents` is a symlink to `drive_c/users/steamuser/Documents`, so I'll probably opt to have the symlink point here. I'm not sure if this is always the case but it seems to be for Proton anyway from the prefixes I investigated on my system.

<hr>

In terms of implementation, Proton will always create the `steamuser` user for the prefix. Wine will create it based on your system username. However, for compatibility purposes, it should also be possible to check the current username (`whoami`) and create the symlink to the documents folder for this user as well. My regular Wine prefix (`~/.wine`) only has `Documents`, so perhaps things like Proton or Wine-GE create the `My Documents` folder for game compatibility? Not sure, just speculation on my part.

Probably some generic function will be created for this, as `~/Documents` *should* always exist but a user may not have that folder. Likewise for some reason the prefix user(s) may be missing a Documents folder, so I'll do a check for this as well.

It seems like it should be straightforward enough. I will probably set this as a checkbox on the Game Menu. When unchecked perhaps the symlink could be removed, probably a backup of the `Documents` folder in the prefix will be made and then restored when the symlink option is unchecked. The option could possibly be added to the Global Menu as well as the Game Menu but this might be problematic, I think it's best to restrict it per-game.

> [Mass Effect] can import saves from the previous game to preserve your choices across the series.

Just out of curiosity as I am planning to do a playthrough of MELE soon, does this not work OOTB with Proton? I haven't heard anything one way or another, maybe for MELE it doesn't matter since they're all the same "game" and this only applies to the originals, but I am still curious :-)

<hr>

Working on implementing this, including some catching of possible edge cases. Should go ok, will try to make time over the weekend to get this added.

**Comment by sonic2kk** [comment]
Note to self: Will also have to document this on the wiki somewhere once implemeneted

**Comment by sonic2kk** [comment]
I have a branch with an implementation of this, but I'm not so sure it does what would be expected based on the link given. Maybe it does though and I am being silly :-) 

The command creates the symlink to the `~/Documents` folder inside the prefix Documents folder, so the realpath ends up being `pfx/drive_c/users/steamuser/Documents/Documents`. And this makes sense given the command, but I am not sure this actually resolves any issue?

![image](https://user-images.githubusercontent.com/7917345/229188001-b3f84c6a-1ace-4293-bc61-ff2dbbf1b562.png)

If the intent here is to *replace* the existing prefix Documents folder with the symlink, that would make a bit more sense, whereby the `Documents` folder in the prefix itself would be the symlink.

I would like to make sure I have the understanding correct here. This will also mean that any existing information in the `Documents` folder would be replaced with the prefix backup, and several Windows games (incorrectly) store game save information in the Documents folder. In fact, I have a suspicion that New Vegas might be one of those games, too.

<hr>

I am not totally sure what the intended functionality is after further development and thought. If you'd like you could share a screenshot of what the Heroic prefix looks like after it creates this symlink.

**Comment by KenJyn76** [comment]
It indeed would need to replace the Documents folder, so in fs it would should be ../steamuser/Documents pointing to ~/Documents. By default, no I don't believe Proton supports save imports. For the Witcher, at least, I manually had to copy my saves into the prefix for the next game, which is not the case  if it's installed via Wine-GE instead of Proton. 

Here's a screenshot of the properties of a Wine-GE Prefix.

![image](https://user-images.githubusercontent.com/12451581/229264588-670a0bf7-41c4-4e1f-bcd9-a0aca40b64da.png)


Thinking more on this, though, doesn't redirecting the steamuser folder accomplish this same thing? I have no way to test it at the moment, but  if ME or Witcher or any other game that needs to access each other's saves are linked to the same steamuser folder, that solves the issue. I think maybe I was overzealous in requesting this.

**Comment by sonic2kk** [comment]
> Thinking more on this, though, doesn't redirecting the steamuser folder accomplish this same thing? I have no way to test it at the moment, but if ME or Witcher or any other game that needs to access each other's saves are linked to the same steamuser folder, that solves the issue

I believe that would solve the issue as well yes, in a slightly different way :-) It means they have access to the full user folder of the prefix, which is not even necessarily a bad thing as it means games which store data in, say, `AppData` would have their data accessible.

That may already solve the issue here :-)

**Comment by sonic2kk** [comment]
Been a little over a week, did the steamuser symlink resolve the issue? :-)

You may already know but I have had a few "complaints" that when messing with the compatdata, save data gets moved too (just how it goes when working with Wineprefixes) so do take care here.

**Comment by sonic2kk** [comment]
Also found out that `winecfg` lets you do this.

![image](https://user-images.githubusercontent.com/7917345/232138311-35840aec-b763-46a7-abb7-097a0bad2d9a.png)

This is from Wine 8.5, but it should be available in older Wine/Proton builds.

Values in winecfg can also be written out to the registry per-prefix, so the approach taken here was unneeded to begin with.
