### ISSUE TITLE
Directx 11/3d acceleration error on steam deck

### ISSUE THREAD

**Issue by jmg3195** [sonic2kk/steamtinkerlaunch#772]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: SteamOS Holo (OS version 3.4.6 stable channel)
- Installation Method: ProtonUp-Qt

## Issue Description
So I'm trying to launch a game trainer on the steam deck with STL. This process hasn't ever failed until the last 2 days. What's weird is both of the games I've had issues with work fine without STL. So I'm not sure what's causing the error or how to fix it. I spent the last 2 days combing through the internet for help and nothing I've tried has worked. This is the error the 2 games have shown (this error is specific to launching the actual game .exe):

"Failed to initialize player
Details:
Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date drivers for your graphics card and have not disabled 3D acceleration in display settings. InitializeEngineGraphics failed"

## Logs
Attached is a screenshot of the error and 2 logs. 

The file titled "steamtinkerlaunchlog.txt" is the log located at:
/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log

The file titled "steamtinkerlaunch.log.for.specific.game.txt" is the log located at:
~/.config/steamtinkerlaunch/logs/steamtinkerlaunch/title/${GameTitle}.log
![DirectX 11 3D acceleration error](https://user-images.githubusercontent.com/51762894/228916325-6bacb711-cf5c-4b1c-884c-433b78c6fddd.jpg)
[steamtinkerlaunchlog.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/11114256/steamtinkerlaunchlog.txt)
[steamtinkerlaunch.log.for.specific.game.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/11114257/steamtinkerlaunch.log.for.specific.game.txt)

**Comment by jmg3195** [comment]
I just realized I only attached the logs for 1 of the 2 games. I would imagine that won't be a problem as the error on both games was exactly the same. If you do want the logs for the 2nd game I'm also happy to provide those :)

**Comment by sonic2kk** [comment]
I don't think this is a SteamTinkerLaunch bug, though I'm not sure why it only happens with STL. I recall a similar issue reported before with #532 and #564, but these weren't STL bugs.

Does this error only appear when launching the game with STL even with the custom command disabled?

Looking at the launch command it looks as though this is a Non-Steam Game being used with STL as the launch command is: `Final outgoing start command: '/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-53/proton waitforexitandrun /home/deck/Games (SSD)/Patch Quest/Patch Quest Build 10645359/Patch Quest.exe'`, and the AppID is `2267307546` - Though this game is available [on Steam](https://store.steampowered.com/app/1347970/Patch_Quest/) with a different AppID (1347970).

Does the game work in Desktop Mode or does it give the same error?

**Comment by jmg3195** [comment]
Yes this error only happens with STL. If I launch the non steam game with a random proton version they both launch and play fine. But the minute I change it to STL and pick the exact same proton version in STL that I tested the game with it does this. The game gives the error in both desktop mode and gaming mode. It is odd the AppID is incorrect. I wonder if I fix that if it'll change anything. I'll have to figure out where the steam_appid.txt is for these games and see if I can modify it to fix that issue. I still feel like that shouldn't cause the directX 11/3D acceleration error though but I could be wrong.

**Comment by sonic2kk** [comment]
Thanks for confirming.

> It is odd the AppID is incorrect. I wonder if I fix that if it'll change anything. I'll have to figure out where the steam_appid.txt is for these games and see if I can modify it to fix that issue

Is this the Steam version of the game though? This looks as though it's running as a Non-Steam game. The path to the game executable at least is not a Steam library folder path.

> I still feel like that shouldn't cause the directX 11/3D acceleration error though but I could be wrong.

Indeed, it's a strange issue. It could perhaps be a Wine prefix issue, maybe it's not pointing to the right place or something. But I don't know why this would be happening. If it's not pointing to a prefix with DXVK perhaps its falling over because of that, usually WineD3D is enough to get a game to boot but maybe not in this instance.

From a search I have seen several reports of users encountering similar issues with Bottles, and even a user saying they ran into it with a game on Steam with Proton, but I don't think I've ever encountered this.

The Wineprefix being pointed to is `/home/deck/.local/share/Steam/steamapps/compatdata/2267307546/pfx`. You could try removing it and then re-trying your game. If this folder doesn't exist in the first place though we may be onto something.

**Comment by sonic2kk** [comment]
~~I can't seem to get any Non-Steam Games to work with Steam *at all* at the moment - They don't open, and Steam doesn't allow me to force a compatibility tool. When running with SteamTinkerLaunch as a launch option (which is invalid usage for a Proton game, but I was just testing) it seems that Steam isn't passing any AppID or game information.~~

~~So I am unable to test Non-Steam Games on my side for the time being :frowning:~~

Reboot fixed it

**Comment by jmg3195** [comment]
You're correct it's a non-steam game .exe (added to my steam library). I did delete that pfx folder you mentioned and it worked! Thank you soooo much! I'm going to delete the pfx folder for the other game I'm having the same issue with and see if it also fixes it :)

**Comment by sonic2kk** [comment]
Oh interesting! I'm really glad to hear it! I wonder if perhaps the AppID was borked, or if maybe switching Proton versions or something caused the issue. Sometimes prefixes can get borked but I'm not sure how specifically it happened in this instance. It could've been anything, Wine can be temperamental like that :sweat_smile: 

If the other game is fixed too feel free to close the issue. You can find the path to the prefix in the log file, it's probably the fastest. It'll be in `/home/deck/.local/share/Steam/steamapps/compatdata/<the games appid>`. The AppID is a bit tricky to find for Non-Steam games but the STL log for that game execution should tell you :-)

As you correctly pointed out the AppID shouldn't really affect DirectX, but a borked prefix *could*. This is because in summary: A wine prefix is basically a contained "Windows environment" with a filesystem structure for games to write things out to (i.e. My Documents, AppData, etc) as well as crucially: DLLs. At a high level these are "code packages" which tell applications how to run, and they live in a Wineprefix (the `/home/deck/.local/share/Steam/steamapps/compatdata/<appid>/pfx` path). One of the DLLs stored here is for DirectX. Normally Proton will create a prefix that uses DXVK, which is an implementation of DirectX. By default, Wine (the project Proton is based on) uses something called WineD3D. It is possible that somewhere along the way, the DLLs for DirectX were messed up in some way. This is why removing the prefix would help, as it would create a new one that would have correct DLLs. It's also possible that other related DLLs somehow got messed up, not sure what else Wine needs for DirectX but maybe some display-related DLLs weren't created or got borked somehow or other (possibly a Steam client glitch).

This can happen occasionally with Wine particularly when switching between versions in my experience but I'm not totally sure how it happened in this case. Either way I wanted to try and give some background on why removing the prefix here may have resolved the issue :-)

> game trainer

I haven't ever used one of these "trainer" programs but I have heard of countless people using them with SteamTinkerLaunch. Not sure if the program already works for you but just a couple of tips I've gleaned from a few months of seeing people talk about them:
- Adding a delay between game start and the trainer start can be helpful - Some people have said the trainer needs a few seconds or more to fully start up before the game, or sometimes the game needs to start before the trainer. STL lets you set those values, just pointing out that it may be necessary
- Some trainers need Winetricks to work but that's probably specific to each program so I can't comment there - Just something to keep in mind though!

Good luck! :-)

<hr>

P.S. - If this fixes your other game, I'll make a note of this issue so if other users run into the problem I can remember that removing the prefix is a potential solution.

**Comment by jmg3195** [comment]
Sorry it took me awhile to get back to you so unfortunately it didn't work on the second game. The game "trainer" is just the program "Aurora" from cheat happens so I would've though deleting the pfx folder for the second game would've done the trick but sadly no. I will definitely try switching which program launches first and play with wait times as well and see if I have any luck lol.

**Comment by sonic2kk** [comment]
Does the second game give the same DirectX error?

**Comment by jmg3195** [comment]
Yep exact same error as the first game

**Comment by jmg3195** [comment]
Well scratch that it was giving that same error with WineD3D turned on (only reason I turned this on is it's required to initially set  up "Aurora". But after turning it off I don't get the error but the game is just a black silent screen so something else must be going on with this on ugh lol

**Comment by sonic2kk** [comment]
This sounds more like a Wine compatibility issue than a SteamTinkerLaunch issue then, but it's hard to say for sure. Are you also trying to run the second game with this trainer program then? It would be interesting to know if the game you're trying to run works "vanilla" without this trainer program.

<hr>

If I understand correctly, this is another game added to Steam as a Non-Steam game and being launched with STL. If that is correct, try enabling the Proton log for the second game in the STL game menu, and then run it. You can do this from Desktop Mode if you want to save from fiddling with STL within the GameScope session. From Desktop Mode you can get the log in `~/.config/steamtinkerlaunch/logs/proton/id`. You can then attach this log and a SteamTinkerLaunch log for your second game. The Proton log won't give output for the forked executable (in this case "Aurora") but it'll give output for your main game which was giving a DirectX error but now is just giving a black screen if I understand correctly?

The STL log isn't strictly necessary but it'll help me understand better what exactly the current situation is :slightly_smiling_face:

**Comment by jmg3195** [comment]
Yes I'm also trying to run this second game with Aurora as well interestingly enough it does work if I'm not using STL

**Comment by sonic2kk** [comment]
Just like the first game then, it works without STL but doesn't with STL. And even without this other program, it doesn't work with STL. I'd recommend to make sure you definitely deleted the right prefix, and then also to attach a SteamTinkerLaunch log and a Proton log of the game execution. I'm no Wine developer but I can have a look to see if anything immediately stands out as an issue.

**Comment by jmg3195** [comment]
I did test running it in STL without aurora and still shows a black screen. I really appreciate your help with all this :) I can imagine it's frustrating trying to help people fix weird issues 
[STL.log.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/11116528/STL.log.txt)
[2448426242.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11116529/2448426242.log)

**Comment by jmg3195** [comment]
I'm also positive I deleted the correct pfx folder (I deleted it several times) as I used protontricks to see what compat data folder belonged to the game

**Comment by sonic2kk** [comment]
> i  can imagine it's frustrating trying to help people fix weird issues

It's no worries, I'll do my best to help, plus non-steam games see very little testing so if there's an overlooked use-case it would be nice to know and try to fix something! I'm also curious myself to know why this specific game may not be working.

The logs you attached don't seem to be from a game launch, at least for some reason they don't have a launch command section where I can see what it's trying to launch. If you're seeing a black screen I would assume it launched correctly. Either way though it's not a big deal, I was mainly looking to see if there were any potential oddities in the path to the exe, which it looks like there's not.

I noticed the game here is running with Proton 7.0-6, you could try with a version of GE-Proton if you haven't already.

The logs attached don't seem to be a Proton log though. In the Game Menu there's an option to enable Proton logging, then after a game launch this file is stored at `~/.config/steamtinkerlaunch/logs/proton/id`. This is a log file created by Proton which gives output of the actual game launch with Wine, the rationale for giving this file is to see if there is anything Wine might be yelling about (i.e. a missing DLL or something).

It's highly unlikely but not impossible that this game could, for some reason, require the Steam Linux Runtime when running with Proton. The Steam client passes this, and STL does too for regular Steam games, but not for Non-Steam games if I remember correctly. Looking at the launch from the first game and from the Non-Steam Game I'm testing anyway it appears that it's not passing the SLR. The Proton log may give a hint, if it complains about missing media codecs or something...

**Comment by sonic2kk** [comment]
I created a new branch [`nonsteam-slr`](https://github.com/sonic2kk/steamtinkerlaunch/tree/nonsteam-slr) which allows the Steam Linux Runtime for Non-Steam games. I put it on a branch because this may have Unforeseen Consequences:tm:. You can install this branch of STL from ProtonUp-Qt by enabling Advanced Mode under its About menu, then choosing "SteamTinkerLaunch-git" and selecting `nonsteam-slr` as the version. You don't need to uninstall STL or anything, it'll automatically get overwritten. Rolling back is also just as straightforward as installing the regular stable again.

I am not so sure that this is whats causing the problem, but it's the only key difference I can think of between launching with and without STL :sweat_smile: 

EDIT: Screenshot for extra clarity

![image](https://user-images.githubusercontent.com/7917345/228979505-3016994b-5bb1-4f48-b9bf-9aaa0511edf4.png)

**Comment by jmg3195** [comment]
I'm assuming it's the 'proton log' option under 'steamuser redirect mode'? I checked that and ran the game again and then pulled the logs from that exact location ~/.config/steamtinkerlaunch/logs/proton/id
[2448426242.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11116697/2448426242.log)

**Comment by sonic2kk** [comment]
It's under "Proton options", and this is the setting, hopefully this makes it a little clearer :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/7917345/228981349-4b620dea-b24f-4a6a-b6a3-5e41c454f632.png)

The log should start with `steam-<appid>.log`. I wonder why there's a SteamTinkerLaunch log in that location, I don't think I've seen that.

This checkbox exports the environment variable `PROTON_LOG=1` which is built into Proton itself, STL just enables it and then sets the output directory for it ([Proton Readme table](https://github.com/ValveSoftware/Proton#runtime-config-options) of Proton runtime options).

**Comment by jmg3195** [comment]
I did also do the above steps in ProtonUp-QT and yup that's the exact setting I clicked am I supposed to change the 'Proton log dir' to something other than 'id'?

**Comment by sonic2kk** [comment]
The version installed from ProtonUp-Qt based on the logs looks like its from master and not from the new branch, it still points to `14.0.20230330-1` when it should be `14.0.20230331-1 (nonsteam-slr)`. The branch with that name can be selected from the dropdown in ProtonUp-Qt.

<hr>

You shouldn't have to change the directroy to something other than `id`, but you could try setting it to a different folder (maybe your home folder or something).

In Desktop Mode, does the game open a window at all? Like a window with just a blank screen?

**Comment by jmg3195** [comment]
Sorry I should've specified I installed the the nonsteam-slr but that was after I copied the log. Now with the nonsteam-slr version it opens and there's a square box in the middle of the black game screen that flashes a handful of times, then the game crashes and closes so doing something a little different now

**Comment by jmg3195** [comment]
In desktop and gaming mode it opens a black window with the game cursor. Now it's doing the flashing and crashing bit with the different nonsteam-slr STL version.

**Comment by jmg3195** [comment]
well I just deleted the pfx folder again out of curiosity and it launched and ran through most of the loading screens then crashed tried it a second time and same thing but hey the fact it's showing me the loading screens for the game is progress lol

**Comment by sonic2kk** [comment]
This is very interesting, it definitely sounds like some kind of game compatibility issue.

Try running the game without STL, and in the Steam launch options set `PROTON_LOG=1 %command%`. Then launch the game. You can use any Proton version that you know works with the game without STL :slightly_smiling_face: 

This will create a file at `/home/deck/steam-<appid>.log`. Attach this file and I'll have a look at it, in case Proton is doing anything strange here that STL might not be.

**Comment by jmg3195** [comment]
Another update I changed the proton version in STL to 7.0.6 again as that's what users on ProtonDB mentioned having success with and the game is working!

**Comment by sonic2kk** [comment]
Oh that's awesome news!! And this is with the SLR fix branch?

If you have the patience for it I would be curious to know if it's broken when you switch back to the stable STL v12.12. Basically that would be a good hint that the SLR is required for this game to work. I suspect that is the case from all of this but it would be interesting to confirm.

If you'd like to actually *play* your games that's fine and I can leave this open until you'd like to test. I will also see if I can test this game myself and if I can reproduce the behaviour.

I didn't realise the game required Proton 7.0-6, that was my fault so sorry about that :sweat_smile: I appreciate all of the patience and testing here, very glad the games are working now!

**Comment by jmg3195** [comment]
Yes it's working with the SLR fix branch :) I'm happy to test that out and let you know what happens, but will probably wait until I've played the game to be safe lol. I'd hate to break something again after all the time we've both spent. I really appreciate all your help! :)

**Comment by sonic2kk** [comment]
No worries, I am happy to help :-)

I usually try to leave issues open for a while before closing, just reply with a message once you get a chance to test. I will also do my own testing and experimenting. Feel free to even send a message saying you still plan to test but haven't gotten around to it. I usually close inactive issues after around 2 weeks if there is pending resolution after a significant discussion.

Thanks! Happy gaming!

**Comment by jmg3195** [comment]
Just wanted to add an update and say you were correct when I switched back to stable STL v12.12 the game wasn't loading correctly. Also I'm unsure if this is related to using the SLR (non-steam game) version, but I'm having issues getting the trainer to work. I sent the logs for the trainer to the dev who made it and they said: "From your log it’s clearly seen the trainer engine fails on createtoolhelp32snapshot api function and this has nothing to do with the trainer codes and about 99 percent of the time this happens due to limited operating system privileges given to the process while on the other hand running as admin gives full access to the trainer engine to carry on it’s duty properly." Not sure how this is the case as I set up root access quite some time ago and my only account on the steam deck is listed as 'admin'. Only mentioning it in case it's useful info in some way :)

**Comment by sonic2kk** [comment]
> Just wanted to add an update and say you were correct when I switched back to stable STL v12.12 the game wasn't loading correctly

Thanks for confirming! I'll test and merge the PR sometime in the near-ish future (probably gonna take a short break soon) now that I know it helps something :-)

> [quote] "From your log it’s clearly seen the trainer engine fails on createtoolhelp32snapshot api function and this has nothing to do with the trainer codes and about 99 percent of the time this happens due to limited operating system privileges given to the process while on the other hand running as admin gives full access to the trainer engine to carry on it’s duty properly"

It could be related to Wine, as system privileges and Wine privileges are for the most part different. I don't think it's related to the SLR though I guess it could be, since the SLR acts as a container environment, though this is meant to only be for library access I think (i.e. for compatibility, not for sandboxing).

I don't use trainer programs and only have a very high level understanding of what they do based on STL issue reports, but I am not sure if this is related to STL. It could be a general Wine issue. You might be best asking online somewhere for advice on running and if it does turn out that STL needs to do something extra here I'd be happy to take another look.

Something that might be worth checking is the Windows version of the prefix. You can enable Winetricks to run before the game in the Game Menu, or since you mentioned Protontricks beforehand it should let you do this too. If the Windows version isn't Windows 10 you could try changing it.

And as well, removing the prefix might help here too if some files are corrupted for some reason, but I am not sure that this is happening here.

> my only account on the steam deck is listed as 'admin'

"Admin" on Linux and Windows are different, and Wine probably shouldn't be fussy either way about your account permissions. Just as an FYI in case you read online about Windows programs needing to run as Administrator, that doesn't really apply when running under Wine as far as I know :-) (at least in my ~10 years of messing around with Wine I haven't come across a case where it's relevant)

<hr>

I am not sure that it's caused by the SLR or STL but if you find out that this is an STL issue I'd be glad to try and resolve it. It's interesting on its own that this game requires the SLR, this is the first instance I know of where a Non-Steam Game has required it, so it was very useful for diagnosing that. Thank you for all your testing and patience, and apologies that I can't do much about the trainer itself not working -- Maybe asking around online from someone who knows more about using trainers under Wine could give more help. It's also worth mentioning that it's possible a trainer is meant to work only with a specific release or build of a game, for example sometimes some programs only work with the Steam or GOG release of a game, or only work with a certain version.

I hope you can get it working and do reach out again if there's something STL-specific that needs changing. I'll close this issue for now but you can re-open or open a new issue if something else comes up.

Good luck! :-)

**Comment by jmg3195** [comment]
Thanks again for all your help and I'll definitely test out your suggestions :)

**Comment by jmg3195** [comment]
No worries I figured the trainer issue was completely unrelated but wanted to mention it just in case

**Comment by sonic2kk** [comment]
Something that might be helpful if you can't/don't want to ask around online for any reason is to try using some google-fu to find potentially related posts for your error. I did a quick scan for `createtoolhelp32snapshot` online and found a handful of results on the Lutris forums, though nothing that looked directly related - Although they were generally about Battle.net and Origin (which are third-party programs) not working with Wine.

Searching around in this way might help you identify if this is a Wine issue or what more specifically is going wrong.

From other STL issue reports I have gotten, I recall some trainers needing some Winetricks to work. I'm not sure if you found a guide or anything on how to get the program to work with your game but it might be worth asking around. If there's a dedicated forum to ask on maybe you could get more assistance too on getting the program to work with Wine if you don't already have confirmation that it works. Wine isn't compatible with every program and usually requires some tweaks to work. A common one I have seen for trainers is requiring some form of dotnet but I'm not sure that's the case here if it's failing at `createtoolhelp32snapshot` (doesn't seem related to dotnet -- from a *very* cursory search from someone who is very much *not* a Wine dev :sweat_smile:) 

Definitely good to mention, just not sure what STL would be doing to break it or what it might need to do to fix it. There could be other factors but if you can find something that I need to fix feel free to reach out again!
