### ISSUE TITLE
Vortex via STL can't handle mods with filenames that include special characters

### ISSUE THREAD

**Issue by CrashTD** [sonic2kk/steamtinkerlaunch#779]
## System Information
- SteamTinkerLaunch version: 12.12
- Distribution: 6.2.9-1-MANJARO
- Installation Method: AUR

## Issue Description
If i try to install the Skyrim mod "[Fores New Idles](https://www.nexusmods.com/skyrimspecialedition/mods/3038)" mod via vortex i get this error:

![image](https://user-images.githubusercontent.com/45145914/230788601-50a5229e-8f09-4e5b-a0d2-755a8f83224f.png).

Looks like vortex stumbles over the special characters in the filenames. e.g. Espa**ñ**ol.txt, Fran**ç**ais.txt, etc. and fails to unpacks them. I tried to reproduce this error via Lutris and the same Vortex version and identical mod file and could not, so i guess the problem is on the STL side. 

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11189080/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
SteamTinkerLaunch sets the locale separately when running Vortex, maybe this is causing the issue. Outside of that, I don't know what would be causing this.

You could try running STL from source and changing/removing the `LC_ALL=C` part of the Vortex start code to see if that fixes the issue, but I'm pretty sure that was there for a reason. Maybe that reason is no longer relevant though.

Might be best to resolve this by having some option to set the Vortex locale or something if that is what's causing the issue.

**Comment by CrashTD** [comment]
That indeed was it :)

```
function wineVortexRun {
	sleep 1 # required!
	LC_ALL="C" PATH="$STLPATH" LD_LIBRARY_PATH="" LD_PRELOAD="" WINE="$VORTEXWINE" WINEARCH="win64" WINEDEBUG="-all" WINEPREFIX="$VORTEXPFX" "$@" > "$VWRUN" 2>/dev/null
}
```

removed the LC_ALL="C" and voilà, it works. thanks a lot!
no idea if that will cause any other problems though.

**Comment by sonic2kk** [comment]
Thanks for testing! I had a feeling that was the problem :-) Since previously special characters caused issues with STL itself when the system locale was set to LC_ALL=C.

I am also not sure what this is for exactly. Maybe at one point this was needed. But if Lutris doesn't do it maybe it's not needed anymore... 

I'm thinking that an option to manually specify the locale for Vortex might be a good idea, with the default of "C". That might not be very useful but I am hesitant to remove the LC_ALL at time of writing, *just* in case.

I'll leave this issue open for now so please do report back if you notice any problems. Depending on what I decide to do I'll also ping back with whatever change I end up making. I think having a checkbox to not set any locale is a bit too little, giving advanced users the option to specify a custom locale for any reason might be useful. Or perhaps the option to just generally specify custom launch arguments for Vortex might be useful. Though if LC_ALL=C is needed for some workarounds it might be better to have it as an explicit option.

I will keep thinking on this, thanks for testing again as it was useful to know this has actually caused an issue :-)

**Comment by sonic2kk** [comment]
Interesting, I found [a comment from Frostworx](https://github.com/sonic2kk/steamtinkerlaunch/issues/41#issuecomment-682588420) (the original creator of STL) which quotes this specific line in the Vortex start code: 

```bash
function wineVortexRun {
# leave LC_ALL=C else your "My Documents" will not be found! 
	LC_ALL="C" PATH="/usr/local/bin:/usr/bin" LD_LIBRARY_PATH="" LD_PRELOAD="" DXVK_LOG_LEVEL=none WINE="$VORTEXWINE"  WINEARCH="win64" WINEDEBUG="-all" WINEPREFIX="${VORTEXPREFIX//\"/}" "$@"
}
```

The start code has changed a little bit in the years since that comment was left, so it is quite possible that `LC_ALL="C"` is no longer needed.

Once I have some time, I will do some tests both with a fresh and new Vortex install to see if this line is still needed to find the "My Documents" folder. I personally don't see why this line would be needed to find the Documents folder, maybe this was an old Vortex/Wine issues that has since been resolved.

**Comment by CrashTD** [comment]
Sure thing, i update if something weird happens or breaks. and i'm of course happy to help test changes. thanks for the quick answer!

**Comment by sonic2kk** [comment]
I thought about it some more and I think simply removing `LC_ALL` is fine, assuming there are no further regressions.

A PR is up at #784 to address this, further testing from more users would be welcome before I merge.

<hr>

If no users report any issues (or if no other users respond), and if myself and OP have no issues with Vortex, I will merge after a while (maybe a week or two).

**Comment by sonic2kk** [comment]
Didn't have any issues and decided to throw caution to the wind and merge this change.

If any issues crop up, don't hesitate to re-open this issue. If other users encounter issues, please open a new issue. I won't get notified of comments on closed issues, though I do *try* to keep an eye on some that might relate to potentially breaking changes when I can. The best way to bring an issue to my attention is to either re-open though (if you are OP) or open a new issues (if you are not OP or the behaviour is somewhat different).

<hr>

Thanks for bringing this up, I had noticed it and wondered if it would cause problems, but didn't remove it as no one had reported that there were issues. Given that removing it has actually fixed an issue, I think it is a worthwhile change :-)
