### ISSUE TITLE
Tiny resolution when switching from Custom command on Steam Deck

### ISSUE THREAD

**Issue by richardoswald** [sonic2kk/steamtinkerlaunch#780]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: SteamOS
- Installation Method: ProtonUp-Qt

## Issue Description
Game shows ultra tiny resolution when switching from the custom command using SteamTinkerLaunch Compatibility Tool on Steam Deck. This is in Steam Deck's Game Mode. I have also tried with other games and other custom apps w/ the same affect.
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/20009874/231244043-840e1793-e255-46e8-bc1b-627b8cc1ffed.png">

![20230410162817_1](https://user-images.githubusercontent.com/20009874/231243255-3e183ce8-582a-4a6e-8a75-542f381298e6.jpg)

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11203216/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
I am not sure this is a SteamTinkerLaunch bug, this is more likely an issue with the Steam Deck and GameScope. This happens after the game has launched and you switch between the custom program and the game, right? If so, I doubt this is a SteamTinkerLaunch issue.

Is there anything specific here that made you think this was an STL issue that I'm missing? Since SteamTinkerLaunch just launches the process, the Steam Deck is what handles actually displaying the programs. And if there are issues here in the GameScope session, there isn't anything I can do about that.

The Steam Deck functionality to switch between game windows is not something available outside of the Steam Deck Game Mode session to my knowledge.

Are you using SteamOS stable or beta out of curiosity? It may be worth switching from one to the other to see if the newer/older version of GameScope fixes it.

> I have also tried with other games and other custom apps w/ the same affect.

This to me especially suggests that it is not a SteamTinkerLaunch issue, but some issue with GameScope itself. I mean, STL doesn't do anything about from launch the programs, and it's up to the GameScope session to display them.

**Comment by richardoswald** [comment]
Ugh, you are correct. When I remove STL from the equation and launch the non-steam custom app (notepad+++ for testing) and switch to the Steam game, it shows the same resolution issue. Back to the drawing board to figure out this Gamescope bug. You can close this as a non-bug then. Thank you.

**Comment by sonic2kk** [comment]
Might be worth reporting as a [SteamOS](https://github.com/ValveSoftware/SteamOS) bug or a [GameScope](https://github.com/ValveSoftware/Gamescope) bug. Not sure where the best place to report it is honestly since GameScope doesn't have the window switching functionality outside of SteamOS.

It's also worth trying either SteamOS stable, beta or preview if you can, to see if it has already been addressed.

Thanks for testing and good luck! :-)
