### ISSUE TITLE
steamtinker takes several minutes to load or open a new page

### ISSUE THREAD

**Issue by saufall** [sonic2kk/steamtinkerlaunch#781]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: nobara 37 newest update
- Installation Method: protonU

P-Qt

## Issue Description
Freshly installed stl from protonUP-Qt, set up a game in steam thats previously configured to run with proton to run under steam tinker launch did not clean proton prefix. it takes a long time (5-10 minutes) to load the game. After the first launch it gets a little better but it still takes 2-3 minutes for the launcher to pop up an 1-2 minutes to load windows.
#issues/317 seems related but I purged my stl settings multiple times and it still takes forever to load. it is especially serious when i quit the STL while it is waiting  to load a window . It immediately takes 10 minutes or so to load the STL at **all.
## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11204149/steamtinkerlaunch.log)
[Skyrim Special Edition.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11204163/Skyrim.Special.Edition.log)

**Comment by sonic2kk** [comment]
Not sure how this could be caused or resolved. The issue you linked (#317) to does indeed seem to be related, but I don't have this issue myself, on my PC (root install), laptop or Steam Deck (both ProtonUp-Qt).

@zany130 Do you recall anything about the issue you opened a while ago? Maybe you could give some advice, though I appreciate that the issue in question was opened a ***very*** long time ago :-)

<hr>

I noticed it seems to get stuck initially when fetching Steam Deck compatibility information. This should only be fetched once but it may account for one single source of a slowdown. It might be worth testing STL while disconnected from any networks, and seeing if the issue persists. It is also possible that it just takes a long time to get to the point where it tries to load the main menu.

Apart from that, I can see in the log timestamps that it does take several minutes to load. But there is nothing I can see from this right now that suggests why it should be taking so long.

<hr>

Out of curiosity, are you using any slower drives (i.e. HDDs) on your machine that may be causing a bottleneck? All of the machines I have tested SteamTinkerLaunch on all use SSDs. My main PC has one HDD but I have no libraryfolders on it, so STL would not even be looking at it.

**Comment by zany130** [comment]
Actually forgot about that issue so had to go look it up. I think that was the first issue i ever made here 😆


Anyway yeah i have had slow starts of STL every now and then.  But they always go away on there own.

Like @sonic2kk said it usually seems to be caused by some download.

One thing to keep in mind is the more things you have enabled obviously the more time it can take to set everything up 

For example STL collections feature can take some time so i usually disable it

**Comment by saufall** [comment]
Does the version of the protonUp-Qt matter if it i used to install tinker launcher? I tried nobara's and flatpak's protonUp-Qt to install the launcher v12.12 and it would almost not work or take an incerdibly long time to launch. when i use the newest appimage protonup-QT to install the tinker launcher takes less time but its still relatively long. 
My steam library and tinker launcher are on a newly bought SD.


> example STL collections feature can take some time so i usually disable it

How do I disable features? edit config files manually?

**Comment by sonic2kk** [comment]
> Does the version of the protonUp-Qt matter if it i used to install tinker launcher? I tried nobara's and flatpak's protonUp-Qt to install the launcher v12.12 and it would almost not work or take an incerdibly long time to launch. when i use the newest appimage protonup-QT to install the tinker launcher takes less time but its still relatively long.

It shouldn't matter, I use STL installed via ProtonUp-Qt on my laptop and Steam Deck, and I wrote the ProtonUp-Qt installation for SteamTinkerLaunch (was my first contribution to ProtonUp-Qt). STL can take some time to load menus but nothing more than about 10 seconds at most on my systems when just switching between them.

How long SteamTinkerLaunch takes to launch should not be tied to how it is installed and especially not by which version of ProtonUp-Qt that you used to install it, as it runs the [same installer code](https://github.com/DavidoTek/ProtonUp-Qt/blob/main/pupgui2/resources/ctmods/ctmod_steamtinkerlaunch.py).

> How do I disable features? edit config files manually?

In this instance, I'm pretty sure just not using a collection will work. Otherwise it should be configurable from the game menu, or by setting `CHECKCOLLECTIONS="0"` in each game config.

However on my systems this is set to `"1"`, and I don't have any speed issues at least not where it takes minutes to load the menus. I am not sure what is causing the slowdowns but trying to run offline would hint at whether or not it is a network issue.

**Comment by saufall** [comment]
> It might be worth testing STL while disconnected from any networks, and seeing if the issue persists.
This is the what happens when i access the launcher offline. it seems to work better. I do live in mainland China and am using a VPN to bypass internet restrictions but maybe the VPN doesnt work for the launcher and it hangs or operates sluggishly with a direct connection. What options related to online features of the launcher should i disable in order to smooth up the experience?
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11205572/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
> What options related to online features of the launcher should i disable in order to smooth up the experience?

~~There are currently no options related to disabling SteamTinkerLaunch's checks. If the checks fail they do just get skipped, but it may be worth adding an option in the global menu to toggle these (ProtonDB rating and Steam Deck rating come to mind primarily).~~ The Global Menu does have some toggles related to fetching game information.
- Download game data
- ProtonDB rating
- ReShade download (not 100% sure but I think this controls fetching the available ReShade versions) 

It could just be that your VPN is causing the slowdown here. I'll look into adding some online feature toggles.

From looking at the logs, it looks like a pretty significant speed bump! Though which download is causing the issue is hard to say.

Since STL doesn't actually depend on these features for functionality, you could try adding some rule somewhere to prevent STL from accessing the Internet. I believe there are programs to allow you to do this, though I don't know how to do it myself.

**Comment by sonic2kk** [comment]
Toggle for fetching Steam Deck compatibility info was added in d5c23f8a23b8f7a17dc076fb1ba0d23cbc6191bd, feel free to test from SteamTinkerLaunch-git (available from source or with ProtonUp-Qt, whichever you prefer). You can try disabling this alongside the other features mentioned to see if removing the online fetching stuff improves your SteamTinkerLaunch speeds, though I am not confident to be honest. It gives a small speedup for me but STL isn't *that* slow to begin with.

Keep in mind as well that when the STL version changes (such as when using a build from git) it refreshes config files, so there is a small slowdown there. This is still only several seconds for me though.

**Comment by sonic2kk** [comment]
Bump, have you had any improvement in loading times when disabling the network calls?

**Comment by saufall** [comment]
> Bump, have you had any improvement in loading times when disabling the network calls?

Actually the loading time went faster before downloading the newer version. I guess its just internet hiccups.

**Comment by sonic2kk** [comment]
The features are still on by default, they can be disabled in the Global Menu. But perhaps it is just network issues.

Thanks for testing, I will close this now :-)
