### ISSUE TITLE
HMM doesn't launch

### ISSUE THREAD

**Issue by Toadlover404Git** [sonic2kk/steamtinkerlaunch#789]
## System Information
- SteamTinkerLaunch version: 12.00
- Distribution: SteamOS
- Installation Method: Flatpak

## Issue Description
I'm extremely frustrated by this. HedgeModManager doesn't launch after all of the steps I've been following to a T on your official guide on Linux Gaming Central, and I can't play Sonic Frontiers, on my Steam Deck, with mods.

It takes forever to run a configuration for another HMM-compatible game I have installed, Puyo Puyo Tetris 2. It usually takes like 10 minutes on that step, then it says "Launching HedgeModManager", and nothing happens.
Why isn't it launching and how do I fix this? I just want to play Sonic Frontiers with mods on a Steam Deck.

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11238448/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
First off, the guide is **not** official. A nice person just wrote a guide on what worked for them.

If you're using SteamTinkerLaunch Flatpak on SteamOS, you're not using STL correctly on SteamOS. However it doesn't appear that you are, but I wanted to mention anyway.

You're also using an outdated version of STL, v12.0. v12.12 will give you some Wine output which can help you debug.

<hr>

I cannot give support for Wine issues when running applications, that goes for games, MO2, Vortex, HMM, whatever. Steam**Tinker**Launch is for tinkerers, so once you update STL you can use the Wine output to search around and see if you can figure out what is wrong. On SteamOS, it seems that .NET 4.8 unfortunately does not always install correctly for some reason, but STL gives you the tools to change Wine versions, prefixes, etc, so manually configuring your HMM installation should still be possible.

If you update and it turns out to be a Wine issue, which I am almost certain it is, then I can't help you unfortunately. Most users either give up because they are not willing to tinker or contribute any kind of technical info/fixes on what is wrong (I am not a Wine dev), so nothing improves. As far as I can tell, it is .NET not installing correctly, and I can't do anything about that as that means Wine is not running it correctly. All STL does is run Winetricks to install it, which has to be done manually anyway, and if that doesn't work, it's out of everyone's hands except the Wine devs.

<hr>

Also, keep in mind the tone of your issue. STL is a hobby project, there is *nothing* "official" here. STL just implements what is required manually and that apparently regularly seems to fail on Steam Deck anyway, but several users report more success on Linux desktop. HMM still works for me personally, including a fresh install on my PC (I generally don't mod games on my Steam Deck, and don't have it on-hand to check, but it worked as of a couple of weeks ago still).

**Comment by sonic2kk** [comment]
I combed through the log provided and STL is not outputting anything strange from what I can see, so I am very confident the issue lies with Wine. There may be a Proton Experimental incompatibility so trying GE-Proton may help, but I am not sure. I use GE-Proton7-43 to launch HMM currently and didn't try any other versions.

The rest of the paths and configuration steps look valid, so I am very confident in saying that like with many other HMM Steam Deck problems I have seen here and previously seen online (STL, Bottles, manual) that the issue lies with Wine somewhere and I would bet it's .NET not installing correctly.

With a fresh install you can verify this yourself (using STL v12.12, as mention) by trying to launch HMM and using the Wine output to search for the problem. You can also see HMM install logs in `/dev/shm/steamtinkerlaunch` and see if .NET is indeed failing to install by examining the logs for each .NET install (there is one for each installed HMM game and HMM itself). Errors along the lines of `ngen.exe not found` or error codes being returned may indicate issues with .NET, and sadly I cannot do anything about that. Some users have said re-installing eventually works, or different Proton versions work better for some users compared to others.

You may also have some success reporting general issues to online troubleshooting communities when it comes to installing .NET 4.8 and Wine, or post about the specific error you find out.

<hr>

Given the tone of this issue as well, I am not sure there is much point in leaving this open, as the issue may require some additional tinkering. Once again, the guide you followed is not an "official" guide created by me, 

You are also not using SteamTinkerLaunch Flatpak, I have verified this from the logs.

I understand that it can be frustrating but this is how modding is, in general. Things are not going to work, it takes several dozens of hours to get games set up with mods. On Linux where support is not official and we are relying on so many moving parts, tinkering is expected - Especially with a program created to allow for tinkering. Perhaps you have the wrong impression of who SteamTinkerLaunch is for.

<hr>

I'm going to close this. Good luck with fixing it and feel free to report back if there is a Winetrick required, even better with a PR to improve HMM support. I have given some pointers on how to go about troubleshooting but I cannot provide general Wine support. I have tried in the past particularly with the seemingly non-tinkerers that came across STL wanting to use Vortex, it is part of what made the last maintainer step down as well, so I can only give general pointers. Wine breakages aren't something I can help with, I'm not a contributor to Wine and I can't investigate each issue that comes in with third-party packages breaking/not working for a given application. I hope you can understand that that creates far too many variables.

Apologies that this didn't go anywhere, good luck with your tinkering!
