### ISSUE TITLE
Input issues with Steam Deck

### ISSUE THREAD

**Issue by trdpatrick** [sonic2kk/steamtinkerlaunch#791]
I'm experiencing a recent issue where I'm launching trainers as a custom command.  As soon as the game executable runs, I lose input on the trainer itself.  Even if I have the trainer window up, screen taps registers in the game itself, not the trainer.  I ran a test where steamtinkerlaunch only opens the custom command and I was able to interact with the trainer options.  I'm using different trainer applications like Aurora, Fling, and custom Resident Evil trainers from Nexusmods and they all experience the same issue.

**Comment by sonic2kk** [comment]
I can't help with input issues like this, this isn't a SteamTinkerLaunch issue. The Steam Deck has various issues when using custom commands as a result of its poor handling of multi-window use cases.

All SteamTinkerLaunch does is launch the programs, after that they aren't really managed by STL. Also, I'm assuming this is in Steam Deck Game Mode, so the issue is likely related to the Steam Deck's implementation of GameScope.

Sorry, I can't do anything about input issues. You'll have to report these kinds of issues to Valve, such as on the SteamOS Issue Tracker.

I hope my explanation on why this isn't a SteamTinkerLaunch bug makes sense at least. When the programs are ran it's up to the compositor and such, in this case likely GameScope, to manage the application. SteamTinkerLaunch isn't really doing anything here that would interfere with the application itself.

If it's a recent issue as well, then it's possibly a regression on Valve's end.

Good luck!

<hr>

Also, in future, please don't ignore the issue template.
