### ISSUE TITLE
complex and not clear enough instructions

### ISSUE THREAD

**Issue by SkylerHere** [sonic2kk/steamtinkerlaunch#793]
title says everything. i dont have flatpak steam, how can i install this without flatpak?

**Comment by sonic2kk** [comment]
SteamTinkerLaunch Flatpak is only for Flatpak Steam, install SteamTinkerLaunch in some other way. There are plenty as listed on [the Readme table](https://github.com/sonic2kk/steamtinkerlaunch#how-do-i-install-it) and wiki.

A popular way to install SteamTinkerLaunch is with ProtonUp-Qt, but you can also install from your package manager. Currently many of the packages are out of date unfortunately but the AUR and Pacstall packages are up to date. Aside from this you can also install by running `sudo make install` which will install STL system-wide. Once installed with any method that isn't ProtonUp-Qt, you can run `steamtinkerlaunch compat add` (ProtonUp-Qt will do this for you).

If you are on Steam Deck, you can download STL and run the main `steamtinkerlaunch` script to install it. ProtonUp-Qt also works on Steam Deck as well.

What made you think that you need Flatpak Steam? It is only one method for installation.

**Comment by sonic2kk** [comment]
Going to close this as this is a question rather than a bug report.

**Comment by SkylerHere** [comment]
You seem confused, so am I. Your guide had me confused and I had to click to like 2 links to get the installations instructions? I followed the manual installation to the letter and even after reboot the app is not opening

**Comment by sonic2kk** [comment]
What are the two links? Installation information is on the Readme, and links to the installation readme. This outlines the hard dependencies needed for SteamTinkerLaunch, and the manual installation steps.

https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#dependencies-1

Two links is not what I would call confusing or complex, and I am not sure what other parts of the steps are complex. It is standard manual installation steps for Linux programs, actually slightly less (no actual "building" is involved for STL since it's just a Bash script).

The [manual install steps](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#build-and-install) are very straightforward. The instructions on the wiki for a system-wide root install can be simplified to "Install all hard dependencies and then from the downloaded SteamTinkerLaunch folder, run `sudo make install`".

Manual Non-Root installation can be done but is for users who want more control over where STL is installed and its usage. ProtonUp-Qt does this and places STL in a relatively sane directory. But again, you will need the hard dependencies. As you followed the install instructions I assume you have met all of the requirements, including the required Yad version.

If STL is not opening you should've stated so in your opening issue, and attached a log.
