### ISSUE TITLE
Issue with resolution and GPU - MO2, Steam Deck, New Vegas.

### ISSUE THREAD

**Issue by rezalopan** [sonic2kk/steamtinkerlaunch#796]
When I try to run New Vegas from Steam Tinker Launch MO2, it detects the GPU of the Steam Deck simply as "VAN GOGH", and doesn't offer any resolution options. 
When I try to run the game it flags up a problem of not detecting the correct resolution and won't launch. It doesn't happen if I launch Fallout New Vegas alone, only if I launch with MO2 in Steam Tinker Launch. I've also tried resetting the ini files, using the game's ini files, forcing it to be 1280x800 in the ini, but nothing has worked. 
Kind of pulling what little hair I have left out here. Hope you have some sort of fix!

Thanks!

**Comment by sonic2kk** [comment]
Sorry, I'm not sure how this is a Steam Tinker Launch issue. I realise you've said it only happens when running with STL but STL isn't doing anything to interfere with this.

It seems like generally, or at least recently, GameScope has been encountering a number of issues with games and programs when used with tools like SteamTinkerLaunch (that is, anything not direct from the Steam client, i.e. a third party mod loader). These are not really issues I can do anything about really. Some examples of issues with Steam Deck Game Mode
- #791 
- #780 (likely a similar problem)
- #772 
- #753 (was never confirmed, but likely related to Game Mode)
- #752
- #747 (mentions some games using WeMod having input/resolution/display issues in Steam Deck Game Mode)

I'd recommend trying in desktop mode and seeing if the problem persists. I'd also suggest making sure you're using MO2 from MO2 Game Mode. That is, not from the MO2 extra button, but after pressing "Play" from STL (or letting the wait requester time out) and then launching MO2 from GUI mode. If it doesn't happen in desktop mode then this is a bug with GameScope.

You could also verify the Proton version being used for the game is the same as the one that Steam is using when running without STL. Some games have issues when using Proton 8.0 (Valve recently rolled back a change for "ELDEN RING"). SteamDB lists "Fallout: New Vegas" as defaulting to Proton Stable, which could be the latest default i.e. Proton 8.0. It may be worth trying an older version of Proton, or a build of GE-Proton, basically to ensure Proton isn't causing the issue.

Running Steam first time setup from the Main Menu might also help, as sometimes the DirectX stuff isn't set up properly. But I don't think that's the case here if running without STL works. I would guess this is probably a problem where GameScope can't properly pass the resolution to the game.

Also, "VAN GOUGH" is the name of the Steam Deck GPU, so that is correct. Many games detect the GPU as this.

STL doesn't provide support when modding games, it's possible that this issue could be specific to Steam Deck Game Mode as there have been various reports of Game Mode not playing nice with third party applications. #780 reported general resolution problems with third party programs in Game Mode.

I don't mod on Steam Deck so I can't test this myself. You might be better off asking for general support on a Linux support forum, or generally looking at what causes this issue on Windows to try and troubleshoot what might be happening.

I don't think there's anything STL can do here to fix the issue as there shouldn't be anything it does to break this. All it does is launch the programs with Proton. Maybe enforcing s resolution for GameScope in the Game Properties from Steam could help but I'm not sure.

Good luck!

**Comment by sonic2kk** [comment]
One report on the Steam forums said they changed the graphics adapter, though New Vegas should only list one I would guess since each adapter gets its own screen. Still worth trying if you haven't already: https://steamcommunity.com/app/22380/discussions/0/2298472007795357911/

There is also [a specific comment](https://www.reddit.com/r/Fallout/comments/o89lae/comment/h34j5j7/?context=3) from this user about editing INI files on reddit. Quote:

> "removed all the ini files." The ones in the game folder, or the ones in Documents/My Games/FalloutNV?

Check the documents in the prefix (STL lets you open the prefix from the Game Files button, I'd recommend doing this from desktop mode if you didn't already try this).

From searching, this seems like it could be some form of game bug. I wonder if Steam is looking in the wrong places for your prefix as this happens sometimes for games on the microSD card. I ran into this issue where games will sometimes not launch from the microSD as the prefix is created in the wrong place, I reported it to Valve but no updates for months unfortunately. It seems intermittent now, but it used to be consistent.

It is possible that in some way, switching between using STL and regular New Vegas is somehow breaking the game configuration. 

When using various games across different computers it's not uncommon for graphics configuration to not work. Sonic Generations is affected by this, for example, it will not be able to find any graphics information if you play on one PC and then try to play on another. Something like this could be happening with New Vegas.

<hr>

The real interesting tidbit will be if this works with STL in desktop mode with MO2 GUI, as this more closely mirrors a regular Linux Desktop. If so that would certainly suggest a problem with GameScope. STL shouldn't be doing anything that breaks resolution options with games. There was an issue previously where the Steam Linux Runtime was not used but that was fixed a couple of months ago and released a month ago with v12.12. I also don't think that would cause a resolution problem here.

**Comment by rezalopan** [comment]
Hey, thanks for the quick and detailed reply! I really appreciate it.

This is definitely a user error! I thought running MO2 from the menu that appears with STL is "Game Mode" since I launched the menu from opening the game. Completely my fault, I'll chalk that one up to me being tired from work and not reading the instructions properly. 

The reason I brought up the GPU part, just as an interesting thing, is that when you launch New Vegas launcher it lists the GPU in a different way, with VAN GOGH in brackets. I think that's partly why I'd got so confused. 

Again, thanks for the reply with all the info. Gonna add something in case anyone runs into the same issue:

Running MO2 from the STL menu is STANDALONE mode, not GAME mode. Only install MO2 this way, don't use it this way.

You need to press the GAME MENU button, then scroll down and where it says "Mod Organizer 2", select GUI. You can also add the game to a collection called "MO2" as well. Only run MO2 that way.

Thanks again!

**Comment by sonic2kk** [comment]
Glad it's working and thanks for testing! I'll see if I can make this more apparent on the wiki. It is mentioned though I should add a more explicit note for Game Mode.

Happy tinkering!
