### ISSUE TITLE
Don't Start MO2/Vortex in Gamescope

### ISSUE THREAD

**Issue by KenJyn76** [sonic2kk/steamtinkerlaunch#798]
Not sure how simple this would be to implement, but is there any way to add functionality to not start programs that aren't the game, such as MO2 or Vortex, in gamescope? I use gamescope for nearly all my games, and having the mod managers open in gamescope can be downright disorienting if using the -f flag.

Thanks

**Comment by sonic2kk** [comment]
Sadly that isn't really feasible, as aside from when you use the extra buttons on the main menu, the MO2 and Vortex processes *are* the "game" processes for all intents and purposes. For example MO2 is responsible for managing the game launch and so on, and it's started in the game's prefix.

When you have MO2 enabled for a game and press the play button, STL uses that as its game start command. There wouldn't really be a way for a program to specify that processes started from another application should use XYZ configuration. I don't believe this challenge would be specific to STL but just in general.

There is no real way to tell Vortex or MO2 to use STL's GameScope configuration I'm afraid. A potential solution is to mod using the extra buttons and then for MO2 at least, just use MO2 to start the game (it has to be done this way so MO2 runs in the game's prefix).

This would also extend to any custom command such as using a custom game launcher. There is no way for a program to say "when my game is opened, use *X* configuration". There are issues like "how do you know what the game process is" and by the time you would be able to detect it, you can't really wrap it in a custom process such as GameScope. Using gameScope is an all-or-nothing situation.

I hope the explanation for why makes sense, sorry about that.

**Comment by sonic2kk** [comment]
Something that might ease the issue slightly is to try and use a more up-to-date version of GameScope, or report issues to improve GameScope usability to Valve directly at [ValveSoftware/gamescope](https://github.com/ValveSoftware/gamescope).

I mention using a more up-to-date GameScope as previous releases of GameScope had frustrating mouse sensitivity, speed and other issues that appear to be fixed in later versions of GameScope-git (I typically just build from source). It may help, but if not, suggesting improvements to Valve is the way to go here.

**Comment by KenJyn76** [comment]
Alright, that's okay. Thank you for the response! Unfortunately, gamescope-git messes up my gamma in my games for some reason at the moment, but I am running the most up-to-date stable. I'll just continue installing mods through `steamtinkerlaunch mo2 s` and only starting MO2 via gamescope when I'm launching the game.
