### ISSUE TITLE
CTD when accessing file directory

### ISSUE THREAD

**Issue by Jtucker40** [sonic2kk/steamtinkerlaunch#805]
## System Information
- SteamTinkerLaunch version: need to check
- Distribution: SteamOS
- Installation Method: Package Manager

## Issue Description
Running SteamTinkerLaunch on Steam Deck, using it mostly to mod FO4 through MO2 at this point. Having an issue where when I attempt to install a mod/file manually through the MO2 gui, MO2 will crash back to the STL main menu. 

Issue asserts any time I attempt to access a file directory through the MO2 gui, such as looking at the install paths as well as add new executables. 

I am fairly new to Linux, is there some Wine or Proton edit I need to make to MO2 look in the right place? Seeing as it STL seems to be simulating a Windows file structure. At work currently but can provide logs when I get back home! Thank you!

EDIT: Should be noted NXM downloads work great and MO2 works fantastic otherwise. Issue asserts in both game and standalone modes, as well as game and desktop mode on the deck.

**Comment by sonic2kk** [comment]
Hmm, this is likely an issue when using MO2 under Wine and not a bug with SteamTinkerLaunch. You noted that you're using SteamTinkerLaunch installed via Package Manager on Steam Deck. Many Steam Deck users have incorrectly stated this and as you've mentioned you're new to Linux I would like to confirm how you installed SteamTinkerLaunch, as installing from Package Manager would be quite involved for a new  Linux user on SteamOS. I would not recommend using SteamTinkerLaunch from the AUR on Steam Deck as this _could_ be the thing causing issues. STL can be installed on Steam Deck by just running the STL script, or by using ProtonUp-Qt.

Aside from this, I appreciate all the information and research you've done around what could be causing the problem, many of the questions I would've asked have already been answered because you followed the issue template and did your due diligence (happens on Game Mode and Standalone Mode, and you outlined the specific cases where the issue arises).

I'd appreciate it if you could update with what version of SteamTinkerLaunch you're using (ideally v12.12 or higher), as well as which version of Proton you're running MO2 with. You can check the version of Proton you're using from the Global Menu.

> I am fairly new to Linux, is there some Wine or Proton edit I need to make to MO2 look in the right place? Seeing as it STL seems to be simulating a Windows file structure. At work currently but can provide logs when I get back home! Thank you!

This is the only part I would like some clarification on. What do you mean "the right place"? Do you think it might be looking for a folder that doesn't exist?

Also, just as a small note, it isn't STL that is simulating a Windows filesystem, that's all Wine :-) STL just downloads, installs and runs MO2 with a given Wine/Proton version.

I just did a test on my Linux Desktop and I noticed that with my current MO2 prefix, builds of Proton using Wine 8 and above (i.e. GE-Proton8-X, Proton 8.0 or Proton Experimental) seem to cause MO2 to just crash. This is probably because of an incompatibility when upgrading the prefix to use a newer Proton version, which happens sometimes, but it's worth nothing that it is possible that this is causing the issue. MO2 may be incompatible with newer Wine versions. Before upgrading the version though, I was able to manually navigate to and select a mod to install for Oblivion.

To test if this could be a Wine issue, before you go changing your Wine version or anything, you can run MO2 from the command line. On Steam Deck, you should be able to find the SteamTinkerLaunch script at `~/stl/prefix`. From this folder, run `./steamtinkerlaunch mo2 start` and you should see some Wine output. The beginning few lines may look something like this:

```
wineserver: using server-side synchronization.
wine: Using setpriority to control niceness in the [-10,10] range
```

From here you can continue to reproduce the crash. You will, hopefully, see some additional output after the crash that should at least somewhat resemble an error message. You can attach this, either as a file or inline, though if attaching inline please attach as a codeblock for easier readability :-)

<hr>

I suspect the core of this issue is going to be a Wine version incompatibility rather than anything STL can really solve, as program crashes like this may happen outside of STL altogether. Still, we can investigate it a little bit and see what's up! :slightly_smiling_face:

**Comment by sonic2kk** [comment]
Hmm, I was able to reinstall MO2 using Proton 8.0-2 and the install mod button worked fine.

One suggestion I would make is to try doing this from the Steam Deck's Desktop Mode if you haven't already. Though I just tried in GameScope on my desktop (the tool the Steam Deck uses to render the Steam client in Game Mode) and I didn't have any problems.

**Comment by Jtucker40** [comment]
Apologies for leaving out so much important information. I am running STL version 12.12, installed via ProtonUp-Qt and and currently on proton-7.0. 

Went to check my proton version and discovered that i had different proton versions selected in the game menu and the global menu. Once I went back and made sure they were both set to proton-7.0, MO is working perfectly again! Thank you for helping me out and making such a great product. Sorry to waste your time with such a dumb bug report.

**Comment by sonic2kk** [comment]
> Sorry to waste your time with such a dumb bug report.

Not at all! I'm very glad it's working and honestly your issue report included pretty much all necessary information.

As for the reason behind the crash, there may be some issues with MO2 and Proton 8, or some versions of Proton 8. Having matching versions either way is a good idea though (I'm considering having an option to default the versions to always match but no ETA on that 😅)

Happy playing! :-)

**Comment by sonic2kk** [comment]
From discussion in #813, it seems that using MO2 with Proton 8 builds (including GE-Proton8-X builds) may be caused by SteamTinkerLaunch using the Steam Linux Runtime. You can refer to that issue for some more context but the workaround is basically, if the crash is happening with Proton 8 in Game Mode, you can try disabling the Steam Linux Runtime in the SteamTinkerLaunch Game Menu (under "Proton Options").

If the crash is happening for you in Standalone Mode, then MO2 may actually *require* the SLR in your case. If so, I can do something similar for what I did with Vortex (#807, #816).

If the crash is happening for both Game Mode and Standalone Mode, then maybe the issue is just a general Wine incompatibility.

<hr>

I should note that, as the user in the linked issue did also, disabling the Steam Linux Runtime is a workaround. Proton is intended to be used *with* the Steam Linux Runtime, because it provides libraries that Proton is built against. Using your system libraries may cause problems for games, but in this case, it seems the libraries that Proton 8's SLR (named "Sniper") is built against may actually have some incompatibilities with MO2.
