### ISSUE TITLE
Vortex on Cyberpunk 2077 doesn't work

### ISSUE THREAD

**Issue by nullfrctl** [sonic2kk/steamtinkerlaunch#821]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: uBlue Silverblue/GNOME v1.5.0
- Installation Method: Flatpak

## Issue Description
Vortex can install just fine, but when starting it, it for one, doesn't detect Cyberpunk automatically, and once started and Cyberpunk 2077 managed, the staging folder is reported as not being on the same drive as the game and so deployment does not work.

Using Vortex's suggested path does not work either, and the issue continues to persist.

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11671759/steamtinkerlaunch.log)

![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/99456326/8a334aeb-3d47-43e2-9657-bb3c2c43edfa)
This is the "fix" Vortex gives, but, the path is _already_ in the same "drive".
![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/99456326/2d02cdd9-bd8a-48c6-b02f-e8284c0025e9)

**Comment by sonic2kk** [comment]
This sounds like an issue with modding a game and not a SteamTinkerLaunch issue? Vortex broke a while ago and does not always detect games automatically. However as you were able to it is fairly straightforward to tell Vortex where to find a game.

As for the drive issue, usually the staging folder goes onto the "root" of the drive, e.g. if you have a steamapps at `/run/media/Gaben/SteamGames/steamapps`, the staging folder is created at `/run/media/Gaben/vortex`. But if your game is already on the same drive, I'm not sure why Vortex doesn't see it. I don't think STL does this for games on the same drive, as it's expected that Vortex can see them.

Maybe for Flatpak Steam something needs to be done differently, I'm not sure. Perhaps this is some oddity with using Steam Flatpak? You may want to try marking the staging folder differently, it may need to point to the Steam Flatpak steamapps. I'm not sure though.

This seems more like an issue with modding than a SteamTinkerLaunch issue. If Vortex starts that's about as far as STL is expected to go, tinkering around with getting mods to work is up to the users because it would be unreasonable to provide support for mods, and because I don't use Vortex 😉 

I'll leave this open though for discussion. Good luck! 

<hr>

I actually own Cyberpunk 2077, but the connection where I currently am is a bit slower than home, so it may take a while to download. Nevertheless I'll try to make some time to test this if I can, though I don't have enough space on my boot drive for Cyberpunk and I don't use Steam Flatpak, but this should help narrow down if it's specific to Flatpak.

**Comment by sonic2kk** [comment]
Actually, reading the issue again, that "null" in the username is interesting. I wonder if there's some username detection issue. That could be causing issues as well, or that could be the root cause. Perhaps this is a Flatpak-specific issue.

Unless your username is actually `null` (possible with your GitHub username, not sure 😄)

**Comment by sonic2kk** [comment]
I took another look at the path in the screenshot for the Vortex "fix" and it also looks wrong, though I can't see the full one.

I can only speak for games on other drives, but I tested with A Hat in Time, and the detected path was `Z:\run\media\username\BigSSD\Vortex\{GAME}\mods`. Since for this issue you're using Flatpak there could be some oddity here where the path needs to be tweaked. As mentioned STL usually does not create staging folders for games on the same drive, but I am not sure how this is handled inside Flatpak.

You can check if staging folders were created anywhere by STL by going to the STL config folder and looking for a `vortex` folder, then checking for a `stages.txt` file. There may be one in the base Steam directory.

**Comment by nullfrctl** [comment]
> Actually, reading the issue again, that "null" in the username is interesting. I wonder if there's some username detection issue. That could be causing issues as well, or that could be the root cause. Perhaps this is a Flatpak-specific issue.
> 
> Unless your username is actually `null` (possible with your GitHub username, not sure smile)

Yeah, my username is actually null.

I have been trying to debug this but unfortunately the Steam Tinker Launch menu just... disappeared? Also, I can't show hidden files in the Wine explorer.exe, which doesn't allow me to select the correct directory. Any idea how to fix both of those?

To further clarify, STL launches the game and uses my Proton settings, but the game menu just doesn't appear anymore. 

## <sub>edit</sub>
I used `flatpak run --command=sh com.valvesoftware.Steam` and was able to do `steamtinkerlaunch settings` and configure from there.

Unfortunately, even though I enabled "Show dot files" in the winecfg for the game, it doesn't apply to Vortex and I still cannot open the correct directory. I also turned on Winecfg in vortex mode but it doesn't winecfg before running vortex, and the tooltip is awfully vague.

**Comment by nullfrctl** [comment]
OKAY! I FIXED IT! by totally random means! **You just need to select the game as being in the S: drive when it prompts you to locate it. Then set the staging folder to the automatically selected one and it WORKS.**

Thanks for helping, but I think it cal be closed now.

**Comment by sonic2kk** [comment]
> To further clarify, STL launches the game and uses my Proton settings, but the game menu just doesn't appear anymore.

This may happen if you press "Cancel" too many times. You can re-enable it with `steamtinkerlaunch wr e` or I think from the Game Menu when you enter settings. If that wasn't the problem, I am not sure :sweat_smile: 

> OKAY! I FIXED IT! by totally random means!

Nice work! I am not sure what the `S` drive for Wine is, but I wonder if it's related to Steam Flatpak. I will document this on the wiki though, thank you for your work!

**Comment by HugKitten** [comment]
> OKAY! I FIXED IT! by totally random means! **You just need to select the game as being in the S: drive when it prompts you to locate it. Then set the staging folder to the automatically selected one and it WORKS.**
> 
> Thanks for helping, but I think it cal be closed now.

I have no S driver and I have no idea what to do. :(

**Comment by sonic2kk** [comment]
If you're not using Steam Flatpak (and thus not using SteamTinkerLaunch Flatpak) then it's unlikely you'll have an S drive mapping.

However you should be able to find another drive mapping. If not, try the Z drive for your global filesystem. Failing all of that, try to find where Steam Flatpak thinks your game is stored. I'm not sure how to do this as I don't use it, but if you can find this out, you can find out how to get Vortex to deploy mods for your game.

However, mod support is not typically an area of support for the SteamTinkerLaunch issue tracker.  It is for reporting bugs, and usability issues with a third-party tool on Linux aren't SteamTinkerLaunch bugs.

There may be potential to resolve problems like this with some Flatpak configuration changes, but someone with more knowledge on that area would have to submit a PR either here or on the STL Flatpak repo :-)

**Comment by HugKitten** [comment]
> If you're not using Steam Flatpak (and thus not using SteamTinkerLaunch Flatpak) then it's unlikely you'll have an S drive mapping.
> 
> However you should be able to find another drive mapping. If not, try the Z drive for your global filesystem. Failing all of that, try to find where Steam Flatpak thinks your game is stored. I'm not sure how to do this as I don't use it, but if you can find this out, you can find out how to get Vortex to deploy mods for your game.
> 
> However, mod support is not typically an area of support for the SteamTinkerLaunch issue tracker. It is for reporting bugs, and usability issues with a third-party tool on Linux aren't SteamTinkerLaunch bugs.
> 
> There may be potential to resolve problems like this with some Flatpak configuration changes, but someone with more knowledge on that area would have to submit a PR either here or on the STL Flatpak repo :-)

I am using flatpak version on both steam and tinker launch. The z drive doesn't give any errors until I try to stage in which case it errors saying it can not write to it. I'm not sure if this is perhaps another issue. The game only appears to be stored on the z drive, and no where else. I couldn't find any information about it anywhere. Would you prefer I submit an issue here or on the flatpak repo?

Edit: Is it possible the issue im having isn't this one but the same issue as #892? I'm having issues with Starfield in particular, and it doesn't look like flatpak version has the changes yet. Sorry if that's the case. ^^

Added the line from #892:
"starfield";"Starfield";"1716740"
```
[sarah@sarah-pc ~]$ flatpak run --command=steamtinkerlaunch com.valvesoftware.Steam vortex games
Gtk-Message: 04:12:25.428: Failed to load module "canberra-gtk-module"
find: ‘/home/sarah/.var/app/com.valvesoftware.Steam/.local/share/Steam/userdata/75431567/config/grid’: No such file or directory
Gtk-Message: 04:12:26.130: Failed to load module "canberra-gtk-module"
grep: /dev/shm/steamtinkerlaunch/VGNLIST.txt: No such file or directory
grep: /dev/shm/steamtinkerlaunch/VGNLIST.txt: No such file or directory
grep: /dev/shm/steamtinkerlaunch/VGNLIST.txt: No such file or directory
grep: /dev/shm/steamtinkerlaunch/VGNLIST.txt: No such file or directory
grep: /dev/shm/steamtinkerlaunch/VGNLIST.txt: No such file or directory
```

Created dir and reran successfully, still getting error:
https://imgur.com/a/igE5zs4

**Comment by sonic2kk** [comment]
The issues could be the same. I'm not sure why adding that line to the vortex games didn't fix it though. The errors in the command line also seem a bit odd, though it's probably just something harmless as a result of being run in the Flatpak.

It's possible there could be other fixes compounding the fix for Starfield (see the changelog for details on Vortex changes) but afaik none of those should necessarily impact deployment, they are related to fixing Vortex installation issues.

You could try letting SteamTinkerLaunch create the Starfield staging directory but I don't even use or like Vortex, so I'm not really sure what's going on.

It could be that the original issue you faced was the same as #892, but is now the same as this issue, where mod deployment on Flatpak is a bit hit or miss apparently.

Could you give the details if possible that Vortex provides on the deployment error? Maybe it'll shed some more light. I suspect the issue is going to be something boiling down to Vortex being unable to hardlink the mods for some reason.

And also finally out of interest, what version of SteamTinkerLaunch is the Flatpak using these days? If it's installing Vortex correctly it must be using some git build :-)

**Comment by HugKitten** [comment]
I deleted everything and reinstalled things and it seems to be working now. No idea what I did wrong last time :3

**Comment by sonic2kk** [comment]
Maybe Vortex needed a reinstall or some kind of hard "do-over" to re-create some files. Maybe it's related to the VGNLIST error, which iirc is "Vortex Games Nexus list" (maybe it failed to download it? Not sure)

Either way, I'm glad it's working!
