### ISSUE TITLE
Vortex NXM handler not working

### ISSUE THREAD

**Issue by nullfrctl** [sonic2kk/steamtinkerlaunch#825]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: uBlue Silverblue/GNOME
- Installation Method: Flatpak

## Issue Description
I've been struggling getting Vortex to work in the first place, but now, getting it to install mods is still difficult. I've changed the .desktop file to match the one in the MO2 wiki section with all mentions of "Mod Organizer" or "mo2" being replaced with vortex, and still, Firefox doesn't prompt for the NXM link nor does Vortex catch the request.

## Logs
The desktop entry used
```desktop
[Desktop Entry]
Type=Application
Categories=Game;
Name=Vortex (SteamTinkerLaunch - steamtinkerlaunch)
MimeType=x-scheme-handler/nxm;x-scheme-handler/nxm-protocol
Terminal=false
X-KeepTerminal=false
Exec=flatpak run --command=steamtinkerlaunch com.valvesoftware.Steam vortex u %u
NoDisplay=false
```

**Comment by sonic2kk** [comment]
>  getting it to install mods is still difficult.

Manually downloading mods is generally the recommended approach instead of using some kind of one-click button.

However, I would try adding `Hidden=false` to the bottom of your desktop entry file, as that appeared to fix the issue for non-Flatpak users (and even recently as reported to still work). See #637 and #756.

If that still doesn't work, you'll just have to live with manually downloading mods. NXM link handling not working is not really an issue I am interesting in pursuing any further. I would accept a PR to fix it, but if the only issue here is that the NXM link handling doesn't work, then this is a wontfix I'm afraid.

**Comment by nullfrctl** [comment]
Fortunately, it turns out the collection works perfectly inside Vortex if you go through the UI and install it that way. I thought I had to go through nexus to install it.
I'm ok installing mods manually after my 200+ mods install through the collection lmao.
