### ISSUE TITLE
"Failed to load module 'xapp-gtk3-module'"

### ISSUE THREAD

**Issue by Pragmer** [sonic2kk/steamtinkerlaunch#827]
## System Information
- SteamTinkerLaunch version: 12.12
- Distribution: Linux Mint 21.1 Vera
- Installation Method: I'm assuming the template is referring to the installation method of STL and not my OS, in which case I was attempting to install it with this method https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#manual . 

## Issue Description
Initially when I had attempted to install Yad I used the app image, and it gave me a "Failed to load module 'xapp-gtk3-module'" error after trying to use it through STL. I continued on until step 11 anyway, in which the same thing occurred. I then found this post in issues https://github.com/sonic2kk/steamtinkerlaunch/issues/596 and attempted to manually install Yad as per these instructions https://github.com/v1cont/yad/issues/180 which are linked to in Step 2 of the STL installation guide. After inputting command 4 almost everything seemed fine except at the end of the long string of "checking" lines it had this:

"checking for gtk+-3.0 >= 3.22.0 gtk+-unix-print-3.0... no
configure: error: Package requirements (gtk+-3.0 >= 3.22.0 gtk+-unix-print-3.0) were not met:

No package 'gtk+-3.0' found
No package 'gtk+-unix-print-3.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTK_CFLAGS
and GTK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details."
Trying to complete step 11 of the installation guide still spits out the same error "Failed to load module 'xapp-gtk3-module'" as well.

I'm sorry if this is basic bitch stuff and I'm just being an ignorant buffoon. Being as what many would probably consider a linux baby for using Mint, I could easily see this being the case.
## Logs

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11682621/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
I am not sure how to resolve this. It seems like you may be missing some dependencies for building Yad on your machine. It's interesting that the Yad AppImage also gave that error, I would've expected it to work fairly standalone. Perhaps this is some oddity with Mint/Debian-based distros in general.

From a quick Google search, it seems that `xapp` is required to build Yad. Not sure why it's needed for the AppImage, though. There was an [AskUbuntu post](https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module) where a user noted that this package should be installed, specifically that it should be installed with `apt` and not `snap` (though I don't believe this is applicable outside of vanilla Ubuntu, as I don't think any other distro has or is willing to adopt Snaps). So you can try the following:

```
sudo apt install xapp
```

Then before building a Yad package yourself, I would recommend trying the AppImage again. On my Arch PC, `xapp` was only installed because Warpinator required it, but it isn't used by SteamTinkerLaunch. I wonder if maybe the GTK dependencies installed it or something, not sure to be honest :sweat_smile: 

<hr>

I'd just like to make a handful of notes:
1. I don't develop Yad, and issues building/using Yad on a distro isn't really a SteamTinkerLaunch issue, so I'm going to close this, but good luck getting STL to run! Hoping for the best. You might be better off asking upstream at the Yad repo for more information.
    - Yad is the GUI toolkit that STL uses, it is developed independent of STL and I can't really provide support for it (the Yad AppImage was built by the previous maintainer Frostworx and works on Steam Deck, and on my Arch PC, an up-to-date `yad` is available in the repos)
3. I believe [Pacstall](https://pacstall.dev/) should be available for use on Linux Mint, and it should package SteamTinkerLaunch. This may be more straightforward to use.
4. It's ok to be new to Linux, we all were at one point, but please be aware that SteamTinkerLaunch is for experienced Linux users and you're expected to know what you're doing (hence the "Tinker" part of STL) - In my experience people who are new to Linux don't normally have a good experience with STL. Of course you are still free to use it, but this is just a disclaimer that when things don't work you're expected to try and figure out why and then report why (if it isn't a system-specific thing)
    - Also, your choice in distro doesn't equal your experience level, don't feel bad about using Mint :-)

And finally, yes, you got the installation method correct, it refers to the method you use to install (or in this case, attempt to install) SteamTinkerLaunch, as there are several (ProtonUp-Qt, manual, package manager, Flatpak for Steam Flatpak, etc)

**Comment by Pragmer** [comment]
Thank you for your willingness to help, I remember trying to install xapp earlier, idk why I forgot to include this in my original post, but this is what gets output when I try to install it.
|
|
|
_Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:_

_The following packages have unmet dependencies:
 xapp : Depends: libxapp1 (= 2.2.8-1) but 2.4.2+vera is to be installed
E: Unable to correct problems, you have held broken packages._
|
|
|
I looked into this a little bit earlier and I iirc this libxapp1 situation is caused my something linux mint does. Not sure if its holding it back altogether or if its just locking it to that version. If I do "sudo apt install libxapp1" it tells me that it is already the newest version (2.4.2+vera). If I try "sudo apt install libxapp1=2.2.8-1" it tells me that it has unmet dependencies AND that those dependencies are not going to be installed.
|
|
|
_Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:_

_The following packages have unmet dependencies:
 mintsources : Depends: mint-common (>= 2) but it is not going to be installed
               Depends: gir1.2-xapp-1.0 but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages._
|
|
|
I believe it is saying that it requires mint-common version 2 or greater, but that doesn't make any sense because if I do "sudo apt install mint-common" it tells me that it is already installed and is the newest version(2.2.7).  The problem package seems to be the "girl.2-xapp-1.0" package. Attempting to install it spits out:
|
_E: Unable to locate package girl.2-xapp-1.0
E: Couldn't find any package by glob 'girl.2-xapp-1.0'_
|
My guess is that this package specifically is the one being held back as stated by previous error messages. But I am not sure if I can or how I would force it through anyway. In the meantime I will try the Pacstall. Even if the Pacstall does end up working I'd still be curious as to what could be going on and your insight if you wouldn't mind. I'd like to learn whenever I can.

**Comment by Pragmer** [comment]
The Pacstall did work, and it let me mod the game I wanted to. Oddly enough the command used to add STL to steam compatibility tools spat out the same error of "Failed to load module 'xapp-gtk3-module'". Despite that, it ran perfectly fine, it seems to be functioning properly. So turns out that I probably could have just ignored that error from the very beginning and been fine.

**Comment by sonic2kk** [comment]
Nice, glad to hear it worked! The description from your earlier comment sounds like there may be issues building Yad on Linux Mint, I'm not fully familiar but it looks like some form of dependency hell 😅 Most likely as you said it's probably something Linux Mint does, I don't think this is anything on you.

Happy tinkering!
