### ISSUE TITLE
Steamtinkerlaunch to use WINE with steam games

### ISSUE THREAD

**Issue by knosuhor** [sonic2kk/steamtinkerlaunch#842]
Is using wine-ge instead proton with steam games possible? Not sure if a am doing something wrong or wine in steamtinker launch is supposed to be used only with non-steam games, but trying that out couldn't launch any game. 
Last thing in log was "RLIMIT_NICE is <-20, unable to use setpriority safely" probably irrelevant.
I am trying to use WINE because cutscenes with windows codecs sometimes work on wine-ge and not proton-ge.

**Comment by sonic2kk** [comment]
Yes, it's possible. However it may not always be compatible, as you're supposed to use Proton and the Steam Linux Runtime with Steam games.

I don't remember if the Steam Linux Runtime is still passed when using Wine, but you could try disabling it if enabling Wine and selecting Wine-GE isn't working. It is also possible that the prefix isn't working correctly when switching between Proton and Wine, because of the symlinking that Proton does. You may need to try a fresh prefix.

This isn't a SteamTinkerLaunch issue but a compatiblity issue I think, so closing.

**Comment by sonic2kk** [comment]
Hmm, in my tests compatibility with Wine seems non-existent. I am not sure why games aren't working but I don't know why it would be a SteamTinkerLaunch issue, because even running the same Wine start command from the logs, my system cannot launch these executables with Wine-GE-8-5.

Something is wrong, but it doesn't work outside of SteamTinkerLaunch for me, so I am not sure what it is and is almost certainly a separate issue.

**Comment by sonic2kk** [comment]
Actually, on further investigation, this *is* a SteamTinkerLaunch issue, because removing the `WINEARCH=` from the launch command allows games to work outside of SteamTinkerLaunch with the launch command. So it seems STL is at fault here.

**Comment by sonic2kk** [comment]
In testing, Steam games generally seem incompatible with Wine, but custom programs and Non-Steam Games (tested Sonic P-06 and Touhou Fumo Facing) seem to work when I modify the code to not set `WINEARCH`. On that note, `WINEARCH` appears to be set improperly in some cases because a game can be 32bit but the custom command can be 64bit.

However these days, Wine is almost always ran as 64bit, even with 32bit executables. So maybe in future I'll enforce all executables to run as 64bit with Wine, just like Proton.

For now, though, this is not really an issue, as it *is* actually a compatibility problem with Steam games. If I were to guess, I would say this is related to DRM. Steam games running with the Proton script usually copy/create a Steam.exe file in the prefix, which is executed with games and used to validate the DRM (as it sees Steam.exe running in the prefix, so it can call out to Steam and make sure you actually own the game and all the other DRM shenanigans). But when running with Wine it doesn't do this, because the Steam.exe isn't started (afaik this is started by the `proton` Python script), and even if it was, Wine executions run in a separate prefix (inside a game's compatdata, STL creates a `wfx` prefix alongside the `pfx`). So probably, only DRM-free Steam games would work.

EDIT: Quite a while later, but if cutscene compatibility is what you're concerned with, you should raise this upstream. There may also be other workarounds/winetricks that can be used, and it might also be worth trying Proton-tkg and its various flavours (such as one based on a more vanilla Wine). But generally speaking, using Wine with Steam games may not work. I wonder if symlinking the Steam exe to the `wfx` would mitigate DRM concerns but I doubt it, that seems ridiculously easy... However games that require various setup tasks such as DirectX will be missing those when running in the `wfx`. I wonder as well if an option to run games in the Proton prefix using Wine would work but I don't think that would end well.
