### ISSUE TITLE
Cannot select Proton Experimental as Proton version without an infinite loop occuring.

### ISSUE THREAD

**Issue by ProjectSynchro** [sonic2kk/steamtinkerlaunch#850]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Nobara 38
- Installation Method: ProtonUp-Qt

## Issue Description
When selecting a Proton Experimental version in steamtinkerlaunch, the game will refuse to launch, and steamtinkerlaunch also refuses to be configured as whatever startup logic that is running to select the correct Proton version is failing to do so.

In the logs I see a lot of repeated instances of:
```
Fri 07 Jul 2023 12:33:33 AM EDT INFO - setRunWineServer - Initiated from 'setNewProtVars'
Fri 07 Jul 2023 12:33:33 AM EDT INFO - fixProtonVersionMismatch - Mismatch for 'experimental' Proton version - Looking for updated Proton Experimental
Fri 07 Jul 2023 12:33:33 AM EDT INFO - fixProtonVersionMismatch - Found potential replacement for Proton Experimental with 'experimental-bleeding-edge-8.0-48973-20230705-p972f98-w043a50-d6be1f6-vc1d24a'
Fri 07 Jul 2023 12:33:33 AM EDT INFO - switchProton - Switching used Proton and its Variables to version 'experimental-bleeding-edge-8.0-48973-20230705-p972f98-w043a50-d6be1f6-vc1d24a'
Fri 07 Jul 2023 12:33:33 AM EDT INFO - switchProton - Requested Proton version 'experimental-bleeding-edge-8.0-48973-20230705-p972f98-w043a50-d6be1f6-vc1d24a' found under '/home/synchro/.local/share/Steam/steamapps/common/Proton - Experimental/proton'
Fri 07 Jul 2023 12:33:33 AM EDT INFO - setNewProtVars - Setting new Proton Variables based on '/home/synchro/.local/share/Steam/steamapps/common/Proton - Experimental/proton'
Fri 07 Jul 2023 12:33:33 AM EDT INFO - setNewProtVars - Continuing with RUNPROTON='/home/synchro/.local/share/Steam/steamapps/common/Proton - Experimental/proton'
```

## Logs
[1328670.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11974649/1328670.log)

**Comment by sonic2kk** [comment]
This can happen if you update the Proton Experimental version and then launch STL without restarting, as it's looking for a Proton Experimental version that was replaced.

Each compatibility tool has an internal name in its toolmanifest file. Proton Experimental versions are named `experimental-<isodate>`. So if a version was released on June 1st for example it would be `experimental-20230601`. If a new version was released on July 1st, it would then become `experimental-20230701`. STL is still looking for the old version and it doesn't know there is a new Proton version updated because of how it caches *internal* Proton tools (i.e. the ones in a libraryfolder, like Proton Experimental). Removing `/dev/shm/steamtinkerlaunch` gets it to recheck.

Try removing `/dev/shm/steamtinkerlaunch` and retry launching STL, it should resolve the mismatch.

**Comment by ProjectSynchro** [comment]
Awesome, that seems to have fixed the issue I was seeing.

Not sure if I should open another issue for this, but if I try and launch an EA Desktop (Mass Effect Legendary Edition in this case), I am getting issues launching:
![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/5131712/e14d7d5d-8c5d-4b83-92d2-b9fa17e9727f)

This is only seen when I try and launch the game with STL, I have nuked my wineprefix to make sure there wasn't some issue leftover from the previous one. I am launching the game with FlawlessWidescreen, but this occurs regardless if there is another application running or not.

**Comment by sonic2kk** [comment]
EA games are known to not work, some people have had success but I have not ever since the migration to EA App instead of Origin. Ubisoft Connect games also seem to not work in my experience, but others again have had success. I never have, EA games usually don't work on my system to begin with so I never bothered investigating much.

You might have success if you try launching the game without STL first so it can do a proper set up. You might also want to avoid using stable STL, it's very outdated now and maybe some things in git can improve support.

But no need to open an issue, this is a wontfix on my end (though a PR is welcome). Glad the original issue is resolved though :-)

EDIT: I would also check to make sure the Steam Linux Runtime - Sniper is installed
