### ISSUE TITLE
Reshade errors in Elden Ring

### ISSUE THREAD

**Issue by lgdsgd2000** [sonic2kk/steamtinkerlaunch#852]
## System Information
- SteamTinkerLaunch version: <v14.0.20230702-3>
- Distribution: < ArchLinux >
- Installation Method: <-git from AUR>

## Issue Description
<I launched the game with reshade enabled and got this error on ArchLinux with kde wayland.
![reshader](https://github.com/sonic2kk/steamtinkerlaunch/assets/75785515/497bb279-839b-44a1-a097-849393e98439)
This seems to be reshade‘s error?
>

## Logs
<[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11991287/steamtinkerlaunch.log)
>

**Comment by sonic2kk** [comment]
I'm not sure how this is a SteamTinkerLaunch bug. If a game is not compatible with reshade on Linux there's nothing I can do, sorry. The game has gotten to the point of trying to load reshade, if it fails there could be a few issues but none that STL can do anything about. As you pointed out this looks to be a reshade issue, meaning STL has installed reshade. Sometimes reshade compatibility breaks on Linux, an older version may fix this (STL allows you to select the reshade version). This could also be a game bug or a driver bug, or a simple incompatibility with reshade on Linux. There's nothing I can do about any of these cases.

Also, Elden Ring implements two pieces of malware called "Easy Anti-Cheat" and "Epic Online Services". These are known to block tools like ReShade, and games which use these may also not function properly when using a tool like SteamTinkerLaunch (even with no additional configuration).

**Comment by lgdsgd2000** [comment]
Thanks! I just heard about STL and confused about this amazing tool.Sorry for the hasty issue.

**Comment by zany130** [comment]
@lgdsgd2000  This could be because of missing header files for the shaders or even conflicting files. 
it could theoretically be an STL issue if the header files (`.fxh` files) are not placed in the right location. Or even missing textures. You would have to check the reshade log that's written to the game directory and check why it failed. Also, you may have better luck asking in the reshade discord and if it is a case of files not being placed correctly I can take a look if it is a bug in STL
