### ISSUE TITLE
Missing Text in Menus

### ISSUE THREAD

**Issue by Nano-Ocelot** [sonic2kk/steamtinkerlaunch#864]
## System Information
- SteamTinkerLaunch version: Both 12.12 and latest git (20230717)
- Distribution: OpenSUSE
- Installation Method: Tried manual build and install as well as ProtonUp-qt

## Issue Description
Some text is missing in menus.

## Screenshots of Issue
![Screenshot_20230611_194637](https://github.com/sonic2kk/steamtinkerlaunch/assets/34014750/19041943-602a-4e4c-b28f-9920e0e8a8fc)
![Screenshot_20230721_220312](https://github.com/sonic2kk/steamtinkerlaunch/assets/34014750/cc8be369-51c2-4cdf-b42d-0e5f04de1632)
![Screenshot_20230721_220333](https://github.com/sonic2kk/steamtinkerlaunch/assets/34014750/dd4cd24e-ceac-4463-b4c9-adb4c495547c)

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12135492/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
That is odd, it sounds like your language files haven not updated. I guess tooltips are missing also?

It may be possible that you have lingering v12.12 language files in a system directory that have not been fully removed, and STL is preferring those over the updated langfiles from the local ProtonUp-Qt install. I can see from the attached log that it is pulling language files from `/usr/share/steamtinkerlaunch/lang/english.txt`, and also that STL is being run from `~/stl/prefix`, so you are using a local install with some system-wide files present, which could be the root cause here.

It isn't recommended to have two STL installs, or to have a partial one left behind when switching from, say, a root install/package manager install to using a local install with something like ProtonUp-Qt.

If you have a lingering root STL install, you can uninstall it from any up-to-date STL Makefile with `sudo make uninstall`. Then, you can try removing your `english.txt` file from `~/.config/steamtinkerlaunch/lang) (or whichever language you are using, the logs just suggest English). Then, re-run the correct version of STL (in this case probably STL-git installed via ProtonUp-Qt). 

Hopefully this resolves your issue.

**Comment by Nano-Ocelot** [comment]
Also should mention that I've tried removing all config files and even a full manual removal of all STL files. Neither solved the issue.

**Comment by sonic2kk** [comment]
I am not referring to config files, I'm referring to files stored in the system directories where STL is installed after a root install.

I can see from the attached log that STL is pulling language files from `/usr/share/steamtinkerlaunch/lang`, but you are running from `~/stl/prefix`, so there is a mismatch of installations here. Try running the Makefile with `sudo make uninstall` to remove any lingering/outdated files from system directories, and removing any existing language files from `~/.config/steamtinkerlaunch/lang`.

```
Fri Jul 21 10:03:22 PM EDT 2023 INFO - setflatpak - started SteamTinkerLaunch from /home/Rylee/stl/prefix/steamtinkerlaunch
...
Fri Jul 21 10:03:22 PM EDT 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Fri Jul 21 10:03:22 PM EDT 2023 INFO - loadLangFile - Language from command line is 'english'
Fri Jul 21 10:03:22 PM EDT 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/usr/share/steamtinkerlaunch/lang'
Fri Jul 21 10:03:22 PM EDT 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Fri Jul 21 10:03:22 PM EDT 2023 INFO - loadLangFile - Found user-installed /home/Rylee/.config/steamtinkerlaunch/lang/english.txt, attempting to update it
Fri Jul 21 10:03:22 PM EDT 2023 INFO - loadLangFile - Found lang file to replace the existing user-installed file with under '/usr/share/steamtinkerlaunch/lang/english.txt'
```

As you can see here, it is replacing the language file in the STL config folder with the one it found in `/usr/share/steamtinkerlaunch/lang`, but STL is installed to, or at the very least being launched from, `/home/Rylee/stl/prefix/steamtinkerlaunch`. For root installs, STL will pull from system directories like `/usr/share` (as that's where the Makefile installs them to), but for non-root installs it will pull from `~/stl/prefix` (or wherever the STL folder is located). This is because the expectation is that if there are files in `/usr/share/steamtinkerlaunch` that we're using a root install. It is not a good idea to end up with partial installs of either method.

**Comment by Nano-Ocelot** [comment]
> I am not referring to config files, I'm referring to files stored in the system directories where STL is installed after a root install.
> 
> I can see from the attached log that STL is pulling language files from `/usr/share/steamtinkerlaunch/lang`, but you are running from `~/stl/prefix`, so there is a mismatch of installations here. Try running the Makefile with `sudo make uninstall` to remove any lingering/outdated files from system directories, and removing any existing language files from `~/.config/steamtinkerlaunch/lang`.

Oh whoops I didn't mean that last comment to be a reply. I didn't notice a response yet.

I thought I managed to get all stray files when I removed it all last time. I'll try again what you mentioned and report back.

**Comment by sonic2kk** [comment]
I am not able to reproduce any issue with missing strings, but for development purposes, I always run with a root install.

![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/7917345/6de91668-e41c-4a0c-98a0-6b2b55fc9047)

The Steam Deck uses a local install to `~/stl/prefix` and STL displays fine on my Steam Deck. I don't have my laptop handy to test there at the moment, but I suspect this is something to do with outdated language files being pulled in, as it seems like strings from v12.12 are present but strings from git are the only ones missing.

**Comment by Nano-Ocelot** [comment]
That fixed it! I must've done something wrong last time I tried that. Oh well. Thanks!

**Comment by sonic2kk** [comment]
No problem, it's also possible to manually remove the system-wide files if you'd ever like to, by manually performing the steps in the Makefile: https://github.com/sonic2kk/steamtinkerlaunch/blob/master/Makefile#L20-L27

You can also use this as a reference in future to see if there are any lingering install files.

Happy tinkering!
