### ISSUE TITLE
HedgeModManager installation fails due to winetricks being missing

### ISSUE THREAD

**Issue by termdisc** [sonic2kk/steamtinkerlaunch#868]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Bazzite-Deck on a Steam Deck
- Installation Method: ProtonUp

## Issue Description
Bazzite is an immutable Fedora OCI image that's similar to Kinoite or Silverblue. It is intended to be a SteamOS replacement, which also means it does not have a system-wide wine or winetricks installed. However, SteamTinkerLaunch does not recognize the similar environment to SteamOS.

When attempting to run `steamtinkerlaunch hmm install`, any functions based on winetricks such as dependency installation will fail. Adding the `winetricks` script to `~/stl/prefix/` will alleviate this issue.

```
cd "${HOME}/stl/prefix"
wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x winetricks
```

## Logs

[installHMM_protonrun.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12197139/installHMM_protonrun.log)
[extWine64Run.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12197140/extWine64Run.log)
[WINETRICKS.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12197141/WINETRICKS.log)
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12197142/steamtinkerlaunch.log)

**Comment by termdisc** [comment]
Additional thought: a check for the existence of `winetricks` may be feasible, and if it is not found, add the script to the prefix folder.

I communicated this to the bazzite devs, and they are adding it as part of the image.

**Comment by sonic2kk** [comment]
Thanks for opening an issue! I hadn't heard of Bazzite, I'm flattered STL is being considered for the distribution :-)

> Additional thought: a check for the existence of winetricks may be feasible, and if it is not found, add the script to the prefix folder.

This is already present. SteamTinkerLaunch has its own configuration folder at `~/.config/steamtinkerlaunch`, so it would not be downloaded to the prefix folder. Instead, STL has a separate option to download Winetricks locally that is not enabled by default outside of SteamOS and Flatpak.

STL does have logic to download Winetricks manually, as it does this on SteamOS and Flatpak where it cannot access systemwide Winetricks even if it were available. In these cases, it will always download Winetricks to `~/.config/steamtinkerlaunch/downloads/winetricks`. It will also manage keeping it up-to-date with `--self-update`. This is why Winetricks works on SteamOS.

When Winetricks is not available on the system and we're on SteamOS, Flatpak, or `DLWINETRICKS` is enabled, SteamTinkerLaunch will download Winetricks itself and store it. However outside of SteamOS and Flatpak, it will not do this automatically, because in most cases the user can just install it themselves with their package manager.

For cases where this is not possible/desired, there is an option in the Global Menu to Download Winetricks (`DLWINETRICKS`), under "Wine Options". Enabling this checkbox will get SteamTinkerLaunch to download Winetricks, and then HMM should install as expected (or anything else that requires Winetricks). Each time something requiring Winetricks is called in STL, we call `chooseWinetricks` to ensure the path is set. This means that if a user tries to install in this case HMM without Winetricks installed, it will be fetched and installed as part of the `chooseWinetricks` call as a pre-install step for HMM.

![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/7917345/216ae580-75bd-41db-be0c-5811f12ee598)

To surmise, STL checks for Winetricks like this:
1. If it already has a path to a valid Winetricks installation stored in its config files, it will use that.
2. If it has not previously found Winetricks, it will look for systemwide Winetricks
3. If systemwide Winetricks is not found, it will branch:
    a. If on SteamOS or Flatpak, download Winetricks
    b. If the user has enabled Download Winetricks on the Global Menu, download Winetricks
    c. If none of these, do nothing

So in the end this is not a SteamTinkerLaunch bug, it is just that this is not the default behaviour outside of a handful of very specific setups.

<hr>

If the developers are adding STL as part of the image and are wanting a better out-of-box experience with Winetricks, they can do a couple of things which would be much preferable alternatives to including Winetricks in the `prefix` folder:
1. Manually set the value in the STL global config file themselves at `~/.config/steamtinkerlaunch/global.conf` - Set `DLWINETRICKS=1`
2. Execute `steamtinkerlaunch set DLWINETRICKS global 1` as a post-installation step, which is a command to update the global config file value.
3. Manually store Winetricks out-of-the-box at `~/.config/steamtinkerlaunch/downloads/winetricks`, though as mentioned when trying to do things that require Winetricks such as install HMM, STL will fetch it if `DLWINETRICKS=1`, so this should not strictly be necessary. 

<hr>

I hope this clears things up for you, this shouldn't be an STL bug so if this fixes the problem feel free to close the issue. And if it resolves it please get in touch with the Bazzite devs again so they don't include `winetricks` in the prefix folder.

Thanks!

**Comment by sonic2kk** [comment]
If I'm not mistaken, it looks like Bazzite might just install Winetricks on the system now: https://github.com/ublue-os/bazzite/commit/341c60773bb44b1c6a220c1f27044d4a3cae1ec9

I think this issue can be closed then, as either Bazzite can configure STL to use Winetricks, or they can use the system Winetricks. In my opinion, installing Winetricks to the system is probably the better solution.

Thanks for the report nonetheless!
