### ISSUE TITLE
settings menu requires yad

### ISSUE THREAD

**Issue by ghost** [sonic2kk/steamtinkerlaunch#87]
Manjaro KDE: current.

With run options set to `stl %command%` I can see that stl runs properly as I get a system notification.
However I do not see any windows, requests, or prompts of any sort for the settings menu.

In order to eliminate the possibility of oudated configs being the cause, I had deleted `~/.config/stl`.
This did not change the behaviour.

**Comment by ghost** [comment]
I have installed `yad` and resolved the issue. I didn't think a dependency was required for the settings menu.

**Comment by frostworx** [comment]
I'm not very happy with the situation as well.
From my [requirements in the README](https://github.com/frostworx/steamtinkerlaunch#requirements):
```
zenity (in fact yad optionally replaces this and has more features, but zenity is the wider spread package and one of both is required)
...
Yad for the GUI (yad is only required for the optional Settings Menu. For the Editor Dialog zenity is enough, so yad is optional)

```
_I already fixed the related issue https://github.com/frostworx/steamtinkerlaunch/issues/84 offline
*("internal" dependencies will be no longer optional)* and also improved the dependency check on yad/zenity_

yad is only in AUR, zenity is in the official repo.
Arch package management doesn't have any **OR** dependency, so the options are:
- leave both optional
- depend on zenity as it is the more official package (won't happen, because I leave the settings on by default *(should be better described in the readme))
- depend on yad (would be function wise the best idea, but forces a pull of a community package which might not even be used, I'd prefer that function wise though)

ping @alanjjenkins

**Comment by frostworx** [comment]
I'll make yad a hard dependency and zenity optional with the next release
