### ISSUE TITLE
Steam Deck - STL Menu not showing Game Menu Options

### ISSUE THREAD

**Issue by SilvertongueRED** [sonic2kk/steamtinkerlaunch#877]
## System Information
- SteamTinkerLaunch version: 12.12
- Distribution: SteamOS (Deck)
- Installation Method: From this site (not flatpack...not sure what package manager is...) 

## Issue Description
Just installed STL from this site on my deck via the code/command line (latest release) and not seeing any options appear in the Game Menu (or Default Menu for that matter). Also, often after using STL as the launch option, it'll prevent me from launching the game at all.

## Logs
Will update with log once I find where that lives on my deck...

**Comment by sonic2kk** [comment]
STL cannot be used as a launch option on Steam Deck. The launch option is only for Native Linux games, as noted on the Readme, and due to a Steam Client limitation it appears that this does not work on SteamOS (#630).

I am not sure what you're referring to though outside of this, do you mean when selecting STL as a compatibility tool, you're not seeing the Game Menu? Does the button just not do anything from the Main Menu? Or are you perhaps saying you're not seeing the Wait Requester at all, for any game?

> Will update with log once I find where that lives on my deck...

It's in the same place the issue told you, `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`. This also matches the location the log is most likely available on your regular Linux Desktop.

<hr>

I am getting the feeling that this is not an STL bug but a question on how to use SteamTinkerLaunch, which is fine but generally better suited for forums and not on this issue tracker.

**Comment by sonic2kk** [comment]
I tested with the most recent Steam Client beta and STL v12.12, and had no issues when testing with a couple of Proton games. I tested several menus including the Game Menu and they loaded no problem. I didn't try any native games as I didn't find any handy.

I think more details on how you're trying to use SteamTinkerLaunch may be required. I'm not totally clear on what the issue is. I was thinking perhaps there was a Steam Client update/regression that broke SteamTinkerLaunch somehow, but I couldn't find any sign of that.

<hr>

Also, as an aside, please do not use SteamTinkerLaunch v12.12. It is incredibly outdated, please use SteamTinkerLaunch from git (either by cloning the repo or using ProtonUp-Qt). I am not planning another SteamTinkerLaunch release for the foreseeable, so stick to using git for updates.

**Comment by SilvertongueRED** [comment]
Sorry as I'm very confused and new to Linux. 

This is all a bit too much for me and I might just wait for a easier Decky plugin for Reshade as that's the only thing I wanted out of this. Is there a way to uninstall this program?

**Comment by sonic2kk** [comment]
SteamTinkerLaunch is not for users who are new to Linux. It is for tinkerers, hence "Steam**Tinker**Launch". It is primarily a Linux Desktop utility for experienced Linux users. Steam Deck support is available for users who may want to use it there for any reason but it is, at its core, an advanced utility program.

You can uninstall SteamTinkerLaunch by running `steamtinkerlaunch compat del` (instead of `compat add` from the installation step) and then removing the downloaded files.

This is likely not a SteamTinkerLaunch bug, perhaps you just didn't set SteamTinkerLaunch as the compatibility tool. But if you are new to Linux, this is likely not the tool for you, which is fine :-) Users who only want one feature like ReShade out of STL are the ones most likely to have a bad experience, as they are not advanced users/developers.

Closing.

**Comment by SilvertongueRED** [comment]
Thanks for the uninstall help. I'll be honest in that I did download the latest version which is still listed as 12.12 on your home page for this. And also, I followed the instructions exactly and selected it as a compatibility tool. I installed it via the Konsole like requested too. I know now this is probably too advanced for me. Thanks.

**Comment by sonic2kk** [comment]
> I'll be honest in that I did download the latest version which is still listed as 12.12 on your home page for this

This is the latest **stable** release, not the latest git version. There are [many changes](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog#changes-in-latest-master) not available in any version on the Releases page.

**Comment by Slvrtnge** [comment]
In closing, I do want to say I love your Little Inferno avatar pic, so don't think I didn't clock that tribute to one of my favorite games. Also long live World of Goo. Take care :)

**Comment by SilvertongueRED** [comment]
In closing, I do want to say I love your Little Inferno avatar pic, so don't think I didn't clock that tribute to one of my favorite games. Also long live World of Goo. Take care :)

**Comment by sonic2kk** [comment]
I think this is the first time anyone has noticed it, nice to see some appreciation for it (and Tomorrow Corporation in general, where the future is... Tomorrow!) :-)
