### ISSUE TITLE
Cannot mount AppImage, check FUSE setup

### ISSUE THREAD

**Issue by callmeEthan** [sonic2kk/steamtinkerlaunch#878]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: SteamOS 3.5 (steam deck)
- Installation Method: Protonup-qt

## Issue Description
Tried to launch games with steamtinkerlaunch compatibility but there was no 'wait requester', game launch normally after a bit.
When I try again in desktop mode, some notification pop up saying "Cannot mount AppImage, check check your FUSE setup". 

## Logs
[non-steam-game.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12282841/non-steam-game.log)
[steam-game.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12282839/steam-game.log)

**Comment by sonic2kk** [comment]
Is the AppImage corrupt/invalid? Check the file size at `~/stl/deps/usr/bin`. You can also try removing the `deps` folder and re-trying again.

This happened once before in #704 and it was due to a network issue where Yad was not downloaded properly.

I don't have SteamOS 3.5, but STL works fine on my Steam Deck.

<hr>

Also, please do not use STL v12.12. It is incredibly out of date.

**Comment by callmeEthan** [comment]
Thank you, it is as you said. Deleting deps folder and reinstall it again fixed it.
I thought v12.12 is the latest version though, what is the latest version now?

**Comment by sonic2kk** [comment]
The latest version is the latest git commit. v12.12 is only the latest "stable" release which was released months ago. It's usually a good idea to use SteamTinkerLaunch-git, which is available also from ProtonUp-Qt :-)

Closing as this is resolved now. Happy tinkering!
