### ISSUE TITLE
Fork Functionality 

### ISSUE THREAD

**Issue by Laz55** [sonic2kk/steamtinkerlaunch#879]
## System Information
- SteamTinkerLaunch version: 
- Distribution: 
- Installation Method: 

## Logs

Hi

On Steamdeck  thr following  function works.for most Trainers /cheats ;however  Flingtrainers latest  updates  will no longer launch. 

For example  Dave The Driver latest  Trainer program  will not pop up when  launching it as a fork it seems the fork function will only work 
for older  Trainers. Any Trainer made in late July made my Flingtrainera will no longer work on fork function on Steamdeck  even on Desktop  mode.

**Comment by sonic2kk** [comment]
Sounds like an application-specific issue the same as #875. Can't reproduce on Linux Desktop and the conclusion in that issue was that this was a Steam Client issue/bug.

Using the "inject" option fixed it for the user in that issue. Closing as duplicate of that issue. Please note that you can also search issues on GitHub to find users who previously had similar issues and what the fix was.

As mentioned in your previous issue reports though, in future please remember to attach logs and other system information asked in the issue template.

I will also note for anyone else reading this in future that issues with third-party applications are not up to SteamTinkerLaunch to fix. If newer trainer applications aren't working perhaps since they work with inject, they expect some application process to be running. But that's not really something STL should deal with, compatibility with third-party applications is never guaranteed, but STL aims to give the tools to help with the tinkering process to get them to work.

**Comment by Laz55** [comment]
Hi


What do you mean as in inject  ? I am a bit confused is there another
setting I need too click?

**Comment by sonic2kk** [comment]
There is an inject command option on the Game Menu. It will override the Fork option. See the linked issue where that user mentioned that using this option fixed their trainer thing.

**Comment by Laz55** [comment]
Hi

The individual  was very specific  there is two options too tick is is it.

1. Injection  custom command  or


2. Use IGCSInjector?

**Comment by sonic2kk** [comment]
You want "Inject custom command". The other option, IGCSInjector, is for a separate DLL injection tool. It is unrelated to custom commands.

**Comment by Laz55** [comment]
Hi

Okay do I still have too   "Use custom command" ticked along with fork
command?


Or just tick the injector?

**Comment by sonic2kk** [comment]
You still have to have your custom command enabled to inject it.

This information should be available [on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Custom-Command). Tooltips should also give you some brief information on the options.

You're best checking the wiki if you have questions or using other forums online to ask questions on STL usage, as this issue tracker is for bugs/enhancement requests. And issues with third-party programs are not bugs.

**Comment by Laz55** [comment]
Hi


Okay just too be clear I tick the following:


1. Fork Command

2. Use Costum Command

3. Inject  Command


Correct?

**Comment by Laz55** [comment]
Hi


I tested  it and it seems that it's not STl ,but the developer  who made
the Trainer such as Dave The Diver Flingtrainer  .

For some reason his current  updated trainers will no longer launch  with
Fork function .


The inject  Command  does not work at all tested  it with older trianers
for other games and even those wouldn't  work with inject
Command;however,  it does work with the fork function  as long as it's not
a trianer that was released  in late July/2023 ,so I think the developer
might have made the Trainer using windows 11 which may have effected STL
function  or  steam is broken .

**Comment by sonic2kk** [comment]
If there is an issue with Wine compatibility, there is not much I can do. Feel free to tinker with other Proton versions or changing the reported Windows version in Wine. Looking online for general tweaks to get the program to run under Wine may help.

**Comment by Laz55** [comment]
Hi

Yes I will look into downloading  different  protons;.  I honestly  can't
stand Linux it's nothing, but trouble  shooting.


I forgot  too mention  I tried a few versions and it will glitch  and say
you need too install Microsoft C++.
