### ISSUE TITLE
YAD file is missing. How can Install it in ChimeraOS?

### ISSUE THREAD

**Issue by lm209** [sonic2kk/steamtinkerlaunch#885]
Hey there, can anybody explain me, how to Install the Missing yad in ChimeraOS?
Thanks 🔥

**Comment by sonic2kk** [comment]
This is not really the place to ask a question like this, you'd be better off asking how to install Yad on ChimeraOS on a more general forum. This is a GitHub issue tracker for reporting bugs and requesting features, not a support forum.

You may be able to use the Yad AppImage on ChimeraOS, if it is not available as a system package. Running `steamtinkerlaunch yad ai` may be able to download it for you, as noted on [the SteamTinkerLaunch wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Yad). However, SteamTinkerLaunch has not been tested on ChimeraOS, I have not used it and know very little about it.

It appears they might have a Discord server from looking on the forums, I'd recommend asking there.

Keep in mind also that SteamTinkerLaunch is for technical users, so if you are not experienced in getting your hands dirty with tinkering, you may not have a good experience with SteamTinkerLaunch.

**Comment by sonic2kk** [comment]
Since this has come up before I have tried improve documentation to make it a bit clearer that a Yad AppImage can be used, and that if no path is specified SteamTinkerLaunch can attempt to download the one Frostworx built for Steam Deck support.
- FAQ: https://github.com/sonic2kk/steamtinkerlaunch/wiki/FAQ#how-can-i-install-yad-on-my-distribution
- Troubleshooting: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Troubleshooting#yad-is-missing-from-my-system

I would also recommend to read the dependencies section of the Installation wiki very carefully, which already covers this.
