### ISSUE TITLE
Vortex not deploying mods and not handling nexus mod links

### ISSUE THREAD

**Issue by Lii-Kun** [sonic2kk/steamtinkerlaunch#892]
## System Information
- SteamTinkerLaunch version: Current git v14.0.20230902-1
- Distribution: Garuda Linux (arch)
- Installation Method:  built from git

## Issue Description
*only tried with Starfield*
Vortex isn't installing mods. It will make folders but not put the files in the folders. Also nexus mods mod install links aren't working.

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12507886/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
I mean, Starfield is just out, and it also isn't in the SteamTinkerLaunch games list, so I would assume this is why. If you've only tried Starfield and it isn't working, this is probably why. I'm not sure why you would expect support for a game that *isn't even officially out yet*.

Outside of this, issues modding games are not SteamTinkerLaunch issues. You're on your own figuring out how to get mods to work once Vortex is installed and running. I don't use or like Vortex, but last time I tried a few months back, Borderlands 2 worked.

**Comment by sonic2kk** [comment]
Another thing to mention is you should make sure the version of Vortex you're using supports Starfield. See this line:

> Sun Sep  3 04:59:17 PM CDT 2023 SKIP - prepareVortexGame - Skip game '1716740' is not supported by Vortex or the ID is not listed in '/usr/share/steamtinkerlaunch/misc/vortexgames.txt'

Make sure you're using an up-to-date Vortex that can deploy mods for Starfield, probably a beta of some kind.

**Comment by sonic2kk** [comment]
Pushed Starfield into `vortexgames.txt`, it's there in master now. You could try updating to `v14.0.20230903-1`, but as mentioned, there is no guarantee of mods working on Linux, ***ever***. Especially not for a game that is not officially out yet. But it has been added to `vortexgames.txt` so if/when it works with Vortex on Linux, it should be picked up by STL.

Since deployment isn't working that indicates a different issue than it simply not being present in `vortexgames.txt`, but /shrug. I have no plans to buy Starfield, and also no interest in doing mod troubleshooting for Vortex. If it still doesn't work, and mods aren't being deployed by Vortex, that isn't SteamTinkerLaunch's problem.

**Comment by Lii-Kun** [comment]
Yea the game isn't fully out yet but vortex supports it  and there are a bunch of mods out already. Anyway putting Starfield into that file seems to have done the trick.  Vortex is deploying mods fine now, and its accepting the nexus links. Thank you!

**Comment by sonic2kk** [comment]
I'm quite surprised that that worked, but I'm glad it did! I guess adding a game to `vortexgames.txt` does more than I thought.

Also, I forgot to mention about the Nexus Mod links that you mentioned: These links are notorious for not working in general, and the advice is to avoid them on any operating system at all costs. Do not use 1-click mime buttons, download mods manually.

Happy gaming!
