### ISSUE TITLE
SteamDeck Vortex Install stalls or doesn't want to install

### ISSUE THREAD

**Issue by shadowcyberdeck** [sonic2kk/steamtinkerlaunch#901]
## System Information
- SteamTinkerLaunch version:  v12.12
- Distribution: SteamOS
- Installation Method: ProtonUp-QT

## Issue Details
After installing STL via ProtonUp-QT, while steamDeck is in deaktop mode and set Starfield to use it via compatability options. Launch Starfield, click "main menu" to get into the STL menu. Click "Vortex", then click "install". The vortex install halts either at the DotNet or "--installvortex - 'WINEDEBUG' ETC.'" progress bar, with no progress being shown.

## Logs
Steamtinkerlaunch.log file: https://mega.nz/file/hMJwDDSS#sN3LiaetLaehJWOyNtcbcfgz8eIsAK7ZSRBqyWXthUs

**Comment by sonic2kk** [comment]
SteamTinkerLaunch v12.12 is too old, it probably doesn't work. Delete your existing Vortex install and try again with SteamTinkerLaunch from git.

Please check the [changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog) in future to see if problems are resolved there.

<hr>

However, I will say that Starfield is not guaranteed to work. I would go into this expecting it to NOT work. You should not expect a game less than a few years old to be moddable on Linux. Likewise, I would also say not to expect Vortex to work, as they made very little effort to get things running under Wine.

Good luck, but I would say to abandon the idea of modding on SteamOS, to avoid all of the stress because ultimately, it is broken.

<hr>

Also, in future, you can upload your log file directly to GitHub, it supports direct file uploads.

**Comment by shadowcyberdeck** [comment]
Might want to update the install documentation.

**Comment by sonic2kk** [comment]
True, the documentation there still assumes STL automatically updates on SteamOS. I'll update it to note this. However, since SteamTinkerLaunch is for experienced Linux users, it's expected that users would try a git release before reporting bugs. [The issue template](https://raw.githubusercontent.com/sonic2kk/steamtinkerlaunch/master/.github/ISSUE_TEMPLATE/bug-report.md) also outlines this, suggesting to check the changelog beforehand.

I'll update the docs, and I'll also include a note that Steam Deck support is heavily secondary.

EDIT: [Steam Deck installation section](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation/_compare/6d04c2cb0087c2d7e5554c8a7586e44e2ea079dc) has been updated.
