### ISSUE TITLE
Wiki request: Add flatpak run --command=steamtinkerlaunch com.valvesoftware.Steam compat add

### ISSUE THREAD

**Issue by reddragonmps** [sonic2kk/steamtinkerlaunch#923]
## System Information
- SteamTinkerLaunch version: Flatpak
- Distribution: Arch Linux

## Feature Description

Today I needed to use SteamTinkerLaunch for one of my games and realized compatibility tools symlink had not been created. I searched through the wiki but did not find the solution I was looking for. Well, this is it. Use the `--command` argument to run SteamTinkerLaunch exectuable inside Steam Flatpak's enviroment. I think this needs to be added to the wiki because I have faced this same problem previously. Maybe in a troubleshooting section, like this:

Troubleshooting (Flatpak)

...

If you don't find SteamTinkerLaunch under Steam's compatibility tools (make sure you have Steam Flatpak installed), you need to create the symlink like in the other packaged releases. To do this you need to run `flatpak run --command=steamtinkerlaunch com.valvesoftware.Steam compat add`, then restart Steam. SteamTinkerLaunch should be listed now.

Flatpak mantainer is looking into it, but as long as the issue isn't resolved the wiki page should help you out fixing common problems like this one.

**Comment by sonic2kk** [comment]
As long as people work around the problem instead of helping to fix it, it won't be added to the wiki. The Flatpak maintainer explained as well that it doesn't affect everyone. I'm not keen on adding instructions so that users ignore the problem instead of trying to provide technical help to understand what this does, why it works, why only some systems need it, etc.

I appreciate the suggestion, but the answer is no, until more information is known about the issue.

**Comment by tfranken90** [comment]
Here's the link for anyone who is interested. 

https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/issues/110
