### ISSUE TITLE
reddit moderator wanted

### ISSUE THREAD

**Issue by frostworx** [sonic2kk/steamtinkerlaunch#928]
Hi,
when I gave up this project I also closed the corresponding subreddit [r/SteamTinkerLaunch](https://www.reddit.com/r/SteamTinkerLaunch) and changed its description to

**[THIS SUB IS DEAD AND UNMAINTAINED AND WON'T REOPEN]**

One might think this is obvious enough, but I still receive multiple join requests _(10 within that last 30 days)_
Apparently there is still demand for it, but I do neither have the time nor the up to date knowledge nor the motivation to maintain this myself
_(in fact I even lost steamtinkerlaunch itself mostly out of sight and also barely play anything anymore - maybe onme of BG3, Phantom Liberty or Diablo 4 (coming to steam) next winter(?))_

Therefore I'd like to ask here if anyone interested in moderating the subreddit - I'd suggest it would make sense to give it to someone who already contributed to the project before.

If there's no interest I will abandon the subreddit (maybe end of 2023) so anybody could pick it. In case it is picked by someone unknown to the project members, I'd suggest to leave a warning here.

happy coding/gaming!

**Comment by sonic2kk** [comment]
Wow, that is very surprising. If that many people for some reason want the subreddit I think it's good to open it again *if* someone can maintain it. I don't use reddit and I'm not interested in creating an account to maintain it. I keep a clear divide between the work I do here with development and issue tracking, and the rest of my life, and I don't want any bleedover. On that front, that would make a community-owned-and-operated forum ideal, to keep "junk" issues and usage questions out of the bug tracker.

<hr>

I do have a couple of concerns about the subreddit, though...

From my view, the hope would be that the subreddit could be a good community support forum and be a good community to share tricks and tips. But at the risk of sounding really harsh I worry that much like a notable amount of the issues filed here, people will just abandon it or create low effort posts without any useful information. Though it would be better for people who are looking for advice to use a subreddit rather than this issue tracker, there is no point to a community forum if everyone is asking questions and no one is answering, and the people who can answer aren't using these forums.

But on the other hand, it could be a good way to actually get some PRs into the project! Honestly, I think this is... massively optimistic, but I would still like more community development work!

<hr>

I think no matter who takes it over, the subreddit should remain explicitly unofficial. I won't be checking it and I'm sorry if this is too selfish but I really don't want anything to do with it :sweat_smile: On one hand that might be off-putting to someone who wants to maintain it, but on the other hand that also means since it's entirely independent of the project, you could have a lot more freedom with managing it -- I won't be breathing down anyone's neck. Just try your best to make sure people know not to come here and complain about the subreddit. Just as I will keep a clear line between the subreddit and repo, so should any subreddit moderator.

So if anyone wants to take it up please feel free to, but to be utterly blunt, keep me out of it :-) And also, make it clear that it's unaffiliated with this project now. If someone takes it up, absolutely best of luck to you, because you are a braver soul than I. It already takes a lot out of me managing this issue tracker, I'm not sure I could manage moderating a subreddit.

<hr>

If no one steps up by end of year, I would say close the subreddit entirely. If someone cares enough after that, they can make their own successor. But I could see an unofficial Discord server becoming more likely in that instance.

Thanks Frostworx, hopefully someone picks this up and can create a nice community, that may also ultimately end up creating more development interest here!

**Comment by frostworx** [comment]
Thanks, sonic2kk!

Wise decision to keep out of the reddit side. It was totally no fun to support "junk" issues _(of course there were also good requests)_ on the one side while coding on the other side here...

Keep the momentum going and have much fun!

**Comment by frostworx** [comment]
FYI: several more join requests dropped in after I opened this issue.

It also didn't help to rename the topic description to
"UNMAINTAINED! JOIN REQUESTS ARE IGNORED - MAINTAINER WANTED: https://github.com/sonic2kk/steamtinkerlaunch/issues/928"

Both that and the still low community activity in this project don't look too promising, but I'll wait some more weeks for someone willing to read and contribute :}

**Comment by sonic2kk** [comment]
I will lock this thread, if someone wants to step up and make some kind of SteamTinkerLaunch subreddit in future, please feel free to! But it should be clear that it's unofficial, and not moderated by me, and was created by the community, for the community.

I don't have much hope that someone will step up (I think if someone was going to, they would've did something by now), but just putting it out there that anyone is still of course free to make whatever community they want, as long as it's clear that it's unofficial :-)

Thanks Frostworx for posting about this though and bringing awareness, even if nobody came in the end. This issue is evidence that there was ample community outreach and no one came.
