### ISSUE TITLE
STL cant find proton versions

### ISSUE THREAD

**Issue by tetoNidan** [sonic2kk/steamtinkerlaunch#929]
## System Information
- SteamTinkerLaunch version: steamtinkerlaunch-v12.12
- Distribution: Arch Linux
- Installation Method: Chaotic AUR

## Issue Description

This is something I noticed yesterday when I manually installed a Proton-GE-8.16 directly to .steam/root/compatibilitytools.d, I could not find it in STL's dropdown when trying to switch proton versions in the STL's Baldurs Gate 3 Game Menu options. Proton-GE-8.16 shows in steam's compatibility dropdown just fine. I decided to try steams proton-hotfix from STL's Game Menu dropdown and went about my gaming session without issue. 

This morning I popped open STL to play Baldurs Gate 3  and I get the STL error popup:

`Requesting Proton 'proton-8.0-4' not found - trying to switch to a similar version`

Proton-GE-8.16 shows up in steams compatibility-tools dropdown and games will launch with it just like the version of GE from yesterday.  What is strange is that this is only happening on one game, Baldurs Gate 3.

I have launched FO4 and STL launches and plays game through MO2 without error, CP2077 launches to game as expected with and without MO2. The STL -> Global MO2 proton is set to 8.0-3c which is not in in the steam compatibility-tools dropdown at all? Also what's strange is that in CP2077 and FO4, I can set the proton version in STL -> Game Menu to protonGE-8.16 with no issues. I did change the STL -> Global Mo2 proton to protonGE-8-16 just to see if that was the issue. Didn't think so as that is just the MO2 proton version but I thought I'd try as that was the only setting that was set close to the error message proton version of 8.0-4 and the 8.0-3c isn't even in the Steam compatibility-tools dropdown. Was worth a shot but cant reproduce the issue outside of Baldurs Gate 3.

Looks like this is just a Baldurs Gate 3 issue.

## Logs

[STL's shm log](https://pastebin.com/pL794r03l)

## Side Note

Im the guy that was asking about Starfield MO2 compatibility and offered to test. It looks like I wont be able to so as I have a optimus laptop and Starfield won't even recognize my nvidia card at all, just the lighter AMD GPU.  Starfield launches with missing textures at a max framerate of 10FPS. Basically unplayable at the moment. Maybe a few years from now bethesda will fix the issue but others with real AMD GPU's will have MO2 support long before that. Sorry about that! 

As always Thanks sonic2kk!

**Comment by sonic2kk** [comment]
Did you restart your PC/remove `/dev/shm/steamtinkerlaunch` after installing this new Proton version? Also, Proton stable not being found could be because of a Proton version update, since Proton 8.0-4 just came out, it may have updated while Steam was opened.

Remember that when Proton versions update, you have to either manually remove `/dev/shm/steamtinkerlaunch` to clear the cached list of Proton versions, or restart your PC (which does the same thing). That has resolved the issue in the past (#850 recently, has come up before but I can't actually find the issues atm :slightly_smiling_face:)

Try removing that folder and seeing if your Proton versions work as expected :-)

> Maybe a few years from now bethesda will fix the issue but others with real AMD GPU's will have MO2 support long before that. Sorry about that!

No problem at all :-)

This is more than likely an issue a Wine/Nvidia driver bug, I don't think it's up to Bethesda to fix in this case :-) I recall particularly for laptops with Nvidia GPUs that this comes up every so often, and a Proton update is usually what fixes it.

Fwiw, Starfield also doesn't run great under Proton for now. I think this is fixed in Mesa-git but not yet in Mesa 23.2.1. I got the game with my 7900XTX and gave it a quick try, but sometimes it dips below 60fps and has 100% GPU usage no matter what graphics settings or resolution is used, even with the latest vkd3d-proton build (which fixes Bethesda's incompetent usage of D3D12). Other games don't have this issue (RE4R runs at 4k60 max with only an average 60% GPU usage, for example), so it's specific to Starfield.

So Starfield is just not well supported on Linux *for now*, you aren't missing too much on Nvidia. I would also not get your hopes up that Starfield mods will work on Linux, from what little I have seen with people trying with Vortex, it doesn't work (and it's not up to STL or other similar tools to fix that, it would have to be fixed in Wine).

**Comment by tetoNidan** [comment]
Removing `/dev/shm/steamtinkerlaunch` did the trick. Was unaware that STL's proton cache had to be reset when installing new protons. Don't remember having to in the past but it's good to know what the issue was and such an easy fix. Well noted now!

As for the Starfield I completely understand what you laying down. I figured it was bethesda because even on windows people are having a hard time getting playable FPS using nvidia from what I've read. I seem to remember seeing problems with optimus laptops in windows not finding nvidia as well, with user fixing issue by turning MUX in bios off  to play. An issue for me as I do not have a MUX. On protondb the only people that seem to get starfield to work remotely well are on AMD, there are a few people with similar specs using nvidia(not optimus though) being able to at least play at low FPS. Makes sense that it could/would be a wine issue though.

I'll close this user error reported as a bug. Thanks for your time once again sonic2kk!

**Comment by sonic2kk** [comment]
Yeah, I thought the reset thing was written down somewhere on the troubleshooting wiki page but I guess not. It's come up often enough that I think it's worth adding :-) I'll do it when I have some free time (or maybe I said this in the past, and that's why it isn't written anywhere 😅)

I wasn't aware Starfield had issues with Nvidia on Windows, too. Maybe I was giving Bethesda a little too much credit ;-)

**Comment by tetoNidan** [comment]
> I wasn't aware Starfield had issues with Nvidia on Windows, too. Maybe I was giving Bethesda a little too much credit ;-)

From what I've read starfield is highly optimized for AMD kind of like cp2077 was optimized for nvidia. Time will tell, I'm not too worried about it. Oldrim wouldn't play for me on linux for the first couple of years either! The only two bethesda games I haven't bought on a super sale and I don't really have a problem giving developers my money. I know that it'll work well one day. The moding issues might be sorted by that time anyway, win win!

**Comment by sonic2kk** [comment]
> From what I've read starfield is highly optimized for AMD kind of like cp2077 was optimized for nvidia

Fwiw, these optimisations don't apply to Linux, since the driver stack is different :-)

**Comment by tetoNidan** [comment]
Truly sorry to hear that, I'm sure it will get better though! Proton seems to progress fast and ages like cherry barreled oak cask scotch, better every year.

**Comment by sonic2kk** [comment]
Completely forgot, but added this to the [Troubleshooting wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Troubleshooting#steamtinkerlaunch-proton-version-list-isnt-updating) now.

**Comment by tetoNidan** [comment]
Thanks sonic2kk!
