### ISSUE TITLE
Proton Not Detected After It Updates In Steam

### ISSUE THREAD

**Issue by Nano-Ocelot** [sonic2kk/steamtinkerlaunch#930]
## System Information
- SteamTinkerLaunch version: 14.0.20231003-1
- Distribution: Opensuse Tumbleweed
- Installation Method: ProtonupQT

## Issue Description
After the main proton versions are updated in Steam a game will fail to launch with a message about how the selected version of Proton could not be found and Steamtinkerlaunch never opens its window either to manually change the version of proton. As it stands the warning notification just loops until I force close the game in Steam or stop the process manually. Restarting Steam doesn't fix the issue either. The only solution that I've found is to reboot the system. I don't quite know the inner workings of STL, but I suspect there's some kind of background process that symlinks proton versions when the system boots up. 

If something like this is true, and this isn't just a bug on my system, is there a way to manually force STL to pull a current list of proton versions? Also could this be automated whenever a game is launched so that this issue could be avoided altogether?

## Logs
I lost the logs after launching the game again with a successful launch post-reboot of my computer.

**Comment by sonic2kk** [comment]
This is expected behaviour, this was already reported multiple times including in #929 most recently (haven't gotten around to adding it to the wiki yet). This also happens if you download a custom Proton version.

No bug, this is intentional behaviour :-)

> but I suspect there's some kind of background process that symlinks proton versions when the system boots up

Nope, we have a file that caches the version name and paths called `ProtonCSV.txt` when `/dev/shm/steamtinkerlaunch` is created, and this is also put into `~/.config/steamtinkerlaunch` (or the STL Flatpak equivalent path). No symlinking here 🙂

**Comment by sonic2kk** [comment]
Updated the [Troubleshooting wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Troubleshooting#steamtinkerlaunch-proton-version-list-isnt-updating) which I mean to do yesterday and forgot :sweat_smile: .
