### ISSUE TITLE
Opening a browser window ends up in chrome crash.

### ISSUE THREAD

**Issue by juampiursic** [sonic2kk/steamtinkerlaunch#936]
## System Information
- SteamTinkerLaunch version: v9.2
- Distribution: Fedora 38
- Installation Method: Fedora COPR https://copr.fedorainfracloud.org/coprs/capucho/steamtinkerlaunch

## Issue Description
I'm trying to launch Remnant 2, and when I want to link my Epic Account, it should open a browser window, it does not. GNOME tells me that chrome and chrome_crashpad_handler both crashed.

## Logs
Sun Oct 15 23:33:35 -03 2023 INFO - initAID - Set AID from STEAM_COMPAT_APP_ID to '0'
Sun Oct 15 23:33:35 -03 2023 INFO - initAID - Set AID from STEAM_COMPAT_DATA_PATH '/home/jursic/.local/share/Steam/steamapps/compatdata/3184435861' to '3184435861', because SteamAppId is '0'
Sun Oct 15 23:33:35 -03 2023 INFO - initAID - Set OSCDP to STEAM_COMPAT_DATA_PATH '/home/jursic/.local/share/Steam/steamapps/compatdata/3184435861'
Sun Oct 15 23:33:35 -03 2023 INFO - loadLangFile - Loading system wide /usr/share/steamtinkerlaunch/lang//english.txt
Sun Oct 15 23:33:35 -03 2023 INFO - getCurrentCommandline - No Proton in command line arguments 'waitforexitandrun /home/jursic/.var/app/com.usebottles.bottles/data/bottles/bottles/EA-App/drive_c/Program Files (x86)/DODI-Repacks/Remnant 2/Remnant2.exe'
Sun Oct 15 23:33:36 -03 2023 INFO - saveOrgVars - Storing some original variables to restore them later
dom 15 oct 2023 23:33:36 -03 INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
dom 15 oct 2023 23:33:36 -03 INFO - emptyVars - Set $PATH to '/home/jursic/.local/bin:/home/jursic/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:'
dom 15 oct 2023 23:33:36 -03 START - ######### Initializing Game Launch 3184435861 using SteamTinkerLaunch v9.2 #########
dom 15 oct 2023 23:33:36 -03 INFO - main - Starting with a clean log
dom 15 oct 2023 23:33:36 -03 INFO - main - Start creating default configs
dom 15 oct 2023 23:33:36 -03 INFO - createDefaultCfgs - START
dom 15 oct 2023 23:33:36 -03 INFO - loadLanguage - First load the default language to make sure all variables are filled
dom 15 oct 2023 23:33:36 -03 INFO - loadLangFile - Loading system wide /usr/share/steamtinkerlaunch/lang//english.txt

**Comment by sonic2kk** [comment]
I think firstly the most important thing to point out is, you're using an incredibly outdated version of SteamTinkerLaunch. You're using v9.2, which was released on March 2nd 2022, about a year and a half ago and there have been several releases since then (v10, v11, v11.11, then a change in project ownership, v12, v12.12). Please update to using SteamTinkerLaunch v12.12 at the very, very oldest, or ideally, a version from the latest git commit, ensuring you do a fresh install. This has a fix that may be applicable, which is to use the Steam Linux Runtime (if the required version for the chosen Proton version is installed) with Non-Steam Games.

I highly suggest using a build from the latest git. This may not be available on Fedora COPR, so make sure you manage the hard dependencies listed on the wiki, as well as any others you might need such as `jq` yourself.

Also keep in mind that all SteamTinkerLaunch packages are community maintained. You may want to ask for a more up-to-date package from someone in the Fedora community.

<he>

Secondly, this does not seem like an STL issue, but moreso a Wine compatibility issue. However, note this section of the log:

> No Proton in command line arguments 'waitforexitandrun /home/jursic/.var/app/com.usebottles.bottles/data/bottles/bottles/EA-App/drive_c/Program Files (x86)/DODI-Repacks/Remnant 2/Remnant2.exe'

Confirm that you're using SteamTinkerLaunch as a compatibility tool and not as a launch option, and also that you have selected a valid Proton version.

Chrome crashing from this really has nothing to do with SteamTinkerLaunch though.

Another thing to mention is that this game appears to be added as a Non-Steam Game but installed via another tool (Bottles?) - This is not supported by SteamTinkerLaunch. Non-Steam Games are only supported when they're ran via Steam, where Steam manages the prefix and not a third-party tool. When you launch a game via Steam, even if it has its own prefix, Steam will create its own. Therefore if you used an installer, you're better off running this installer via Steam itself.

If you're using a Bottles Steam shortcut or something along these lines, something like what Lutris let's you do, this is fully unsupported by SteamTinkerLaunch. If the shortcut is running a Bottles command and is not the EXE directly added to Steam, you'll likely encounter issues.

After all of this, if the issue persists, you could try running with and without the Steam Linux Runtime.

Lastly, after doing all of this, have you confirmed that this issue is specific to SteamTinkerLaunch?

**Comment by sonic2kk** [comment]
Looking at the file path, I notice `DODI-Repacks`. A quick search suggests that this is a game crack. It also notes the EA App, and as far as I know, this game does not use the EA App.

Please confirm that you have legally purchased this game as well, and if you still experience issues, purchase the game on Steam and see if you still have issues. If you cannot, and this is an illegal copy, please close this issue.

**Comment by sonic2kk** [comment]
Closing as the SteamTinkerLaunch version is very out-of-date, this may be using STL to launch a shortcut set up by another tool, this may not be a legal copy of the game, and browsers failing to open from a game is most probably not something to do with STL.
