### ISSUE TITLE
More verbose console output for installation

### ISSUE THREAD

**Issue by krittinen** [sonic2kk/steamtinkerlaunch#962]
## System Information
- SteamTinkerLaunch version: v14.0.20231008-2 (steamos-3.5)
- Distribution: SteamOS 3.5.1

## Feature Description
When installing HMM on SteamDeck the terminal shows "Installing HedgeModManager" for what seems like an eternity (about 2 hours in my case), with no indication that the process is still ongoing or has frozen, checking btop++ also shows little CPU usage, an option to show a more detailed step breakdown would be appreciated.

**Comment by sonic2kk** [comment]
This should already be present in `/dev/shm/steamtinkerlaunch`, under some HMM-labelled log. There should be logs for Winetricks installation. This should show the Winetricks installation log, as well as a HMM start log for when startup will inevitably fail. 

Also, HMM is really broken on Steam Deck, and no one has come forward to help maintain it, so very little is being done on it. Just a heads up. The startup log is given so those who understand more about Wine can troubleshoot and contribute relevant fixes to either Wine or STL or whichever project needs it, but that has not happened. So when HMM fails, please don't submit a bug report either here or upstream, instead encourage anyone you know who can actually diagnose the problems to help fix them :-)

My suspicious is that it's related to the Steam Linux Runtime and Winetricks, but I haven't confirmed that. The core of the issue is related to dotnet48 failing to install from what was discovered before, but no fix was investigated or contributed. I'm starting to think the hope of SteamTinkerLaunch being by-developers-for-developers, and that the Steam Deck being solely a Linux enthusiast device, have died long ago.
