### ISSUE TITLE
Hedgemodmanager installs correctly but causes Sonic Frontiers to crash

### ISSUE THREAD

**Issue by Gordon3002** [sonic2kk/steamtinkerlaunch#972]
## System Information
- SteamTinkerLaunch version: 12.12
- Distribution: SteamOS 
- Installation Method: ProtonupQT Flatpak

## Issue Description
I installed steamtinkerlaunch via ProtonupQT to install hedgemodmanager. I set hedgemodmanager to use proton 7 because that's the only proton version that seems to work, it installs and launches fine but when I install the mod loader Sonic Frontiers won't launch anymore, Steam says "starting" then "stop" and then just goes back to "play" without launching. I even installed .NET 4.0 and 4.8 in a Proton 5.0 prefix but it changes nothing, I also put mscore.dll in the folder with the .exe file but same result.
How do I get the mod loader to function properly ?

## Logs

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13297623/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment]
I'm not a Wine developer, I can't help if .NET 4.8 fails to install. On SteamOS it mostly appears broken but it works on my Arch PCs.

I'll probably add a flag to disable HMM on SteamOS because it doesn't work most of the time and absolutely no one has volunteered to help, so sorry, there's no fix unless you can get .NET 4.8 to install correctly for the Sonic Frontiers prefix.

Winetricks on SteamOS seem like a huge mixed bag but if you figure it out feel free to leave a comment because it could be helpful to others. But since all STL does is run Winetricks to install dotnet48, if that fails, not me, the HMM Devs, or the Winetricks Devs can help. It's an issue with running the dotnet installer under Wine.
