### ISSUE TITLE
MO2 not running even with 2.4.4

### ISSUE THREAD

**Issue by AzaleaCatgirl99** [sonic2kk/steamtinkerlaunch#982]
## System Information
- SteamTinkerLaunch version: Latest git master build
- Distribution:  SteamOS 3.5.5
- Installation Method:  protonup-qt

## Issue Description

MO2 will not launch even with 2.4.4

## Logs
 unable to post logs as of rn, but if this is any help, it shows an error saying "could not determine pid of '/home/deck/.local/share/Steam/steamapps/common/Proton 8.0/dist/bin/wineserver'

I've had issues with the wineserver' before, I just haven't been able to figure out how to fix it

**Comment by sonic2kk** [comment]
Without logs, **including Wine run logs for MO2**, I cannot help much. I have seen some Wineserver issues like this in the past (#730) and a restart seemed to fix it, no idea if this applies on SteamOS though. Using mod tools on SteamOS is a very bad idea, so I have never and will never do it.

**Comment by sonic2kk** [comment]
Fresh install of MO2 still works over here on my Linux PC (the primary platform for STL). If it doesn't work on SteamOS, I'm not that interested in fixing it as it's likely some very SteamOS-specific problem, and I am already considering pulling "official" SteamOS support anyway. But we'll see if we can find something out.

**Comment by sonic2kk** [comment]
Another thing you could potentially try is re-installing MO2 with `innoextract-1.9-9`, you can grab it from the [Arch mirrors](https://archive.archlinux.org/packages/i/innoextract/) and replace the `innoextract` in `~/stl/deps/usr/bin` with the one from the mirrors.

MO2 was tested by one user a long time ago on SteamOS 3.5 Preview and it was found we needed `innoextract-1.9-8`. Since then `1.9-9` has come out, but I didn't bump to it, as I was unsure if it would work. If you find that a reinstall with `1.9-9` works, I can bump the dependency.

If you suspect the PID message is more likely to be the root cause, however, feel free to look into that avenue first. A reboot seems to be the main way to resolve it, though replacing the `innoextract` dependency may also not be a bad idea. If something gets messed up, `steamtinkerlaunch cleardeckdeps` will remove all third-party tool dependencies, and rerunning SteamTinkerLaunch will re-download the original dependencies including `innoextract-1.9-8`.

**Comment by sonic2kk** [comment]
Sorry, I can't help without a log, and the issue template asks you to provide a log before opening issues. Please re-open if you are unable to resolve this on your own, making sure that you provide a STL log and a MO2 wine run log, and have tried, in summary, the following:
- Check that a clean install with STL-git does not fix the issue - Remove the Wine prefix at `~/.config/steamtinkerlaunch/mo2`, but I get the impression this was already tried
- Restarting your Steam Deck in an attempt to resolve the wineserver issue
- Using a newer `innoextract`, since this is needed to install MO2 on SteamOS
- Checking that you are, for sure, using MO2 v2.4.4 without an existing v2.5.0 install
- Checking that the `startMO2` log in `/dev/shm/steamtinkerlaunch` contains no noticeable Wine errors. If it contains something about a minidump, this is a Wine issue that I cannot fix, but would indicate that v2.4.4 is not being used
- Checking that you are using the same Proton version to install and run MO2 (changing them requires you to change versions)
- Checking that `steamtinkerlaunch mo2 repairpfx` does not fix the issue

If you have a Linux PC, and if you use STL on it, it would be good to check if the problem persists there as well. But I have sadly gotten the sense that most Steam Deck owners are not Linux enthusiasts, so if you don't, it's no worries.

I'll also say, as a disclaimer though I may have said it in a previous issue, I don't condone using MO2 on SteamOS, even if you get it working.
