### ISSUE TITLE
Adding BG3ModManager Support

### ISSUE THREAD

**Issue by spannerman79** [sonic2kk/steamtinkerlaunch#985]
## System Information
- SteamTinkerLaunch version: steamtinkerlaunch-v12.12
- Distribution: EndeavourOS

## Feature Description

Just like with MO2, could support for [BG3ModManager](https://github.com/LaughingLeader/BG3ModManager) be added?

Thanks

**Comment by sonic2kk** [comment]
I'm not interested in adding more mod tool support, STL is not a modding tool. This could be used as a custom command though.

STL is a tool for Linux enthusiasts to tinker with launch options, mod tools are expensive in terms of time and features to maintain. They break often under Wine, and they invite many difficulties.

Beyond this, I'm not interested in adding a mod tool that is specifically for one game. It would have to be very broad.

Eventually, Vortex support will have to be pulled once they replace Vortex Mod Manager with the C# Vortex app (which has native support), and no one is helping maintain HMM either.

Maybe you got the wrong idea about what STL is, but it's not here for mods. Especially not a mod manager for one or a tiny handful of game. Once again, **SteamTinkerLaunch is NOT a modding tool, it is not for people who just want to install MO2**.

<hr>

Finally, please use SteamTinkerLaunch from git and not v12.12, which is very old at this point.

**Comment by sonic2kk** [comment]
Going to lock this as well because mod tool requests invite all kinds of demanding, entitled users piggybacking off a polite request.

You were polite in your request but I'm tired of losing sleep over the replies this will inevitably get from non-enthusiasts or people who probably use STL just to mod their games, trying to convince me to add support. These requests come I'm every so often and it always ends up as a strain on my mental health.

To these users: The answer is no, the answer will always be no, because either it can be installed manually easily, or it requires tweaks that make it difficult to maintain under Wine, and STL is not a tool for mods.
