### ISSUE TITLE
Vortex mod manager doesn't start with no log.

### ISSUE THREAD

**Issue by miyoku157** [sonic2kk/steamtinkerlaunch#991]
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Garuda Dragonized (so Archlinux )
- Installation Method: Installed inside Garuda

## Issue Description
I'm trying to install and launch Vortex mod manager. But i can't manage to launch it. I've followed the step of the wiki and i know that it successfully downloaded the setup because I can find the setup. 
I think it has installed Vortex because i can find the files inside the wine prefix in the "drive_c/Program Files/Black Tree Gaming Ltd/Vortex". There is still a doubt because in the middle of the installation i got an error that i can't remember the message (i will try to get back the error message) but it let me cancel/ignore or retry but retry lead me on a website microsoft.
I've try the ignore.
And if i try to start Vortex, I just have Starting vortex followed by Vortex exited.
My install files for proton and dotnet and the steamtinkerlaunch log.
If someone has an idea?
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13502550/steamtinkerlaunch.log)
[installVortex_protonrun.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13502642/installVortex_protonrun.log)
[installDotNet.log ](https://github.com/sonic2kk/steamtinkerlaunch/files/13502645/installDotNet.log)

**Comment by sonic2kk** [comment]
You're using SteamTinkerLaunch v12.12, you should try STL from git as there were many changes (the STL changelog, which the issue template told you to read, lists the changes). If it still doesn't work, then it's a Wine incompatibility which I cannot fix.

The dotnet log is especially telling and what you've said sounds like it tried and, as expected, faiiled to install dotnet48, which was removed from STL-git a very, very long time ago.

Try clearing your Vortex prefix, installing STL from git, and re-installing Vortex. If that yields no success I can't help, and I absolutely utterly detest Vortex, so I won't be working on it anymore. If you need Vortex, you could always encourage someone from the community to contribute.

I'm not sure why so many people are using v12.12 because it's extremely out of date. I'm not sure why so many people are still using it despite constant communication on the issue tracker stating not to use it, is there something I can explain better here? Am I the outlier that tries git builds, changelog, and commit history before reporting bugs? This isn't directed at you specifically, I'm just genuinely curious.

Good luck!

**Comment by miyoku157** [comment]
Well i'm going to try to remove the current version of STL and reinstall the git version. 
I didn't know STL before going to garuda and it's preinstall inside the iso file. Maybe it's one of the reasons?

**Comment by sonic2kk** [comment]
I didn't know it came as part of Garuda, but maybe if it comes pre-installed that's one of the problems.

Ugh, maybe I'll have to make another release then, but I really don't feel like dealing with another massive influx of nasty users again that v12 brought... I simply don't have the time or desire to go through that again. We'll see then I suppose.

**Comment by sonic2kk** [comment]
Did you get a chance to check if a newer STL version worked with a fresh install? If so, did it work? If not, try doing fresh installs each time of older versions by manually selecting a Vortex version in the global menu, in case newer Vortex releases are broken under Wine.

**Comment by miyoku157** [comment]
I tried to use STL with the git version. And i also tried to use the older version to install 1.8 but I didn't manage to get it work (when i look at the log, it still tried to install a 1.9 something). 
So in the end, i finished installed my mod manually, it was easier than using vortex for me.

**Comment by sonic2kk** [comment]
If Vortex 1.8 doesn't work then it's a Wine issue that I can't do anything about (assuming you definitely tried with a fresh prefix and a new enough GE-Proton version).

Glad it works manually, I recommend that over mod managers any day (I didn't wrrite nor do I endorse the Vortex integration with STL).

STL is not a modding tool and I'll be very happy when people stop using it for that and actually use it for other things, treat the mod tools as secondary, and can step up to submit PRs to help it instead of creating issues for a tool I detest and don't use, and cannot support.

Sorry if that's harsh, but I get seriously stressed every time I see a Vortex issue, and cannot wait until I can remove it from STL.
