### ISSUE TITLE
STL won't launch some Non steam VN game but steam with same proton can.

### ISSUE THREAD

**Issue by lt-gen2er** [sonic2kk/steamtinkerlaunch#993]
[2476853868.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13540891/2476853868.log)
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: SteamOS  3.5.7
- Installation Method: ProtonUP-QT

## Issue Description
Gonna play some Non steam VN games on Steam Deck with translation program. 
Tried to launch with STL(in game setting set the proton version 8.0-4 and all other settings keeps default)came with errors (you can review the log it seems it can not find the front program window).
And I also tried to use steam app open this game with same proton(8.0-4), it will launch with no issue.

## Logs
Please review attached log files
[2476853868.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13540895/2476853868.log)

**Comment by sonic2kk** [comment]
Non-Steam Games may not work, but also, you're using STL v12.12, which is very old. You should install STL-git (can be done manually or with ProtonUp-Qt). There were some changes made to how STL handles Non-Steam Games, mainly around using the Steam Linux Runtime which can improve compatibility (fixed a few issues, first one and the one I remember off-hand was #772). STL v12.12 is insanely out of date, you shouldn't be using it anyway.

> (you can review the log it seems it can not find the front program window).

Yes, it appears that the game window isn't loading, so STL can't find it. To rule out that this isn't a Wineserver issue, try rebooting your Steam Deck if using STL-git doesn't fix the problem.

Also, Steam Deck is probably not going to be officially supported for much longer, as I am selling my LCD Steam Deck and certainly will not be using STL on my new OLED Steam Deck, and no one has come forward to support it.

So try STL-git and see if that has better compatibility. If you have a Linux Desktop PC, try to confirm if the issue happens there as well. Apart from that, check if it works on Steam Deck Desktop Mode.

<hr>

If none of that works, then I can't help since this is likely some Non-Steam Game + Steam Deck specific combination. Non-Steam Games are highly secondary for STL (I don't condone buying games on other stores outside of for preservation purposes and condemn the use of some storefronts), and Steam Deck is virtually unsupported at this point already, and unless someone steps up to help (which is doubtful at this point, I've been asking for a year), it'll be official.

**Comment by lt-gen2er** [comment]
> Non-Steam Games may not work, but also, you're using STL v12.12, which is very old. You should install STL-git (can be done manually or with ProtonUp-Qt). There were some changes made to how STL handles Non-Steam Games, mainly around using the Steam Linux Runtime which can improve compatibility (fixed a few issues, first one and the one I remember off-hand was #772). STL v12.12 is insanely out of date, you shouldn't be using it anyway.
> 
> > (you can review the log it seems it can not find the front program window).
> 
> Yes, it appears that the game window isn't loading, so STL can't find it. To rule out that this isn't a Wineserver issue, try rebooting your Steam Deck if using STL-git doesn't fix the problem.
> 
> Also, Steam Deck is probably not going to be officially supported for much longer, as I am selling my LCD Steam Deck and certainly will not be using STL on my new OLED Steam Deck, and no one has come forward to support it.
> 
> So try STL-git and see if that has better compatibility. If you have a Linux Desktop PC, try to confirm if the issue happens there as well. Apart from that, check if it works on Steam Deck Desktop Mode.
> 
> If none of that works, then I can't help since this is likely some Non-Steam Game + Steam Deck specific combination. Non-Steam Games are highly secondary for STL (I don't condone buying games on other stores outside of for preservation purposes and condemn the use of some storefronts), and Steam Deck is virtually unsupported at this point already, and unless someone steps up to help (which is doubtful at this point, I've been asking for a year), it'll be official.

Thank you for the quick response and instructions.

Just tried the latest git version STL on steam deck oled, game started with no issue.

Hopefully the official support will not be unavailable so soon!

**Comment by sonic2kk** [comment]
Glad STL git worked, guess this was an SLR issue after all! I will close this issue then.

> Hopefully the official support will not be unavailable so soon!

I will likely drop it early next year unless someone can step up to help maintain it. But the userbase that SteamOS has cultivated is not conductive to attracting developers, so I don't think that'll happen, and anyone who could help maintain STL likely also does not want to be bothered with SteamOS, a platform not made for tinkering and that largely has a non-technical userbase.

At minimum someone would have to be around to help troubleshoot issues on SteamOS and submit PRs to fix those issues, and once I sell my LCD Deck, I cannot do that anymore. There's no point to advertising support for a platform I can't test on if that makes sense. But ideally they would also be also be able to improve support independent of issues, improving it for their own use-cases, and working on some things outlined in #859.

If the community want SteamOS support and can evidence that by maintaining it, it will stay, but otherwise it cannot.
