### ISSUE TITLE
Option to change place for the prefix

### ISSUE THREAD

**Issue by LinuxfarmerHH** [sonic2kk/steamtinkerlaunch#994]
Steamtinkerlaunch installs pretty well here, included a running Vortex that is unable to "Deploy a mod", where all solutions from it's helper tool are not available. Reason: The Steam Library is on a physical different disk drive and no type of links can be deployed from the default prefix home.

## System Information
- SteamTinkerLaunch version: v14.0.20231121-1
- Distribution: Linuxmint 21.2 Cinnamon

## Feature Description
Offer some way to change the prefix home, searched the Wiki and got no clue how to do that.
-->

**Comment by sonic2kk** [comment]
Do you mean change the Vortex prefix location? If so, it can be changed from the global menu or manually in global config file `config.vdf` (at `~/.config/steamtinkerlaunch/global.conf`) by changing `VORTEXCOMPDATA`.

However, deployment should work across different drives, because STL creates the staging folder and uses hard link deployment. It should be at the drive root:

![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/7917345/ae1347d2-568d-4f53-b295-a915ace447e8)

Unless the Steam Client itself is not installed to the boot drive, I have no idea what would happen in that case, I have never seen that before. 

But, Vortex is unmaintained and I no longer really accept Vortex issues because no one who uses Vortex can help with development.

I would double check the Vortex deployment folder. It could be that this is just yet another thing no longer working with Vortex under Wine. I implore you not to use it :-)

**Comment by sonic2kk** [comment]
I should also note for courtesy that Vortex support in STL will be removed soon, for many reasons:
1. No one has stepped up to help out with maintaining it (Honestly, very few people help out with STL, and it's very sad)
2. It's going to be replaced with a native Linux tool that uses an entirely different stack (C# + .NET, not NodeJS)
3. I hate Vortex. Like, I really hate Vortex. I refused to use it on Windows, I refused to use it when it was Nexus Mod Manager, I always tell people not to use it, and I end up doing the same here most of the time on Linux.
4. I have decided the mental health strain is just not worth it, I have tried and in the end, I'm not willing to lose sleep over a tool I'm supposed to develop for fun in my free time.
