### ISSUE TITLE
Vortex Wine Prefix Gets Stuck on Win7 when upgrading from v12

### ISSUE THREAD

**Issue by shinyquagsire23** [sonic2kk/steamtinkerlaunch#995]
## System Information
- SteamTinkerLaunch version: v12.12, v14 master (as of this post)
- Distribution: SteamOS
- Installation Method: ProtonUp-Qt

## Issue Description
Was helping a friend install Vortex on their Steam Deck for CP2077, installed v12 from ProtonUp-Qt because I assumed the default would be the best option. Found out it didn't work, so I upgraded to master and tried installing Vortex v1.7.0 per some Reddit post. But for some reason that didn't work, and the Vortex installer complained the system was outdated. Ended up having to manually delete the wine prefix to get it to install on master correctly. As far as I can tell, upgrading from older versions doesn't re-create the prefix or set it to Win10 from Win7 as is required in order to get the installer to run correctly.

## Logs
none

**Comment by sonic2kk** [comment]
>  As far as I can tell, upgrading from older versions doesn't re-create the prefix or set it to Win10 from Win7 as is required in order to get the installer to run correctly.

The Windows version issue is a bug with Vortex under Wine when using such an old version, and it is expected that the prefix wouldn't get automatically re-created. The prefix would already be set to Win10 by Proton (STL does not alter this whatsoever), the Win7 warning issues is not my problem, it's because Vortex is fundamentally broken under Wine.

The issue here is not that the prefix gets stuck on upgrading, it's that the prefix is totally broken because you tried to install with v12.12. So I think you have perhaps misunderstood the issue; Vortex didn't install properly before and the prefix must be cleared, just as you would have to do if you installed it manually.

Still, I'm absolutely astonished that Vortex works on SteamOS. You are the first person in a very long time to report Vortex installing correctly.

Also, you did the right thing to use STL-git, it is the recommended version. Using the latest stable version of software especially on SteamOS is a bad idea.

<hr>

There is nothing to fix here, prefixes should be re-created when program installation fails or when manually trying to install another version, just like you would do manually. Removing the prefix or trying to guess when to re-create it automatically would be disastrous, since the prefix is actually what contains all of the Vortex data. Plus, it would be quite difficult to guess when to re-create the prefix with any accuracy.

Not to mention, to put it bluntly: I ***detest*** Vortex Mod Manager. It is one of the pieces of software I hate the most. I am no longer spending any time to maintain it outside of ensuring it downloads correctly. Plus, no one from the community has actually tried to help out, despite several requests for help. But even if I was maintaining it, there would be nothing really I could do here.

And, as a courtesy warning:
1. Vortex support will probably be removed from STL in the medium-term once the native Linux C# + .NET Vortex App is in a more usable state. This will replace Vortex Mod Manager, and since it is an entirely different application with an entirely different architecture, the existing Vortex integration won't apply to it. Not to mention it will run natively and support Proton games, negating the need for all of these broken attempts and sleepless nights trying to get Vortex to work, only for Nexusmods to break it.
2. Official SteamOS support will be dropped soon, although STL will still function on it in a very basic sense, and though I will still accept PRs to improve support, I will no longer advertise official support. I got a Steam Deck OLED and will be getting rid of my LCD Steam Deck, and have no intention of doing any kind of development work on my new Steam Deck. I have also been trying to get others to help develop STL for a year, and directly asked for SteamOS support almost 6 months ago (#859), but no one from the community (which, ideally, should be enthusiast-centric) stepped up to help. If the community cannot help themselves, then I cannot continue supporting SteamOS on my own, since I will no longer be using STL on it.

<hr>

Sorry that there's nothing that I can do, and sorry if my words were harsh, but so many Vortex issues have come in, and I wish STL wasn't used for this program anymore to be honest. I don't use Vortex and to be blunt don't care about it at all. It was implemented a long time ago, before I took over this project, and I have been making strong attempts to distance STL from being some mod tool. Especially given how rude and entitled many users have been about the mod tools, they apparently have no understanding of how Wine works and expect STL to be a magic tool. It was a bit refreshing to get an issue with more technical detail on Vortex, but sadly I cannot do anything, and it was a damn sight better than some of the other issues I've gotten.
